### ISSUE TITLE
[FEATURE] Добавить столбцы "Сумма сделки" 

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#100]
### Опишите проблему, которую решает ваша фича

Сумма сделки видна только в окне "Выставить заявку". В блоттере в "Сделках" отображается только цена и количество.
![image](https://user-images.githubusercontent.com/99450543/165512068-0ec015a5-f0a7-4f9d-a98f-e14f37a36417.png)

### Опишите предлагаемое вами решение

В раздел "Сделки" блоттера добавить колонки с суммой сделки

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/107

**Comment by PilgrimViis** [comment]
Вынес комиссию в отдельную таску, потому что для неё нужны доработки на бекенде. Объем сделки добавим.

**Comment by PilgrimViis** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/107
