### ISSUE TITLE
[BUG] "Заявки" и "Стопы" в блоттере не открываются, если запрос групп заявок возвращает ошибку

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1011]
### Опишите баг

Если запрос /orderGroups возвращает ошибку, например 404, то два таба в блоттере: "Заявки" и "Стопы" - становятся пустыми и не отображают заявки:
![2023-06-06_09h46_30](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/f0ce2239-f5b6-4291-996a-eab5c70c8402)

### Воспроизведение

1. Открыть консоль F12. Залогиниться в Астрас.
2. В блоттере перейти во вкладку "Заявки". Посмотреть на отображение данных.
3. Переключиться на "Стопы".

### Среда.

Windows 10
Google Chrome v113.0.5672.127 

### Ожидаемое поведение

"Заявки" и "Стопы" в блоттере открываются и отображают актуальную информацию по биржевым и условным заявкам.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Это критичный баг. Просьба заняться как можно скорее. Нет гарантии, что АПИ по уведомлениям не отвалится, у него приоритет ниже чем у торгового апи. Я думаю это риск.
