### ISSUE TITLE
[BUG] На телефоне при смене бумаги информация в блоттере пропадает на короткое время

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1013]
### Опишите баг

На мобильном телефоне в Гугл Хроме или Фаерфоксе при переключении бумаги через панель поиска или через блоттер (клик на тикер в табе Заявки, Стопы или Позиции) вся информация в открытой вкладке блоттера пропадает на несколько секунд и только потом подгружается.

Кроме того, под панелью поиска сам активный тикер не сразу подгружается, появляется только через пару секунд:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/1bf24b55-e309-4de9-977c-ba3b6e4175e0

### Воспроизведение

1. Авторизоваться в Астрас с телефона. Перейти в "Блоттер".
2. Нажать на любой доступный тикер из "Заявки" или "Стопы".
3. Посмотреть на отображение вкладки блоттера и активного тикера под панелью поиска.
4. Перейти в раздел "Позиции" и сменить бумагу. Проверить отображение данных.
5. Поменять бумагу через панель поиска.

### Среда.

Android 10
Google Chrome v110, Mozilla Firefox

### Ожидаемое поведение

При смене бумаги заявки и позиции в блоттере не пропадают
Под панелью поиска сразу отображается активный инструмент

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Блоттер тут вообще не причем. При ЛЮБОЙ смене инструмента полностью перерисовывается дашборд
