### ISSUE TITLE
[BUG] Добавить пояснение для скрытых уведомлений по портфелю

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1017]
### Опишите проблему

Сейчас в настройках в Профиле в блоке "Уведомления" можно скрыть уведомления по портфелю, тем самым нативные и пуш-уведомления по исполнению заявки не будут отображаться. Но бывают еще уведомления по смене цены по тикеру, которые будут приходить, несмотря в целом на отключение уведомлений по портфелю в Профиле. Это может вызвать путаницу у клиентов:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/55aee7fb-bd33-4b38-a9e7-4e2cef08380a

### Опишите предлагаемое вами решение
В Профиле при наведении мыши на поле "Скрыть уведомления для портфелей" появляется тултип с пояснением: "касается только исполненных заявок в рамках выбранного портфеля"

### Среда.

Windows 10
Google Chrome v114.0.5735.110

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Это ожидаемое поведение.
Отключение уведомлений по портфелю никак не должно аффектить уведомления по цене.
Уведомления по портфелю это уведомления, которые как-то изменяют его состояние. Сейчас это только исполнение заявки.

Уведомления изменения цены с портфелем никак не связаны. Инструмента даже может не быть в порфеле.
Тем более это нелогично, что устанавливая уведомление на цену и переключаясь на портфель и отключенными уведомлениями, я могу пропустить уведомление по цене

**Comment by PilgrimViis** [comment]
@ilya7am , уведомление по портфелю это про заявки и сделки. Так как ты запутался, то значит это не очень очевидно. Перепиши эту задачу чтобы там отображался tooltip с описанием того, что будет отключено, пожалуйста.
