### ISSUE TITLE
[BUG] Для новых выставленных виджетов не работает переключение лейбла

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1019]
### Опишите баг

Если на дашборд выставить новые виджеты и поменять лейбл в шапке виджета, то виджет не обновится под новый инструмент. Помогает перезагрузка страницы или смена темы/языка приложения:
 
https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/c2a4c165-ee22-4335-a9d5-4ad6c7e9ef67

### Воспроизведение

1. В Настройках в Профиле включить привязку инструментов к лейблам.
2. Проверить переключение лейблов в уже выставленных виджетах.
3. Выставить новые виджеты.
4. В новых виджетах поменять лейбл.
5. Посмотреть на смену тикера в шапке виджетов.

### Среда.

Windows 10
Google Chromw v114

### Ожидаемое поведение

Для любых виджетов при смене лейбла указывается инструмент, привязанный к этому лейблу

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@ilya7am конкретный список виджетов, где не работает переключение
