### ISSUE TITLE
[FEATURE] Унифицировать отображение бордов по привязанным к лейблам бумагам

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1021]
### Опишите проблему, которую решает ваша фича

При включенной привязке инструментов к лейблам в некоторых случаях привязанный тикер пишется вместе с режимом торгов, а иногда указывается и без него. Это может вызвать дополнительные вопросы. Лейбл можно присвоить через виджеты: Выбор инструмента, Все инструменты и Блоттер:

 1. **Выбор инструмента:**
- Борд ставится, только если тикер привязан сразу к нескольким лейблам: в первый раз напишется просто тикер (без борда), но в последующие - уже дописывается борд, даже если борд - дефолтный:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/cb2b44a6-ee1e-4918-a499-598b99469120)

- Если выбирать небазовый борд, например SBER(SMAL), то опять же при указании тикера в первый раз - не будет указан борд, хотя уже в этом кейсе он важен:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/d3e9864b-ac08-46b0-ad62-1e48e5c9b741)

2. **Все инструменты и Блоттер:**
Если выбрать тикер через виджет "Все инструменты" или "Блоттер", то борд вообще не будет указываться, хотя бумага может быть привязана к двум и более лейблам. В таком случае указание борда будет только, если тикер выбран через "Выбор инструмента":
![2023-06-07_17h19_17](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/3c97f8b5-f81f-4eb6-802c-2a3dd99ed341)

### Опишите предлагаемое вами решение

Для "Выбор инструмента", "Все инструменты" и "Блоттер":
- если у тикера дефолтный борд, то борд не нужно указывать, даже если тикер привязан к двум и более лейблам.
- если борд - небазовый, то его сразу в первый раз нужно указывать через "Выбор инструмента".

### Дополнительная информация

Для виджета "Карта рынка" не нужны лейблы, лучше скрыть, как для "Календарь событий", "Арбитражная раздвижка":
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/b54266b1-51ea-4195-a499-2f353ca648b5)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Все итак уже унифицировано. Нет никакой разницы между виджетами. 
1. Борд появляется у тех тикеров, у которых в списке одинаковые symbol, чтобы их хоть как-то можно было различить.
2. При выборе инструмента из Блоттера у него вообще нет борда

**Comment by PilgrimViis** [comment]
@ilya7am в принципе согласен с Сергеем. В этом выпадающем окне борд нужен только для того, чтобы не перепутать. В виджетах в хедерах будет продублирован он когда будет выбран и никто не запутается. Что касается карты инструмента, то вынеси пожалуйста в отдельный issue, это баг.
