### ISSUE TITLE
[FEATURE] альтернативная раскладка клавиатуры

### ISSUE THREAD

**Issue by aronsx** [alor-broker/Astras-Trading-UI#1022]
### Опишите проблему, которую решает ваша фича

когда раскладка переключена на русский язык - перестают работать горячие клавиши, если писал что-то в чат и краем глаза увидел движение, невозможно быстро открыть сделку

### Опишите предлагаемое вами решение

сделать привязку клавиш вне зависимости от раскладки

### Опишите альтернативные решения, о которых вы думали

как вариант можно добавить альтернативную клавишу для каждой сделки и уже пользователь самостоятельно может указать клавишу в альтернативной раскладке 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Давайте сделаем это в виде опции. Вы не первый кто об этом пишет, но я боюсь в браузерном приложении делать слишком широкие настройки для выставления заявок....
