### ISSUE TITLE
[FEATURE] блоттер в одну строку

### ISSUE THREAD

**Issue by aronsx** [alor-broker/Astras-Trading-UI#1023]
### Опишите проблему, которую решает ваша фича

Когда весь экран заполнен стаканами, перед глазами не хватает состояния портфеля

### Опишите предлагаемое вами решение

Создать виджет, подобный панели ribbon, в котором будет отображаться состояние портфеля

Пример: 
дашборд заполнен стаканами:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/45541409/0b5951fd-e1b5-4e00-adfb-e61e2d86a0a7)

Чтобы просто посмотреть состояние портфеля - приходится создавать виджет блоттер, выглядит так:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/45541409/6df8599d-42a3-4dd3-a9f1-3d4269756efb)

Было бы удобно создать виджет, аналогичный ribbon, чтобы данные портфеля всегда были перед глазами 
![Screenshot 2023-06-08 at 11 28 37](https://github.com/alor-broker/Astras-Trading-UI/assets/45541409/3fff8c61-3b51-443f-8d16-c92c6e02d4bf)

### Опишите альтернативные решения, о которых вы думали

Второй вариант:
Если разместить блоттер внизу страницы, есть пара нюансов:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/45541409/12ec8e99-59e9-4a92-83e7-a0cf82ed0518)

1. есть неиспользуемое пространство шапки
2. широкие столбцы с названием
![Screenshot 2023-06-08 at 11 40 12](https://github.com/alor-broker/Astras-Trading-UI/assets/45541409/86046e0f-a06f-4044-9834-037ba1f5a827)

добавить функционал скрытия шапки виджета (например по дабл клику при зажатом контол), либо просто при растягивании 

при растягивании сохранить высоту ячейки таблицы (29)
была высота 29:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/45541409/fdb510ab-fc04-4ea6-9932-eaf2b15049ca)

стала 45:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/45541409/9c9191a2-3a53-464e-b965-35434708ab2d)

добавить возможность при растягивании на вкладке блоттера на вкладке портфолио размещаться всем столбцам в строку: в 10 стобцов на срочном рынке и в 9 на фондовом

сейчас максимально 4 столбца:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/45541409/8aab77c4-7097-4f6f-ac6d-ab11fe7b38ea)

Даже если уместить все столбцы в одну строку без скрытия шапки - уже будет удобнее и функциональнее

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Очень понравилось предложение. Для скальперов то что надо. Сделаем.

**Comment by sbelashevskiy** [comment]
Добавлен новый виджет "Сводка по портфелю" (Portfolio Summary)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/6a4b81ae-b8b9-4558-a1ec-abea8c93bf6f)
