### ISSUE TITLE
[BUG] Округление объема в заявке

### ISSUE THREAD

**Issue by ErmakovAnton** [alor-broker/Astras-Trading-UI#1028]
### Опишите баг

При выставлении заявки с дробным количеством (например 0.66) заявка округляется по мат. правилам. В данном случае на биржу ушла заявка в размере 1 шт. Необходимо запретить выставлять заявки с значениями после запятой в графе "количество"

### Воспроизведение

В графе заявки введите дробное значение кол-ва инструмента и отправьте на биржу.

### Среда.

Любой браузер

### Ожидаемое поведение

Должны выходить ошибка о недопустимости выставления заявки с дробным количеством.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
1. Округление - это логика работы биржи. В задаче не приведено, на какой бирже это происходит
2. По поводу запрета округления - есть режимы торгов  (SMAL), где можно выставлять заявки, меньше стандартного лота, поэтому значение кол-ва инструмент может быть дробным

**Comment by sbelashevskiy** [comment]
И на это уже создавали issue https://github.com/alor-broker/Astras-Trading-UI/issues/809

**Comment by PilgrimViis** [comment]
@ErmakovAnton подстветил эту задачу для бекендеров. Надеюсь сделают. Т.к. это дубликат, то эту я закрою. Предлагаю продолжить обсуждение в #809
