### ISSUE TITLE
[TECHNICAL] Обновить версию Angular до 16

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#1034]
### Опишите проблему, которую решает ваша фича

Вышла новая версия Angular. NgZorro тоже уже обновлен

### Опишите предлагаемое вами решение

Обновить версию angular и сопутствующих компонентов

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@sbelashevskiy Данила на следующей неделе не будет, чтобы было меньше конфликтов предлагаю эту задачу взять в понедельник или эту пятницу.
