### ISSUE TITLE
[BUG] Убрать привязку инструментов к лейблам для виджета "Карта рынка"

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1036]
### Опишите баг

Для виджета "Карта рынка" не нужны лейблы, лучше скрыть этот выпадающий список, как для "Календарь событий", "Арбитражная раздвижка":
![2023-06-28_14h28_30](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/1bc14e7a-b683-45da-8b72-3622941acef7)

### Воспроизведение

1. Залогиниться в Астрас и зайти в Профиль.
2. В табе "Общие" поставить чекбокс для "Включить привязку инструментов к лейблам".
3. Выставить виджет "Карта рынка".
4. Проверить отображение лейблов в шапке виджета.

### Среда.

Windows 10
Google Chrome v114.0.5735.110

### Ожидаемое поведение

Нет возможности сменить лейбл в виджете "Карта рынка"

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Для карты рынка привязка НУЖНА. При клике на инструмент этот виджет выбирает его в текущей группе
