### ISSUE TITLE
[BUG] В Мозилле и Сафари на телефоне при клике на "назад" страница ссо зависает

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1041]
### Опишите баг

Сейчас при работе в моб. версии Астрас в Google Chrome и клике “назад” один раз - возвращает на таб “Заявка”. Но в Firefox и Сафари при однократном клике “назад” сразу перебрасывает на sso, причём на странице авторизации появляется бесконечный лоадер, нельзя заново ввести логин/пароль:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/97508072-9af7-497b-bc75-7b542ab77f85)

### Воспроизведение

1. С телефона авторизоваться в Астрас.
2. Выбрать бумагу и перейти в таб "График".
3. Нажать на кнопку "назад" на телефоне.
4. Посмотреть на изменения на странице.

### Среда.

Android 10
- Google Chrome v110
- Mozilla Firefox v110
- Safari (iOS 16.2)

### Ожидаемое поведение

При клике на "назад" один раз - возвращать на таб "Заявка" как в Гугл Хром. 
Если при многократном клике "назад" возвращается страница ссо, то страница не подвисает и нет бесконечного лоадера

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@agushasok посмотри пожалуйста

**Comment by PilgrimViis** [comment]
Мы потратили 3 дня чтобы разобраться с этим багом. И не получается это нормально воспроизвести. Это никогда не "нажать один раз назад". Это надо упрямо, 4-6 раз нажимать "назад", чтобы оно воспроизвелось. Так как этот кейс весьма призраный, вряд ли кто-то будет упрямо нажимать 5 раз кнопку назад чтобы чего-то добиться, то тратить время на эту задачу смысла больше не вижу. 
Предлагаю так же проверить это поведение на стороне КК. Если там ситуация будет похожей, то создать тикет  уже на стороне sso.
