### ISSUE TITLE
[BUG] При выставлении скальперских стаканов по одной бумаге лимитки с одним id снимаются несколько раз 

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1049]
### Опишите баг

При клике на ~ (снять все лимитки) для выставленных Скальперских стаканов по одной и той же бумаге -  лимитные заявки снимаются для каждого из стакана, тем самым появляются ошибки 400: "Duplicate Cancel or Replace message for OrderID received":

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/45e9617c-660f-4488-896b-6077017ec0ff

### Воспроизведение

1. Выставить несколько Скальперских стаканов, в настройках стаканов "включить горячие клавиши".
2. Открыть консоль F12 - Network.
3. Выставить три лимитки по APTK.
4. Нажать ~ в рабочей области Астрас.
5. Посмотреть на снятие лимитных заявок.

### Среда.

Windows 10 
Google Chrome v114.0.5735.110 

### Ожидаемое поведение

Лимитка с уникальным id снимается только один раз, нет попытки снять лимитку еще раз.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Вполне логичное поведение. Каждый стакан это независимый виджет, он не может знать, что лимитка была/будет отменена другим виджетом. А из соображений производительности перепроверять статус лимитки нет смысла.
В конечном итоге команда выполнена - заявка снята. На дальнейшее функционирование ошибка никаким образом не влияет.

И главный вопрос: ЗАЧЕМ пользователь будет добавлять несколько ресурсоемких стаканов на один и тот же инструмент?

**Comment by PilgrimViis** [comment]
Думаю что проблема есть, но фишка в том что люди не открывают 2 стакана на один инструмент. Это не имеет смысла с точки зрения бизнес логики. Поэтому закрою задачу. Исправлять это, делаю синхронизацию между стаканами без явного бизнес-кейса использования двух стаканов одновременно, смысла не вижу.
