### ISSUE TITLE
[OTHER] Убрать опечатки в справке "Арбитражная раздвижка"

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1053]
Подправить текст для справки "Арбитражная раздвижка", а именно:
![2023-07-04_17h25_13](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/225e3ace-a9a7-407f-92b4-c0fc902b5a34)

**Comment by MorozovDen** [comment]
Готово
