### ISSUE TITLE
[FEATURE] Менять активный инструмент через настройки виджета

### ISSUE THREAD

**Issue by aronsx** [alor-broker/Astras-Trading-UI#1054]
### Опишите проблему, которую решает ваша фича

Для выбора инструмента требуется добавлять виджет на дашборд, либо держать его в свернутом виде, чтобы можно было выбрать нужный тикер. Если на дашборде находится один виджет выбора инструмента (обычно максимум один, т.к. и так много полезного пространства занимает), то приходится переключать цветовые лейблы, для выбора инструмента для определенного стакана.

Если зайти в настройки скальперского стакана или графика чарта и выбрать интрумент в поле и сохранить - стакан/чарт отвяжется от цветовой группы

### Опишите предлагаемое вами решение

При входе в настройки стакана/чарта и при выборе инструмента в графе тикер - менять инструмент во всех привязанных к цветовой группе виджетах

В качестве крутого бонуса было бы очень удобно для перехода к этой строке в настройках использовать горячую клавишу и сохранение настройки по клавише enter (переход к настройке в активном интсрументе, на котором находится указатель мыши)

### Опишите альтернативные решения, о которых вы думали

Альтернативным решением добавление всплывающего меню поверх активного виджета с полем выбора интрумента. 
Возможно с кнопкой в шапке виджета, либо по горячей клавише

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@aronsx проблема понятна. Но мне кажется это будет путать людей. Сейчас выбрать инструмент в настройках надо тогда, когда ты хочешь создать виджет не подключенный к активному инструменту. Я думаю эту проблему можно решить лучше. Сделать виджет-строку с выбором инструмента. Как думаете?

**Comment by aronsx** [comment]
ну виджет строка все равно имеет шапку с цветовым лейблом. это частично решит проблему поиска, но место уменьшит (например на ноуте 13“ место на вес золота). по факту частично подобный функционал уже есть, если сжать до минимума виджет подбора инструмента.

смысл этой фичи скорее возможность сменить инструмент без добавления виджетов и дополнительных пожирателей полезного пространства

если зайти в настройки любого виджета, который привязан к цветовой группе и поменять тикер в настройке, то установка этого тикера для всей цветовой группы и обновление во всех виджетах этой группе воспринимается более интуитивно понятным исходом, нежели открепление от цветовой группы виджета и обновление в нем тикера

**Comment by aronsx** [comment]
случайно на планшете не туда кликнул и закрыл таску

**Comment by PilgrimViis** [comment]
Я тут немного сомневаюсь, честно говоря. Проконсультируюсь с коллегами и решим будем делать или нет.

**Comment by PilgrimViis** [comment]
Мы решили эту проблему по другому, но близко к вашему "алтернативному решению" Сегодня или завтра опубликуем. Теперь вы можете кликнуть на заголовок виджета и изменить инструмент прямо там.

**Comment by sbelashevskiy** [comment]
Реализрвана смена инструмента черех заголовок виджета в рамках https://github.com/alor-broker/Astras-Trading-UI/issues/772
