### ISSUE TITLE
Мобильная версия Astras на iPad

### ISSUE THREAD

**Issue by aronsx** [alor-broker/Astras-Trading-UI#1060]
### Опишите проблему, которую решает ваша фича

В данный момент астрас не работает на ipad 
Десктопная версия не кликабельна, а мобильная версия не открывается

![IMG_31BBA9A3C9EF-1](https://github.com/alor-broker/Astras-Trading-UI/assets/45541409/e49b4542-f3b1-4c1c-a7fc-cdbaad4a7a35)

### Опишите предлагаемое вами решение

Добавить возможность открывать мобильную версию на ipad, которая адаптирована по телефоны
Весь требуемый тач функционал там реализован

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
> Как скоро можно увидеть на astras.alor.ru/mobile?
> 
> Пока не работает
сегодня опубликуем
