### ISSUE TITLE
[BUG] Цвет заявки в скальперском стакане (светлая тема)

### ISSUE THREAD

**Issue by PullPlus** [alor-broker/Astras-Trading-UI#1071]
### Опишите баг

Проблема с цветом первой выставленной заявки, в скальперском стакане (светлая тема). 

### Воспроизведение

Использовать светлую тему.
Использовать скальперский стакан.
Выставить заявку.

При выставлении второй заявки, цвет приходит в норму.

### Среда.

Windows. 
Подробностей от клиента нет.
Скорее всего, не зависит от платформы.

### Ожидаемое поведение

Заявку должно быть хорошо видно.

### Скриншоты

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/92271662/78f27038-ff4b-43a0-a75c-61052b83d11f)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/92271662/e6f9a547-70d7-4c96-a08a-e9ec5e1c8e4f)

### Правила

- [X] Я согласен следовать правилам

**Comment by aronsx** [comment]
менять цвет наслоившихся заявок вполне полезно, да и проблем с зеленым цветом на зеленом фоне лично я не испытываю в светлой теме. может просто сделать цвет одиночной заявки более контрастным?

**Comment by PullPlus** [comment]
Да, допустим можно сделать потемнее. Вопрос не в том что бы сделать так же как при 2х заявках.
Просто, на плохих мониторах (например дешевые TN-матрицы) может быть плохо видно такое сочетание.

**Comment by PilgrimViis** [comment]
Давайте сделаем чуть потемнее текст.
