### ISSUE TITLE
[BUG] Невозможно назначить Ecs в горячих клавишах, так как по escape закрывается модальное окно

### ISSUE THREAD

**Issue by aronsx** [alor-broker/Astras-Trading-UI#1072]
### Опишите баг

невозможно назначить Ecs в горячих клавишах, так как по escape закрывается модальное окно

### Воспроизведение

1. зайти в настройки горячих клавиш
2. выделить любой инпут для указания клавиши
3. нажать эксейп

### Среда.

- macos Venturs
- edge
- v113

### Ожидаемое поведение

в инпуте указана клавиша Esc, модальное окно осталось открытым для возможности дальшейшего сохранения 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Не вижу большой пользы от клавиши Esc в данном контексте. В то же время, ломать UX и делать так чтобы для этого окна Esc игнорировалась тоже не очень правильно. Возможно вам подойдут клавиши Delete или Backspace?
