### ISSUE TITLE
[FEATURE] Отображение цен в стакане

### ISSUE THREAD

**Issue by sergshabal** [alor-broker/Astras-Trading-UI#1075]
### Опишите проблему, которую решает ваша фича

Сделать в стаканах одинаковое количество знаков после запятой для цен

### Опишите предлагаемое вами решение

сейчас столбец цен выглядит примерно так:
4.5
   4
3.5
   3
   2
1.5

А должен выглядеть так:
4.5
4.0
3.5
3.5
2.5
1.5

### Дополнительная информация

<img width="506" alt="Снимок экрана 2023-07-12 в 13 59 28" src="https://github.com/alor-broker/Astras-Trading-UI/assets/669294/3eecf4d8-ae98-42b4-b882-a5c8c1b54e08">

### Правила

- [X] Я согласен следовать правилам

**Comment by sergshabal** [comment]
<img width="278" alt="Снимок экрана 2023-07-12 в 14 18 38" src="https://github.com/alor-broker/Astras-Trading-UI/assets/669294/97997860-be43-4458-ae5d-8cc0bc5ce38b">
Вот пример стакана валюты. Аски в данном случае выглядят терпимо, а вот лесенка из бидов выглядит плохо.

**Comment by sergshabal** [comment]
в скальперском такая лесенка и в бидах и в асках

**Comment by PilgrimViis** [comment]
Давайте сделаем в виде опции.
