### ISSUE TITLE
[FEATURE] Выставление стоп-лоссов и тейк-профитов на графике

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#1079]
### Опишите проблему, которую решает ваша фича

выставляю отдельно стоп-лосс или тейк-профит заявками без отражения уровней на графике

### Опишите предлагаемое вами решение

Реализовать визуальное отражение и возможность перемещений заявок стоп-лосс или тейк-профит на графике. Пример реализации https://drive.google.com/file/d/1Ihe02kETqmY3tfjOCTkt1mkAHgb95hRE/view?usp=drive_link

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Не получается посмотреть пример. 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/a60c75a3-d0f2-4d14-8af7-579d1f923ff8)

@profull-art можете сделать доступ для всех пожалуйста?

**Comment by profull-art** [comment]
Открыл доступ

чт, 9 нояб. 2023 г. в 10:28, PilgrimViis ***@***.***>:

**Comment by profull-art** [comment]
Открыл доступ
