### ISSUE TITLE
[FEATURE] Автоматическое выставление заявок на закрытие.

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1081]
### Опишите проблему, которую решает ваша фича

Думаю будет плюсом добавить функционал в стакан на закрытие сделок ( с 2х сторон) , а именно автоматическое выставление столоса и лимитки на закрытие. 

### Опишите предлагаемое вами решение

В настройки стакана добавить "Автоматизация".
Лимитная заявка на закрытие (в пунктах или процентах)   (ни тейкпрофит, а именно лимитка , т.к. по тейкпрофиту будет проскальзывание)
Стоплосс заявка (в пунктах или процентах) 

К примеру:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/dc0a6384-8515-4401-9a7f-f5c545ae7f73)

//в пунктах
Лимитная заявка на закрытие 100
стоплосс 30 

Выставляем лимитку на вход в рынок (покупка) , после исполнения заявки автоматически в стакан выставляется встречная заявка на закрытие через 100 пунктов (лимитная) и стоплосс на 30 пунктов ниже точки входа

один из параметров можно оставить пустым , а второй прописать .... в этом случае выставится только один из ордеров. 

Не важно войти по лимитке или по рынку, работать должно в обоих случаях.  
Стоплосс и лимитку можно передвигать после выставления. 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@uncrashable у нас появились связанные заявки. Пожалуйста переформулируй в терминах наших связанных заявок и мы сделаем

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/7923ffbc-4491-45a8-9daa-af7e046b74ac)

**Comment by uncrashable** [comment]
Попробую =) 
В скальперский стакан (далее сс) добавляем раздел, (как то его надо обозвать, "Автоматизация" к примеру, он пригодится еще т.к. надо будет со временем феатуру доделать с Условными заявками для сс ):
и так.. раздел "Автоматизация" 

Заявка на закрытие  [ 0 ] ( при =0  выставляться не будет) // можно добавить выбор % или пункты
StopLoss [ 0 ]
, если 
Заявка на закрытие  [ 100 ] 
StopLoss [ 20 ], то 

при входе в рынок , не важно как (рыночной или лимитной) , система выставит сразу две заявки 

1) лимитная , на закрытие позиции (система должна считать, в какую сторону я стал (лонг или шорт) , если в лонг , то автоматически выставится заявка на шорт , с той лотностью которая у меня на руках, на 100 пунктов от цены входа. 
2) стоплосс на 20 пунктов ниже  от цены входа. Если в терминах попробовать описать, то тут выставиться связная заявка по цене = цена входа - 20 пунктов, в кол-ве = N (т.е. сколько лотов было на входе) , условие меньше сигнальной цены,  тип маркет.


Пример: 

Настройка:
Заявка на закрытие  [ 100 ] 
StopLoss [ 20 ] 

Сделка: 
Вход по рынку по цене 100, на 50 лотов в лонг
автоматизация выставит лимитку в шорт по цене 200

StopLoss по цене 30.
