### ISSUE TITLE
[BUG] Условная заявка не выставляется по инструменту MGTSP

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#1084]
### Опишите баг

При формировании условной заявки по инструменту MGTSP (TQBR) МГТС-4ап и MGTS (TQBR) МГТС-5ао на  ФР МБ заявка не выставляется, т.к. не активны кнопки купить/продать в виджете Выставить заявку.
Изменение параметров сигнальной цены, условия (больше/меньше) не приводит к результату (кнопки не активны)
![Снимок экрана 2023-07-19 в 10 41 42](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/a698f2c4-7f97-4bda-810d-1d3c41937e66)

### Воспроизведение

1. выбрать инструмент MGTSP (TQBR) МГТС-4ап
2. открыть виджет Заявки
3. выбрать тип Условная
4. проставить параметры условной заявки
5. попробовать нажать на кнопку Купить/продать - они не отражаются активными (нажать невозможно)

### Среда.

браузер Chrome Версия 114.0.5735.198 (Официальная сборка), (x86_64)

### Ожидаемое поведение

При формировании условной заявки и проставлении параметров заявки должны быть активны кнопки Купить/Продать для выставления заявки.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Важное дополнение. Через другой терминал и через API напрямую, заявка ставится.
