### ISSUE TITLE
[FEATURE] Заявка с графика. Шаг цены

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#1095]
### Опишите проблему, которую решает ваша фича

Имеем виджет Тех.анализа и инструмент с некоторым шагом цены (для примера - MOEX:KMTZ и шаг 0.5).
Когда водим указателем около шкалы с ценой, то значения отображаются корректные, т.е. с шагом. - округляются к ближайшей цене.
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/5d62b472-9c55-4e2e-a880-3262aa0f2147)

При выставлении заявки с графика, т.е. нажатия (+), в виджет выставления заявки попадает точная цена щелчка. Кнопки покупки/продажи при этом логично блокируются, поскольку цена некорректна, однако происходит это молча и не очень понятно почему.

При этом если встать в поле с ценой и подвигать значение колесом мыши или клавишами Up/Down, то цена меняется на положенные 0.5, но новые значения аналогично некорректны, т.к. не кратны 0.5. Справиться с этой ситуацией одной мышью будет затруднительно

https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/72b539a7-448a-4130-862a-8534e4345e28

### Опишите предлагаемое вами решение

1. При выставлении заявки с графика, значение цены брать аналогично тому, что отображалась на графике с учетом округления.
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/6b38899e-a68e-4380-bfb9-e5d41609ae6a)

2. В случае когда пользователь сам вставил значение с некратной ценой, то при использовании колеса мыши или Up/Down - первым изменением цены делать округление до шага цены. Т.е. если пользователь вставляет 310.9, то при нажатии Up менять на "311", вместо "311.4". 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/fcd0947d-5457-49f7-b1a9-c72d8e857e21)

### Правила

- [X] Я согласен следовать правилам

**Comment by agushasok** [comment]
решено в рамках https://github.com/alor-broker/Astras-Trading-UI/issues/1084
