### ISSUE TITLE
[BUG] Автоматически не сдвигаются виджеты после удаления блоттера "Лента" 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1099]
### Опишите баг

При закрытии "Ленты"  все виджеты остаются на месте , (не смещаются вверх). 
Как например если открыть , а потом закрыть виджет "Сводка по портфелю" , то все виджеты займут это пустое пространство. 

### Воспроизведение

1. Создать виджет "Лента" 
2. закрыть виджет "Лента"
3. Посмотреть на реакцию остальных виджетов

### Среда.

WIN 7 
Chrome

### Ожидаемое поведение

окна должны занять свободное пространство , как на примере закрытия остальных виджетов

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Согласен с Сергеем. Это не баг, это фича, чтобы не менять размер рабочего пространства если оно зафиксировано снизу. Если же сверху, то если вариант только расширять виджеты, меняя их размеры. Что само по себе неправильно по моему мнению.
