### ISSUE TITLE
[FEATURE] Размер лота в окне информации на фондовом рынке МБ

### ISSUE THREAD

**Issue by EvgenyMargolin** [alor-broker/Astras-Trading-UI#110]
### Опишите проблему, которую решает ваша фича

 Часть клиентов вопрос задают (где посмотреть размер лота по инструменту на РЦБ) или же у них не принимается заявка именно из-за неправильно рассчитанного объема заявки из-за отсутствия информации о лотности. 
Объем заявки в окне ввода заявки - это хорошо, но по этому объему у клиента будут вопросы - откуда он такой насчитался, если информации о лотности нет на виду.

### Опишите предлагаемое вами решение

Добавить в окно информации по умолчанию поле с информацией о размере лота. Такое поле есть в АТ и квике.

### Дополнительная информация

Еще один момент - в то же окно информации можно добавить поле со статусом торговли по этому инструменту. Это уже не факт, что нужно. Но бывали случаи, когда клиент пытается поставить заявку по бумаге, по которой торги в данный момент не проводятся. 

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Хорошо, сделаем.
