### ISSUE TITLE
[BUG] Виджеты перекрывают друг на друга 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1100]
### Опишите баг

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/6f689f7a-f0f3-4432-ad07-7952b87fc8df)

### Воспроизведение

1. создать виджет "Сводка по портфелю" 
2. Открыть любой другой виджет

### Среда.

Win 7
Chrome

### Ожидаемое поведение

Виджеты не должны накрывать другой виджет со сводкой

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Ожидаемое поведение. Никакого перекрытия нет. Увеличивается кол-во виджетов на дашборде - уменьшается размер строки. Дашборд не может расти бесконечно.  Нужно просто увеличить высоту виджета:

**Comment by uncrashable** [comment]
https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/1ccf981b-5625-4f2b-8434-86d6bee64434

**Comment by uncrashable** [comment]
там прям пол текста перекрывает

**Comment by sbelashevskiy** [comment]
Там текст не перекрывается. Весь дашборд разбит на строки и столбцы. Каждый виджет занимаем определенное кол-во столбцов и строк. Добавляя новый виджет добавляется определенное кол-во столбцов и строк. При этом экран физически не расширяется. Т.е на каждую строку приходится высота экрана / кол-во строк. Также для столбцов.

Когда дашборде слишком много виджетов, каждая строка сжимается.
На виджет "Сводка по портфелю" приходтися 1 строк. После добавления нового виджета ее высота уменьшаяет и содержимое виджета сжимается.

Как решить эту проблему я описал выше

**Comment by PilgrimViis** [comment]
Они не перекрывают друг друга. Сергей в принципе подробно расписал что происходит. Если тебе мешает такое поведение, то надо увеличить виджет-строку в 2-3 раза и потом начинать добавлять виджеты.
