### ISSUE TITLE
[BUG] Отображение надписи в скальперском стакане "Режим - стоп-лимит заявка" 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1102]
### Опишите баг

Несколько раз замечал, но не пойму как воспроизвести. 
Иногда вижу что в стакане указывается надпись "Режим - стоп-лимит заявка"  , хотя никакие клавиши не нажаты. 
Причем если нажать Ctrl (по умолчанию) то она пропадает, потом не воспроизводится

### Воспроизведение

1. открыть скальперский стакан
2. не знаю что сделать нужно , 

### Среда.

Win7 
Chrome

### Ожидаемое поведение

такого быть не должно

### Скриншоты

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/176e25de-6aab-4528-afbe-86f2fc69a403)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Недостаточно информации. Ни  разу такое не наблюдал и сейчас не наблюдаю
Непонятно какая схема кликов мыши используется,
Сколько стаканов,
Это только на одном стакане или сразу не всех

https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/7bb9a114-af52-492b-9750-0faee590177b

**Comment by uncrashable** [comment]
https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/bf29a776-6e64-409f-b20b-8ac074a23f16

то же видео где я показать хотел наезд виджетов.... вот поймал я этот баг или что это ... вообщем он у меня появляется когда я пытаюсь сделать видео запись , зажимаю правый шифт и принт скрин и после у меня эта надпись остается  на всех стаканах

**Comment by sbelashevskiy** [comment]
Это проблема в приложении для захвата видео с экрана. При нажатии Shift+PrtScn (или Ctrl+ЗкеЫст) оно перехватывает управление и ASTRAS вообще не видит чтобы пользователь отпускал клавишу Shift. ASTRAS вообще перестаёт видеть нажатия клавиатуры, пока не будет выполнено действие в приложении для захвата видео

1. Технической возможности исправить это нет
2. Далеко не все пользователи используют такие приложения
3. При повторном нажатии проблема исчезает

**Comment by PilgrimViis** [comment]
Давайте попробуем сделать чтобы по клику оно убиралось хотя бы. Полностью поддерживать мы это просто не сможем, т.к. расчитывать что Астрас будет совместим со всеми горячими клавишами всех программ это просто наивно, но так мы хотя бы сможем нивелировать цену ошибки. Чтобы человек просто куда-то кликнул и оно пропало. 
@sbelashevskiy попробуй тогда так сделать, если получится то получится, если нет то я закрою задачу как wont'fix.
