### ISSUE TITLE
[FEATURE] Выставление заявки. Отображение изменения цены в % от текущей позиции.

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#1105]
### Опишите проблему, которую решает ваша фича

Изначально требуется выставить лимитную заявку на определенный процент от текущей позиции.
На текущий момент сделать это быстро можно так:
В виджете ТА выбрать инструмент "Диапазон цен". От своей позиции выставить нужный процент, при этом опустить курсор около края шкалы, чтобы в том же месте нажать (+) и выставить заявку по нужной цене.
https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/612ecf46-cb11-41c9-ba1c-5d4004132790
В целом работоспособно, хоть и не очень удобно. Плюс, заявка с графика ТА открывает модальный виджет "Выставления заявки", а не умеет пользоваться отдельным виджетом (как это делает стакан).

### Опишите предлагаемое вами решение

При наличии позиции по инструменту, в поле с ценой лимитной заявки в правом стороне выводить процент от текущей позиции
![123](https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/dd680ba2-c7ad-4cdb-8587-cad173363791)
При изменении цены стрелками, колесом мыши, или выборе новой цены из стакана - менять это значение соответственно.
Отображать либо тем же цветом, что и цена, но использовать "+"/"-", т.е. "+2.3%" / "-1.4%" в зависимости от направления цены (выше/ниже) текущей позиции, либо разными цветами - зеленый (выше), красный (ниже), как на скриншоте выше.
Применить для полей в условной (цена, сигнальная цена) и лимитной (цена) заявке.
Сделать включение возможности опциональным для виджета.

### Опишите альтернативные решения, о которых вы думали

В ТИ это сделано отдельной отдельной строкой, сразу с подсчетом потенциальной прибыли
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/f5c67f54-e6e7-4cad-bdeb-f4177779da0a)

### Правила

- [X] Я согласен следовать правилам

**Comment by agushasok** [comment]
Договорились не делать опциональным возможность включения опции
