### ISSUE TITLE
[BUG] Приходят некорректные уведомления после исполнения условной заявки

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1114]
### Опишите баг

1. Если включить уведомления в браузере и выставить **стоп**, то после его исполнения, "в колокольчике" или в нативном уведомлении придут лишние уведомления по рыночной заявке (дубликаты и заявки с ценой 0):
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/fca891cc-9186-4373-a1ff-1d12626b5b9d)
![2023-08-04_16h51_41](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/20ba7d00-dedd-4acb-92f8-ba18d4b633ee)

2. Если выставить **стоп-лимит**, то после исполнения условия стоп-лимита - "в колокольчике" или в нативном уведомлении приходят несколько одинаковых записей с одним id заявки и ценой, хотя биржевая заявка еще не исполнена:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/11b6e999-3320-47a3-b2b8-27b9c679a510)

### Воспроизведение

1. Разрешить получать уведомления в браузере.
2. Выставить стоп по SBER. Дождаться исполнения стопа и выставление рыночной заявки. 
3. Проверить уведомления "в колокольчике" или нативном уведомлении.
4. Выставить стоп-лимит, дождаться его исполнения и выставления лимитки. Проверить уведомления.

### Среда.

Windows 10
Google Chrome v114

### Ожидаемое поведение

После исполнения условной заявки - по биржевым заявкам (лимитки и рыночные заявки) уведомление приходит только при их исполнении. Приходит одно уведомление с верно указанной ценой и номером id заявки.
Если лимитная заявка не исполнена, то и уведомление не приходит.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я думаю это все же не баг. Бекенд нам присылает именно так. Но дублирующиеся уведомления мне тоже не нравятся. Понятно, что одно из них о том что исполнился стоп, другое что исполнилась рыночная заявка по этому стопу. Но вот третье тут непонятно откуда. Давайте в рамках этой задачи попробуем навести порядок и сделать следующее.
1. Как-то обозначать что сработал стоп, вместо стандартной фразы про исполненную заявку для всех случаев. 
2. Если по рыночным заявкам приходят уведомления с ценой исполнения (а на скрине я думаю именно они) то давайте оставим только его, и уберем с нулевой ценой.
3. Если происходит частичное исполнение, не на полный объем, то было бы неплохо писать "Частично исполнена)
