### ISSUE TITLE
[FEATURE] Создание стоп заявки из графика

### ISSUE THREAD

**Issue by maksim-zakharov** [alor-broker/Astras-Trading-UI#1130]
### Опишите проблему, которую решает ваша фича

Если я кликаю по графику чтобы поставить заявку по выбранной цене
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/8353612/4926a1b8-1bbb-4efc-be75-7b214135a61c)
хотел бы я лимитку - вопросов нет
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/8353612/df99b3c2-b796-4e77-a768-fdf56505cea8)
но если я хочу поставить стоп - цена сюда не проксируется и приходится ручками вписывать цену какую я хотел, если я ее запомнил
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/8353612/4d4c941a-2dcd-4a2b-9e26-8e3f900813da)

если выбрать limit - там появляется поле price и там цена есть да

### Опишите предлагаемое вами решение

При клике на создание заявки из графика - выбранная цена должна проставляться в triggerPrice по умолчанию также, как и price

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Данную проблему нужно будет решить в рамках https://github.com/alor-broker/Astras-Trading-UI/issues/1108
