### ISSUE TITLE
[FEATURE] Кнопки быстрого закрытия/переворота позиции

### ISSUE THREAD

**Issue by maksim-zakharov** [alor-broker/Astras-Trading-UI#1131]
### Опишите проблему, которую решает ваша фича

Если у меня есть позиция которую я хочу закрыть по рынку - мне нужно:
1) открывать стакан/окно заявки, 
2) вбивать объем 
3) и жать кнопку 

(3 действия). 

Хочется это ускорить.

### Опишите предлагаемое вами решение

В списке позиций сбоку добавить кнопки "Закрыть позицию" и "Перевернуться" которые будут закрываться и переворачиваться по рынку. Итого 1 действие вместо трех. Как реализовано в Тинькофф

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/8353612/18b2ad7e-0420-43a9-a4f8-0706fe013a33)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Лучше бы это сделать контекстным меню:
1. Если добавлять кнопки, то их придется размещать в начале таблицы, т.к. если пользователя этот виджет сделал узким или добавлено много столбцов, то кнопки справа буду  просто скрываться скролом. В то же время добавление кнопок слева еще отнимет место у столбцов
2. Если добавляются кнопки, то клик по ним нужно бы подтверждать, чтобы предотвратить случайный клик. А  вызов контекстного меню и выбор из него определенного пункта уже исключает какое-то случайное действие

**Comment by PilgrimViis** [comment]
Обсудили. Думаю сделать можно, если сделаем чтобы можно было скрывать и добавлять эти кнопки по желанию. В идеале чтобы это было в окне выбора колонок, но так чтобы при этом не занимало много лишнего места.
