### ISSUE TITLE
[FEATURE] Добавление кнопки - закрыть все позиции

### ISSUE THREAD

**Issue by AlexFayzulin** [alor-broker/Astras-Trading-UI#1139]
### Опишите проблему, которую решает ваша фича

Временами, у рынка бывают панические распродажи, и иногда ты можешь застать это в самом начале движения, и закрыть свои позиции оперативно. Но когда в твоем портфеле 20+ позиций, и пока ты кликнешь на каждую, введешь количество, нажмешь продать - проходит уйма времени. Было бы круто иметь кнопку close all на такой случай. Чтобы при ее нажатии по всем позициям в портфеле выставлялся рыночный ордер на продажу. 

### Опишите предлагаемое вами решение

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/143788648/c2ce23ff-4841-4cf1-bbff-67d8b80b6f8c)
Добавить функцию close all positions. возможно в правом верхнем углу на основной панели 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Как думаете, если сделать кнопку в блоттере в строчке с позицией "Закрыть позицию" это решит вашу проблему? https://github.com/alor-broker/Astras-Trading-UI/issues/1131 Вот тут описано подробнее.

**Comment by AlexFayzulin** [comment]
> Как думаете, если сделать кнопку в блоттере в строчке с позицией "Закрыть позицию" это решит вашу проблему? #1131 Вот тут описано подробнее.

Нет, это чуть чуть другой функционал. Он решает проблему, но частично. Скорость исполнения всё равно не та. Закрыть 50 позиций сделав 50 кликов и закрыть 50 позиций сделав 1 клик - это совсем разные вещи.

**Comment by sbelashevskiy** [comment]
Добавлена кнопка в заголовок таблицы позиций
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/a8095ec3-a564-4eb8-868b-4b29e3e08c35)

Кнопка закрывает все отображаемые в таблице позиции. Т.е. если применен фильтр, то закроются только те позиции, которые ему удовлетворяют
