### ISSUE TITLE
[FEATURE] Добавить кладки в блоттере - P/L %, Текущая цена, Доля в портфеле.

### ISSUE THREAD

**Issue by AlexFayzulin** [alor-broker/Astras-Trading-UI#1140]
### Опишите проблему, которую решает ваша фича

Очень не хватает данных вкладок. Обратите внимание как реализовано у конкурентов.  

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/143788648/c254b28b-9578-4e5b-8a16-dcaad64958d7)

### Опишите предлагаемое вами решение

Добавить данные вкладки

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
P\L - уже есть в позициях.
Текущая цена - Можно, но зачем? Ещё есть виджет с выбором инструментов, он показывает цены и их изменениях. Можно настроить список из ваших позиций и наблюдать за ценами.
Доля в портфеле - возможно полезный функционал. Подумаем как можно сделать.

**Comment by AlexFayzulin** [comment]
> P\L - уже есть в позициях. Текущая цена - Можно, но зачем? Ещё есть виджет с выбором инструментов, он показывает цены и их изменениях. Можно настроить список из ваших позиций и наблюдать за ценами. Доля в портфеле - возможно полезный функционал. Подумаем как можно сделать.

P/L есть, но в абсолютных значениях, а в % нет. Вот хотелось бы видеть процентное изменение по позиции. Это существенно удобнее, чем просто видеть сколько денег накапало. 

Виджет "Выбор инструментов" используется для другого - чтобы быстро выбрать какой-либо инструмент, которого еще нет в портфеле. К примеру, у того ж Тинька (и пока у него единственного) реализована штука как в трейдинг-вью. Где ты можешь просто кликнув на график вбить тикер. В Астрас пока самый быстрый способ который я нашел - это через "Выбор инструментов"

**Comment by PilgrimViis** [comment]
@AlexFayzulin в целом согласен с вами про пользу данного функционала. Я думаю сделаем, но не скоро. Тут нужны существенные доработки для расчётов и контроля P\L

По поводу выбора инструментов, хочу обратить ваше внимание что есть ещё такой подход. Может быть будет вам полезно.
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/a61b90e9-2865-4a75-aa19-39951f7c6984)

**Comment by AlexFayzulin** [comment]
> @AlexFayzulin в целом согласен с вами про пользу данного функционала. Я думаю сделаем, но не скоро. Тут нужны существенные доработки для расчётов и контроля P\L
> 
> По поводу выбора инструментов, хочу обратить ваше внимание что есть ещё такой подход. Кликаете на заголовок на стрелочку справа от имени инструмента. Может быть будет вам полезно. ![image](https://private-user-images.githubusercontent.com/6408195/295507382-a61b90e9-2865-4a75-aa19-39951f7c6984.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODA4MjAsIm5iZiI6MTcwNDg4MDUyMCwicGF0aCI6Ii82NDA4MTk1LzI5NTUwNzM4Mi1hNjFiOTBlOS0yODY1LTRhNzUtYWExOS0zOTk1MWY3YzY5ODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDk1NTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJiYmM2MGZiZTVjZGE5MDJhYzIzMGY0YzkyNDI3NDhkNzNjODY2YzE2Y2E3Njg4YjU4ZDM5ZDk1NWU5YzViMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6w44NiKWJWW4fuNa_tOvq2IoGt0_Mo81Sq_DmJpEL4s)

а мне казалось что пнл в процентах это довольно просто и условно как формула работает )  (текущая цена - цена покупки) / цена покупки * 100 вот и PnL в процентах и просто дополнительным столбиком добавить. Как и пункт текущая цена, чтобы в блоттере видеть сразу. 

в маленький уголочек кликать тоже не оч удобно ) удобно - тапать по графику и сразу писать тикер ) пока из виджета выбор инструмента для меня самая удобная навигация, но тоже не идеально

**Comment by PilgrimViis** [comment]
> а мне казалось что пнл в процентах это довольно просто и условно как формула работает ) (текущая цена - цена покупки) / цена покупки * 100 вот и PnL в процентах и просто дополнительным столбиком добавить. Как и пункт текущая цена, чтобы в блоттере видеть сразу.

Ох, видимо ещё от праздников не отошёл. Я перечитал вашу задачу, я не так вас понял. Да, сделаем. Поменял приоритет.

> в маленький уголочек кликать тоже не оч удобно ) удобно - тапать по графику и сразу писать тикер ) пока из виджета выбор инструмента для меня самая удобная навигация, но тоже не идеально

Понял вас, тогда вот ещё одна фишка. Жмёте Ctrl-F И сразу пишите тикер. Курсор автоматически перейдет в поле виджета выбора инструмента.
