### ISSUE TITLE
[FEATURE] Добавить панель объемов в рыночные ордера виджете Заявка. 

### ISSUE THREAD

**Issue by AlexFayzulin** [alor-broker/Astras-Trading-UI#1141]
### Опишите проблему, которую решает ваша фича

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/143788648/6faae6ad-db78-4d24-bea5-bf6aca1b0f4f)
Не хватает такой же панельки, но для входа по рынку

### Опишите предлагаемое вами решение

Добавить такую панель 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@sbelashevskiy сделай пожалуйста вместе с задачей по рефакторингу которую ты сейчас делаешь. Панель должна быть та же самая, не надо делать для этого отдельную настройку. И можно в стоп заявки тоже добавить.
