### ISSUE TITLE
Активация заявки через тикер в Телеграм

### ISSUE THREAD

**Issue by OlgaSHU888** [alor-broker/Astras-Trading-UI#1144]
### Опишите проблему, которую решает ваша фича

Быстрое открытие окна заявки по заданному инструменту через нажатие на тикер в сообщениях Телеграм чата. 

### Опишите предлагаемое вами решение

Связка торгового терминала с ТГ чатом может обеспечиваться посредством создания некой ссылки, в которую "подставляется" выбранный инструмент (при кликанье на тикере). 
По аналогии с обратной ситуацией, когда ТГ чат привязывается к квику или метатрейдеру для автоматического создания в чате сообщений об ордерах, например. 

### Опишите альтернативные решения, о которых вы думали

Встроить в Астрас чат, который будет внутренним и который сможем связать с окнами заявок. Потом настроить автоматический экспорт сообщений из внешнего ТГ чата во внутренний чат Астраса

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Дубликат https://github.com/alor-broker/Astras-Trading-UI/issues/1038

**Comment by MorozovDen** [comment]
На самом деле не дубликат. На сколько понимаю, тут другая задача у Ольги.
