### ISSUE TITLE
[FEATURE] Быстрое переключение дашбордов 

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#1145]
### Опишите проблему, которую решает ваша фича

Быстрое и удобное переключение дашбордов.

### Опишите предлагаемое вами решение

Удобно было бы, если переключение по дашбордам осуществлялось не через комбобокс, как сейчас, а кнопками вверху на черной полосе. Сразу за комбобоксом выбора дашборда пустое пространство. Сейчас надо ткнуть в комбобокс, затем в выпадающем списке попасть в мелкую строчку - не очень удобно переключаться.
Кнопки можно сделать небольшие, разноцветные и с одной заглавной буквой названия дашборда. Не знаю, насколько это предложение будет удобно на телефонах, но, чтобы сократить место на вехней полосе, слово "заявка" можно убрать, оставить пиктограмму добавления заявки или добавить иконку и слово "заявка" над графиком. В 99% случаев заявку добавляют или через тык в стакане на цене или по любой кнопке на графике или около него.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Fixed #1143
