### ISSUE TITLE
[BUG] В светлой теме лишний зеленый фон после чистки лок. хранилища

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1147]
### Опишите баг

Если почистить локальное хранилище (localStorage.clear()) или открыть Астрас в режиме инкогнито в любом браузере в светлой теме, то при появлении модалки советов (`joyride-step__container`)  ставится background-color: rgba(56, 142, 60, 0.7). После клика на "крестик" зеленая заливка пропадает. В темной теме такого нет, нужно убрать:
![2023-09-05_17h22_25](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/4a0dd6f8-94b3-4c48-8dd7-b000c9695b26)

### Воспроизведение

1. Зайти в Астрас, выбрав светлую тему приложения.
2. Нажать F12 и в Console ввестиl ocalStorage.clear().
3. Обновить страницу и подождать пару секунд.

### Среда.

Windows 10,
Google Chrome v114.0.5735.110
Mozilla Firefox v117.0

### Ожидаемое поведение

В светлой теме, как и в темной, при появлении советов фон терминала не становится зеленым.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я думаю это некритично. Пусть будет

**Comment by PilgrimViis** [comment]
А хотя с другой стороны, может и стоит пофиксить. У нас же сейчас настройки с сервера получаются. Да и по идее не особо сложно должно быть. Ладно, давайте исправим.

**Comment by sbelashevskiy** [comment]
@ilya7am
Вообще это нелегитимный кейс. После переноса настроек на сервер так настройки больше сбрасывать нельзя. Настройки должны сбрасываться через меню профайла.

**Comment by ilya7am** [comment]
Кейс также воспроизводится в режиме инкогнито в любом браузере (в светлой теме), без какой-либо чистки данных в консоли. Думаю, лучше все равно подправить
