### ISSUE TITLE
Секундный тайм фрейм (интервал)

### ISSUE THREAD

**Issue by Haliavschik** [alor-broker/Astras-Trading-UI#1152]
### Опишите проблему, которую решает ваша фича

Добрый день!
Прошу в Астрас добавить секундный тайм фрейм (интервал).
1-5-10 сек.
Удобный скальперский тайм фрейм, который позволит более точно входить в сделку.

### Опишите предлагаемое вами решение

Добавить секундный тайм фрейм (интервал).

### Опишите альтернативные решения, о которых вы думали

На данный момент пользуюсь трейдингвью алор. Но в нем нем горячих клавиш.

### Правила

- [X] Я согласен следовать правилам

**Comment by Haliavschik** [comment]
Добрый день!
Подскажите ориентировочный срок исполнения.

**Comment by PilgrimViis** [comment]
Секундные у нас есть. Но есть страх, что будет оно тормозить. Проверь пожалуйста.

**Comment by Haliavschik** [comment]
Я не вижу секундного тайм фрейма в астрасе.
