### ISSUE TITLE
[BUG] Ошибка Bad request при редактировании кол-ва лотов (Выставить заявку)

### ISSUE THREAD

**Issue by zlobinm** [alor-broker/Astras-Trading-UI#1153]
### Опишите баг

При редактировании количества лотов в виджете Выставить заявку , появляется ошибка в уведомлении:

Ошибка
Http failure response for https://api.alor.ru/commandapi/warptrans/FX1/v2/client/orders/estimate: 400 Bad Request

### Воспроизведение

1. Создать виджет Выставить заявку
2. Удалить число по умолчанию, чтобы остался 0 (placeholder="0")

### Среда.

- Google Chrome 116.0.5845.141 (Официальная сборка), (64 бит)
- Mozilla Firefox 116.0.5845.141 (Официальная сборка), (64 бит)
- Microsoft Edge - 116.0.5845.141 (Официальная сборка), (64 бит)
- Yandex Браузиор

### Ожидаемое поведение

Не влияет на выставление заявки.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
#1108 Исправлено будет в рамках этой задачи.
