### ISSUE TITLE
[BUG] Отображение некорректного портфеля в блоттере при входе в новый договор без денег 

### ISSUE THREAD

**Issue by Patimov** [alor-broker/Astras-Trading-UI#1167]
### Опишите баг

Пользователь осуществил вход в Астрас по реквизитам нового договора, на котором нет активных портфелей с деньгами. В меню выбор портфелей отображается "Нет портфелей". При этом в блоттере отобразился портфель другого пользователя, который ранее осуществлял вход в Астрас под своей учетной записью. Вход в режиме частного окна также не решил проблему. После пополнения портфеля проблема не исчезла. Но закрытие блоттера и повторное открытие проблему решило.
На скриншоте портфель 75024CM не имеет отношения к данному договору.

### Воспроизведение

Зайти в Астрас под новой учетной записью с портфелями без денег в браузере, из под которого ранее были входы под другими учетными записями с деньгами.

### Среда.

- ОС Windows 7
- Яндекс Браузер
- Версия 23.7.5.704 64 бит

### Ожидаемое поведение

Отображение в блоттере только тех портфелей, которые имеют отношение текущей учетной записи.

### Скриншоты

![Screenshot_1](https://github.com/alor-broker/Astras-Trading-UI/assets/144675227/4784f174-5312-46b2-aa86-115ad1aee71a)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я правильно понимаю, что никакого нарушения конфиденциальности не было? По сути только заголовок виджета "Блоттер" имел имя от прошлого пользователя?

Вообще Астрас не поддерживает работу с портфелями без зачисленных денег\бумаг. По многим виджетам будет неприятный опыт у пользователя. Я думаю проблему нужно решить радикально и не давать логинам без портфелей заходить в Астрас. Обсужу с коллегами.

**Comment by Patimov** [comment]
Насколько я понял, нарушения конфиденциальности не было. Только заголовок виджета "Блоттер" имел имя от прошлого пользователя.

Совсем радикально не хотелось бы. Поскольку как иначе проверить, поступили ли денежные средства на счет. И наоборот, при выводе, увидеть, что всё списано, задолженности нет, итд.

**Comment by sbelashevskiy** [comment]
Вообще данное поведение не зависит от того есть у учетной записи портфели без денег или нет. Ранее это была общая проблема при смене учетной записи.

Такое поведение наблюдалось, когда настройки виджетов хранились в браузере пользователя без привязки к учетной записи. 
Когда менялся логин, настройки оставались прежними, виджет пытался получить данные по портфелю (который хранится в настройка виджета блоттер), но API  никакой информации не выдавал.

Сейчас настройки хранятся на сервере и прикреплены к учетной записи.
Единственный возможный вариант воспроизвести это - если пользователь когда-то раньше запускал старую версию приложения, то при запуске новой версии настройки перемещаются на сервер.
Но даже в этом случае API не выдаст никаких данных по портфелю.
Пользователю будет достаточно переключить портфель/удалить и добавить заново виджет блоттер/привести дашборд к стандартному виду/выполнить сброс настроек терминала.

**Comment by PullPlus** [comment]
"не давать логинам без портфелей заходить в Астрас", слишком непонятное решение со стороны пользователя. Он, скорее всего, сразу побежит в техподдержку.

Было бы хорошо как-то вывести предупреждение об отсутствии портфелей, с рекомендацией заведения средств для их открытия и получения полного функционала.

**Comment by PilgrimViis** [comment]
Да, давайте так и сделаем. Предлагаю сделать в виде модалки, чтобы человек точно не пропустил эту информацию. В ней нужно написать следующее.
"Часть функционала терминала недоступна, если у вас нет портфелей без позиций или денег. Если пока не решили переводить ли позиции к нам или нет, но хотите посмотреть терминал вы можете сделать следующее:
1. Через кабинет клиента зачислить 10 рублей через СБП на любой ваш портфель.
2. Если не хотите зачислять деньги, то можете посмотреть видео на youtube про Astras либо посмотреть документацию https://alor.gitbook.io/astras которая может дать представление о функционале

Если вы уверены, что на ваших счетах есть деньги или позиции, то свяжитесь с тех. поддержкой, мы попробуем разобраться в проблеме"
