### ISSUE TITLE
[FEATURE] В окне выставления заявки брать цену bid/asc при нажатии

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#118]
### Опишите проблему, которую решает ваша фича

При открытии заявки со стакана нет возможности оперативно изменить цену при резком движении цены.

### Опишите предлагаемое вами решение

При выставлении заявки при нажатии на цену из bid/asc - подставлять это значение в поле с ценой.

### Опишите альтернативные решения, о которых вы думали

Сделать возможность выставлять не конкретную цену, а просто "bid"  ("ask"), как это реализовано в AlorTradingView, например.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Тут правда осталась какая-то проблема в стаканах которые сильно двигаются. Надо изучить поближе.

**Comment by sbelashevskiy** [comment]
В текущем виджете есть проблема с возможностью клика по ячейке с ценой при быстром обнолвении стакана. 
Данная проблемв была вынесена и решена отдельно (см. Issue #167 )

Реализация запрошенной функциональности быдет выполнена в следующих фазах, возможно вместе с реализацией Issue #142
