### ISSUE TITLE
[FEATURE] Переименовать поддержку в Телеграм

### ISSUE THREAD

**Issue by Tattydes** [alor-broker/Astras-Trading-UI#1184]
### Please describe, is your feature request related to a problem?

Сейчас непонятно, что пункт "Поддержка" подразумевает переход в Телеграм

![11140bd0fd](https://github.com/alor-broker/Astras-Trading-UI/assets/116548833/abc8437f-b3ec-49a1-baa4-ac578da5a5ca)

### Describe the solution you would like

Переименовать на "Телеграм"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contribution guideline

**Comment by MorozovDen** [comment]
тогда уж лучше "Поддержка в ТГ"
