### ISSUE TITLE
[FEATURE] Сохранение настроек в скальперском стакане

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1186]
### Опишите проблему, которую решает ваша фича

В данный момент у нас нет сохранения настроек каждого стакана в отдельности

### Опишите предлагаемое вами решение

Необходимо реализовать автоматическое сохранение настроек на каждый стакан отдельно 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Имеется в виду, чтобы настройки стакана были привязаны к инструменту и сохранялись без участия пользователя при смене инструмента и обратно.
