### ISSUE TITLE
[FEATURE] Корректировка поля сетки в скальперском стакане и выделение "круглых" чисел

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1188]
### Опишите проблему, которую решает ваша фича

Прошу скорректировать отображение линий ценовых уровней и шрифта самих цен на целых значениях.
Сетка , которая у нас сейчас разделяет стакан - малофункциональная и постоянно смещается относительно цен . 

 

### Опишите предлагаемое вами решение

1. Прикрепить сетку , что бы она не "ездила" ( на видео обратите внимание , что при перемещении стакана, сетка съезжает)  - сетка должна быть статичной. 
 

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/b313a598-b6fb-4454-af32-6ce48ea2959b

2. Выделить жирной линией "круглые" значения в стакане(555,00 , 556,00 и т.д.) , а так же шрифт целых значение цен также выделить жирным 
![chrome_kOf9QNFgZK](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/48fb6ba6-9efd-43a3-be4f-3d840a17161d)
Пример на Сбере 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/be4fef75-6b29-40e6-ab1c-a295be835b5f)
в некоторых приводах есть настройка 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/b8b62aff-b4ac-4ff5-b5e5-1d82ccedae01)
Тут можно выбрать с каким шагом будут основные и промежуточные уровни отображаться .
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/101ebf15-c436-4603-a8e9-7a9b20986615)

### Правила

- [X] Я согласен следовать правилам

**Comment by uncrashable** [comment]
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/693adc54-8796-4b75-a74e-bc45085e5759)
для примера

**Comment by sbelashevskiy** [comment]
Этот функционал уже реализован
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/f540c08f-d2f2-49c7-bab5-441debe6e701)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/1e2dfde7-89ef-48f4-844d-38549f54f6f6)
