### ISSUE TITLE
[FEATURE] Добавить возможность рисования в виджет "График" 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1189]
### Опишите проблему, которую решает ваша фича

Виджет "График" очень удобный из-за его компактности, скальперы постоянно используют маленькие графики под стаканом. 

### Опишите предлагаемое вами решение

Прошу добавить возможность рисовать на графике , хотя бы самые элементарные - горизонтальные линии и наклонные линии (луч) для построения трендов.  
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/43957967-51b1-4a38-b149-0220a64dd494)
виджет теханализ не подходит 

### Правила

- [X] Я согласен следовать правилам

**Comment by uncrashable** [comment]
![Uploading image.png…]()
Эти два инструмента нужны

**Comment by sbelashevskiy** [comment]
Виджет график не поддерживает рисование. Это легковесный график, предназначенный исключительно для отображения.

Могу как альтернативу предложить в настройки графика тех. анализа добавить опции какие панели отображать.
По умолчанию все панели будут включены и график будет отображаться как сейчас.
Если для пользователя что-то избыточно, то он просто это оключает.
Таким образом график тех. анализа можно привести к виду:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/144c60ba-79a5-455c-a024-c58c9384e0d0)

**Comment by PilgrimViis** [comment]
@sbelashevskiy прикольно, не знал что так можно.
