### ISSUE TITLE
[TECHNICAL] Смена темы в тех. анализе

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#1190]
### Опишите проблему, которую решает ваша фича

При переключении темы на самом чарте тема меняется только частично.

### Опишите предлагаемое вами решение

1. Попробовать отключить использование localStorage: use_localstorage_for_settings, save_chart_properties_to_local_storage. Но судя по всему это не работает
2. Реализовать логику изменения темы: переопределять свойства чарта, удалять/обновлять запись tradingview.current_theme.name в localStorage

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Спасибо. Тоже хотел задачу создать. Надо ещё раз посмотреть в чем может быть проблема. Только давай не сейчас, а на следующей неделе займемся ей.
