### ISSUE TITLE
[FEATURE] Изменить дизайн кнопок

### ISSUE THREAD

**Issue by Tattydes** [alor-broker/Astras-Trading-UI#1197]
### Please describe, is your feature request related to a problem?

Кнопки в светлой теме выбиваются из общего стиля

### Describe the solution you would like

Изменить цвет и скругление у кнопок

**Макет:** https://www.figma.com/file/qUctvS64BOn5a03j3ZG2yl/Astras?type=design&node-id=1479%3A1761&mode=design&t=z7Yt7jbXrQS1X0O8-1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contribution guideline

**Comment by sbelashevskiy** [comment]
Исправлены только стили кнопки "Отмена". 

Представленные стили неполные и противоречивые. Disabled кнопка в одном месте имеет такой же цвет, что и обычная в другом. Нет стилей для hovered/focused состояний.

Более такого в используемом фреймворке нельзя так просто брать и менять отдельные элементы и их разновидности. Цветовые схемы хранятся в переменных и изменение цвета одного элемента аффектит другие.
Так изменение одной кнопки аффектит вообще ВСЕ кнопки в приложении.
Цвета нужно подбирать по специальному калькулятору https://theme.antd.group/

Предлагаемы изменения затрагивают вообще все кнопки (т.к. как раз меняет дефолтный стиль кнопки) причем на обоих темах. Применение такой цветовой схемы делает текст кнопок нечитаемым, а в hover/focused режимах еще и режет глаз.

Кроме того по умолчанию в темной и светлой теме кнопка имеет цвет фона равный основному цвету и контрастную границу. В hovered/focused режимах рамка и текст принимают primary цвет. Это более согласуется с подходом используемого фрэймворка и цветовых схем.

Кроме того, такая кастомизация породит проблемы обновления используемого фреймворка и использования других его элементов. Именно в результате такой кастомизации кнопка "Отмена "стала иметь такой неприглядный вид.
Во-первых, при настройке цветовых схем она уже отличалась от других кнопок.
Во-вторых, кнопка принимала цвет основного текста. Поменяли цвет текста (https://github.com/alor-broker/Astras-Trading-UI/issues/1094) и кнопка стала черной
