### ISSUE TITLE
[BUG] Постоянное открепление виджета 'график' от группы

### ISSUE THREAD

**Issue by AFoXi** [alor-broker/Astras-Trading-UI#1206]
### Describe the bug

При нажатии на тикер в списке Позиций в блоттере происходит открепление виджета графика от группы. Приходится заново прикреплять к группе.

### Reproduction

1) создать виджеты: график, блоттер. 2) объединить их в группу. 3) выбрать в блоттере раздел Позиции (в портфеле должны быть какие-то позиции). 4) кликнуть на позицию. В этот  момент происходит открепление виджета график. 

### Platform

MacOS, Chrome

### Code of Conduct

- [X] I agree to follow this project's terms

**Comment by sbelashevskiy** [comment]
Проблема исправлена в https://github.com/alor-broker/Astras-Trading-UI/issues/1193

**Comment by AFoXi** [comment]
у меня проблема сохранилась.

https://github.com/alor-broker/Astras-Trading-UI/assets/84922533/09514c3f-4207-497d-84c3-01162ce17f4a

**Comment by sbelashevskiy** [comment]
Задача имеет статус Awaiting Publication - релиза изменений еще не было

**Comment by AFoXi** [comment]
Благодарю!
