### ISSUE TITLE
[FEATURE] Добавить большее количество цветов на якорь

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1208]
### Опишите проблему, которую решает ваша фича

Для скальперских стаканов удобно , когда вместе с инструментом в стакане , автоматически меняется и привязанный к нему график. У нас сейчас слишком мало якорей (цветов) 

### Опишите предлагаемое вами решение

Добавить большее кол-во цветов для якоря  ( 20 шт ) [правка 8шт)
Можно использовать цвета с цифрами или символами , а то цветов не хватит 

### Опишите альтернативные решения, о которых вы думали

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/bf7d72bb-c206-4a8e-bf4e-7c613de81cbf)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я не понимаю зачем нужно 20 различных привязок? Можешь подробнее описать в чём проблема пожалуйста?

**Comment by uncrashable** [comment]
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/2c2e9761-52d9-470d-abaa-a515d56498fd)
У меня не большой монитор , помещается 8 стаканов. 
У кого то будет 10 , ну и с запасом , если кто то будет использовать 2 монитора  или 4К монитор где стаканов будет много якорей не хватит.  Стакан привязывается к графику снизу , для быстрого переключения , т.е. я меняю тикер в стакане , а график автоматом меняется из-за якоря.  Сейчас возможно подвязать только 5 стаканов таким способом, хотелось бы побольше. 
Хотя лучше бы придумать систему привязки по большему количеству. Необязательно цвета, а символы или цвет и цифра, или что бы самому можно было вводить символы для привязки.

**Comment by PilgrimViis** [comment]
Хорошо, давайте добавим цвета до 8 штук.
