### ISSUE TITLE
[BUG] Некорректное исполнение стоп-заявки

### ISSUE THREAD

**Issue by Patimov** [alor-broker/Astras-Trading-UI#1226]
### Опишите баг

Пользователь открыл позицию по Si-12.23 29.09.2023 в 12:34:20. Выставил стоп лимит на продажу в 12:41:43 с ценой триггера 97490. Такой цены в данную торговую сессию не было, но в 13:05:14 стоп исполнился, была выставлена заявка на продажу, которая исполнилась по цене рынка 97713-97117.

### Воспроизведение

Выставить стоп-лимит на продажу

### Среда.

ОС Windows 8.1
Браузер Chrome Version 109.0.5414.165 (Official Build) (64-bit)

### Ожидаемое поведение

Корректное исполнение стопа. Отсутствие активации в данном случае.

### Скриншоты

![photo_2023-10-03_17-15-43](https://github.com/alor-broker/Astras-Trading-UI/assets/144675227/8246a7d3-f73c-4ba2-b42e-c5405221b5f6)

### Дополнительная информация

Информацию по заявкам и сделкам приложу дополнительно при необходимости.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Задачу передали коллегам. Так как она вообще не связана с UI Астрас, а только с бекендом, то тут задачу закрою.
