### ISSUE TITLE
[FEATURE] Заполнение значения "Остаток" на вкладке "Стоп" виджета блоттер

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#1227]
На указанной вкладке поле "Остаток" всегда имеет значение "0/qty", т.е. даже если заявка выполнена у нее всегда будет одно и то же значения.
Это значение захаркожено:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/d5974769-93c0-4d20-be9c-bd9e60567006)

Судя по респонзу API нужное поле приходит:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/aa1e85f0-38f3-417c-bdc6-9be6064426ad)

хотя его и нет в документации.

Нужно использовать это поле, а не константу 0

**Comment by PilgrimViis** [comment]
Скорее всего бекенд всегда возвращает 0. Но давай возьмем поле с бэка, так лучше всё равно.
