### ISSUE TITLE
[BUG] Ошибки в карточке по облигации

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#123]
### Опишите баг

в карточке по облигации ошибки: написано: Ближная Put (орфографическая ошибка), Ближнаяя Call (орфографическая ошибка)

### Воспроизведение

1. Поправить орфографию

### Среда.

версия

### Ожидаемое поведение

Поправить орфографию

### Скриншоты

![photo_2022-05-04 18 03 40](https://user-images.githubusercontent.com/104637334/166711860-3acb27a8-bec4-44e1-bd93-0bb26836a90b.jpeg)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
https://www.investopedia.com/articles/investing/031513/guide-embedded-options-bonds.asp 
Прошу удалить про Put и Call. Про орфографию оставить, мы поправим.
