### ISSUE TITLE
[FEATURE] Поиск инструментов для нестандартных режимов торгов 

### ISSUE THREAD

**Issue by PullPlus** [alor-broker/Astras-Trading-UI#1233]
### Опишите проблему, которую решает ваша фича

Для поиска инструмента, в нестандартном режиме торгов, приходится использовать выражение:
MOEX:ISIN:TQOD
<Биржа>:<ISIN>:<Режим>

Это не очевидно! 

### Опишите предлагаемое вами решение

Добавить фильтр режимов, для поиска.

### Опишите альтернативные решения, о которых вы думали

Добавить описание того как искать эти инструменты, в справку.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Это не очевидно, но этот функционал и нужен очень редко. Добавлять фильтр во все поисковые окна с тикерами (а минимум 3 + почти  в каждых настройках виджета) тоже весьма странная трата рабочего места. Как вы это видите?

**Comment by PilgrimViis** [comment]
В общем я согласен что проблема есть. Но я понятия не имею как её решить, чтобы это не занимало место и было удобно. Посоветовался с коллегами, они тоже не предложили ничего интересного. Ваша идея про отдельный виджет мне кажется всё таки избыточно. Поэтому закину задачу на будущее, если появятся идеи мы вернемся к ней.
