### ISSUE TITLE
[FEATURE] Доработать отображение сделок на графике

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#1237]
### Опишите проблему, которую решает ваша фича

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/21736dfb-f429-47ad-899b-d3c2ebe8bf54)

Здоровенный значок! Ну, кто придумал его использовать?)))
Во-первых, свечки перекрывают. Во-вторых, не сильно вяжется по теме - прямо как на картах: вот тут ты вчера кофе попил, а тут тебя ограбили в подворотне.

Второй момент - точность позиционирования. Вот для примера, 3 заявки:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/d229f857-b68c-4a11-b9a1-512bd2dc41bc)

А вот как они отображаются в зависимости от ТФ:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/cbc969d5-0552-4b85-a038-36bf6c97d1a6)

Т.е. на 1D они числятся 29ым числом, а всё что меньше - 28ым. Выставлены по своей цене, а свечка не та. В итоге болтаются значки, там где даже и цена не ходила.

### Опишите предлагаемое вами решение

1. Взять другой значок, поменьше. Сделать цвета менее яркими или, может, прозрачнее - всё же это вспомогательный элемент.
2. Позиционировать значок в тот временной интервал, где была сделка.
3. Во всплывающее поле добавить дату и время сделки.

### Опишите альтернативные решения, о которых вы думали

Еще предлагаю рассмотреть необходимость отображения каждой сделки. При небольшом количестве - всё неплохо, но если какой-нибудь скальпер включит их отображение на 1H или 1D - получит карту злачных мест, вместо свечек. В том же ТИ, например используется группировка сделок внутри ТФ, а сам значок расположен над хаем свечки
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/acfcb176-499b-4c1c-bf27-fe8736fec383)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
1. Мы можем использовать только те значки, которые предлагает график (которые доступны из меню рисования для пользователя). Не нравится значок - предложите какой использовать, да такой, чтобы его было видно на разных масштабах и такой чтобы для него был тултип для размещения дополнительной информации, да такой, чтобы его можно было привязать к ЦЕНЕ, чтобы потом можно было отследивать среднюю цену (см. исходную задачу https://github.com/alor-broker/Astras-Trading-UI/issues/974)
2. На приложенных вами скринах вообще ничего не видно. У вас были сделки 28 числа, они и отображаются судя по всеми. Либо приложите нормальные скрины с осью цен. На приложенных скринах время сделок вообще не совпадает
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/7368136e-9228-422b-a5c9-76d44700fe15)
3. Цвет выбран как раз для того, чтобы значки было видно когда они попадают на свечки. Это исключительно на ваших скринах такой масштаб, что значки значительно больше свечек. Увеличьте масштаб и посмотрите как выглядит

**Comment by PilgrimViis** [comment]
Соглашусь с коллегой, к сожалению этот спорный вариант это компромисс, с тем чтобы иметь и функционал и решить проблему. TV весьма ограничивает нас тут.

**Comment by PilgrimViis** [comment]
Задачу пока закрывать не буду, отложим на будущее. Может через некоторое время сможем найти альтернативное решение.

**Comment by dzeron13** [comment]
Коллеги, извините за долгий ответ.
1. В качестве значка я бы предложил, что-то такое и такого размера:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/46c0d959-9b9e-4b7b-876c-4992ce3594ac)
Вы прилагаете скриншоты, на которых масштаб такой, что ширина свечи >= ширине значка. На таком масштабе свечки обычно не смотрят, поэтому в реальности на 1D это выглядит так:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/99450543/cbdd24f2-3590-42a9-b113-57b1f6ae6cad)

2. В части дат, да. И посмотрел не туда и после очистки и обновления значки отображаются корректно. Проблема была, что они выстраивались на линии одного ТФ, а не разных согласно их времени. Считаем временным глюком.

3. Отображение даты/времени в тултипе, видимо, по возможности.

**Comment by sbelashevskiy** [comment]
`В качестве значка я бы предложил, что-то такое и такого размера:`
Что это за значок и где он находится на панели рисования?
У него есть тултип?

Мы можем отрисовывать только те объекты, которые есть на панели рисования

**Comment by dzeron13** [comment]
Теперь понял. Я думал это просто значок нарисованный, а это готовый элемент со своим значком. Тогда, конечно, отбой.

**Comment by PilgrimViis** [comment]
В общем задачу частично решили, сам значок сменить не можем из-за ограничений ТВ. Поэтому закрою задачу.
