### ISSUE TITLE
[BUG] Прыгает панель сделок при изменении размера окна 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1239]
### Опишите баг

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/c776de34-c2f3-4a1a-a23c-c10dd386b279

При изменении размера окна , постоянно происходит какой-то "перерасчет" в панели со сделками 

### Воспроизведение

Создать виджет Скальперский стакан
Изменить внутренние размеры панели кластеров или размер  таблицы с ценами и объемами

### Среда.

WS 7 
Chrome

### Ожидаемое поведение

Очень сбивает. 
При изменении окна , "перерасчет" происходить не должен

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Панель "прыгает" потому что для отрисовки нужно знать сколько по ширине сделок отрисовать.
Перерасчет ДОЛЖЕН происходить чтобы корректно производить отрисовку.

Что за кейс такой когда пользователь все время сидит и изменяет размер панели в виджете?

**Comment by sbelashevskiy** [comment]
Кроме того, я даже такого поведения не наблюдаю

https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/39d21a19-d17f-4455-8164-6b99aa72a17a

Указанных данных явно не хватает для идентификации проблемы. Больше походит на то, что компьютер пользователя по производительности не тянет отрисовку

**Comment by uncrashable** [comment]
Кейс: 
1. Когда в стакане появляется бОльший объем - приходится немного расширять стакан - происходит отрисовка 
2. Когда в панеле кластеров уже набрался больший объем , и не видно сколько там суммарно в кластере уже набралось 

Чаще всего , происходит из-за просмотра кластеров , т.к. их постоянно сдвигаем , подбираем ширину, и часто смотрим кластера на истории.   Это не сильно критично , но очень сбивает , кажется что резко куда то рынок полетел.

**Comment by sbelashevskiy** [comment]
Странно. Такое ощущение, что наблюдается это в какие-то определенные периоды, но не постоянно.
Пару часов назад получалось поймать, сейчас нет:

https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/2634d67c-f445-4b2f-8f77-70d254db515e

Но, как минимум, при изменении размера панели вижу отправку запроса к API по кластерам. Возможно это тормозит при каких-то пиковых нагрузках.

**Comment by uncrashable** [comment]
https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/c71685e0-83ab-444f-b954-02e5400cad52

Вот тут даже когда центровку просто кликаешь , все дергается.
