### ISSUE TITLE
[FEATURE] В окне "Выбор инструмента" нет связи с графиком

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#124]
### Опишите проблему, которую решает ваша фича

При выборе в диалоге "Выбор инструмента" нет "замка" или нет связи с графиком, чтобы их вместе связать и переходить на график.

### Опишите предлагаемое вами решение

При выборе в диалоге "Выбор инструмента" добавить связь с графиком, чтобы можно сразу переходить на график.

### Дополнительная информация

![photo_2022-05-04 18 20 15](https://user-images.githubusercontent.com/104637334/166715621-7e2c6d0f-3d83-4f5f-b28d-bdbaef4ef79c.jpeg)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Это что-то странное. Связь должна быть! Похоже на баг, но не понятно как это воспроизвести. Надо выяснить.

**Comment by PilgrimViis** [comment]
Я предполагаю, что проблема в том, что после изменения настроек виджет перестал "следить" за активным инструментом. Так или нет?

**Comment by maximvt** [comment]
Сегодня все работает как надо с выбором   в диалоге "Выбор инструмента".  Возможно помогло то что я вчера обновил браузер до последней версии.
