### ISSUE TITLE
[BUG] Сбиваются выбранные объемы при входе в меню

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1240]
### Опишите баг

Сбивается выбранный Рабочий объем после входа в меню скальперского стакана 

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/e54d41ec-fdd8-44e9-91d9-d9b56146e103

### Воспроизведение

Создать виджет скальперский стакан 
настроить рабочие объемы 
Переключить на 2-3 или 4ый объем. 
Зайти в меня настроек стакана (шестеренка) 
Выйти из меню 

### Среда.

WS 7
Chrome

### Ожидаемое поведение

Рабочий объем должен оставаться таким же , как и при входе в данное меню. 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Выбранный объем никогда не сохранялся при входе в меню и при перезагрузке страницы.
Элементарно в настройках объем может быть изменен, удален, тогда сохраненных выбор будет некорректен.

**Comment by PilgrimViis** [comment]
Давайте сделаем чтобы сохранялось. Иначе люди могут не заметить и на другие объемы выставить заявки.
