### ISSUE TITLE
[FEATURE] Научить программу понимать шрифт "неверной" раскладке клавиатуры 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1241]
### Опишите проблему, которую решает ваша фича

При  поиске инструмента , не всегда обращаю внимание на выбранный язык системы и могу написать в поиске 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/75afe55c-791e-4d2e-aec2-1af2bd5d45a1)
ПФЯЗ вместо GAZP(тикер Газпрома) 
, можно ли научить программу что бы она считывала запрос учитывая оба языка ( транслитерацию) или как это правильно называется ...  

### Опишите предлагаемое вами решение

... 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Считаю что данная фича не имеет смысла, т.к. переключить раскладку это 1 нажатие на клавиатуре. И даже может быть вредна. Например, ты ищешь какой-то гипотетический инструмент ПАО Кировский "ПФЯЗ", а тебе выдает Мечел.

В качестве совета по решению проблемы, советую поискать какие-то расширения для браузера, возможно есть что-то что решит твою проблему.
