### ISSUE TITLE
[FEATURE] Оповещения

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1243]
### Опишите проблему, которую решает ваша фича

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/d83279f5-3481-4e11-95be-a6e6442bc969)
При активном трейдинге эти оповещения очень мешают. Давайте куда нибудь их спрячем. 

### Опишите предлагаемое вами решение

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/ccaf00ae-b710-48fc-84d1-53411f891df3)
у нас есть большая панель вверху , предлагаю сделать окно таким же способом с возможностью прокрутки 

### Правила

- [X] Я согласен следовать правилам

**Comment by uncrashable** [comment]
как в квике

**Comment by sbelashevskiy** [comment]
Оповещения отключаются в настройках профиля:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/4b2617ea-4d99-4803-a24a-788902b50348)

Если не отключаются какие-то определенные оповещения, но нужно указать какие.
Судя по скринам не отключаются оповещения о создании группы

**Comment by PilgrimViis** [comment]
Уведомления выключатся в настройках.
