### ISSUE TITLE
[FEATURE] Отображение уровней в стакане и на графике.

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1244]
### Опишите проблему, которую решает ваша фича

Трейдеры очень часто используют уровни , в стакане и на графике. Хотел бы улучшить функционал отображения. 

### Опишите предлагаемое вами решение

Добавить горячую клавишу для установки уровня в стакане, который бы автоматически дублировался на график(который привязан к стакану)  и наоборот.  
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/7a46fe68-c805-4dd4-84b7-2d05de17ef8d)
На скриншоте видно , был выставлен уровень, в стакане он подсвечивается с датой (дату не  обязательно делать)  и на графике  он так же отображался прямой линией  , вот такой вариант сделать , просто полоска 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/b0285fe0-00d6-46ec-98b7-4902114aa217)

По возможности, сделать что бы данный уровень чертился на всех графиках , которые имеют общей якорь. 
Включая виджет График и  Тех анализ. 
Помню Вы говорили что рисовать в виджете график нельзя , но может таким образом мы получим желаемое. Т.е. тут рисование получится через стакан. 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/1082

**Comment by PilgrimViis** [comment]
Дубликат https://github.com/alor-broker/Astras-Trading-UI/issues/1082
