### ISSUE TITLE
[BUG] Перерасчет средней цены при частичном закрытии сделок

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1245]
### Опишите баг

Средняя цена не перерасчитывается , при частичной закрытии позиции.

### Воспроизведение

1. Скальперский стакан 
2. Зайти в сделки по разным ценам. Посмотреть среднюю.
3. Закрывать по частям позиции и смотреть среднюю цену (которая не меняется) 

### Среда.

WS7
Chrome

### Ожидаемое поведение

При частичном закрытии позиции средняя так же должна постоянно перерасчитываться. 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@uncrashable 
в блоттере средняя цена обновляется?
совпадает со значением в стакане?
обновляется после перезагрузки страницы?

**Comment by PilgrimViis** [comment]
Желательно номера сделок или заявок. Есть подозрение, что проблема на бекенде.

**Comment by PilgrimViis** [comment]
И что значит "закрывать по частям позицию". Значит ли это что твоя заявка разбилась на несколько сделок или что ты выставлял несколько заявок чтобы закрыть позицию?

**Comment by uncrashable** [comment]
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/3a299ad4-0ef9-418c-afc9-f647c96f988d)

**Comment by uncrashable** [comment]
https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/0b6d6ca8-83ad-45fb-9c84-22b643dc83a9

Попробовал перезагрузить страницу , когда находился в сделке и часть позиции закрыл , -  не пересчитывается она

**Comment by uncrashable** [comment]
> И что значит "закрывать по частям позицию". Значит ли это что твоя заявка разбилась на несколько сделок или что ты выставлял несколько заявок чтобы закрыть позицию?

Закрыть позицию частями это означает выставить заявку не на полный объем , который у тебя на руках , и раздробить ее. 

Если я вхожу в позицию 1 лотом, потом еще и еще , у меня на руках  3 лота например и я ставлю не одну  лимитную заявку , что бы закрыть сразу 3 лота , которые у меня на руках , а по частям  , т.е. я ставлю 1 ...выше еще 1 лот и еще выше 1 лот. 


Ну тут можно по разному закрывать .... сперва 1 лот потом 2 , или 2 потом 1 ... - частями

**Comment by sbelashevskiy** [comment]
Со стороны ASTRAS я проблем не вижу - не могут кол-во лотов в позиции обновиться, а цена не обновиться.
Значения в стакане и блоттере совпадают.
Соответственно, цена не пересчитывается на беке

**Comment by PilgrimViis** [comment]
Мы проверили на фронтенде проблемы быть не должно. Я сообщил коллегам с бекенда о проблеме. Т.к. с нашей стороны мы больше ничего сделать не сможем, то задачу закрою.

**Comment by Extred** [comment]
Это ожидаемое поведение, средняя цена считается именно так. По опросу клиентов - большинство за такой расчет (не FIFO или аналоги).

**Comment by PilgrimViis** [comment]
> Это ожидаемое поведение, средняя цена считается именно так. По опросу клиентов - большинство за такой расчет (не FIFO или аналоги).

Т.е. частичное закрытие позиции не меняет среднюю цену? Ну нифига себе новости блин... Очень странно.
