### ISSUE TITLE
[FEATURE] Добавление индикаторов теханализа

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#125]
### Опишите проблему, которую решает ваша фича

Не хватает индикаторов теханализа. 
Например, Аллигатор Била Вильямса, ADX (Averega Directianal Index),  MACD, только ADX нужен полный с тремя линиями, а не с одной.

### Опишите предлагаемое вами решение

Добавить индикаторы теханализа. 
Аллигатор Била Вильямса, ADX (Averega Directianal Index) (только ADX нужен полный с тремя линиями, а не с одной), MACD.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Да, такое в планах есть. В будущей мажорной версии сделаем.

**Comment by PilgrimViis** [comment]
Зависит от https://github.com/alor-broker/Astras-Trading-UI/issues/181

**Comment by PilgrimViis** [comment]
Сделали и опубликовали. Только ADX вроде с одной линией только. Но надо в настройках графика полазить, может там будет.
