### ISSUE TITLE
[FEATURE] Отображение времени в истории сделок

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#1253]
### Опишите проблему, которую решает ваша фича

Сейчас в истории сделок отображается только дата, без времени, которое иногда нужно, как минимум для разработчиков (когда нужно сопоставить историю сделок с отображение на графике, например)

### Опишите предлагаемое вами решение

Отображать дату и время

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Время будет занимать лишнее место. Для исторических сделок в большинстве случаев нужна только дата. Но если прям надо, то можно в отдельную колонку наверное вынести.

**Comment by sbelashevskiy** [comment]
Когда возникает какой-то вопрос по сделкам, что без времени их идентифицировать невозможно. Простой пример: https://github.com/alor-broker/Astras-Trading-UI/issues/1237.
Пользователь приложил историю откуда-то. Время со временем терминала вообще не совпадает.
Запрашивать скрин с терминала бесполезно - время сделки есть только у суточных сделок. В истории только даты

**Comment by PilgrimViis** [comment]
В общем давай добавим, только без секунд. Т.е. 15:58 например.
