### ISSUE TITLE
[BUG] Список инструментов дублируется на новом дашборде

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1256]
### Опишите баг

Если в виджете "Выбор инструмента" создать новый список инструментов, то в нем отобразятся все бумаги с текущего выбранного списка:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/cd039dde-95ac-4413-b5ae-ba2d3d58e000

После перезагрузки страницы новый список отображается корректно.

### Воспроизведение

1. Составить список разных бумаг в watchlist.
2. В настройках виджета "Выбор инструмента" создать новый Список.
3. Переключиться на него. Посмотреть на его отображение.
4. Добавить новый тикер. Обновить страницу.

### Среда.

Windows 10
Google Chrome v117.0.5938.13

### Ожидаемое поведение

Для каждого Списка инструментов - свой watchlist бумаг, который не дублируется при создании нового Списка.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Будет решено в рамках #742
