### ISSUE TITLE
[FEATURE] Открыть панель кластеров по двойному клику

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1259]
### Опишите проблему, которую решает ваша фича

Можно ли сделать , что бы при нажатии двойным кликом мышь , панель кластеров открывалась полностью ... вот так 

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/a51ce48f-55f6-42da-9892-b8d443983af4)

и повторном нажатии возвращалась как было до ее полного открытия 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/1f163dc6-4f11-4fd8-9eb7-f20ad12f344b)

### Опишите предлагаемое вами решение

... 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@sbelashevskiy прокомментируй пожалуйста

**Comment by sbelashevskiy** [comment]
Думаю, можно

**Comment by uncrashable** [comment]
Панель кластеров должна открываться не смещая часть стакана , в котором прописаны объемы и цена. 
Т.е. она должна по 2ому клику перекрыть панель принтов. 
При повторном двойном клике, она возвращается в положение, при котором видно один вертикальный столбик панели кластеров.

**Comment by uncrashable** [comment]
Типо такого 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/d96d7b34-86d7-4e4e-881c-746b55152eff)

**Comment by uncrashable** [comment]
https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/6b62611b-4574-4d89-9389-35ded6266e8b

Например как это реализовано
