### ISSUE TITLE
[FEATURE] В блоттере по фьючерсам сделать фильтр по не нулевым позициям

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#126]
### Опишите проблему, которую решает ваша фича

На срочном рынке в таблице фьючерсов, мешают визуальному восприятию лишние строки по фьючерсам с нулевыми позициями. 

### Опишите предлагаемое вами решение

Предложение, в таблице фьючерсов, в блотере как-то убрать фьючерсы, по которым у меня нет позиций или сделать фильтр не нулевых позиций.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/101 вот эти 2 задачи связаны. Возможно решаются одинаково.

**Comment by PilgrimViis** [comment]
Исправили вместе с  #145
