### ISSUE TITLE
[FEATURE] Автоматическое снятие SM при закрытии позиции

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1261]
### Опишите проблему, которую решает ваша фича

При закрытии позиции лимитной заявкой в скальперском стакане, SM(который выставляется по шифту) остается стоять в стакане.  После закрытия сделки , он уже не нужен.

### Опишите предлагаемое вами решение

После закрытия сделки SM должен сниматься автоматически 

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/76aae3c4-caa6-4a1c-b492-b7587c89a0cc

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Мы уже обсуждали этот вопрос. В данной задаче я не вижу, чтобы ты как-то решил те проблемы которые я перечислял. Мы не можем внедрять фичи, которые будут мешать торговле тех, кто НЕ торгует внутри дня. Мы не будем снимать заявки клиентов, потому-что для скальперской торговой стратегии заявки больше "не нужны". Прошу больше не создавать дубликаты этой задачи, пока мы не добьёмся консенсуса по этому вопросу при встрече о которой договаривались. Если ты не согласен с этим подходом, мы можем привлечь рабочую группу или руководство к обсуждению.
