### ISSUE TITLE
[BUG] Приходят уведомления при отключенной функции

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1263]
### Опишите баг

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/00fe1bdf-791a-418d-bc69-151b6892d496

### Воспроизведение

Создать виджет скальперский стакан 
В меню отключить уведомления 
Выставить заявку , после исполнения приходит уведомление

### Среда.

Ws7
Chrome

### Ожидаемое поведение

Должны срабатывать только выбранные уведомления

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
В настройках отключаются уведомления, которые показываются в правом верхнем углу.
На видео push-уведомления, которые либо отключаются совсем, либо для определенного портфеля
