### ISSUE TITLE
[BUG] Подсветка объемов

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1264]
### Опишите баг

При выбранной настройке , объемы должны подсвечиваться по другому. 
Если у меня в настройках выставляется "заполненость полосы объема"  50 000 , то в стакане "мелкие объемы" должны отображаться минимальной (почти не видимой заливкой), а сейчас они отображаются в полном объеме, как будто не реагируют на настройку. 

### Воспроизведение

Создать виджет скальперский стакан 
В настройках стакана выбрать выделение объема "По границам ..." 
Выставить в "заполненность полосы объема" большое значение 

### Среда.

Ws7
Chrome

### Ожидаемое поведение

Описал выше 

### Скриншоты

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/f4bf3341-f4cf-4689-9f89-d79f23394ea4

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
На видео нет подсветки вообще. 
Подсветка имеет назначенный цвет
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/d13d66ee-f540-4a24-bff2-d69200347f9f)
На виде отображаются только строки с фоном продавцы/покупатели

**Comment by uncrashable** [comment]
Все верно
