### ISSUE TITLE
[BUG] ... отражение графиков и настройка стакана

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#127]
### Опишите баг

1) По тикерам Ebay, Li, Enr, Tcs не корректно отражаются графики. 2)При настройке "стакана" в продвинутых настройках не сохраняются изменения и "Стакан" не отражается после этого.1)

### Воспроизведение

1. поправить и синхронизировать отражение графиков.
2. поправить и сделать возможным индивидуальные настройки стакана 

### Среда.

версия

### Ожидаемое поведение

1. графики синхронизированы
2. реализована возможность индивидуальных настроек стакана

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Некорректно заполнено. Тут две разных задачи. Не указана версия браузера.
