### ISSUE TITLE
[FEATURE] Добавление кнопок плюс/минус в виджетах заявки, для изменения цен и количеств нажатием кнопки мыши

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#1271]
### Опишите проблему, которую решает ваша фича

Для изменения цен и количеств в виджетах заявки необходимо производить или клавиатурой или колесиком мыши, это не совсем удобно. 

### Опишите предлагаемое вами решение

Предлагается добавить рядом с полями цен и количеств плюс/минус, для изменения через нажатие кнопки мыши. Скрин аналогов прилагаю

### Дополнительная информация

![изображение](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/ad828430-3ac8-4f68-9bd8-c628bf30322f)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Мне кажется, что будет только место занимать. Плюс они маленькие, пока ты прицелишься в эти кнопки, больше времени потратишь чем дотянуться до клавиатуры. Да и тем более ты сам сказал, есть колёсико мыши. Сомнительная фича ИМХО. Задачу закрою, если хочешь можем в РГ обсудить отдельно.

**Comment by MorozovDen** [comment]
у нас даже в Алор-трейде это есть. Очень не удобно руку с мыши на клавиатуру перекладывать, реально это отнимает много времени, при том, что потом надо опять руку на мыш, чтобы сделать ей выбор или купить, или продать, энтер же не нажмешь. Колесиком тоже на один пункт сдвинуть еще попасть надо.  Достаточно только плюс и минус.
![изображение](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/213ef6c7-626c-4222-a7d8-48f4c7e4f2b2)

**Comment by ErmakovAnton** [comment]
Поддержу Дениса. Вещь удобная.
