### ISSUE TITLE
[BUG] При исполнении условной заявки в "Остатке" отображаются штуки, а не лоты 

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1273]
### Опишите баг

Сейчас при исполнении условной заявки пишется число исполненных штук, хотя вся заявка - указывается в лотах. Например, по EURRUB_TMS ( 1 лот = 0.01 штук) пишется, что исполнилась 1 штука из 100 лотов:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/bb06333b-72a4-48bf-addd-be8b3b3769da)

Или по CBOM - тоже перемешаны лоты и штуки:
![2023-10-18_16h26_31](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/02eeba61-2177-4bf4-ba08-4af84c8ed342)

### Воспроизведение

1. Выставить условную заявку по EURRUB_TMS, 100 лотов.
2. Дождаться ее исполнения.
3. В блоттере в табе "Стопы" для "Остаток" проверить число исполненных лотов

### Среда.

Windows 10
Google chrome v118.0.5993.72 

### Ожидаемое поведение

Исполненный остаток указывается в лотах, как и весь объем заявки.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Если это так, то это вопрос к бэку.
В ASTRAS берется корректное поле:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/4b0a3b72-e823-4b04-8f6f-6cd94ad9f2d8)


1. При этом это поле приходит, но в документации в описании WS респонза его вообще нет.
2. В других подписках указано, что это поле в лотах
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/a5217da8-ce46-492b-ad15-31699a48141c)

**Comment by PilgrimViis** [comment]
@sbelashevskiy спасибо за рисёрч

**Comment by PilgrimViis** [comment]
На бекенде сделали
