### ISSUE TITLE
[FEATURE] ... окно с заявками и загрузка графика

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#128]
### Опишите проблему, которую решает ваша фича

Не удобное размещение окна с заявками. 
На вкладке график, при переходе с большего таймфрейма на меньший, подгружается история чуть ли не за год, приходиться ждать приличное время, чтобы увидеть график на текущее время.

### Опишите предлагаемое вами решение

окно с заявками размещать как отдельный виджет 
увеличить скорость загрузки графика
сделать фильтр предустановок размера графика: 1, 3, 7 дней, 1, 3, 6 месяцев, 1 год и более

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Это совершенно точно 3 разные проблемы. Прошу разделить их на 3 разных issue. Причем увеличить скорость загрузки графика это дубль. Уже есть баг про долгую анимацию графика.
