### ISSUE TITLE
[TECHICAL] Подумать над новыми правилами eslint

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#1289]
Составить список общий правил, которые мы хотим изменить в наших линтерах.

**Comment by sbelashevskiy** [comment]
https://typescript-eslint.io/rules/array-type - оставить только тип []. Array<> выглядит ужасно
https://typescript-eslint.io/rules/ban-types - не встречал в коде кейсов, но выглядит нужным
https://typescript-eslint.io/rules/default-param-last
https://typescript-eslint.io/rules/explicit-function-return-type
https://typescript-eslint.io/rules/member-delimiter-style

https://typescript-eslint.io/rules/naming-convention - выглядит полезным, но нужно очень аккуратно настроить

https://typescript-eslint.io/rules/no-confusing-non-null-assertion
https://typescript-eslint.io/rules/no-duplicate-enum-values
https://typescript-eslint.io/rules/no-duplicate-type-constituents
https://typescript-eslint.io/rules/no-empty-function
https://typescript-eslint.io/rules/no-extra-non-null-assertion
https://typescript-eslint.io/rules/no-extraneous-class
https://typescript-eslint.io/rules/no-inferrable-types
https://typescript-eslint.io/rules/no-loss-of-precision
https://typescript-eslint.io/rules/no-magic-numbers
https://typescript-eslint.io/rules/no-misused-new
https://typescript-eslint.io/rules/no-mixed-enums
https://typescript-eslint.io/rules/no-non-null-asserted-nullish-coalescing
https://typescript-eslint.io/rules/no-unnecessary-boolean-literal-compare
https://typescript-eslint.io/rules/no-unnecessary-condition

https://typescript-eslint.io/rules/no-unsafe-assignment - нужно проверить есть ли в коде кейсы

https://typescript-eslint.io/rules/no-unsafe-enum-comparison
https://typescript-eslint.io/rules/no-unsafe-return
https://typescript-eslint.io/rules/no-unused-expressions - нужно проверить существующий код
https://typescript-eslint.io/rules/no-unused-vars
https://typescript-eslint.io/rules/no-use-before-define
https://typescript-eslint.io/rules/no-useless-constructor
https://typescript-eslint.io/rules/prefer-nullish-coalescing
https://typescript-eslint.io/rules/prefer-readonly
https://typescript-eslint.io/rules/prefer-string-starts-ends-with
https://typescript-eslint.io/rules/restrict-plus-operands
https://typescript-eslint.io/rules/strict-boolean-expressions - нужно проверить на коде
https://typescript-eslint.io/rules/switch-exhaustiveness-check


Возможно, что некоторые правила уже подключены. Нужно проверять
