### ISSUE TITLE
[FEATURE] ... настройки в окне инструмента

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#130]
### Опишите проблему, которую решает ваша фича

В настройках инструмента, нужно в ручную выбирать название биржи.  Желательно сделать так, чтобы в окошке "биржа" автоматически  прописывалась та биржа, к которой инструмент относится

### Опишите предлагаемое вами решение

В настройках инструмента, нужно сделать так, чтобы в окошке "биржа" автоматически  прописывалась та биржа, к которой инструмент относится

### Дополнительная информация

![photo_2022-05-05 10 18 12](https://user-images.githubusercontent.com/104637334/166878398-481491cb-edf2-4715-b132-6a457e735da0.jpeg)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я не думаю, что это возможно сделать. Давайте посмотрим на SBER. Он торгуется и на московской и на питерской бирже. Поэтому мы автоматически не сможем по тикеру найти биржу. Тикер уникален только в рамках одной биржи. Поэтому закрываю задачу как невозможну.
