### ISSUE TITLE
[FEATURE] Выбор отображаемых таймфреймов в виджете "График"

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#1305]
### Опишите проблему, которую решает ваша фича

Я испытываю трудности когда вижу кучу неиспользуемых мной таймфреймов на графике

### Опишите предлагаемое вами решение

Добавить возможность настройки отображаемых таймфреймов

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я вспомнил, что в ТВ графике есть избранные таймфреймы. В принципе функционал не критичный. Юзкейс редкий.
