### ISSUE TITLE
[FEATURE] Настройка отображаемых панелей в виджете "Тех. анализ"

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#1306]
### Опишите проблему, которую решает ваша фича

По умолчанию в виджете включено отображение всех панелей, которые занимают место
Это затрудняет использование данного виджета для определенных целей, например https://github.com/alor-broker/Astras-Trading-UI/issues/1189

### Опишите предлагаемое вами решение

Вынести в настройки какие панели отображать, чтобы пользователь мог отключать ненужные ему элементы.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
А можно сделать, чтобы это настраивалось из настроек самого ТВ? Может быть у них есть возможность включить настройку отображения этих панелей в своих настройках?

**Comment by PilgrimViis** [comment]
В целом фича интересная. Вопрос что мы можем, а что не можем скрыть. Давайте когда возьмем эту задачу, сделаем скрин терминала и обозначим красными прямоугольниками те области которые могут быть скрыты пользователем.

**Comment by sbelashevskiy** [comment]
Из самого графика панели не отключаются. Это можно сделать только программно. 
Отключить можно практически все. Пример как раз в https://github.com/alor-broker/Astras-Trading-UI/issues/1189#issuecomment-1724963364
