### ISSUE TITLE
[BUG] Ошибка расчета показателей P|L в блоттере

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#1318]
### Опишите баг

В виджете Блоттер во вкладке Позиции не верно отражается показатель P/L дн., по каким то причинам равен показателю Текущие объем.
Также не корректно отражаются данные P/L за день и P/L за день, %. примерно в 100 раз больше.
![Screenshot_37](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/278a26af-c4ac-427a-b500-22b304997f5a)
![Screenshot_38 (1)](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/a6150ccd-04e9-43b6-8390-4f9c9c094464)

### Воспроизведение

1. Открыть позицию
2. Открыть виджет Блоттер
3. Открыть вкладку Позиции/ показатель P/L дн.
4. Открыть вкладку О портфеле, проверить данные P/L за день и P/L за день, %

### Среда.

CHROM

### Ожидаемое поведение

1. Открыть позицию
2. Открыть виджет Блоттер
3. Открыть вкладку Позиции/ показатель P/L дн. -данные должны отражаться с учетом изменения цены рынка по инструменту в сравнении с ценой открытия позиции
4. Открыть вкладку О портфеле, проверить данные P/L за день и P/L за день, % - данные должны отражаться с учетом изменения цены рынка по инструментам в портфеле в сравнении с ценой открытия позиции (суммарно)

### Скриншоты

![Screenshot_37](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/dee621f8-f89a-49f5-80c0-4ff640c26c7b)
![Screenshot_38 (1)](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/06349742-7243-4b3f-9351-dda3accf01fa)
![Uploading image_2023-11-13_12_37_43.png…]()

### Дополнительная информация

Информация от нескольких клиентов

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Проблема на стороне бекенда, им сообщили.
