### ISSUE TITLE
[BUG] В панели сделок в Стакане не всегда отображается количество сделок 

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1327]
### Опишите баг

В Виджете "Скальперский стакан" не отображается часть сделок в панель сделок:
Для фьючерсов, акций часть сделок не отображается (есть квадратик, но нет объёма сделки). Хотя в виджете "Все сделки" сделки приходят. Например, для ALRS-12.23 в стакане пропали сделки на 5 и 15:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/54737f85-7e05-4c29-b47c-8bba095efe14)

Также и для LKOH-12.23 часть сделок не отображается:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/ae99b8df-5208-496e-91e2-092fab1b85f0)

### Воспроизведение

1. Выставить виджеты "Скальперский стакан". Выбрать ALRS-12.23 и LKOH-12.23.
2. Выставить виджеты "Все сделки" по этим двум фьючерсам.
3. Подождать осуществление сделок в панели сделок в стаканах.
4. Проверить отображение данных.

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

Все сделки в панели сделок отображаются корректно, все цифры прогружаются и читабельны.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Рамка потому и пустая, что такой цены нет в стакане
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/34773fef-8200-46c0-b990-18647a956fa7)
 И чтобы этого добиться ты отключил опцию "Показывать цены между лучшими ценами покупки/продажи".
 
 Как раз чтобы это обработать и была сделана такая отрисовки - если цены нет в стакане, то рисуется незакрашенный квадрат
