### ISSUE TITLE
[BUG] При отрисовке Скальперсокго стакана по текущему инструменту пропадают предыдущие сделки

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1328]
### Опишите баг

1. При создании нового Скальперского стакана для текущего инструмента (копирование текущего Стакана или просто через Виджеты)- предыдущие сделки по бумаге не отображаются (как будто инструмент не торгуется). Также и просто при перезагрузке страницы - сделки по текущему инструменту (желтый лейбл) пропадают.

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/7181ad7b-799b-40bd-97d2-1cadb493df89

Но если создать стакан или перезагрузить страницу, когда выбран активным (желтый лейбл) инструмент НЕ в стаканах, то проблема не наблюдается, сделки "не сбрасываются".

2. При смене бумаг отображаются сделки (которые не видны) в самом верху или низу Стакана, хотя это неверно, сделки проходили по другим ценам:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/0ed04917-d514-4cad-9631-d0eb338c550e

### Воспроизведение

1. Активный инструмент - ALRS-12.23. Выставить виджет "Скальп. стакан" по ALRS-12.23.
2. Выставить новый виджет. Проверить панель сделок.
4. Перезагрузить страницу. Проверить панель сделок.
5. Поменять бумагу на VTBR-12.23.Проскроллить панель сделок.

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

1. Сделки в панели сделок не сбрасываются, не пропадают при перезагрузке страницы или выставлении нового виджета.
2. Все последние сделки по бумаге видны в Стакане при смене бумаги и не расположены в самом верху или низу стакана.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
"2. При смене бумаг отображаются сделки (**которые не видны**) в самом верху или низу Стакана, хотя это неверно, сделки проходили по другим ценам:"

Т.е ты начинаешь бесконечно перетаскиванием ползунка мыши начинаешь бесконечно скролить стакан.
Явно же лаг отрисовки из-за скорости скролла

**Comment by sbelashevskiy** [comment]
По пункту 2 я не наблюдаю ничего подобного:

https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/c25c4103-4dd4-438e-b3c4-095372966ac2

@ilya7am при репорте таких багов нужно:
1. Воспроизводить баг больше одного раза
2. Баг  воспроизводить не на пределе производительности твоей машины
3. Баг  воспроизводить по такому же кейсу, как это может сделать пользователь, чтобы это имело хоть какой-то смысл. Пользователь скролит стакан чтобы выбрать нужную цену, а не чтобы просто увести его в какой-то предел. Такой сценарий не предполагает перетаскивание скрола просто мышью - такой скрол рандомный, цена прыгает то вверх, то вниз. Скрол должен производиться колесом мыши, когда хотя бы видно изменение цены
4. Нужно прикладывать больше информации - график изменения цены на инструмент, принт сделок из виджета "Все сделки"

По приложенным данным можно только сделать вывод, что это лаг отрисовки, вызванный некорректным скролом

**Comment by ilya7am** [comment]
@sbelashevskiy, п.2. связан не со скроллом, а с тем, что в панели сделок не отображаются предыдущие сделки при смене инструмента, хотя линия между сделками (зеленая или красная) ведет в самый верх или низ стакана. Как будто предыдущая сделка была по самой дорогой или дешевой цене в стакане. Начинаешь скроллишь в то место, куда ведет полоска- но сделки не видны. Скролл тут нужен, чтобы увидеть, что сделки не отображаются.

1. Переключись на Скальп. стакан, где пустая панель сделок (из-за бага в п.1).
2. Дождись осуществления одной сделки (виджет Все сделки).
3. В стакане в панели сделок появится эта сделка и "бесконечная" полоса перед ней.

Баг воспроизводился на своем ПК, несколько раз по разным бумагам. Это возникает также во время перерисовки стакана и связано с п.1, поэтому указал в этой задаче. Не зависит от включенный опций "отображения нулевых объемов" или "спреда", повторяется в любом теме.
Например, для ALRS-12.23 поймал одну сделку и баг появился опять:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/228d790a-c1a8-442a-8e29-9d54d525f9f4


Для LKOH-12.23 - полоска есть, но при скролле, сделок нет:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/9131402d-dcdf-40b8-920f-075b635193a1)

**Comment by sbelashevskiy** [comment]
@ilya7am, я понимаю, что баг связан не со скролом, потому и нужно детально описывать как его повторять

**Comment by sbelashevskiy** [comment]
@ilya7am ,
напиши еще раз ПОЛНЫЙ сценарий как повторить п2.

В твоем описании п. 1 основывается на наличии нескольких стаканов.
При этом в последнем видео у тебя 1 стакан

**Comment by ilya7am** [comment]
Баг из п.2 можно воспроизвести и на одном, и на неск. стаканах, наличие неск. открытых стаканов не избавит от бага. Когда сделок в панели сделок в стакане нет, и приходит новая сделка по бумаге - то баг появляется. Можно взять один стакан для проверки.

Сценарий:
1. Добавить себе на дашборд неск. бумаг. Например, ALRS-12.23, GAZP-12.23, LKOH-12.23, ROSN-12.23.
2. Выставить один Скальп стакан и виджет "все сделки".
3. Переключаться между инструментами, пока не появится пустая панель сделок по бумаге в Стакане.
4. Дождаться осуществления новой сделки по этой бумаге.
5. Посмотреть на отображение сделок и "линии между сделками" в Стакане.

**Comment by sbelashevskiy** [comment]
Дак в том то и дело, что чтобы воспроизвести этот баг нужно либо два и более стакана на один и тот же инструмент (что бессмысленно с точки зрения пользователя.), либо стакан и виджет "Все сделки" на ОДИН И ТОТ ЖЕ ИНТСТРУМЕНТ.

И переключаться нужно не рандомно тыкая иснтрументы, а так, чтобы по одному инструменту прогрузились сделки, потом переключиться на другой инструмент, по которому проходит очень мало сделок, и дождаться когда на нем появится очередная сделка. Вот тогда сделки миксуются.

А не так, как дано в описании: никаких манипуляций с добавлением стаканов и перезагрузкой страницы вообще не нужно
