### ISSUE TITLE
[FEATURE]Сделать фильтр предустановок размера графика

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#133]
### Опишите проблему, которую решает ваша фича

На вкладке график, при переходе с большего таймфрейма на меньший, подгружается история чуть ли не за год, приходиться ждать приличное время, чтобы увидеть график на текущее время.

### Опишите предлагаемое вами решение

Сделать фильтр предустановок размера графика: 1, 3, 7 дней, 1, 3, 6 месяцев, 1 год и более

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/58 эту проблему решим когда пофиксим этот баг. Поэтому закрываю как дубль.
