### ISSUE TITLE
[BUG] Не выставляются заявки с графика

### ISSUE THREAD

**Issue by Extred** [alor-broker/Astras-Trading-UI#1335]
### Опишите баг

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/3522038/e56d8e19-75e9-4ce3-ae5f-639ab567fae7)

При нажатии на + не вылезает меню. 

### Воспроизведение

1. Сбросить все настройки и кеши
2. Открыть дефолтный дашборд
3. Попробовать выставить заявку с гарфика

### Среда.

Chrome 119.0.6045.160

### Ожидаемое поведение

Появляется меню постановки заявки с графика

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Дубликат https://github.com/alor-broker/Astras-Trading-UI/issues/1333

**Comment by sbelashevskiy** [comment]
Меню и не должно появляться, это не Trading View. Если на дашборде нет виджета "Выставить заявку", то должен открываться диалог
