### ISSUE TITLE
[BUG] Сохранение настроек стакана

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#134]
### Опишите баг

При настройке "стакана" в продвинутых настройках не сохраняются изменения и "Стакан" не отражается после этого.

### Воспроизведение

поправить и сделать возможным индивидуальные настройки стакана

### Среда.

браузер Chrom

### Ожидаемое поведение

сделать возможным индивидуальные настройки стакана с сохранением нового формата стакана

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
К сожалению, не удается воспроизвести этот баг. Нужно больше информации.

**Comment by sbelashevskiy** [comment]
Вероятно, имеется ввиду, что при указании некорректного знаяения для "Группа", виджет становится пустым
![image](https://user-images.githubusercontent.com/29191749/167772196-661b9dae-4d32-4541-8478-787ff41e7ab0.png)
в сравнении с состоянием, когда просто нет данных
![image](https://user-images.githubusercontent.com/29191749/167772241-7c65329b-5696-4c62-96a8-31b71764d463.png)
