### ISSUE TITLE
[FEATURE] Автоматическое масштабирование виджетов

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#136]
### Опишите проблему, которую решает ваша фича

В дополнение к #97 про ширину колонок в блоттере, хочется помянуть автоматическое масштабирование виджетов на рабочей области. Сейчас расставить виджеты по своему усмотрению и в своих пропорциях, это очень тяжело, если не сказать, что невозможно. Открытые виджеты растягиваются на всю область.

Приложил видео со "способом" уменьшения размеров виджета):
https://user-images.githubusercontent.com/99450543/166920233-f4f99c34-20a4-455f-9843-c0269a088543.mp4

Масштабирование ширины колонок в блоттере не отрабатывает при изменении размера виджета:
https://user-images.githubusercontent.com/99450543/166920973-d4033050-5be8-456a-849b-f66a6da0872e.mp4

### Опишите предлагаемое вами решение

Добавить возможность свободно менять размеры виджетов.
Автоматически масштабировать содержимое виджета под размер. Тут имеется в виду "в разумных пределах". Понятно, что если включить отображение всех колонок, а потом сжать виджет до 5 см - глупо чего-то ожидать. Но масштабировать таблицу, минимально сжимая колонки до ширины названия - было бы неплохо.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Проблема понятна. Я предлагаю такое решение, которое мы сможем сделать довольно быстро. Сделаем чтобы по умолчанию (если виджетов нет) сетка была не 1x1, а скажем, 5x3. Если кому-то понадобится растянуть больше, то ему это будет сделать проще.

**Comment by PilgrimViis** [comment]
Я всё таки открою эту задачу ещё раз. Связана ли она с блоттером или нет, пока непонятно, но тут неплохо расписано. Пригодится. А по поводу частичного решения проблемы, при очистке дашборда, вынесу это в отдельную задачу #161

**Comment by PilgrimViis** [comment]
@dzeron13 мне кажется мы это уже сделалали. Если вы говорили о чем-то другом, то можете заново открыть задачу.
