### ISSUE TITLE
[FEATURE] ... Добавить недельный таймфрейм на виджет График

### ISSUE THREAD

**Issue by rasharp** [alor-broker/Astras-Trading-UI#1366]
### Опишите проблему, которую решает ваша фича

В виджете график есть все ТФ кроме недельного (по сравнению с виджетом тех.анализ) Странная дискриминация
![firefox_2IMMPiEIHX](https://github.com/alor-broker/Astras-Trading-UI/assets/43497120/e0437282-697b-42b0-b9a3-d1e74c2d0ff8)
![firefox_Wz9TgSa0nW](https://github.com/alor-broker/Astras-Trading-UI/assets/43497120/ceb0b5a4-693b-42a8-a14a-2dc98b183a80)

### Опишите предлагаемое вами решение

Добавить недельный ТФ в список доступных

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Если в теханализе есть, то добавить нам не сложно. Сделаем.
