### ISSUE TITLE
[FEATURE] Срок жизни для лимитной заявки на срочном рынке

### ISSUE THREAD

**Issue by PullPlus** [alor-broker/Astras-Trading-UI#1369]
### Опишите проблему, которую решает ваша фича

Выставление заявки с определённой датой жизни, на срочном рынке. Такой функционал есть в других терминалах.

### Опишите предлагаемое вами решение

При выставлении лимитной заявки на срочном рынке, добавить пункт с датой окончания действия заявки.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Да, можно сделать. Уточнил у коллег, в API такое уже есть

**Comment by sbelashevskiy** [comment]
Непонятно каким образом это поле должно сочетаться со значениями в "Тип исполнения заявки"
