### ISSUE TITLE
[FEATURE] Настройки виджетов

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#137]
### Опишите проблему, которую решает ваша фича

Некоторые настройки у виджетов кажутся неоптимальными или вовсе не ясны

### Опишите предлагаемое вами решение

Опишу по всем виджетам одной кучей:

**График**
- Тикер. Добавить поиск по тикеру или названию компании, как это сделано в "Выбор инструмента".
- Биржа. Сделать выпадающим списком.
- Режим торгов. 1) Добавить описание опции. 2) Реализовать списком, если список значений из нескольких штук.

**Блоттер**
- Портфель. Выпадающим списком.
- Биржа. Выпадающим списком.

**Стакан**
- Тикер. Добавить поиск
- Биржа. Выпадающим списком.
- Глубина. "0" считается валидным параметром. Возможно, стоит начать с "1"?
- Группа. 1) Привести к единому названию с виджетом "График". 2) Добавить описание.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Согласен, это хорошо было бы сделать. Добавил в планы на следующий этап, т.к. если вопросы. По тому же режиму торгов не совсем понятно как это сделать по хорошему.

**Comment by PilgrimViis** [comment]
Данная задача связана с
https://github.com/alor-broker/Astras-Trading-UI/issues/350
https://github.com/alor-broker/Astras-Trading-UI/issues/587 

По сути после косметических правок по глубине и добавлению поиска будет тоже закрыта.

**Comment by PilgrimViis** [comment]
Поиск по тикеру добавили.

**Comment by dzeron13** [comment]
@PilgrimViis MOEX в поиске потерялась (
![image](https://user-images.githubusercontent.com/99450543/200519204-9d3e6310-8391-43f0-986e-6c3b38567bc8.png)

**Comment by PilgrimViis** [comment]
По выбранному портфелю биржа ищется, но да как то не подумали. Повесил баг.

**Comment by PilgrimViis** [comment]
Тут нужно сделать поиск по группе торгов на бекенде. Остальное все есть.
