### ISSUE TITLE
[FEATURE] Цвет иконки избранного дашборда

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#1372]
### Опишите проблему, которую решает ваша фича

При текущем выделении не особо понятно, что дашборд помечен как избранный. Все иконки одинаково серые (черные на светлой теме). Меняется есть заливка / нет заливки

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/a81e9236-ae1d-478b-9976-d2d1488410e2)

### Опишите предлагаемое вами решение

Менять цвет иконки, как это сделано в Выборе инструмента
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/f5c5c4a3-6497-41c9-8b4c-293f3fd0eeeb)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я согласен. И ещё один аргумент, это то что интерфейс будет одинаковым. Так правильно сделать.
