### ISSUE TITLE
[FEATURE] Очередность столбцов виджета Все сделки 

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#1375]
### Опишите проблему, которую решает ваша фича

Поступило несколбко запросов на изменение очередности столбцов в виджете Все сделки (первым столбец с ценой, потом с кол-вом) , но такой возможности нет.

### Опишите предлагаемое вами решение

 Предлагается дополнить функционал возможностью перемещать очередность солбцов, по аналогии как в Блоттере

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@sbelashevskiy скажи пожалуйста, мы можем такое добавить вообще для всех таблиц? По идее этот функционал полезный, хотелось бы его иметь по умолчанию. Но не хотелось бы тратить много времени, если это будет проблемно.

**Comment by MorozovDen** [comment]
Поддерживаю
