### ISSUE TITLE
[BUG] Пропадает выделение объема при изменении прозрачности цвета

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1377]
### Опишите баг

В настройках стакана, есть настройка выбора цвета подсветки объема и ПРОЗРАЧНОСТЬ. 
Вот если прозрачность уменьшить, хотябы на 1 деление , подсветка вообще пропадает. 

### Воспроизведение

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/9c3d65f5-13a4-49de-a2b0-80d007830dcc

### Среда.

ОС Windows 
Chrome

### Ожидаемое поведение

Должна меняться прозрачность цвета

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Также обсуждали проблему, что пропадает основной фон (зона продавцов и покупателей) когда накладывается подстветка  и ее доля очень мала

**Comment by sbelashevskiy** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/1420
