### ISSUE TITLE
[FEATURE] Добавить подтверждение действия удаления инструмента в виджете Выбор инструмента 

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#1378]
### Опишите проблему, которую решает ваша фича

Защита от случайного нажатия и уделения инструмента из виджета Выбор инструментов

### Опишите предлагаемое вами решение

Добавить запрос на подтверждение действия по удалению после нажатия на крестик

### Дополнительная информация

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/1acad4b5-b831-4abf-9cf7-5836938d9002)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Мы обсудили и решили сделать следующее
* Колонка удалить должна быть опциональной, т.е. её можно убрать через настройки
* Добавить удаление в контекстное меню
