### ISSUE TITLE
[BUG] При расширении Скальперского стакана отображается лишняя надпись "Нет данных" 

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1380]
### Опишите баг

Если выставить Скальперский стакан и увеличить его по вертикали, то на короткое время появится надпись "нет данных", лучше ее скрывать:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/2850684e-f5ca-44cd-925c-14b624718f3a

Ошибок в консоли при этом нет. Иногда надпись "нет данных" остается несколько секунд. Ошибка воспроизводится по разным бумагам.

### Воспроизведение

1. Выставить "Скальперский стакан" по любой бумаге.
2. Увеличить виджет по вертикали.
3. Проверить отображение заявок и цен в стакане.

### Среда.

Windows 10
Google Chrome v119.0.6045.200 

### Ожидаемое поведение

При ресайзе виджета "Скальперский стакан" не становится пустым, не появляется надпись "нет данных", когда данные есть

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Ну логично что нет данных. Ему нужно погрузить больше строчек из истории. А если подгружаться из-за лага интернета будет долго, то мы что будем кривые данные показывать пользователям? @sbelashevskiy что думаешь?

**Comment by sbelashevskiy** [comment]
Да, при увеличении стакана вниз ему нужно полностью перерисовываться, отсюда и эта надпись
