### ISSUE TITLE
[BUG] При авторизации по пустому договору с телефона скрыть портфель от пред. аккаунта

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1382]
### Опишите баг

На телефоне на бою и на деве при авторизации в Астрас по другому договору - появляются ошибки 401 и 403 от предыдущего портфеля:
![mobile_file_2023-12-11_13-18-45](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/bc32fbd6-9d00-4954-b69b-91e3708c5f62)

Причем нет модального окна с пояснением при авторизации, как это сделано в десктопной версии (напр. на деве для P073575, пароль: 123456):
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/d0f499b2-cb9f-4ced-9f32-395ceb40e785)

В самих табах "Заявка", "Блоттер", "Корзина Заявок" указывается портфель от предыдущего аккаунта:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/786cc8b3-242f-4595-b460-7d19dcfcb201)

### Воспроизведение

1. Зайти с телефона в Астрас на деве под P039004.
2. Разлогиниться и зайти под другим аккаунтом (пустым, без позиций): напр. P073575, пароль: 123456.
3. Проверить модальное окно с уведомлением о пустом портфеле, посмотреть на отображение портфелей.

### Среда.

Android 9
Googlce Chrome v120
Mozilla Firefox v119

### Ожидаемое поведение

1. При авторизации под новым договором нет ошибок 401 или 403
2. Появляется модальное окно с информацией о том, что нет открытых позиций:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/8013fb43-d760-4377-bbe4-c0e366cbb556)

3. В табах "Заявка", "Блоттер", "Корзина Заявок" не указывается портфель от предыдущего аккаунта.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Надо добавить просто модалку.
