### ISSUE TITLE
[FEATURE] Сделать перевод buy, sell на русский язык

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1383]
### Опишите проблему, которую решает ваша фича

Сейчас в виджете "Блоттер" (табы Заявки, Стопы, Сделки, История сделок, Сделки РЕПО) и виджете "Все сделки" для графы "Сторона" в русском интерфейсе отображаются английские buy/sell, хотя в окошке для сортировки - русские обозначения:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/5b7134ad-3677-46c1-9890-681950af6e79)

### Опишите предлагаемое вами решение

Лучше сделать слова "Покупка" и "Продажа", если выбран русский язык приложения, по аналогии со статусами заявок и сделок:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/7224dec1-06ed-42fd-960b-c0d99f51af53)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Слишком длинно как по мне. Спрошу у РГ.
