### ISSUE TITLE
[BUG] На Android не открываются справки по виджетам

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1384]
### Опишите баг

При авторизации в Астрас с телефона и клике на "справка" для любого виджета - не открывается справка (ни в модалке, ни через переадресацию на https://alor.gitbook.io/astras/), кнопка "Справка" выглядит как нерабочая. Повторяется и в Хроме, и в Фаерфоксе. Проверено на трех устройствах - Android 8, 9, 10:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/643bbee2-6c92-4233-9cfe-9f1eef1c4887)

### Воспроизведение

0. Почистить историю браузера, cookie и данные сайтов.
1. Залогиниться в Астрас с Android в Гугл Хром/Фаерфокс.
2. Для любого виджета нажать на значок "Справка".
3. Прочитать справку.

### Среда.

Android 8. Google Chrome v120, Firefox v120
Android 9. Firefox v119
Android 10. Google Chrome v120 

### Ожидаемое поведение

Справки открываются на Adroid, можно изучить информацию по разным виджетам.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Справка открывается когда эта кнопка одна, например в виджете Info
Тут проблема с UX - кнопки слишком маленькие, по ним сложно попасть когда их несколько.
Нужно править в рамках изменений в мобильной версии
