### ISSUE TITLE
[FEATURE] Трансформация полей

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#139]
### Опишите проблему, которую решает ваша фича

Эта ячеистая структура не очень корректно срабатывает при трансформациях полей. Иногда сразу и не поймёшь, куда какие поля убежали. 

### Опишите предлагаемое вами решение

Создать кнопку "вернуть предыдущее состояние полей" или "вернуть стартовое состояние полей". Ещё хорошо бы сделать кнопку блокировки каждого поля, чтобы можно было исключить изменение размеров и положения выбранных полей при изменении другого.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Какая ячеиская структура? Какая трансформация полей? Я ничего не понял =(

**Comment by dzeron13** [comment]
Как я понимаю, коллега под "полями" подразумевает виджеты и их автоматическое масштабирование.
А восстановление изначальной расстановки виджетов было бы к месту. Сейчас для этого приходится удалять все виджеты (кнопкой с корзинкой) и обновлять страницу.

**Comment by PilgrimViis** [comment]
#161 Частично решит описанную проблему. Саму задачу закрою, т.к. описано плохо, тут материала просто нет. Сама проблема с тем, что расширение размерной сетки неудобно теперь понятна, спасибо @dzeron13.  По поводу расстановки виджетов, есть мысль, сделать сохранение дашбордов и переключение между сохранёнными.  Может быть даже на MVP вынесем, надо посмотреть как по коду будет.
