### ISSUE TITLE
[BUG] не корректный график в виджете Теханализ

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#1390]
### Опишите баг

В Виджете Теханализ отражается не корректный график по инструментам срочного рынка, спреды на Si, Ed. в виджете Теханализ подставляется формула, а не забирается сам инструмент с биржи.  В виджете График рисуется нормальный график

### Воспроизведение

виджет Теханализ
выбрать тикер euz3euh4
сравнить со стаканом

### Среда.

Chrome

### Ожидаемое поведение

Грвфик в виджете Теханализ соответствует стакану котировок и графику в виджете График

### Скриншоты

![image_2023-12-13_12_06_20](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/46af1a68-c8d0-4fa3-ba02-87a30e4634d9)
![image_2023-12-13_12_07_52](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/49bf7ef7-5781-4965-8d47-70fb59f97d2b)
![Снимок экрана 2023-12-13 в 11 05 58](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/a59e1ce2-0a44-4137-a185-7cf5e89e87d6)
![Снимок экрана 2023-12-13 в 11 06 20](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/42343173-d755-44b5-98b7-6eb6282f3ec9)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@agushasok посмотри пожалуйста, подозреваю опять синтетические инструменты пошалили.
