### ISSUE TITLE
[FEATURE] Добавить большее кол-во якорей в СС (скальперский стакан)

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1395]
### Опишите проблему, которую решает ваша фича

Недостаточное кол-во якорей

### Опишите предлагаемое вами решение

Необходимо добавить кол-во якорей до 16 штук.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Под якорями имеется ввиду количество цветов привязки
