### ISSUE TITLE
[FEATURE] Добавить описание инструмента при наведении курсора мыши

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1396]
### Опишите проблему, которую решает ваша фича

При переключении к новому инструменту, приходится искать данные в другой таблице( системе).
На фьючерсах сшц меняется по некоторым инструментам, из-за изменения стоимости курса доллара

### Опишите предлагаемое вами решение

Прошу добавить : 

//обязательные
Объем лота
Стоимость шага цены (СШЦ) 
// по возможности 
Максимальное кол-во лотов к покупке 
Максимальное кол-во к продаже(шорт)

### Дополнительная информация

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/3a97a487-3e23-4137-a556-0562422c5508)

### Правила

- [X] Я согласен следовать правилам

**Comment by uncrashable** [comment]
Т.к. есть задача, где мы отобразим кол-во лотов в покупку и в продажу, то по этой задаче необходимо сделать, что бы в выпадающем окне было только : 
СШЦ - стоимость шага цены 
ЛОТ - кол-во акций в лоте.

**Comment by PilgrimViis** [comment]
Один момент. Вместо доступно в лонг и доступно в шорт, надо будет сделать так как у нас есть в виджете выставления заявок. Кидаем estimate api и показываем результат оттуда.

**Comment by PilgrimViis** [comment]
Договорились что
1. Мы сделаем панельку с L\S прямо на скальперском стакане. Где будет как раз цифра сколько доступно в лонг и шорт и частично перекроет необходимость этой панели.
2. Если Женя понимает, что вариант с созданием виджета инфо внизу и скролом до него когда нужна информация о лотности проблемый, то мы всё таки делаем эту панельку.
