### ISSUE TITLE
[FEATURE] Отобразить % изменение за день по инструменту в сс

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1398]
### Опишите проблему, которую решает ваша фича

Информативно видеть, на сколько изменилась текущая цена по инструменту, относительно вчерашней цены закрытия. 

### Опишите предлагаемое вами решение

В стакан, в панель принтов, добавить индикатор % изменения от закрытия. Данные у нас есть в виджете "Выбор инструмента"
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/fd619625-34b2-4a92-afcb-d66070e00142)

### Опишите альтернативные решения, о которых вы думали

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/51543849-63df-4013-9d2b-b4cb861e3664)
Индикатор добавить "фоновый" чтобы не бросался в глаза. 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Для существующих виджетов нужно включить отображение в настройках.
Для новых виджетов отображение будет включено по умолчанию
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/8d79239b-45c5-415a-a95b-838faaf4f1ca)
