### ISSUE TITLE
[BUG] Не обновляются новости

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1401]
### Опишите баг

Не обновляются новости и карта рынка в моменте

### Воспроизведение

1. Открыть виджет новости, посмотреть последнее время выхода новостей, затем переключиться на другую вкладку , например "По портфелю", вернуться обратно, посмотреть время последних новостей. 
2. Открыть карту рынка и сравнить показатели, которые меняются в виджете "Выбор инструмента" , но не меняются в "Карта рынка" 

### Среда.

ОС WS10 
Chrome 

### Ожидаемое поведение

Новости хотелось бы получать моментально быстро, насколько это возможно. 

### Скриншоты

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/8a73f4be-e277-421b-9600-4832a455ad08

![chrome_vL9Wp4B6uj](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/41aa3dd3-5461-45f5-8dac-3e6347184f20)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/1441 вынес в отдельную задачу.
