### ISSUE TITLE
[FEATURE] Отобразить индикатор НЕ шортовых и лонговых бумаг (LS- панель )

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1402]
### Опишите проблему, которую решает ваша фича

У нас список маржинальных бумаг постоянно меняется. Было бы удобно видеть , какие бумаги можно шортить, а какие нет. 
Причем есть возможность подписать доп соглашение и тогда этот список будет другой. Т.е. данные нужны по каждому клиенту отдельно. 

### Опишите предлагаемое вами решение

Договорились сделать некую LS-панель, для отображения.
Смысл ее заключается в том, что клиент видит кол-во лотов доступных в покупку(с учетом всех подключенных услуг) и в продажу. Если продажи =0 , то бумага не шортовая. 
Обновление панели сделать при : выставлении заявок, срабатывании сделок и по времени ( 1 раз в минуту). 
Расположение: выше (перенесенной) панели рабочих объемов. 
В общем виде выглядит вот так: 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/8e8e59ab-89cd-496e-9091-75ffa50e13fa)

Для примера видео: 

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/e1b6477c-4a60-47eb-b528-4b1e065c3647

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Договорились закрыть при обсуждении.

**Comment by PilgrimViis** [comment]
Договорились что Женя допишет в эту задачу про панельку с доступно в лонг\ доступно в шорт.

**Comment by uncrashable** [comment]
> Договорились что Женя допишет в эту задачу про панельку с доступно в лонг\ доступно в шорт.

Готово!

**Comment by PilgrimViis** [comment]
@uncrashable нам нужна цена для расчёта L и S. Мы возьмем цену (аск-бид)/2.

**Comment by uncrashable** [comment]
> @uncrashable нам нужна цена для расчёта L и S. Мы возьмем цену (аск-бид)/2.

Не совсем понимаю ваш расчет.  В таком случае получится средняя цена.  думаю в какой то момент расчет будет не верен. Если спред будет большой , то расчеты LS будут производиться по средней ( а таких заявок не будет в стакане).  
Почему нельзя для расчета L взять бестаск, а для расчета S взять бестбид , значения будут куда точнее.

**Comment by uncrashable** [comment]
L= сумма депозита с учетом услуг(плечи и т.д.)  / (бестаск*кол-во бумаг в лоте) 
// результат округлить до целого в меньшую сторону.

**Comment by PilgrimViis** [comment]
> L= сумма депозита(сумма свободных средств) с учетом услуг(плечи и т.д.) / (бестаск*кол-во бумаг в лоте) // результат округлить до целого в меньшую сторону.
Это так не работает. Для расчёта к покупке к продаже нужна цена.

**Comment by PilgrimViis** [comment]
> > @uncrashable нам нужна цена для расчёта L и S. Мы возьмем цену (аск-бид)/2.
> 
> Не совсем понимаю ваш расчет. В таком случае получится средняя цена. думаю в какой то момент расчет будет не верен. Если спред будет большой , то расчеты LS будут производиться по средней ( а таких заявок не будет в стакане). Почему нельзя для расчета L взять бестаск, а для расчета S взять бестбид , значения будут куда точнее.

Согласен
