### ISSUE TITLE
[FEATURE] Добавить индикатор пинг

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1411]
### Опишите проблему, которую решает ваша фича

Индикатор "пинг", будет пинговать сервер при выставлении заявок в стакан, тем самым, трейдер может контролировать соединение и видеть скорость выставления заявки на сервер. 

### Опишите предлагаемое вами решение

1 вариант. Предлагал выставить индикатор прям в скальперский стакан. 
2 вариант. В Астрасе вверху справа есть индикатор коннекта. Подумать его доработку и подумать куда разместить индикатор. 

Индикатор обновляется только при выставлении и снятии заявок, либо при сделках(если это рыночная заявка)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я помню что мы решили использовать существующий индикатор, но там был какой-то нюанс... @sbelashevskiy ты не помнишь какие нужны были доработки?

**Comment by sbelashevskiy** [comment]
Договаривались замерять время отправки запросов по заявкам

**Comment by sbelashevskiy** [comment]
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/a9c7da6e-fecc-4787-b4d1-bafa4e3a4541)
