### ISSUE TITLE
[BUG] В блоттере для инструментов с небазовыми бордами отображается базовый режим торгов

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1418]
### Опишите баг

Если выставить заявку по небазовому борду - например, SLAV (MTQR) или ORUP (MTQR), то потом при клике на этот инструмент в табе "Заявки", "Позиции" или "Стопы" - в прикрепленных виджетах отображается базовый борд PRMO, это неверно:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/00570d13-2b30-41c6-b70b-8c6c962c7fd3

### Воспроизведение

1. В "Выбор инструмента" указать MOEX:ORUP:MTQR.
2. Выставить заявку по этой бумаге, проверить instrumentGroup в консоли по запросу выставления заявки.
3. В блоттере перейти на "Заявки". Проверить желтый лейбл рядом с бумагой и борд в шапке виджетов. 
4. Сменить бумагу и нажать на ORUP. Проверить борд в связанных виджетах.
5. Повторить шаг 4 для вкладки "Позиции" и "Стопы" в блоттере.

### Среда.

Windows 10
Google Chrome v119

### Ожидаемое поведение

При клике на бумагу в блоттере отправляется запрос с параметром режима торгов, а именно https://api.alor.ru/md/v2/Securities/MOEX/ORUP?instrumentGroup=MTQR, как сейчас реализовано в виджете "Выбор инструмента" при клике на бумагу:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/d3a6544e-10a3-4df6-b6ac-992aef1081a2)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Ни в одном из указанных случаев API не присылает режим торгов. Тем более он не присылается для позиций. Позиция это определенная бумага в портфеле, а режим ее торгов - способ ее торговли. Учитывается именно бумага, а не как ее приобретали.

Режим торгов должен совпадать только при редактировании заявок

**Comment by PilgrimViis** [comment]
В позициях согласен с Сергеем, это бред. Но в заявках и стопах режим торгов должен быть. Если дейстивительно нет, то как на беке добавят я думаю правильно будет добавить и в Астрас.

**Comment by sbelashevskiy** [comment]
В респонзах для заявок нет никакой инфы о борде
ни для стопов
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/dbd5fd26-f59f-41a0-9445-a6ce7dc2174a)
ни для лимиток
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/ab25bb4d-f09c-49d5-9b5a-e5f61627ea04)

Такой инфы даже нет при запросе данных по заявке по http
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/e8916c72-a0b4-47a9-84f9-ebae933fefb9)
 
Соответственно брать эту информацию неоткуда
