### ISSUE TITLE
[FEATURE] Выставление заявки вынести в виджет

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#142]
### Опишите проблему, которую решает ваша фича

Сейчас при выставлении заявки с кнопки "+" или со стакана появляется диалоговое окно, перекрывающее другие виджеты. Если мы говорим о небольшом количестве сделок в день, но это подход вполне приемлем. Но он абсолютно не подойдет для трейдеров, чей стиль торговли хоть как-то приближен к скальпингу.
Например, кому-то необходимо иметь на рабочей области несколько стаканов по разным инструментам и возможность оперативно выставлять заявки по ним.
В текущей реализации у таких торговцев будет два пути:
1. Открыть несколько стаканов и выставлять заявки с них. 
2. Открыть несколько стаканов и виджет "Выбор инструмента", в котором переключать активную бумагу и выставлять заявку через "+".
В обоих случаях это большая потеря в скорости.

### Опишите предлагаемое вами решение

1. Вынести выставление заявки в отдельный виджет.
что неминуемо потребует
2. Реализовать возможность связывать виджеты между собой в одну группу (примеры: Aurora, Альфа-Директ, Тинькофф)

Понимаю, что разрабатывается в первую очередь терминал, а не скальперский привод, но такая реализация была бы более гибким решением, где каждый сможет настроить рабочее место под себя. Кроме того, открытие дополнительного окна поверх виджетов несколько не вписывается (сугубо, ИМХО, конечно) в концепцию веб-терминала и напоминает скорее десктоп-приложения.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Хорошая идея для нового виджета. Думаю стоит сделать в будущем.

**Comment by PilgrimViis** [comment]
@sbelashevskiy Давай сделаем виджет, только надо чтобы он был поменьше чем наше модальное окно. Предлагаю сократить количество полей в таблице с ценами до бида и аска и уменьшить размер лого (или вообще его убрать)
