### ISSUE TITLE
[FEATURE] Скорректировать выставление заявок по нажатию клавиш мыши и клавиатуры в сс

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1421]
### Опишите проблему, которую решает ваша фича

У нас сейчас лимитная заявка в стакан выставляется после того, как кнопка мыши отжимается, т.е. не по нажатию , а по отпуску. 
Если  кнопку мыши, нажать и держать , то ничего не происходит. 

У клавиатуры другое срабатывание. Если зажать клавишу клавиатуры (например выставить заявку на покупку по лучшей цене), то в систему начинает поступать масса заявок, которая будет постоянно выставлять заявки выше и выше. 

### Опишите предлагаемое вами решение

1. Мышь: заявка должна выставлять при нажатии на кнопку. (также проконтролировать, что бы не было повторного выставления заявок, если нажать кнопку мыши и держать в стакане :  1 клик = 1 заявка)
2. На клавиатуре сделать тоже самое, выставление(снятие) по нажатию кнопки. Если зажать кнопку и держать, повторно заявка не должна срабатывать. 

p/s/ так же прошу обратить внимание, что в стакане "работает" стандартное для виндовс выделение стакана. Это надо как то убрать , очень мешает 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/aa1ef70a-aaf8-4dad-b213-0cbee9bee58b)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@uncrashable мы же договорились, что не будем реализовывать ту странную логику по нажатиям, иначе это просто сломает стакан. Мы решили что уберем выделение и по идее это должно исправить проблему. Если этого не сделать, то пока ты ведешь вышкой с зажатой кнопкой у тебя выставится миллион заявок и другие проблемы которые мы обсуждали.

**Comment by uncrashable** [comment]
> @uncrashable мы же договорились, что не будем реализовывать ту странную логику по нажатиям, иначе это просто сломает стакан. Мы решили что уберем выделение и по идее это должно исправить проблему. Если этого не сделать, то пока ты ведешь вышкой с зажатой кнопкой у тебя выставится миллион заявок и другие проблемы которые мы обсуждали.

Да, мы обсудили что надо попробовать и посмотреть решиться ли проблема. Если нет, то надо подумать как сделать так, что бы стакан не сломался. 

Давайте пока удалим выделение. А дальше , в рамках задачи будем двигаться, если все ок  - закроем ее и все.
