### ISSUE TITLE
[FEATURE] Добавить контрастность к цветам в стакане, сменить размер шрифта

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1424]
### Опишите проблему, которую решает ваша фича

Шрифт в стакане у нас вроде как больше серый , чем черный. Нужно сделать более контрастным. 

### Опишите предлагаемое вами решение

Шрифт в стакане сделать черный

Также уменьшить сам шрифт (посмотреть FontSize = 11 или 10) - необходимо что бы стакан был компактный, вверх и вниз нужно максимально больше видеть ценовых уровней. 

Также уменьшить расстояние ячеек , в которых находится шрифт. 

### Правила

- [X] Я согласен следовать правилам

**Comment by uncrashable** [comment]
для примера 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/03474096-c55d-405f-b43d-5a2fc643eed6)

**Comment by sbelashevskiy** [comment]
Добавлены настройки сетки стакана
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/d32b9899-9a48-4711-aa8e-1a958a68ce0b)
