### ISSUE TITLE
Процентное изменение цены на малых таймфреймах.

### ISSUE THREAD

**Issue by Goldenboyss** [alor-broker/Astras-Trading-UI#1428]
Нужно добавить процентное изменение цены на малых таймфреймах для скальперов и внутридневных трейдеров.

![процентное изменение цены на младших тф](https://github.com/alor-broker/Astras-Trading-UI/assets/153299638/b126c2d2-8134-427b-b27c-a923d5d77ffe)

**Comment by uncrashable** [comment]
Что вы имеете ввиду ? 
Что бы бала настройка , при которой показывалось, выросла цена или упала относительно последних 5 минут или 15 минут. Т.е. каждые , например, 5 минут берутся за нулевую точку ????

**Comment by Goldenboyss** [comment]
> Что вы имеете в виду? Что бы бала была настроена, при которой заказывалось, цена выросла или упала относительно последних 5 минут или 15 минут. Т.е. женщины, например, 5 минут берутся за нулевую точку ????

На данный момент, в таблице "Выбор инструмента", есть показатель дневного изменения цены, который отображается относительно цены закрытия предыдущего дневного бара. Я хочу предложить добавить в эту таблицу на выбор пользователя другие таймфремы. Эти показатели младших таймфреймов будут отображать процентное изменение цены относительно предыдущего бара.
