### ISSUE TITLE
Отображение заявок на графике в "Астрас"

### ISSUE THREAD

**Issue by Haliavschik** [alor-broker/Astras-Trading-UI#1429]
### Опишите проблему, которую решает ваша фича

Здравствуйте!
Выставленные заявки (табличная часть с указанием лотов) на графике мешают, закрывая своей информацией сам график.
![photo_2023-12-21_19-39-49](https://github.com/alor-broker/Astras-Trading-UI/assets/144210452/6cab3b89-c28b-4654-aebc-8eabbc3f9381)

### Опишите предлагаемое вами решение

Прошу либо добавить возможность двигать по графику таблицу с информацией о количестве лотов в выставленных заявках либо перенести таблицу с информацией о количестве лотов в левую часть графика (дальше середина экрана).

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Мы попробуем сделать, но так как эта интеграция то не обещаем. К сожалению мы не на 100% всесильны в этом виджете с  графиком.

**Comment by sbelashevskiy** [comment]
Добавлены настройки для отображения
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/109f5ac8-543e-4d99-b45d-56cd773743cc)
