### ISSUE TITLE
[FEATURE] Поменять значки закрепления виджета

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#143]
### Опишите проблему, которую решает ваша фича

Значки закрепления виджета (открытый / закрытый замок) между собой едва различимы.
![image](https://user-images.githubusercontent.com/99450543/167022510-9e456e2a-dd82-4f49-a5ba-c85bc5efe32c.png)
Разрешение 1920x1080.

### Опишите предлагаемое вами решение

Поменять значки, на легко-отличимые между собой.

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Попробовали увеличить размер иконок в заголовке - выглядит не очень хорошо.
Принято решение отказаться от разных иконок, заменить их одной стандартной иконкой, которая изменяет цвет в зависимости от состояния:
![image_2022-05-12_14_23_05](https://user-images.githubusercontent.com/29191749/168064253-7b679b86-aeec-4fc8-96f0-feb6c1d19132.png)
