### ISSUE TITLE
[FEATURE] Процентное изменение цены на маленьких таймфреймах.

### ISSUE THREAD

**Issue by Goldenboyss** [alor-broker/Astras-Trading-UI#1430]
### Опишите проблему, которую решает ваша фича

На данный момент в таблице «Выбор инструмента», есть показатель только дневного изменения цены, который отображает процентное изменение цены относительно цены закрытия предыдущего дневного бара.

### Опишите предлагаемое вами решение

Предлагаю добавить в эту таблицу, на выбор пользователя, процентное изменение цены младших таймфреймов.
Эти показатели младших таймфреймов будут также отображать процентное изменение цены относительно цены закрытия предыдущего бара.

### Дополнительная информация

![процентное изменение цены на младших тф](https://github.com/alor-broker/Astras-Trading-UI/assets/153299638/7f46e9f5-4da8-435d-befe-f3965003002c)

### Правила

- [X] Я согласен следовать правилам

**Comment by MorozovDen** [comment]
Интересное предложение! Обязательно предусмотерть сортировку этих столюбцов, будет выполнять роль несложного сканера.
