### ISSUE TITLE
[FEATURE] Подсветка айсберг-заявок

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1434]
### Опишите проблему, которую решает ваша фича

Можно улучшить функционал, добавив в стакан подсветки айсберг заявок. 
По определению с Мос биржи : 

Заявки типа "Айсберг" представляют собой классические безадресные лимитированные заявки, в которых указывается общее количество контрактов и их "видимое количество".

Данный тип заявки проявляется в стакане порциями. Когда видимая часть полностью исполняется в рынке, тогда "всплывает" следующая порция. Так может повторяться до тех пор, пока вся скрытая часть не будет исчерпана.
Подробнее на Московской бирже: https://www.moex.com/s3171

### Опишите предлагаемое вами решение

В стакане , айсберг заявку определить можно только тогда, когда у нее обновится ее видимая часть, хотя бы 1 раз. 

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/545cb041-e04e-418a-92b2-db9d1da90175

На видео показываю айсберг заявку (шортовую) с видимой частью 500 лотов. 

Нужно подумать как определить алгоритм проявления. 
Опишу что думаю по этому поводу, может поможет:
Мы видим стакан заявок, если по какой-то цене СДЕЛКА прошла БОЛЬШЕ чем там была ЗАЯВКА, то вероятно там будет айсберг. 
Поясню. Покупатель двигает рынок вверх(к примеру) и скупает все заявки на своем пути. По какой-то цене(любой) мы видим лимитную заявку 57 лотов, покупатель кидает заявку "по рынку " на 100 лотов, но цена ни на пункт не смещается выше этой заявки. Она полностью исполнилась в эти 57 лотов, и на этом месте появится новая лимитка на 457 лотов (если айсберг с видимой частью 500 .
100 лотов - 57 (обновляется айсберг и от 500 лотов еще отнимут 43 лота)   

При обнаружении айсберг заявки необходимо подсветить(выделить) цену и объем в стакане. 
По классике , выделяют светло-голубым цветом на некоторый период времени. Далее, цвет исчезает, принимая свои настройки.
Можно вот такую аккуратную рамку сделать 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/019bb222-3349-49ee-8c31-f3d43a0de860)
 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
> Нужно подумать как определить алгоритм проявления.

@uncrashable я пока закрою задачу, алгоритма я не увидел. Мы договаривались, что ты напишешь алгоритм определения таких заявок. Твоего примера абсолютно недостаточно чтобы это реализовать
