### ISSUE TITLE
[FEATURE] Отображение цен в стакане по облигациям в рублях

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#1436]
### Опишите проблему, которую решает ваша фича

Многие брокера начали предоставлять стакан по облигациям в формате выраженном в рублях (стоимость+нкд), это удобно для среднесрочной торговли и для понимания новым клиентам.

### Опишите предлагаемое вами решение

Предлагается добавить возможность в настройках стакана включить "Показывать цену облигаций в рублях", при включенном режиме отображается стоимость+нкд облигации в рублях . Возможно стоит предусмотреть так же и в блоттере возможность включения режима, что срежняя цена по облигациям отображается не в процентах от номинала, а так же стоимость+нкд по которой преобретались

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Честно говоря не нравится мне эта идея. Не вижу в ней особого смысла. Для облигаций её стакан в доходностях. Торговать облигации со стаканом в рублях бессмысленно...

**Comment by Suastoye** [comment]
Это удобно для неискушенных инвесторов. Они очень часто не видят, что по бумаге была амортизация (даже порой такого термина не знают), а при таком стакане сразу все видно. Корме того, если будет считаться "грязная" цена с учетом НКД отпадет необходимость считать цену покупки. Так сделано в МП, это очень упрощает задачу  - помочь клиенту купить бумаги.

**Comment by PilgrimViis** [comment]
> Это удобно для неискушенных инвесторов. Они очень часто не видят, что по бумаге была амортизация (даже порой такого термина не знают), а при таком стакане сразу все видно. Корме того, если будет считаться "грязная" цена с учетом НКД отпадет необходимость считать цену покупки. Так сделано в МП, это очень упрощает задачу - помочь клиенту купить бумаги.

1. Эта проблема решается с помощью окна оценки объема заявки. Там учитывается НКД. Так же видна и цена 1 бумаги 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/fea2d52d-f217-413c-ba46-b731e97240c2)

2. Стимулировать у клиента вредные торговые привычки тоже плохо. Облигации должны торговаться по доходности. Не важно сколько они стоят рублей, важно сколько они стоят в %. Или даже к RUONIA или ОФЗ со схожей дюрацией.

**Comment by PilgrimViis** [comment]
3. И вообще, цена облигации в рублях это величина очень сильно переменчивая. Каждый выплаченный аморт, это падение цены. Зачем это в стакане? Не спроста биржа котирует их в процентах.

**Comment by PilgrimViis** [comment]
4. А если облигу сливают? Если котировать облиги в рублях, то непонятно что кто-то слил в этот день на 5% или это аморт выплатили или просто ставка ЦБ поднялась. Да и не у всех облигаций номинал в 1к. Есть много и по 10к и по 50к и т.д. И всю эту математику в голове гораздо сложнее держать.

**Comment by MorozovDen** [comment]
Предлагается же не отказаться от отображения в %% от номинала, а дополнить возможностью просматривать еще в одном варианте отображении цены. Надо не забывать, что приходящим клиентам с того же Тинькофф придется "переучиваться" на наше отображение. Т.е. этим мы облегчим "комфортный" переход к нам.

**Comment by PilgrimViis** [comment]
> Предлагается же не отказаться от отображения в %% от номинала, а дополнить возможностью просматривать еще в одном варианте отображении цены. Надо не забывать, что приходящим клиентам с того же Тинькофф придется "переучиваться" на наше отображение. Т.е. этим мы облегчим "комфортный" переход к нам.

Я спросил у Ермакова зачем они сделали это в МП. Он сказал, что в Астрасе это не нужно потому что мы считаем оценку заявки. В общем я пока задачу закрою, если всё таки считаешь, что делать надо, подними, пожалуйста, вопрос в чате рабочей группы. Если коллективно решим, что делать надо, то сделаем.
