### ISSUE TITLE
[FEATURE] Общий вид скальперского стакана(сс)

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1437]
### Опишите проблему, которую решает ваша фича

Постараюсь отрисовать общий вид готового скальперского стакана с комментариями.

Основной акцент сделать на компактность и "строгость", стаканов на мониторе должно помещаться максимально много , имея между собой минимальную, но видимую рамку.  

### Опишите предлагаемое вами решение

![Скальперский стакан финал](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/20eac39d-4601-4df3-bd62-80a585b2971f)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Добавлены настройки горизонтальных линий
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/d9b0a2e6-1dcf-4386-9cfc-8752a6cd0695)
Множитель основных уровней также задает "круглые числа"

Добавлена команда для снятия всех условных заявок
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/b44a45fc-81e0-4386-8c59-d8a6c0c664e0)
