### ISSUE TITLE
[FEATURE] Корректировка отображения инструментов в таблице

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1438]
### Опишите проблему, которую решает ваша фича

Когда инструменты имеют длинные названия, а ячейка, в которых отображается это название узкое, то срабатывает перенос текста на следующую строку. В итоге таблица становится неудобно-читаемой. 

### Опишите предлагаемое вами решение

Отключить перенос текста на следующую строку. 
И индикатор (якорь) надо как то тоже подумать, что бы не переносился на строку ниже. Может вертикальной черточкой его отображать перед названием инструмента
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/fb556976-889b-4d27-a948-b2ce7a52ed5e)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Блин мы перенос сделали потому что не смогли придумать как сделать чтобы помещалось и то и то и не было обрезаний. Тут варианта 2 либо мы обрезаем название либо переносим, мы решили переносить. Не знаю что тут ещё можно придумать честно говоря, полосочка проблему не решит, а всего-лишь удлинит слово для переноса на 1 символ.

**Comment by uncrashable** [comment]
> Блин мы перенос сделали потому что не смогли придумать как сделать чтобы помещалось и то и то и не было обрезаний. Тут варианта 2 либо мы обрезаем название либо переносим, мы решили переносить. Не знаю что тут ещё можно придумать честно говоря, полосочка проблему не решит, а всего-лишь удлинит слово для переноса на 1 символ.

а у нас есть в планах, дать трейдеру возможность самому настраивать ширину столбцов  перетаскиванием?

**Comment by uncrashable** [comment]
> Блин мы перенос сделали потому что не смогли придумать как сделать чтобы помещалось и то и то и не было обрезаний. Тут варианта 2 либо мы обрезаем название либо переносим, мы решили переносить. Не знаю что тут ещё можно придумать честно говоря, полосочка проблему не решит, а всего-лишь удлинит слово для переноса на 1 символ.

Если сделать возможность перетаскивание(расширение) панелей, то каждый трейдер под себя сможет настроить ширину . 
Текст лучше что бы занимал 1 строку, если наименование(или значение) длинное , пусть смещается под следующий столбец. 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/f3c43e92-d5bf-4798-be72-e0e60d0a373f)
а то вот тут вверху например, вообще очень много места занимает. 
Трейдеру и так понятно какой это столбец

**Comment by uncrashable** [comment]
А по поводу полосочки , я вот что имел ввиду. 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/50350c14-e801-4166-8dbe-dc1c9f927871)
Только я тут полосочку сделал огромную для наглядности. Ее можно засунуть перед тикером например.

**Comment by agushasok** [comment]
Добавили изменение ширины столбцов в виджеты с таблицами, в том числе и виджет выбора инструмента

**Comment by PilgrimViis** [comment]
Добавили изменение ширины колонок.
