### ISSUE TITLE
[FEATURE] Сохранение настроек в Астрас

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1439]
### Опишите проблему, которую решает ваша фича

У меня есть рабочий ПК и ноутбук. После того, как я настроил рабочее пространство на ПК, на ноутбуке оно отображается также. 
Но у меня рабочий ПК с монитором 34 дюйма, и 4к разрешением, а ноут 15.6 FullHD. Это создает проблемы отображения виджетов.

### Опишите предлагаемое вами решение

Можно ли продумать, какие настройки будут сохраняться и передаваться, а какие нет. 

Например если я начертил уровни какие то на графике, алерты, настроил стакан...и прочее  - их есть смысл передавать. 
А вот расположение и размер виджетов, думаю можно убрать из сохранений. 
Можно ли сделать что то подобное? 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
В данный момент могу предложить тебе сделать раздельные дашборды для 2 разных компьютеров. К сожалению мы не можем сделать то что ты предлагаешь, это довольно сложно, а юзкейс довольно редкий и есть метод с дашбордами, который проблему нивелирует.
