### ISSUE TITLE
[FEATURE] Привязка курсора в окне графика 

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#144]
### Опишите проблему, которую решает ваша фича

В окне графика курсор имеет перекрёстные линии. Горизонтальная - привязана к цене закрытия свечи. Это не всегда удобно. 

### Опишите предлагаемое вами решение

Предлагаю отвязать курсор от цены закрытия, либо сделать условие только близкого прилипания, либо добавить включаемое перекрестие, которое можно располагать где хочешь без привязки и так же видеть значения на шкалах.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я думаю мы можем это сделать в виде отдельной настройки графика. Если кто-то захочет, то привяжет к курсору.

**Comment by PilgrimViis** [comment]
По сути надо сделать как в tradingview графике у нас сейчас. Я думаю даже не надо делать это в виде опции. Пусть будет новое поведение по умолчанию.
