### ISSUE TITLE
[FEATURE] Уменьшить расстояние между строками 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1440]
### Опишите проблему, которую решает ваша фича

Можно ли сделать отображение более компактным. Хочется видеть больше информации , а прокрутка создает дополнительное неудобство. 
Например в виджете выбор инструмента, вертикальное расстояние , на мой взгляд очень большое. 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/340c8365-55fc-44c1-9825-2595d8a9a1eb)

### Опишите предлагаемое вами решение

Уменьшить межстрочное расстояние ...посильнее 

### Правила

- [X] Я согласен следовать правилам

**Comment by Goldenboyss** [comment]
Поддерживаю!

**Comment by PilgrimViis** [comment]
Я думаю это надо сделать как глобальную опцию для всех таблиц в настройках профиля. Сделать выбор из 3 вариантов
"обычный" - antd small (у нас сейчас вроде стоит по умолчанию small?)
"компактный" - кастомный
"обычный" - antd medium
