### ISSUE TITLE
[BUG] Премаркет

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1451]
### Опишите баг

Коллеги, сегодня наблюдал размещение новых бумаг на МосБирже. Заметил, что наш стакан  не отображает котировки. Даже уже после того, как торги начались, наш стакан котировок не получал, после того как я обновил страницу , только тогда увидел их. Видео не записал, но сделал пару скриншотов. 
Торги начали в 16-10. Аукцион открылся за 10 минут. Все эти 10 минут у нас было так : 
![не передаються данные с премаркета](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/d0e070f5-65a2-4ceb-82f8-cbcfb63c929e)
Для сравнения добавил стакан квика, там заявки смешенные , но все же они есть. 

Далее, за несколько секунд , до начала торгов, аукцион останавливают и в стакане уже видно заявки, и проходит сделка по цене открытия....  а у нас в стакане пусто, хотя на графике уже данные появились.

![chrome_AlGEoSJy3p](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/c55c53df-62dc-4931-8718-bdb3eda16ad1)
В чате видел писали эту проблему и про обычный стакан. 

### Воспроизведение

Такие премаркеты бывают и утром перед открытием биржи, думаю можно и там проконтролировать и перед открытием вечерней сессии.  Надо открыть наш стакан (любой ) и сравнить с данными другого торгового терминала. 

### Среда.

Ws 10 
Chrome

### Ожидаемое поведение

В стакане должны заявки отображаться пре и пост маркета. 

### Правила

- [X] Я согласен следовать правилам

**Comment by uncrashable** [comment]
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/0fbb1870-294c-480b-97fd-6731bf8290a5)
время аукционов

**Comment by PilgrimViis** [comment]
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/608b2a75-8bd3-4de4-8465-971ee69a4f21)
Про стакан на премаркете тоже кто-то писал в чате.

**Comment by PilgrimViis** [comment]
Привет. Поговорил с коллегами с бэка. Говорят что проблема на их стороне полностью. Они в курсе, задача у них есть. Но когда руки дойдут не знают. Так как мы тут совершенно бессильны, на гитхабе закрою таску.

**Comment by ddmitr** [comment]
А есть информация когда починят? Проверил на акциях - и аукцион открытия и закрытия на акциях показывают ерунду. Даже с другого брокера заявки потывал попробовал - не отображаются.
