### ISSUE TITLE
[BUG] Активная лимитная заявка не отображается в стакане, хотя есть на графике

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1458]
### Опишите баг

Для опционов, по которым нет аск или бид в стакане, при выставлении заявки не отображается активная лимитная заявка в Стаканах, хотя есть в "Тех анализе". Например, так было замечено для ED-3.24M210324PA1.08, CNY-3.24M210324CA14.75:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/d1af4724-04ad-41a6-bc0c-2db6fe96ffaf

Хотя видно, что в Скальперском стакане появилась "стрелка" внизу, то есть заявка была замечена, но на нее нельзя перейти. Причем, при выставлении еще одной лимитной заявки- уже обе появятся в стаканах.

Баг плавающий, не всегда воспроизводится, по некоторым стаканам без аск иди бид - все отлично срабатывало. В консоли при этом ошибок нет.

Для ED-3.24M210324CA1.1 (были аски и биды в стакане) - выставил 1 лот на продажу по цене 0.0185 - но в обычном стакане не отобразилась заявка:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/a21a12c6-67a2-4b3a-978b-1f745bf7d916)

### Воспроизведение

1. Выбрать опцион ED-3.24M210324PA1.08 (когда нет бид в стакане).
2. Выставить лимитную заявку на покупку.
3. Проверить отображение заявки в Тех анализе, в Стакане и Скальперском стакане.
4. Выставить еще одну заявку и проверить ее отображение в стаканах.

### Среда.

Windows 10
Goole Chrome v120.0.6099.110 

### Ожидаемое поведение

Активные лимитные заявки отображаются в Тех анализе, в Стакане и Скальперском стакане сразу же при выставлении заявки.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
В скальперском стакане и тех. анализе заявки привязываются к цене.
В обычном стакане цены отображаются исключительно из данных, которые приходят с бэка (OrderBookGetAndSubscribe)
Стакан не может отобразить заявок, которые отсутствуют в OrderBookGetAndSubscribe.

Соответственно это баг нужно адресовать бэку

**Comment by sbelashevskiy** [comment]
Как я описал выше это проблема бэка - с бэка не приходит данная лимитка вообще

**Comment by PilgrimViis** [comment]
@ilya7am у нас не получилось воспроизвести =( Есть подозрение что это бекенд тормозил и не присылал обновления по стаканам
