### ISSUE TITLE
[FEATURE] ... Скорость выставления алертов.

### ISSUE THREAD

**Issue by Goldenboyss** [alor-broker/Astras-Trading-UI#1461]
### Опишите проблему, которую решает ваша фича

На данный момент в виджете -  «Заявка»  в графе условие уведомления пусто, а это значит, чтобы задать условие, требуется сначала кликнуть по пустой графе и только затем, выбрать из предлагаемого списка какое-либо условие. Есть также другая проблема, - в предлагаемом списке нет знака - «Равно». 

### Опишите предлагаемое вами решение

Предлагаю сделать по умолчанию знак «Равно».  Это позволит сократить время выставления алертов.

### Дополнительная информация

![Алерты в Алоре](https://github.com/alor-broker/Astras-Trading-UI/assets/153299638/224eaf8a-211f-48d5-8c07-3a6caf8c30b8)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Какой смысл у операции "Равно"? Вряд ли в стакане будет цена один в один такая какую вы хотите. Оно проскользнет и ваша заявка не исполнится.

**Comment by PilgrimViis** [comment]
А что делать если в стакане не будет такой цены? Допустим вы поставили Равно на 95. А заявки прошли по 95.01 и 94.99. Цены в стакане =95 не было никогда, уведомление не сработало. Какой был смысл в таком уведомлении?

**Comment by Goldenboyss** [comment]
> А что делать, если в стакане не будет такой цены? Допустим, вы поставили Равно на 95. Заявки были выполнены до 95.01 и 94.99. Цены в стакане =95 не было никогда. Какой был смысл в таком обучении?

Смысл в том, что цена коснулась этого значения, т.е. теоретически была на этом уровне. А этого должно быть уже достаточно, чтобы алерт направил нам оповещение об этом.

**Comment by agushasok** [comment]
Проблема будет решена в рамках задачи #1524

**Comment by varo1n** [comment]
![Снимок экрана 2024-04-03 в 14 26 17](https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/c2d21f86-10ae-4c89-8820-f5ad813e73cc)
Добавьте еще в контекстное меню в виджете Теханализ, как это сделано в TradingView. Только не открытие виджета с параметрами уведомления, а быстрое выставление.
