### ISSUE TITLE
[BUG] Неверно отображаются поля P/L %

### ISSUE THREAD

**Issue by agushasok** [alor-broker/Astras-Trading-UI#1494]
### Опишите баг

Посмотреть, в чём причина таких расчётов и исправить

### Воспроизведение

<img width="642" alt="image" src="https://github.com/alor-broker/Astras-Trading-UI/assets/45139991/229cc52f-e4ba-4371-9fc3-bf72930faf12">

### Среда.

Любая

### Ожидаемое поведение

Должны отображаться правильные значения

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
На скрине девовский портфель. Там криво.
