### ISSUE TITLE
[FEATURE] Рыночные заявки в аукционы

### ISSUE THREAD

**Issue by zlobinm** [alor-broker/Astras-Trading-UI#1499]
### Опишите проблему, которую решает ваша фича

В OpenAPI Alor добавлена возможность выставлять рыночные заявки на аукционе открытия и закрытия.
В терминале отсутствует.

### Опишите предлагаемое вами решение

Добавить возможность выставлять рыночные заявки в периоды аукционов открытия и закрытия MOEX.

### Дополнительная информация

В OpenAPI Alor, в тело запроса нужно добавить поле "timeInForce". Добавить проставление поля в терминале.

Пример апи:

{
    "side": "buy",
    "quantity": 1,
    "comment": "коммент",
    "instrument": {
        "symbol": "тикер",
        "exchange": "MOEX"
    },
    "user": {
        "portfolio": "D12345"
    },
    "timeInForce": "OneDay"
}

### Правила

- [X] Я согласен следовать правилам

**Comment by agushasok** [comment]
Необходимо сделать на беке проверку периода аукционов и подставление поля timeInForce: 'oneDay', если инструмент на аукционе открытия/закрытия. На фронте не очень, с точки зрения оптимизации, каждый раз при выставлении маркет-заявки делать запрос инструмента, чтоб узнать, на аукционе он сейчас или нет
