### ISSUE TITLE
[FEATURE] Накладывается панель объемов на данные в стакане, при отключении доп панелей

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1503]
### Опишите проблему, которую решает ваша фича

При отключении доп панелей(принтов(сделок)) в меню сс, панель объемов накладывается на данные самого стакана. При этом нет возможности ее куда либо сместить, особенно если стакан маленький. 

### Опишите предлагаемое вами решение

Сделать панель объемов и LS панель опциональную. 
Что бы трейдер мог сам регулировать  ее расположение(либо внутри стакана, либо вывести ее обратно на верхнюю панель). 

### Опишите альтернативные решения, о которых вы думали

Возможно, LS панель, не всем нужна.  Поэтому можно сделать ее также опциональной и разместить в меню "Доп панели"

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Добавлена возможность отключать и отображать панель объемов сверху стакана
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/774984b6-0b79-4811-9fce-744df46eec0f)

Также для short/long панели
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/ade243a5-1370-4e10-b04d-1b279bd2a79a)

Отображение изменения цены также перенесено в "Дополнительные панели"
