### ISSUE TITLE
[FEATURE] Добавить возможность в коридорах в сс использовать только одну частью стороны условной заявки

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1506]
### Опишите проблему, которую решает ваша фича

В данный момент, в сс, при включение функции "Использовать коридоры", трейдер обязан указывать И условную заявку снизу И условную заявку сверху. 
Если трейдеру нужно использовать только одну заявку, то система ему это сделать не позволит.  
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/40ae4f88-9572-4fdf-aecd-7fdef3106f76)

Причем сейчас обратил внимание, что система примет значение равную 0. Чего лучше не допускать. Т.к. она выставляет лимитную заявку на закрытие по той же цене , по которой был и вход в позицию. 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/14d61a07-bec7-4049-81af-f1e7941cdc9e)

### Опишите предлагаемое вами решение

Необходимо добавить возможность ввода данных в поле условных заявок и в одну сторону. 
Т.е. если трейдеру необходимо ставить только условные заявки на закрытие позиции по убытку. 
Причем нужно, что бы система учитывала сторону в позиции (в покупку заходит трейдер или в продажу).  
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/2ff4e1f3-2de7-4338-bf1d-8e986789479b)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@agushasok можешь пожалуйста проверить дает ли выставить связанные заявки бек, когда 1 лимит и 1 условная.

**Comment by uncrashable** [comment]
> @agushasok можешь пожалуйста проверить дает ли выставить связанные заявки бек, когда 1 лимит и 1 условная.

Добрый день. Есть информация по этому вопросу?

**Comment by PilgrimViis** [comment]
> > @agushasok можешь пожалуйста проверить дает ли выставить связанные заявки бек, когда 1 лимит и 1 условная.
> 
> Добрый день. Есть информация по этому вопросу?

да всё в порядке. Уже сделали.
