### ISSUE TITLE
[FEATURE] Коридоры в Скальперский стакан

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1507]
### Опишите проблему, которую решает ваша фича

В данный момент система коридоров в сс неудобная.
Предлагаю скорректировать описания и их работу.  

### Опишите предлагаемое вами решение

Переименовать: 
Условная заявка сверху (≥), Условная заявка снизу (≤) на 

Условная заявка на закрытие позиции по **прибыли**
Условная заявка на закрытие позиции по **убытку**
Внести корректировку в сс в понимание направления в сделке (покупка или продажа) - система должна автоматически это понимать и выставлять условные заявки относительно того, в каком направлении трейдер выставляет заявку. 
При входе в позиции "по рынку" система также должна срабатывать. 

Пример. 
Единицы цены = Пункты
Условная заявка на закрытие позиции по **прибыли** = 100
Условная заявка на закрытие позиции по **убытку** =20

При выставлении лимитной заявки или входе по рынку в лонг, система должна выставить автоматически условную заявку на закрытие позиции по убытку (т.е. ниже точки входа) на 20 пунктов ниже, а на закрытие по прибыли на 100 пунктов выше точки входа. 

При условии, что трейдер заходит в шортовую сделку, у него прибыль будет ниже точки входа в позицию, но система должна это будет учесть и также , на тех же условиях выставить ему условную заявку в прибыль на 100 пунктов ниже точки входа, а на закрытие позиции по убытку на 20 пунктов выше его точки входа. 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
> При условии, что трейдер заходит в шортовую сделку, у него прибыль будет ниже точки входа в позицию, но система должна это будет учесть и также , на тех же условиях выставить ему условную заявку в прибыль на 100 пунктов ниже точки входа, а на закрытие позиции по убытку на 20 пунктов выше его точки входа.

Вот это я не понял.

**Comment by uncrashable** [comment]
> Условная заявка на закрытие позиции по **прибыли**
> Условная заявка на закрытие позиции по **убытку**

Если у нас будет вот такая трактовка : 
Условная заявка на закрытие позиции по прибыли
Условная заявка на закрытие позиции по убытку

То думаю будет более понятно. 

Выше я описал логику прибыли и убытка , для трейдеров, которые открыли позицию в лонг и в шорт: 

У трейдера, который купил актив, прибыль будет выше точки входа в позицию
У трейдера, который продал(шорт), прибыль будет ниже точки входа в позицию 

и я акцентировал внимание на то, что бы система это понимала. 

Если я ставлю значения 
Условная заявка на закрытие позиции по прибыли 100
Условная заявка на закрытие позиции по убытку 50
, то если я зайду в лонг, то коридор должен выставляться  на 100 пунктов ВЫШЕ точки входа, и на 50 пунктов НИЖЕ точки входа. 

, а если я захожу в шорт, при тех же настройках, система должна поставить мне коридор на 100 пунктов НИЖЕ точки входа, и на 50 ВЫШЕ точки входа, 
.. т.к. прибыли я хочу больше чем убытка.
