### ISSUE TITLE
[FEATURE] Использование индикаторов сообщества Trading View в Astras 

### ISSUE THREAD

**Issue by AlorKek** [alor-broker/Astras-Trading-UI#1516]
### Опишите проблему, которую решает ваша фича

Механизм добавления собственных или сторонних индикаторов через опен апи (или иным способом) в Астрас без ограничения в 2 одновременно добавленных индикаторов, как это реализовано в оригинальном Trading View без подписки.

### Опишите предлагаемое вами решение

В Trading View есть инструмент Pine, через который можно просмотреть код индикатора. В уже имеющиеся в Астрас индикаторы можно добавить еще один справочник (собственный, пустой), в который была бы возможность выгрузить код стороннего индикатора.

### Дополнительная информация

Есть идеи как это можно реализовать?

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Спасибо за предложение, это действительно было бы здорово. Мы уже изучали этот вопрос и общались с коллегами из tradingview, к сожалению это невозможно Pine доступен только на платформе tradingview.com, другим они этот функционал не дают.

**Comment by PilgrimViis** [comment]
Как только они дадут такую возможность, мы сразу реализуем.
