### ISSUE TITLE
[FEATURE] Создать оповещение на событие

### ISSUE THREAD

**Issue by mvalenkaz** [alor-broker/Astras-Trading-UI#1539]
### Опишите проблему, которую решает ваша фича

Я испытываю трудности в определении момента достижения ценой акции на ее графике заданной величины, особенно сложно когда много графиков и за всеми надо следить, а цена очень быстро может придти в нужную точку. И к тому же не находишься рядом с монитором. Это необходимо чтобы не пропустить точку входа.

### Опишите предлагаемое вами решение

При достижение на графике ценой определенного значения (например, уровня) или  пересечение средних ( по условию) на экране появляется сообщение Alert и сопровождается звуковым сигналом. При этом на экране может быть открыт график другой акции.

### Опишите альтернативные решения, о которых вы думали

Tradingview реализовал эту фичу

### Дополнительная информация

такая фича есть и ВТБ и Финам но только на телефонной версии. Необходимо чтоб в браузерной версии выскакивалор это сообщение поверх всех окон и сопровождалось звуковым сигналом

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. А почему не подходит для этого фунционал уведомлений который есть сейчас?
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/a5245d37-a230-4af7-8963-c52d2dd5d5b5)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/199da762-c0a0-48d7-a26c-cab388f70ec5)

**Comment by mvalenkaz** [comment]
В чате поддержки написали обратиться сюда по этому вопросу.

**Comment by PilgrimViis** [comment]
> В чате поддержки написали обратиться сюда по этому вопросу.

То есть как я понял, в поддержке не знали про эти уведомления? Я расскажу коллегам про это, чтобы в следующий раз они знали. А задачу закрою тогда.
