### ISSUE TITLE
[FEATURE] Доработка графиков (виджет Тех. анализ)

### ISSUE THREAD

**Issue by offvine** [alor-broker/Astras-Trading-UI#1545]
### Опишите проблему, которую решает ваша фича

Что хотелось бы видеть и чего бы не хотелось:

- Активация поиска инструмента простым нажатием любой буквы как это нативно сделано в TV (было бы здорово, если такой функционал был на всех виджетах, где есть возможность поиска инструмента)
- Возможность сохранения своих шаблонов
- Синхронизация объектов рисования между несколькими графиками
- Сделать более компактной верхнюю панель: по сути их там две и дублирующаяся кнопка поиска инструмента, а их бы в одну компактную объединить без дублей
- Нижняя панель, где выбор временных диапазонов, по большому счету бесполезная, часть функционала доступна по горячим клавишам, часть со шкалы цен, в целом только драгоценное место занимает.

### Опишите предлагаемое вами решение

Предлагаю убрать лишнее и добавить нужное

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
- Активация поиска инструмента простым нажатием любой буквы как это нативно сделано в TV (было бы здорово, если такой функционал был на всех виджетах, где есть возможность поиска инструмента)
Нажмите Ctrl-F и активируется поиск
- Возможность сохранения своих шаблонов
Под шаблонами вы понимаете настройки отображения графика или применённые индикаторы?
- Синхронизация объектов рисования между несколькими графиками
Как вы это видите? Какую проблему решает данная фича?
- Сделать более компактной верхнюю панель: по сути их там две и дублирующаяся кнопка поиска инструмента, а их бы в одну компактную объединить без дублей
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/a7b4c2f2-c8c8-491f-bf11-4cb12c04b824)
Вы это имеете в виду? Если да, то не вижу особого смысла. Мы все равно не используем пространство слева от кнопок виджета (закрытие, справка и т.д.)  поэтому по факту экономии не будет
- Нижняя панель, где выбор временных диапазонов, по большому счету бесполезная, часть функционала доступна по горячим клавишам, часть со шкалы цен, в целом только драгоценное место занимает.
@sbelashevskiy мы можем сделать настройку чтобы её убрать?

**Comment by offvine** [comment]
> * Активация поиска инструмента простым нажатием любой буквы как это нативно сделано в TV (было бы здорово, если такой функционал был на всех виджетах, где есть возможность поиска инструмента)
>   Нажмите Ctrl-F и активируется поиск

Не работает. При при при клике по графику и после Ctlr+F активирует поиск по страница, при клике по пустому пространству или другим виджетем активируется поиск в первом виджете поиск инструмента (браузер - vivaldi)
<img width="1672" alt="Screenshot_77" src="https://github.com/alor-broker/Astras-Trading-UI/assets/157825005/5d9a6316-10d2-4d9a-9901-8e687c59d905">

> * Возможность сохранения своих шаблонов
>   Под шаблонами вы понимаете настройки отображения графика или применённые индикаторы?

Настройки графиков
> * Синхронизация объектов рисования между несколькими графиками
>   Как вы это видите? Какую проблему решает данная фича?

Если пользоваться больше чем одним графиком на инструмент (у меня, например, минимум два тф всегда открыты, старший с общей картиной и младший для контроля текущей ситуации), то отображение на первом графике с младшим тф объектов, нанесенных на графике более старшего тф, помогает быстрее увидеть важные места, и в целом проще ориентироваться общей картине происходящего.
<img width="526" alt="Screenshot_79" src="https://github.com/alor-broker/Astras-Trading-UI/assets/157825005/3f68228f-8eb5-46ad-b8ae-7870dc6008f1">
Так бы это выглядело. По-моему с красными линиями легче увидеть и оценить ситуацию в триггерных зонах.

> * Сделать более компактной верхнюю панель: по сути их там две и дублирующаяся кнопка поиска инструмента, а их бы в одну компактную объединить без дублей
>   ![image](https://private-user-images.githubusercontent.com/6408195/311771609-a7b4c2f2-c8c8-491f-bf11-4cb12c04b824.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTk2NDUsIm5iZiI6MTcxMDE5OTM0NSwicGF0aCI6Ii82NDA4MTk1LzMxMTc3MTYwOS1hN2I0YzJmMi1jOGM4LTQ5MWYtYmYxMS00Y2IxMmMwNGI4MjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMjMyMjI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWZjY2EyYzZhNzFmZjE1NWE5ZTA2YjBjYzY0ZGE1MTcyYjE2MTRhMmJmZjA1NDY1ZmE4OWI4YTcyMmE5YTBmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CEXGrPDaeUYU7Wvy_PC5lMelMz-o_bq2rZn_wEo1UHY)
>   Вы это имеете в виду? Если да, то не вижу особого смысла. Мы все равно не используем пространство слева от кнопок виджета (закрытие, справка и т.д.)  поэтому по факту экономии не будет

Да, я про эти элементы поиска. Если эти две панели(верхнюю с кнопками закрытие, справка и т.д. и нижнюю с выборами тф. и т.д.) в одну объединить нельзя, то да, смысла убирать только верхний элемент поиска нет, тогда пустое пространство занимающее место еще больше будет бросаться в глаза.
> * Нижняя панель, где выбор временных диапазонов, по большому счету бесполезная, часть функционала доступна по горячим клавишам, часть со шкалы цен, в целом только драгоценное место занимает.
>   @sbelashevskiy мы можем сделать настройку чтобы её убрать?

**Comment by offvine** [comment]
> Судя по скрину у вас нету виджета выбор инструмента на доске. Если добавите его то будет работать.

Т.е. нету? Если эти 4 виджета не выбор инструмента, то какой тогда?
<img width="606" alt="Screenshot_81" src="https://github.com/alor-broker/Astras-Trading-UI/assets/157825005/a53a4f04-de07-4526-9715-b090310deb7b">

**Comment by uncrashable** [comment]
> * ия поиска инструмента простым нажатием люб

Да, если кликнуть по графику, то Ctrl+F уже не работает - открывает поиск на странице гугла

**Comment by uncrashable** [comment]
@PilgrimViis  - Синхронизация объектов рисования между несколькими графиками 

Поэтому предложению я за! Удобная вещь. 

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/ff4e2f99-952e-43ca-89f4-84e42396ed56


Экономит время для рисования. 
Обычно трейдеры используют сразу несколько открытых графиков с разными таймфреймами. 
И было бы удобно, что бы связанные графики отображали элементы рисования - там даже курсор синхронизируется.

**Comment by PilgrimViis** [comment]
> * Сделать более компактной верхнюю панель: по сути их там две и дублирующаяся кнопка поиска инструмента, а их бы в одну компактную объединить без дублей
> * Нижняя панель, где выбор временных диапазонов, по большому счету бесполезная, часть функционала доступна по горячим клавишам, часть со шкалы цен, в целом только драгоценное место занимает.

Будет решено в рамках #1306

**Comment by sbelashevskiy** [comment]
1. "Активация поиска инструмента простым нажатием любой буквы как это нативно сделано в TV (было бы здорово, если такой функционал был на всех виджетах, где есть возможность поиска инструмента)"

Активирован поиск по нажатию клавиш. Также поиск по ctrl+f. Касается только этого виджета т.к. это сторонний компонент со своим собственным поведением, влиять на которое мы не можем. Этим и объясняется почему поиск не активировался после клика на график.

2. "Возможность сохранения своих шаблонов"
Реализовано

3. "Синхронизация объектов рисования между несколькими графиками"
Данная функция является платной на платформе 
https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/de7eab33-79fd-4d4e-81f7-66e0f8c1e160
А локальная реализация в Trading View работает ТОЛЬКО на trading платформе (т.е. графики интегрированы с терминалом) и недоступна в версии только график
https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/25b7580b-8f21-4432-9aa9-b82321a9e9ea

Сам по себе график не предоставляет какого либо интерфейса синхронизации. Это значит, что данную функцию внешними средствами без ущерба производительности и стабильности не реализовать.

4. "Сделать более компактной верхнюю панель: по сути их там две и дублирующаяся кнопка поиска инструмента, а их бы в одну компактную объединить без дублей"

Я не вижу какого-либо дублирования. Заголовок виджета является его неотъемлемой стандартизованной частью. 
Поиск и смена инструмента в заголовке работает по правилам терминала, ОБЩИМ для всех виджетов, которые привязываются к инструментам. 

Поиск и смена инструмента внутри графика это функционал сторонней библиотеки. Кроме того, только этот поиск позволяет задать синтетический инструмент.

Кому-то хватает привязки к активному инструменту, выбранному из списка инструментов или блоттера или виджета все инструменты. Кто-то меняет инструмент у каждого виджета через заголовок. А кому-то удобнее пользоваться на графике TV поиском. А кому-то нужен функционал именно синтетических инструментов, который доступен ТОЛЬКО из поиска графика.

В любом случае, если кому-то встроенный поиск не нужен, то его можно будет отключить из настроек графика. 

6. "Нижняя панель, где выбор временных диапазонов, по большому счету бесполезная, часть функционала доступна по горячим клавишам, часть со шкалы цен, в целом только драгоценное место занимает."

Это стандартная функциональность графика. Используемая библиотека по факту признанный стандарт. Думаю, если бы эта панель было бесполезной, то разработчики Trading View ее отключили или вынесли бы ее в настройки.

Тем не менее данную панель можно будет отключить из настроек виджета.
