### ISSUE TITLE
[FEATURE] Пожелания к виджету "График"

### ISSUE THREAD

**Issue by offvine** [alor-broker/Astras-Trading-UI#1546]
### Опишите проблему, которую решает ваша фича

По приоритету:

1. Сохранение масштаба и позиции при переключении тф
2. Активация поиска инструмента с любой клавиши, без надобности кликать на кнопку для поиска
3. Возможность настраивать тему и сохранять шаблоны
4. Минимальный набор для граф анализа (уровни, наклонки, горизонтальные лучи, прямоугольники)
5. Синхронизация объектов рисования между графиками

### Опишите предлагаемое вами решение

Предлагаю добавить эти штуки

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
По сути мини график нужен для одной единственной цели. Что тех кому надо создать много маленьких графиков и следить за кучей инструментов. Для всех остальных целей есть тех. анализ виджет. Поэтому мы не видим необходимости тратить время на доработку этого графика. По поводу поиска же, у нас есть глобальный поиск инструмента по Ctrl-F, Он активирует поиск в виджете "выбор инструмента"
