### ISSUE TITLE
[FEATURE] Не отражается финансовый результат

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#155]
### Опишите проблему, которую решает ваша фича

Не отражается финансовый результат отдельно по каждой открытой позиции в виджете Блоттер

### Опишите предлагаемое вами решение

- добавить в настройках колонку, отражать по умолчанию.

### Дополнительная информация

Расчет дохода или убытка отдельно по каждой открытой позиции. Расчет: текущая цена последней сделки - средняя цена открытия позиций.

### Правила

- [x] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@profull-art можете, пожалуйста, написать Аvatars08 в телеграм? Не пожалеете =)
