### ISSUE TITLE
[BUG] Не работает центровка Скальп. стакана при отсутствии асков или бидов 

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1556]
### Опишите баг

Если в СС нет асков или бидов, то центровка стакана (клавиша "пробел") не работает.
Например, для GAZPP200324PE135 или ROSB 
![2024-03-15_12h45_37](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/8ab3edd6-3b52-4e95-a5c1-e639f63bbd82)

Для GAZPP200324PE135 приходится в настройках отключать опцию "Показывать цены между лучшими ценами покупки/продажи", чтобы сократить стакан и увидеть аски.

### Воспроизведение

1. Выбрать инструмент, когда по нему нет асков или бидов. Например, ROSB.
2. Зажать "пробел" в СС.
3. Проверить центровку стакана.

### Среда.

Windows 10
Google Chrome v120.0.6099.200

### Ожидаемое поведение

Если в стакане только аски или только биды, центрировать СС по ним при зажатой клавише "спейс".

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Если нет асков и бидов то центрировать не по чему. Центровка происходит по середине между асками и бидами.

**Comment by sbelashevskiy** [comment]
@ilya7am,
 когда заводишь такие баги, то подбирай, пожалуйста, инструменты:
 1. Не понимаю при чем тут указан ROSB - по нему есть и аски и биды
 2. GAZPP200324PE135  - это опцион, он в принципе торгуется не так, как какой-нибудь SBER. Ты на разброс цен у него посмотри 0,02-500. В принципе не понимаю зачем его в скальперском стакане открывать

**Comment by uncrashable** [comment]
> @ilya7am, когда заводишь такие баги, то подбирай, пожалуйста, инструменты:
> 
> 1. Не понимаю при чем тут указан ROSB - по нему есть и аски и биды
> 2. GAZPP200324PE135  - это опцион, он в принципе торгуется не так, как какой-нибудь SBER. Ты на разброс цен у него посмотри 0,02-500. В принципе не понимаю зачем его в скальперском стакане открывать, тем более с включенным отображением спрэда

Тут речь идет о ,,планке,, , т.е. когда инструмент достиг максимального или минимального значения ценового диапазона. 
Такое бывает не часто, поэтому указать на конкретный инструмент , можно только в день ситуации. 

Когда откупают инструмент и он вырос на 10 или 20% , биржа убирает из стакана аски , видно остается только биды , торги идут, т.е. продать по бидам можно. И вот при такой ситуации , если нажать пробел , то центровка срабатывает непонятно как , центрируется чуть выше по стакану , приходится крутить колесиком мыши , что бы найти этот бестбид и все остальное
