### ISSUE TITLE
[FEATURE] Не отражается доступный лимит в лотах

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#156]
### Опишите проблему, которую решает ваша фича

В виджете Боттер не отражается максимально достуное количество лотов к покупке или продаже выбранного инструмента. 

### Опишите предлагаемое вами решение

Добавить колонки отражения "Можно купить" и "Можно продать"

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Идея интересная и фича вроде полезная. Опасения вызывает то, что придется много запросов кидать, чтобы данные были актуальные. На фронтенду обсчитывать риски будет некорректно. Мы подумаем, что можно сделать.
