### ISSUE TITLE
[BUG] Ошибка после авторизации

### ISSUE THREAD

**Issue by zlobinm** [alor-broker/Astras-Trading-UI#1574]
### Опишите баг

После авторизации появляется ошибка
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/104907168/0a38b283-4d5a-47ee-9eb2-58694089a958)

### Воспроизведение

- Авторизоваться / 
- Воспроизводится при наличии / отсутствии виджетов
- Режим обычный / инкогнито

### Среда.

- ОС Windows, Android
- Google Chrome
- Microsoft Edge etc.

### Ожидаемое поведение

-

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Проблемы на бэке из-за обновления инфраструктуры.

**Comment by PilgrimViis** [comment]
На беке пофиксили.
