### ISSUE TITLE
[FEATURE] Быстрое изменение заявки

### ISSUE THREAD

**Issue by PullPlus** [alor-broker/Astras-Trading-UI#1583]
### Опишите проблему, которую решает ваша фича

При изменении заявки на виджете теханализ приходится прожимать подверждение мышкой каждый раз.

### Опишите предлагаемое вами решение

Добавить обработку клавиши enter в окне изменения заявки. Добавить настройку изменения заявок без подтверждения.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я думаю Enter не получится. Потому что ему надо будет мышкой кликнуть наружу чтобы выйти из поля ввода значения (цены, кол-ва и т.д.). Поэтому можно попробовать сделать Ctrl-Enter
