### ISSUE TITLE
[BUG] Кнопка "Снять все заявки" не снимает заявки 

### ISSUE THREAD

**Issue by zlobinm** [alor-broker/Astras-Trading-UI#1584]
### Опишите баг

У алготрейдеров не снимаются все заявки кнопкой "Снять все заявки".

### Воспроизведение

- Воспроизводится при количестве заявок в несколько тысяч. 
- Проявляется для обычных и стоп-заявок

### Среда.

- Webfront

### Ожидаемое поведение

-

### Дополнительная информация

Кейс:
_Остановил создание ботом стоп-заявок. Их на момент было 208.
Зашёл в астрас и нажал массовую отмену. В результате у меня в астрасе сейчас отображается, 
что активных стоп-заявок нет (и обновлял несколько раз и уже страничка спокойна минут 5). 
А в текущем коннекте на получение стоп-заявок по вэбсокету висит 139 активных стоп-заявок._
т.е. в итоге: 
- было 208 заявок
- Нажал кнопку. По сокету пришли активных 139

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@zlobinm при нажатии кнопки "Снять все заявки" отображается какое-нибудь сообщении об ошибке?

**Comment by zlobinm** [comment]
@sbelashevskiy Добрый день. Про ошибку не сообщали, значит делаю вывод что не было ошибки. сообщали только что снятия не происходило. 
Вот цитата из другого кейса:

_Говорит, что все верно выбрано, но в блоттере ничего нет. Сейчас попытался снять все заявки через кнопку Снять все в этом виджете, но ничего не произошло_

**Comment by sbelashevskiy** [comment]
как понять, что в блоттере ничего нет? В итоге заявки снялись?

**Comment by zlobinm** [comment]
- В Блоттере не отображались Активные заявки. т.е. у клиента было свыше 10 тыс. заявок (снятые, исполненные, активные). Он не видел какие Активные. Фильтр не помог.
Это лишь цитата в подтверждение того, что реальные обращения были. 
- Заявки в итоге не снялись.

**Comment by sbelashevskiy** [comment]
Честно говоря вообще ничего не понятно. 
Тут речь о 208 заявках
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/4810242f-4e07-4d53-b3ca-181b7412b7e1)

Говорится, что активных заявок нет. 

ASTRAS вообще не рассчитан на работу с ботами, только на взаимодействие с человеком. WARP не предоставляет методов для массовой отмены заявок. Каждая заявка отменяется одна за другой. Понятно, что при количестве > 10000 могут быть проблемы. Если при отмене возникла ошибка - она будет отображена в стандартном уведомлении вверху экрана справа.

**Comment by zlobinm** [comment]
_- Говорится, что активных заявок нет - вообще таблица пустая или именно активных нет?_
Предполагаю что речь именно про Активные заявки. При фильтре Активных заявок, показывает, будто нет.
Не удалось собрать больше инфы, т.к. кейс прислан уже после сессии, в которую возникло.

_ASTRAS вообще не рассчитан на работу с ботами, только на взаимодействие с человеком. WARP не предоставляет методов для массовой отмены заявок. Каждая заявка отменяется одна за другой._
Знаем, согласны. 
Клиенты ожидали, что то, что делается в АПИ, будет также работать и с Астрас.

**Comment by PilgrimViis** [comment]
Я эту задачу пока закрою, чтобы не было дубликатов. Она должна быть решена в рамках https://github.com/alor-broker/Astras-Trading-UI/issues/1587 В той задаче эту прилинковал, чтобы не забыть проверить.
