### ISSUE TITLE
[BUG] Проблема с уведомлениями в браузере Safari на Mac OS

### ISSUE THREAD

**Issue by varo1n** [alor-broker/Astras-Trading-UI#1593]
### Опишите баг

Здравствуйте. Не работают уведомления в веб-терминале Astras в Safari. В системных настройках все включено, но Astras пишет, что нужно включить. Выключать/включать пробовал, перезагружать и тд пробовал. Уведомления от других сайтов и программ работают.

### Воспроизведение

В терминале: Виджет "Выставить заявку" - Уведомления
В системе: Настройки - Уведомления - Astras

### Среда.

ОС - MacOS Sonoma 14.4.1
Браузер - Safari 17.4.1

### Ожидаемое поведение

Исправьте, пожалуйста ошибку, чтоб веб-терминал видел включенные уведомления в системе.

### Скриншоты

![Снимок экрана 2024-04-03 в 14 42 18](https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/f4694769-5363-4193-b32d-9959a40edbfc)

### Правила

- [X] Я согласен следовать правилам

**Comment by agushasok** [comment]
Добрый день, попробуйте разрешить уведомления через настройки Safari, как на видео


https://github.com/alor-broker/Astras-Trading-UI/assets/45139991/77d7f88e-aac1-4aaf-a590-c9e0400a11f9

У меня работают
<img width="1728" alt="image" src="https://github.com/alor-broker/Astras-Trading-UI/assets/45139991/6fcbdf41-f638-4b2b-b014-dc42da479866">

**Comment by varo1n** [comment]
<img width="1231" alt="Снимок экрана 2024-04-04 в 14 31 25" src="https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/86c1d0ca-b0a6-47dc-8023-a76f0817cc27">

У меня по какой-то причине Астрас в браузере даже не запрашивает разрешение. В виджете "Выставить заявку" все та же надпись. 

![Снимок экрана 2024-04-04 в 14 43 25](https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/fd45660b-a9fe-45b8-819b-8c5dae40bfa0)

Пробовал вызвать уведомление путем выставления и отмены лимитки, но вместо запроса просто показывается как будто уведомление внутри страницы без звука, а нужны именно системные уведомления как у вас.

Получается проблема на моей стороне, раз у вас все работает..

**Comment by varo1n** [comment]
И правда, проблема была у меня. Перечитал интернет, оказалось всему виной блокировщик рекламы AdGuard, который перманентно блокировал уведомления от всех сайтов, из-за этого они не могли даже отправить запрос. Как исправить не нашел, попрощался с блокировщиком. Вопрос решен, всем спасибо )
