### ISSUE TITLE
[FEATURE] Перетаскивание заявок в стакане

### ISSUE THREAD

**Issue by varo1n** [alor-broker/Astras-Trading-UI#1594]
### Опишите проблему, которую решает ваша фича

Здравствуйте. В веб-терминале Astras изменить выставленную заявку возможно только отменой старой и выставлением новой, либо через вкладку "Заявки" виджета "Блоттер". Оба способа в большинстве случаев занимают много времени. Возможно изменить перетаскиванием в виджете "Тех. анализ", но это не совсем удобно при работе в стакане или в случае, если виджет "Тех. анализ" вовсе не используется при работе (открыты виджеты "Скальперский стакан" и "График" по отслеживаемым инструментам.

### Опишите предлагаемое вами решение

![Снимок экрана 2024-04-03 в 15 08 08](https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/a3590359-9338-40cd-b32c-6623c2415f69)

Сделайте отдельную кнопку для отмены заявки в стакане (_крестик чуть правее заявки_), а при нажатии на наименование заявки (_SL(1)_) и перетаскивание возможность изменять цену заявки. Проще говоря сделайте так, чтобы можно было перетаскивать заявки в стакане, а для отмены отдельную кнопку.

### Опишите альтернативные решения, о которых вы думали

Как альтернативный вариант для сохранения компактности можно сделать перемещение заявок левой кнопкой мыши, а отмену заявки правой кнопкой мыши.

### Дополнительная информация

Будет особенно круто, если сделаете оба варианта и добавите пункт в настройки виджета "Скальперский стакан", а там каждый выберет сам себе как ему удобнее.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
При перетаскивание стоп заявок возникает проблема. А именно, какую именно цену вы хотите изменить перетаскиванием. По идее реализовать это без проблем можно только одним способом, если меняем сразу 2 цены. Пример.
Была лимит цена 100 и триггер 90. Перетащили на 10 пунктов. Стала лимит цена 110 и триггер 100.

**Comment by uncrashable** [comment]
В Астрас есть горячая клавиша, которая снимает все стоп заявки "f" - по умолчанию. 
Также можно нажать мышью на саму стоп заявку - она отменится

Крестик займет много места. Когда работаешь одним лотом не сильно заметно , а когда объемы на тысячи, будет смещение большое.

**Comment by uncrashable** [comment]
а поповоду перемещения заявки - да. Нужная вещь.

**Comment by varo1n** [comment]
> При перетаскивание стоп заявок возникает проблема. А именно, какую именно цену вы хотите изменить перетаскиванием. По идее реализовать это без проблем можно только одним способом, если меняем сразу 2 цены. Пример. Была лимит цена 100 и триггер 90. Перетащили на 10 пунктов. Стала лимит цена 110 и триггер 100.

Да, именно так, перетаскивание заявок с сохранением расстояния до триггера, это логично. В точности как вы описали в примере будет замечательно.

**Comment by varo1n** [comment]
> Крестик займет много места. Когда работаешь одним лотом не сильно заметно , а когда объемы на тысячи, будет смещение большое.

Согласен, и так место все время экономить приходится. Указал альтернативный вариант, перетаскивание левой кнопкой мыши, отмена правой или наоборот.

**Comment by uncrashable** [comment]
Сейчас обычные лимитки можно перетаскивать в стакане. Проблем не наблюдал. 
Если нажал на лимитку и отпустил мышь она снимется , а если зажать и перемещать мышь она будет передвигаться. 
Со стопами так же сделать. Не будет лишних движений.
