### ISSUE TITLE
[BUG] Тех. Анализ. Битые свечи за последние 10 мин.

### ISSUE THREAD

**Issue by PullPlus** [alor-broker/Astras-Trading-UI#1595]
### Опишите баг

Виджет Тех. Анализ.
На минутных свечах, в пределах последних минут 10, регулярно попадается битая свеча (по объёму). Подробности на скриншотах.
Апи выдаёт те же свечи, что и ТВ.

### Воспроизведение

Открыть "Тех. Анализ".
Сверить последние свечи с другим источником.

### Среда.

Независимо

### Ожидаемое поведение

Совпадение объёмов свечей с другими источниками.

### Скриншоты

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/92271662/54395bdd-ba31-4cf7-bd34-fc81f7948a4d)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/92271662/80422662-07d2-44e6-9eb2-ee69fe8f84a8)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Не совсем точное описание. Не достаточно наблюдать за графиками в течении 10 мин.
Если просто открыть графики и наблюдать за ними 10+ минуту, то они будут совершенно идентичными т.е обновляются только по сокету. 
Проблема проявляется именно на свечах, которые прогружены из истории, а не добавлены на график из сокета.
Причем проявляется именно на последних свечах и через какое-то время (после обновления страницы) битые свечи исчезают

**Comment by sbelashevskiy** [comment]
Причем спорный вопрос где данные верные. Сейчас в TV объем у приведенной свечи точно такой же, как в астрас
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/61ebad13-2077-498e-95b3-34381f1413fe)

**Comment by sbelashevskiy** [comment]
Данную проблему нужно решать на стороне API.
Для одного и того-то запроса в разные моменты времени возвращаются разные данные.
Например на запрос https://api.alor.ru/md/v2/history?symbol=LENT&exchange=MOEX&from=1712552278&to=1712577213&tf=60

сначала возвращается следующий респонз:
![1](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/106ab775-7201-4a87-b19d-386b47b83e87)

который не соответствует данным в TV и quick (для стороннего брокера).

При этом по прошествии 1-3 минут тот же самый реквест имеет уже другой респонз:
![2](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/6fb8c89e-d48e-42d0-908d-eff6cdebaebf)

который уже совпадает с данными TV и quick.
Получается, что изначально, при погрузке истории ASTRAS отображает некорректные данные, которые приходят из API.
Если через какое-то время обновить страницу, то API уже присылает корректные данные
