### ISSUE TITLE
[BUG] Не сохраняются настройки объектов рисования

### ISSUE THREAD

**Issue by varo1n** [alor-broker/Astras-Trading-UI#1600]
### Опишите баг

Здравствуйте. В Астрас не сохраняются последние использованные настройки объектов рисования после перезагрузки окна терминала. На видео все показано наглядно.

### Воспроизведение

- виджет Тех. анализ
- создать любой графический объект
- изменить настройки
- перезагрузить окно терминала
- создать точно такой же графический объект

### Среда.

- macOS Sonoma 14.4.1
- Google Chrome 123.0.6312.107

### Ожидаемое поведение

Как в TradingView. После изменения настроек созданного объекта, следующий такой же объект должен создаваться с последними использованными настройками в тч после перезагрузки окна терминала.

### Скриншоты

https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/e90ec02a-cd00-463f-9432-f8731e532fa5

### Правила

- [X] Я согласен следовать правилам

**Comment by uncrashable** [comment]
У меня так же.  Еще заметил , что постоянно приходится включать "Магнит" на панели инструментов. 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/e1a5ae58-a09b-413f-a9c9-adce8bbe770c)
Т.е. получается что не сохраняются настройки, которые вносятся в панель инструментов
