### ISSUE TITLE
[FEATURE] Добавить информацию в всплывающее окно инструмента

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1608]
### Опишите проблему, которую решает ваша фича

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/605634b5-bc34-46e5-b5e4-10d1b94f5d63)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/15d1b690-8b7c-432d-8f1d-e2debe79723a)
Прошу добавить в выпадающее окно информацию: 
- лот (кол-во в лоте) 
- стоимость шага цены (сшц) 

### Опишите предлагаемое вами решение

..

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Не вижу особого смысла это делать. Если виджет информация об инструменте, в котором можно посмотреть если забыл параметры для этого инструмента.

**Comment by uncrashable** [comment]
> Не вижу особого смысла это делать. Если виджет информация об инструменте, в котором можно посмотреть если забыл параметры для этого инструмента.

В виджете нет такой информации 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/880365e1-a65f-4227-acdc-834777fcaf90)
Нужно взять лот и в ручную умножить на шаг цены , который нужно еще и определить. 

А добавить этот нужно для удобства и скорости. Т.к. есть инструменты , которые не часто торгуешь и при переключении было бы удобнее напомнить себе , что бы выбрать верный объем
