### ISSUE TITLE
[BUG] В настройках виджетов в "Режим торгов" не отображается борд по активной бумаге

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1614]
### Опишите баг

При выборе бумаги из "Блоттер" или "Все инструменты"  - в настройках виджетов не отобразится борд по активному инструменту. Хотя для некоторых виджетов - поле "Режим торгов" помечено как обязательное (например, для "Тех. анализа"):
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/fb35d502-cfba-45cc-a1b3-a4e9a0f05405)

Причем, при выборе бумаги из "Выбор инструмента" в запросе прописывается параметр instrumentGroup (https://api.alor.ru/md/v2/Securities/MOEX/SBER?instrumentGroup=TQBR), который подставляется в поле "Режим торгов" в виджеты по бумагам и все отображается корректно, поле  "Режим торгов" не пустое.

### Воспроизведение

1. Создать виджет "Тех анализ".
2. Зайти в настройки виджета, перейти в "Продвинутые".
3. Перейти на бумагу из "Блоттера" или "Выбор инструмента".
4. Проверить заполнение поля "Режим торгов".

### Среда.

Windows 10
Google Chrome v120

### Ожидаемое поведение

В поле "Режим торгов" отображается борд, который указан в круглых скобках в шапке виджета рядом с тикером:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/05b0cd22-f07b-43f9-ba57-5d4957274355)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
При выборе из блоттера и всех инструментов у инструмента НЕТ БОРДА. потому он и не отображается. 
В заголовке отображается дефолтный борд, который получается дополнительно по инструменты вместе с его названием.

В настройках отображается фактический выбор. А фактический выбор такой, что у инструмента НЕТ борда. 
Борд это ОПЦИОАНЛЬНОЕ ПОЛЕ, оно и не должно отображаться везде и всюду.

Борд во всех инструментах доступен только когда столбец был добавлен в таблицу.
В блоттере борд доступен из заявок, стоп-заявок и сделок. Из позиций борда нет

**Comment by ilya7am** [comment]
Посмотрел по виджетам, в новом релизе убрали пометку обязательного поля (*) в настройках виджетов (как было на скрине вверху). Поэтому теперь выглядит корректно, поле с бордами опциональное. Думаю, можно закрыть задачу.
