### ISSUE TITLE
[BUG] Пустая строка настройки уведомлений в Профиле в Гугл Хроме

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1617]
### Опишите баг

В Google Chrome на десктопе и на телефоне в "Профиле- Уведомления" не подгружается текст настройки для одного из уведомлений:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/aebb9766-5656-41f2-8e4a-384cd0069796)

Хотя в Mozilla Firefox и Edge нет "пустой строки", загружается 9 типов уведомлений. Ощущение, что в целом это лишнее строка с несуществующим уведомлением:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/0395f476-3d03-4e93-960b-0309e6a0b7eb)

### Воспроизведение

1. Зайти в Астрас через Гугл Хром.
2. Перейти в Профиль- Уведомления.
3. Проверить отображение записей и тумблеров.

### Среда.

Google Chrome v120.0.6099.200 
Mozilla Firefox v124.0b9
Edge v122.0.2365.80 

Android 9

### Ожидаемое поведение

В Уведомлениях нет пустых строк, текст везде отображается

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Вообще не зависит от браузера
Firefox
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/41084454-a3c6-44f2-9def-37b3b73f0fdb)
Edge
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/2f73a967-801f-4bf5-9b66-a25ac9358fb1)

@ilya7am Ctrl+F5 нужно нажимать когда видишь различия в браузерах, чтобы не вводить в заблуждение
