### ISSUE TITLE
[BUG] Подправить механизм поиска бумаги и расчет объема заявки в "Корзина заявок"

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1624]
### Опишите баг

В "Корзине заявок" после выбора инструментов не всегда считается "объем заявки", хотя деньги в портфеле имеются на указанную сумму.
Например, для APTK и AKUP на сумму 1000 рублей - по `/commandapi/warptrans/FX1/v2/client/orders/estimate/all` в теле запроса не отсылается вторая бумага (AKUP), хотя ее цена низкая и на 500 рублей можно выставить не одну заявку:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/708db101-4473-4e14-b9e0-f3c226a7f8c9)

Кроме того, раньше для "Корзина заявок" была привязка к порфтелю. При поиске бумаги отображались варианты бумаг только по конкретному рынку. Сейчас при выборе валютного рынка можно увидеть предложения акций, облигаций. Например, могу выбрать на валютке акцию APTK:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/9810f467-bc31-4a80-8aa9-44755eeca29c)

Из-за этого при выставлении заявки будет ошибка 400, заявка не выставится:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/65dbd91f-29b9-4009-be13-f9510a5cec1f)

### Воспроизведение

1. Создать виджет "Корзина заявок" для D61971.
2. Указать APTK и AKUP, сумма - 1000 рублей.
3. В консоли проверить запрос /all и значения в поле "Объем заявки".
4. Поменять рынок на валютный и в панели поиска Корзины выбрать APTK. Выставить заявку по ней.

### Среда.

Windows 10
Google Chrome v120

### Ожидаемое поведение

1. Верно считает объем заявки, исходя из бюджета по бумаге. В консоли отправляются все инструменты, объем заявок по которым не превышает бюджет по ним.
2. Поиск в корзине заявок привязан к рынку и отображает только бумаги конкретного рынка.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
1. Не наблюдаю ничего подобного

**Реквесты нужно смотреть последние, не взятые произвольным образом.** 
Реквест на скрине сделан когда был добавлен первый инструмент. После него видно, что был осуществлен другой поиск.
Если на скрине обратная сортировка, при которой реквесты сначала идут самые свежие, то не понятно почему взят второй, а не первый.

Чтобы утверждать, что что-то не работает, то сначала нужно посмотреть сколько свободных денег на портфеле.
Судя по всему там всего было около 500р, потому первая позиция расходовала весь бюджет, а на вторую ничего не оставалось.
Естественно, что если оценивать ТОЛЬКО 1 позицию, что на нее будет хватать этих 500р. При этом нужно хотя бы посмотреть сколько лотов позиций можно купить, что вырезано на всех скринах
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/52be5f72-d511-4fa1-9d8c-1fbed4af2d4f)

2. НИКОГДА не было привязки к рынку. Точно также, как и при выставлении заявок. Была и есть только фильтрация по бирже. Если это нужно исправить, то это не баг, а фича реквест

**Comment by ilya7am** [comment]
По п.1: при выборе бумаги для виджета у нас автоматически заполняется поле "Цена" (испр. https://github.com/alor-broker/Astras-Trading-UI/issues/1588), но если сначала вбить цену, а потом указать сам тикер, то в запросе /all не будет этой бумаги. Причем, при смене бумаги на новую (и автомат. подстановке лучшей цены в поле) также не будет считаться "Объем заявки".

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/9747f684-ce5f-4b43-a25d-a9b6afe07ed1

Вне зависимости от порядка заполнения полей должен высчитываться объем заявки по заявке(-ам) в Корзине. И при смене бумаги на новую - меняться показатель "Объема".


По п.2: Понял, спасибо, Сергей, возможно ошибся. Был уверен, что такая привязка была давно.

**Comment by PilgrimViis** [comment]
@sbelashevskiy  сказал что пофиксил то что ты написал в коменте в другой задаче. Поэтому эту закрываю.
