### ISSUE TITLE
[BUG] Убрать "задергивание" при перетаскивании заявок в стакане 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1630]
### Опишите баг

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/3605cb0a-9a86-4ead-aeaf-bfe7b686e080
При перетаскивании Лимитных или Стоп заявок , происходит некое задергивание. Заявка сперва перемещается на свое место где и была , потом только переставляется. 

Можно это убрать ? 

### Воспроизведение

В СС перетягивайте любую заявку . 

### Среда.

Хром на виндовс 

### Ожидаемое поведение

Заявка должна сразу переставится без задергиваний 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
При перетаскивании пользователь указывает цену.
После этого формируется запрос, отправляется
и уже после этого происходит обновление стакана и заявка рисуется там, где она должна быть.

Я не вижу в этом большой проблемы. Это гораздо лучше, чем мы будем искусственно на фронте менять цену у заявки, которая еще не поменялась и которая может не поменяться в следствии какой-либо ошибки при выполнении запроса.

**Comment by uncrashable** [comment]
визуально это лишнее движение -  сбивает,  может личное восприятие такое

**Comment by sbelashevskiy** [comment]
Реализовано в другой задаче
