### ISSUE TITLE
[FEATURE] Добавление полей в виджет "Скринер облигаций" и справление ошибок

### ISSUE THREAD

**Issue by Suastoye** [alor-broker/Astras-Trading-UI#1648]
Добавьте, пож-та, в виджет поля:
1. Период купона
2. Дата выплаты ближайшего купона
3. Размер ближайшего купона
4. Дюрация (лет)
5. Номинал
6. Остаточный номинал
7. НКД
8. Текущая цена (цена последней сделки)
9. Поле "Доср. выкуп/погашение" разбейте на 2: "Оферта", "Амортизация"
10. Дата ближайшей оферты
11. В настройках виджета сделайте возможность ставить:
 - фильтр по погашению облигаций с... по...
 - фильтр по дате выплаты ближайшего купона
 - фильтр по ставке купона с... по...
 - фильтр по признаку "требует тестирования/не требует тестирования"
 - фильтр по признаку "для квалифицированного инвестора/не для квалифицированного инвестора"
 - фильтр по признаку "субординированные облигации/не субординированные облигации"
12. Поле "Тип купона" не подгружается тип купона.
13. Исправить орфографическую ошибку в настройках при выборе поля "Режим торгов" (написано Режим торогов)
![К пункту 12](https://github.com/alor-broker/Astras-Trading-UI/assets/154803042/d1983e56-4b38-41f0-8754-912ec70c3c6e)
![К пункту 13](https://github.com/alor-broker/Astras-Trading-UI/assets/154803042/861c73e5-07ad-464d-bb00-23d43445c44e)

**Comment by PilgrimViis** [comment]
Часть того что не касается новых полей сделаем оперативно. Остальное посмотрим как сложно будет достать. Спасибо за фидбек.

**Comment by PilgrimViis** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/1660 
В общем вот эти поля не сможем отдать. Создал отдельную задачу, их сделаем чуть позже. Всё остальное опубликуем со дня на день надеюсь.

**Comment by Suastoye** [comment]
Добрый день. Спасибо за обновления по новым полям. Сегодня посмотрела, и есть ошибки по подкачке данных. 

НКД в скринере 0 по выбранному инструменту (хоть 0 там не может быть по умолчанию), в инфо об эмитенте другая цифра, и она кривая.. не совпадает с данным на сайте МБ.. Амортизация почему-то есть по всем бумагам... тоже странно.

Откуда подкачиваются данные? Почему они не совпадают с данным МосБиржи? Причем купон совпадает, НКД нет. 

Скрины прилагаю.
![Скринер облигаций](https://github.com/alor-broker/Astras-Trading-UI/assets/154803042/b1a3b92c-5026-4d74-a848-3b38a023df80)
![Скринер облигаций_МБ](https://github.com/alor-broker/Astras-Trading-UI/assets/154803042/c919fb68-6ae4-46f3-abed-27fbedd91b09)

**Comment by PilgrimViis** [comment]
@Suastoye данные мы берем с сервиса интерфакса rudata. Оттуда же берет rusbonds. Сами они берут с НРД насколько я знаю. Вполне допускаю, что у нас может быть ошибка где-то. Вы не могли бы ваш комментарий перенести в отдельную задачу пожалуйста? Мы обязательно разберемся.

**Comment by Suastoye** [comment]
Добрый день, хорошо, перенесу. По скринеру сюда добавлю новые баги. и в отдельную задачу вынесу пожелания
