### ISSUE TITLE
[BUG] По одному инструменту можно выставить стоп-лосс несколько раз

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1655]
### Опишите баг

При установке стоп-лосса через СС - можно выставить стоп-лосс несколько раз, хотя стоп-лосс заявка - заявка на закрытие позиции и она должна быть одна:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/136c4d61-6b02-4cc4-8b78-1ce539561539)

### Воспроизведение

1. Включить "покупать по кликам без уведомлений" в настройках СС.
2. Выбрать бумагу, по которой есть позиции в портфеле.
3. Зажать "шифт" и выставить несколько стоп-лоссов через СС.

### Среда.

Windows 10
Google Chrome v120

### Ожидаемое поведение

SM должна выставляться только одна, при повторном выставлении (через левый шифт) нужно снять текущую SM и поставить в другом месте по новой цене.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
1. У нас нет особого типа заявки "стоп-лосс". У нас есть только стоп по рынку и мы никак не отличаем одни стопы от других, а соотвественно, не можем понять стоп-лосс это или пользователь просто поставил какой-то другой стом по рынку.
2. Стоп-лосс ставится на текущий объем позиции. Объем позиции меняется со временем.
3. См. п. 2 - пользователь же наверное не совсем глупый. С какой целью он будет ставить кучу стоп-лоссов? Наверное, он таки отменит предыдущие заявки и поставит стоп-лосс по нужной ему цене и с текщим объемом.

**Comment by uncrashable** [comment]
> 1. У нас нет особого типа заявки "стоп-лосс". У нас есть только стоп по рынку и мы никак не отличаем одни стопы от других, а соотвественно, не можем понять стоп-лосс это или пользователь просто поставил какой-то другой стоп по рынку. Если следовать описанной логике, то мы просто будем сносить все стопы по рынку, которые пользователь поставил, несмотря на то, что они могли быть поставлены в соответствии с какой-то стратегией. Не нужно забывать, что это только один из множества виджетов и что если даже через него нельзя выставить какую-то заявку, то пользователь не сделает это через диалог или виджет выставления заявок.
> 2. Стоп-лосс ставится на объем (кол-во лотов) позиции, который был на момент выставления. И в любом случае при каких-либо операциях с инструментом выставленный ранее стоп-лосс становится неактуальным т.к. его объем уже не сопадает с текущим. Тогда уже бэк должен считать может ли пользователь ставить еще заявки или нет, т.к. только на бэке есть информация об опциях клиента. Потому и estimate считается на бэке, а не в приложении.
> 3. См. п. 2 - пользователь же, наверное, не совсем глупый. С какой целью он будет ставить кучу стоп-лоссов? Наверное, он таки отменит предыдущие заявки (для этого есть хоткей) и поставит стоп-лосс по нужной ему цене и с текущим объемом. Для этого и сделаны индикаторы заявок в стакане, графике, блоттере.
> 
> Для примера в альфа инвестициях или даже в том же QUICK пользователя никто не ограничивает в количестве выставляемых стоп-лоссов. При этом пользователь сам выбирает на какое кол-во лотов ставить заявку в соотвествии со своей стратегией. Единственное ограничение, которое я вижу в QUICK - это подсчет доступных лотов при выставлении заявки - т.е. если у меня 5 лотов, на 2 я поставил стоп-лосс, то я могу поставить еще не более чем 3 лота. И то сообщение появляется для инструмента, если он не доступен в маржу.
> 
> Соотвественно, откуда утверждение, что стоп-лосс можно ставить только один?
> 
> Более того, работа стоп-лосса уже обсуждалась в другой задаче #1174

______________________________________________

У нас ее нет - но она есть =)))))) 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/aedfdc3f-1dd8-4cb5-be55-e6f8a5d3c930) - тут используется термин "Стоп лосс". 
Коллеги это формулировка, которой пользуются очень многие трейдеры, пусть она технически и не стоп лосс. Но это легче для понимания у трейдеров.  
Мне конечно уже объяснили и я использую другую терминологию. СтопМаркет и СтопЛимит - тогда давайте менять и в описании(см скрин выше чтобы не было путаницы). 
Опять заставляете меня тратить деньги на эти тесты xD 
Видео: 
Uploading chrome_iUIdV6Uc7Z.mp4…
На видео покупаю 1 лот , ставлю два СМ(стопмаркет) - первый закрывает мою позицию (в этом и есть истинный его смысл) , а второй зачем ? У меня позиция закрыта. Если мне надо что бы я вошел по каким то условиям в шорт , то я буду использовать СЛ заявки(которые ставятся через Ctrl) или просто лимитные. 
Я также не вижу смысл в массовом выставлении. и в той задаче это и описывал и там еще есть доп функционал по автоматическому снятию при перевыставлении.

Трейдер просто может даблкликнуть в стакане и получит ненужное ему действие.  

Тут сама логика существования шифта и была для того что бы позицию закрыть и не более. 
А утверждение это взято из практики(опыта) трейдеров

**Comment by uncrashable** [comment]
Для примера. 

https://github.com/alor-broker/Astras-Trading-UI/assets/105817664/2179555f-4bdc-4b2a-aa24-a100e3417465
