### ISSUE TITLE
[FEATURE] Значки сделок в виджете Теханализ

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#1661]
### Опишите проблему, которую решает ваша фича

При активной торговле очень неудобно смотреть отображение сделок в виджете Теханализ 
![Без имени](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/5eaa545b-26cc-43b2-bb24-e107cb6cf28b)

### Опишите предлагаемое вами решение

Если используем стандартные значки, то предлагаю перейти на использование следующих значков "стрелок", которые можно чуть уменьшить и раскрасить разными цветами. Рапсоложены тут
![Без имени-1](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/6d24d4f8-2f46-41b4-bf04-75f69d222365)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
1. Нужно пояснить когда стрелка направлена вверх, когда вниз.
2. Нужн цвета, которые удовлетворяют словиям:
видны, когда накладываются на тело свечи (под разные темы)
видны, на основном фоне (под разные темы)
3. Тултипов не быдет
4. Читабельность нисколько не улучшается - одно дело, когда нарисовано пару значков вне свечей (что впринципе не может быть), а другое, когда они наложены на реальные данные
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/a99eb153-92c7-47af-b999-8fea222f3444)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/5bce334e-c057-4b64-b9f4-437869d305d3)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/caa87cd2-fb34-4d47-961d-1bf3a81739fa)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/98b4f9f9-1571-4d8e-9516-9fdb8507b45d)

**Comment by MorozovDen** [comment]
Тултипы доступны только в одном случае? Заметка или Заметка на экране из "инструментов комемнтирования"

**Comment by MorozovDen** [comment]
1-2
Если сделка "покупка", то стрелка вверх, цвет синий
Если сделка "продажа", то срелка вниз, цвет желтый, оранжевый 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/a2923659-ce94-4a6f-bd73-4fbc2b24130d)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/7187db24-46a8-4bab-a7d7-5a4d99aae5d5)

**Comment by MorozovDen** [comment]
Может пока тултипы не сделаны, то реализовать так?

**Comment by sbelashevskiy** [comment]
"Тултипы доступны только в одном случае? Заметка или Заметка на экране из "инструментов комментирования""

Сейчас они и используются для значков сделок

**Comment by MorozovDen** [comment]
Понял. Тогда смею предложить последний вариант к обсуждению - добавить дополнительную возможность выбрать отображать сделки "с тултипами" и "без". Пользователь сам выберет, на сколько подробное отображение ему важно.

**Comment by varo1n** [comment]
А зачем вам разные цвета этих стрелок? Ведь направление стрелки показывает направление сделки.. Можно сделать одним цветом, контрастным к цветам темы и свечей, а т.к. у многих свои настройки оформления удобнее всего для конечного пользователя будет выбор типа стрелок и цвета.
