### ISSUE TITLE
[BUG] Ошибка длительности действия заявки при ее изменении

### ISSUE THREAD

**Issue by varo1n** [alor-broker/Astras-Trading-UI#1662]
### Опишите баг

При выставлении стоп-лимитной заявки и попытке ее изменить путем перетаскивания в виджете "Тех. анализ" в окне изменения заявки автоматом выставляется странное значение поля "Действ. до". При подтверждении выпадает уведомление с ошибкой и заявка пропадает.

### Воспроизведение

1. Создать заявку стоп-лимит
2. В виджете "Тех. анализ" изменить заявку путем перетаскивания

### Среда.

- MacOS Sonoma
- Safari

### Ожидаемое поведение

Значение поля "Действ. до" должно оставаться таким же, как было при создании заявки.

### Скриншоты

![Снимок экрана 2024-05-06 в 13 14 09](https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/b2a5edf7-a216-400f-a033-3bf554eb54e2)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Это не баг. Если вы оставляете пустое поле, то заявка считается бессрочной. Мы для бессрочных заявок проставляем 10000 год. Да, несколько пессимистично, но надеюсь для целей наших клиентов это достаточно ^_^

**Comment by PilgrimViis** [comment]
В документации написал про это поведение

**Comment by sbelashevskiy** [comment]
Проверьте, пожалуйста, что Вы при создании и редактировании заявки не очищаете поле "Действ. до".
Только в этом случае я наблюдаю данную проблему. Если это поле пустое, то это означает, что заявка бессрочная.

https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/cbd14d40-c686-4e41-a1c6-04ac6eaa8da2

Если у Вас проблема проявляется как-то иначе, то приложите, пожалуйста, видео с конкретным воспроизведением. Потому что по описанным шагам проблема не наблюдается

**Comment by varo1n** [comment]
Наверно я не правильно сделал акцент. Проблема не в том, какая дата действия стоит, уверен 8000 лет за глаза хватит для любых целей )) Проблема в том, что при изменении перетаскиванием заявка отменяется с ошибкой. Видео прилагаю.

https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/af9a4b23-77f2-422f-b9ec-eb4791197be8
