### ISSUE TITLE
[BUG] Не показываются сделки по инструментам режима MTQR в виджете Все сделки

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#1667]
### Опишите баг

В виджете Все сделки не отображаются сделки по инструментам торгующимся в режиме MTQR

### Воспроизведение

Открыть виджет Все сделки, в поиске выбрать инструмент moex:ntzl:mtqr

### Среда.

Win11, EDGE

### Ожидаемое поведение

Отображать сделки по инструментам в режиме MTQR

### Скриншоты

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/94173b6d-8490-4c49-b0d7-45a97bb65417)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Режим торгов тут ни при чем. По инструменту ntzl в принципе сделки не приходят. Нет их и в QUIK

https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/64a7c3e8-c44a-4600-b64b-acf9de0b2687

**Comment by MorozovDen** [comment]
а в Астрас тогда график (тех анализ) из чего строится? откуда данные берутся?
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/afd6ed0f-b35a-4246-b3c1-bf119653bc00)

**Comment by sbelashevskiy** [comment]
У данных свече другой источник. 
У данного инструмента вообще целый ряд аномалий:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/9141c6b4-08c5-485e-aac9-6d999871053c)

**Comment by sbelashevskiy** [comment]
В общем данная проблема будет решена в https://github.com/alor-broker/Astras-Trading-UI/issues/1673.

У нас в принципе сделки запрашивались только для стандартного режима.
Для этого инструмента стандартный режим установлен RPMO. Но на нем вообще нет никакой активности, потому и сделок нет.

Добавлено исправление - запрос сделок для конкретного режима. Это помогает. И в quik сегодня сделки для этого режима  тоже появились - может просто торговать стали активнее.
