### ISSUE TITLE
[BUG] Ошибка шага цены при Изменении заявки по бумагам режима MTQR

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#1671]
### Опишите баг

При Изменении заявки по тикеру moex:ntzl:mtqr в поле Цена при прокрутке колесика мышки меняется не по шагу цены (шаг цены 0,01, а меняется по 0,0001). Выявленно только при Изменении заявки, если новую ставить, то шаг цены меняется нормально. Эмитент в режием MTQR. Пробовал другие эмитенты этого режима - такая же ситуация.

### Воспроизведение

Выставить заявку по moex:ntzl:mtqr , попытаться Изменить заявку, колесиком мышки изменить цену в заявке 

### Среда.

Win11, Edge

### Ожидаемое поведение

"Изменить заявку" и при нажатии "вверх-вниз" на клавиатуре или при прокручивании колесиком мыши в поле "Цена" цену менять по шагу цену по указанному инструменту

### Скриншоты

![Без имени](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/b623610c-d3f3-4c83-b81e-8ade4e9da919)
![Без имени-1](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/61b3c159-44b8-4d0b-86b8-ca79a2100007)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Однако для стоп заявок проблема еще существует - API игнорирует режим, с котором создавалась заявка.

создаем заявку с параметрами:
{"instrument":{"symbol":"NTZL","instrumentGroup":"MTQR","exchange":"MOEX","isin":"RU0002614686"},"quantity":1,"triggerPrice":68.33,"condition":"More","stopEndUnixTime":1718279979,"side":"buy","price":68.33,"user":{"portfolio":"D61971"}}

а при считывании возвращается:
{
    "id": "11203056",
    "exchangeOrderId": null,
    "symbol": "NTZL",
    "brokerSymbol": "MOEX:NTZL",
    "portfolio": "D61971",
    "exchange": "MOEX",
    "board": "RPMO",
    "type": "stoplimit",
    "side": "buy",
    "condition": "more",
    "status": "working",
    "transTime": "2024-05-13T11:59:49.1890129Z",
    "updateTime": null,
    "endTime": "2024-06-13T11:59:39.0000000Z",
    "error": null,
    "qtyUnits": 1,
    "qtyBatch": 1,
    "qty": 1,
    "filled": 0,
    "filledQtyUnits": 0,
    "filledQtyBatch": 0,
    "price": 68.33,
    "avg_price": 0,
    "stopPrice": 68.33,
    "existing": true,
    "timeInForce": "oneday",
    "iceberg": null,
    "volume": 68.33
}

Это нужно править в API

**Comment by sbelashevskiy** [comment]
Исправлено в API
