### ISSUE TITLE
[FEATURE] Горячие клавиши на снятие стоп-заявок

### ISSUE THREAD

**Issue by varo1n** [alor-broker/Astras-Trading-UI#1675]
### Опишите проблему, которую решает ваша фича

В настоящий момент для управления позициями и заявками в разделе "Общее для всех открытых стаканов" доступно две горячие клавиши:
- Снять лимитные заявки
- Закрыть позиции по рынку

Проблема в том, что снимаются только лимитные заявки, стопы остаются.

### Опишите предлагаемое вами решение

Думаю не будет лишним добавить пункты:
- Снять все заявки (лимитные, стоп-лимитные, стоп-маркет)
- Снять все заявки и закрыть все открытые позиции по рынку

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
> По поводу снятия всех стоп заявок, думаю будет не лишним. Т.е. сделать кнопку которая снимет все стоп заявки со всех стаканов. А снять все заявки и закрыть все позиции можно будет сделать нажатием 3х кнопок (снять все лимитные заявки, снять все стоп заявки и закрыть все позиции по рынку) , думаю это не сложно будет нажать.

Кнопка которая снимает заявки со всех стакано уже есть
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/6f09800a-1b6f-4706-b7a6-b2cf11e90c34)


По поводу хоткея который снимает стоп заявки по аналогии с лимитками, думаю можно сделать.

**Comment by varo1n** [comment]
> Кнопка которая снимает заявки со всех стаканов уже есть
> По поводу хоткея который снимает стоп заявки по аналогии с лимитками, думаю можно сделать.

Именно одна горячая клавиша на снятие всех заявок: лимит, стоп-лимит, стоп-маркет.

> Закрытие всего по рынку, пока брать не будем. Это надо реализовывать на бекенде отдельно по хорошему.

Так такая функция уже есть.. Хотелось бы к ней подвязать еще и закрытие всех заявок. Некая экстренная кнопка, которая закрывает и отменяет вообще все.
![Снимок экрана 2024-05-24 в 11 13 43](https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/5a72f879-e809-42d0-b6d8-9ec0bbfeaa14)
