### ISSUE TITLE
[FEATURE] Виджет Выбор инструмента как Список инструментов в TradingView

### ISSUE THREAD

**Issue by varo1n** [alor-broker/Astras-Trading-UI#1685]
### Опишите проблему, которую решает ваша фича

Приветствую. Виджет Выбор инструмента не позволяет гибко настроить и упорядочить добавленные инструменты. Сортировка только по колонкам тикер, цена и т.д. Например, вы не сможете сделать список акций входящих в индекс IMOEX и отсортировать их по весу в индексе.

### Опишите предлагаемое вами решение

Сделать как в TradingView:
- Свободное расположение инструментов, перетаскиванием внутри списка.
- Возможность добавлять разделы.

### Дополнительная информация

![Снимок экрана 2024-05-23 в 22 20 54](https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/6e4e3682-fb99-4c66-a40b-c897c64a15ef)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@agushasok какие твои мыслин на этот счёт по поводу реализации?

**Comment by sbelashevskiy** [comment]
1. А что мешает в качестве разделов использовать разные списки? В TradingView, например, разные списки еще и разные разделы выглядят избыточными. Гораздо логичнее создать несколько маленьких  списков интересующих бумаг и переключаться между ними. Вот и будет деление по разделам. Каждый список можно открыть в отдельном виджете и тогда они будут перед глазами. Это гораздо удобнее, чем один большой список с разделами, которые еще и сворачиваются
2. Есть также возможность пометить инструмент избранным и сортировать по этому флагу. Судя по скрину либо это отключено, либо настройки очень старые - это фича уже давно включается по умолчанию

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/961cca65-b29d-46b1-80ef-b9fa53bd881d)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/a39aa63d-3d60-455a-8be5-8e01abc59cc5)
