### ISSUE TITLE
[FEATURE] Возможность отключать подсказки

### ISSUE THREAD

**Issue by varo1n** [alor-broker/Astras-Trading-UI#1695]
### Опишите проблему, которую решает ваша фича

Всплывающие подсказки часто мешают.
![Снимок экрана 2024-05-29 в 13 37 16](https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/655013ad-ea89-49f6-84ec-54dfa171c0f9)
![Снимок экрана 2024-05-29 в 14 13 29](https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/70e5f867-2f0c-457a-b1be-2438cc11908c)

### Опишите предлагаемое вами решение

Добавьте в настройки возможность отключать всплывающие подсказки.

### Правила

- [X] Я согласен следовать правилам

**Comment by varo1n** [comment]
Вот отличный пример. Подсказка закрыла самую важную область стакана.
![Снимок экрана 2024-05-29 в 17 41 15](https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/2776a499-6a67-4412-895c-4c01c64bfa2d)

**Comment by PilgrimViis** [comment]
Думаю сделать надо, но только в скальперском стакане в виде настройки. Там я вижу необходимость держать на некоторых элементах типо SL мышку.В остальных случаях решение простое - не держите мышку в этом месте долго и закрывать не будет.
