### ISSUE TITLE
[FEATURE] Сохранение настроек рабочего пространства в файл

### ISSUE THREAD

**Issue by varo1n** [alor-broker/Astras-Trading-UI#1696]
### Опишите проблему, которую решает ваша фича

Сегодня столкнулся с не приятной ситуацией, которая отняла достаточно времени. Решил обновить терминал, очистил кэш, перезагрузил страницу и мне открылось полностью дефолтное окно. Терминал обновился, появилось уведомление с новыми фичами и исправлениями. Но сбросилось вообще все, настройки терминала, сохраненные дашборды, настройки всех виджетов и тд. Настройка с нуля заняла достаточно много времени, хорошо не додумался обновить во время открытой позиции.

### Опишите предлагаемое вами решение

Добавить возможность экспортировать все настройки в файл.

### Дополнительная информация

Подобное случилось первый раз. До этого обновлял терминал, но после обновления настройки сохранялись.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Терминал обновляется самостоятельно, для этого не нужно сбрасывать кэш. 

Но я вижу другой юзкейс. Сброс кэша это то что тех поддержка всегда советует в первую очередь, поэтому если сделаем экспорт пространства, то сохраним время пользователям в этом случае.

Думаю можем сделать

**Comment by sbelashevskiy** [comment]
Сброс настроек нужен только в случае, если с ними что-то не так. 
Если мы сделаем сохранение настроек в файл, то проблемы, которые ыиксятся сбросом, станун нерешаемые

**Comment by PilgrimViis** [comment]
@varo1n это неправда. Удалять кэш нужно только при неполадках. Если у вас есть какие-то проблемы с обновлениями без очистки кэша, то проверьте свой антивирус. Например, в Касперском вот такая настройка  насильно пихает определенную строчку в веб-сайт, и из-за этого браузер не понимает что обновление не удалось. Он сверяет хэш-сумму архива с кодом сайта, видит что она изменилась (из-за строчки которую добавляет Касперский) и считает что обновление прошло. В реальности же ничего не обновилось. 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/db51ff2b-7247-429f-ae3e-da351bf8e2f7)

**Comment by sbelashevskiy** [comment]
@varo1n это десктоп или планшет?

**Comment by varo1n** [comment]
У меня мак, антивирусов нет, браузер safari. В windows браузерах Ctrl+F5 это обновление с очисткой кэша, в safari нет такого хоткея, есть только Command+R просто обновить страницу, кэш можно сбросить только через меню как на моем скриншоте выше, наверно по этой причине мне и советовали перед перезагрузкой страницы терминала очищать кэш. Повторюсь, что это случилось первый раз, до этого сбрасывал кэш, обновлял терминал и все настройки сохранялись.

**Comment by varo1n** [comment]
> @varo1n это десктоп или планшет?

десктоп

**Comment by sbelashevskiy** [comment]
@varo1n ,
можете указать логин, который используете для входа?
Это конфиденциальности не нарушает, а мы хотя бы сможет логи посмотреть.
Очень странное поведение на Вашей конфигурации: все признаки, что либо сброшены настройки, либо терминал запущен с дестопа.

**Comment by sbelashevskiy** [comment]
@varo1n,
Вы и раньше под этой учеткой сидели?
Может раньше по номеру телефона логиниль или как-то еще?
Просто, очень странно - за последние 90 дней логи есть только за вчера

**Comment by varo1n** [comment]
@sbelashevskiy до этого логинился через P086989 и через телефон, точно не вчера перешел на 88315.

**Comment by sbelashevskiy** [comment]
Это очень странно. Согласно нашим логам за последниий год по учетке P088315 первая активность появилась 29 мая в 17.04 по MSK. 
До этого никакой активности через ASTRAS не наблюдается
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/e9fa1d04-a34e-4029-a81d-74cfa996d4d7)
Т.е терминал вообще впервые встретил пользователя с такой учеткой и создал для него все настройки по умолчанию.

Для сравнения активность по учетке P086989:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/b8d88131-e294-43c0-9f9d-4e01bfafe141)
Явность есть активности типа "Разрыв соединения".

Так что больше походит, что никакого ошибочного поведения со стороны терминала нет, а причина в путанице с настройками

**Comment by varo1n** [comment]
@sbelashevskiy могли данные для входа быть в этом кэше? Если да, то это единственное логичное объяснение. Данные лежали в кэше, я заходил как 88315, а кэш подтягивался из 86989, потом когда сбросил кэш, то 88315 воспринялся как новый пользователь с дефолтными настройками. Скорее всего я коряво выразился, но думаю суть поймете ))

**Comment by varo1n** [comment]
@sbelashevskiy Вот например отчет за 22 мая по 88315. Кроме как в Астрасе у меня возможности торговать нет из-за операционки, с мобильного или планшета в Астрас не захожу.
<img width="1484" alt="Снимок экрана 2024-05-30 в 14 07 52" src="https://github.com/alor-broker/Astras-Trading-UI/assets/165905131/e1971713-b5fc-497e-93df-25886d8f8394">
