### ISSUE TITLE
[FEATURE] Возможность выбора шрифта

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#1713]
### Опишите проблему, которую решает ваша фича

Шрифты в web это боль и грусть.
В 2024 все еще возникают проблемы с корректной отрисовкой шрифтов в браузере.
Локальные шрифты пользователя в разных браузерах могут выглядить по-разному. 
Например, если у шрифта отутствует определенный вес (жирность), то браузер выполнит отрисовку на свое усмотрение. Это порождает такие  проблемы https://github.com/alor-broker/Astras-Trading-UI/issues/1703

У некоторых пользователей текущие шрифты вызывают дискомфорт и они не хотят из-за этого использовать терминал

### Опишите предлагаемое вами решение

Подобрать "безпроблемные" шрифты и дать возможноть их выбора пользователю

### Дополнительная информация

Шрифты **обязательно** должны иметь 2 начертания (вес, жирность): 400 и 500

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Новый дефолтный шрифт https://fonts.google.com/noto/specimen/Noto+Sans

Доп. шрифты на выбор.
https://fonts.google.com/?query=Roboto
https://fonts.google.com/specimen/Open+Sans?query=Open+Sans
https://fonts.google.com/specimen/Source+Sans+3

С засечками. 
https://fonts.google.com/noto/specimen/Noto+Serif?query=Noto+Serif

Для тех у кого на 1 хромосому больше. 
https://fonts.google.com/specimen/Caveat?query=Caveat&noto.query=Caveat
