### ISSUE TITLE
Дополнения в Скринер облигаций 

### ISSUE THREAD

**Issue by Suastoye** [alor-broker/Astras-Trading-UI#1716]
### Опишите проблему, которую решает ваша фича

Помогает быстро формировать портфель из выбранных облигаций и отслеживать его динамику

### Опишите предлагаемое вами решение

1. Для удобства пользования Скринером облигаций в Астрас предлагаю скопировать туда меню из виджета "Выбор инструмента". То есть нажимаешь на выбранную облигацию с Скринере и сразу можешь выбрать дальнейшее действие (подробнее см скрин)
2. Для быстрого формирования портфеля из выбранных облигаций в Скринере сделать доп. вкладку (рядом с Скринер, Графики, третьей в ряд), например: "Избранное" или Моя корзина", чтобы понравившиеся облиги можно было сразу же туда добавить. А в  меню (из п 1.) добавить пункт "Добавить в "Избранное" или "Моя корзина".
3. Далее клиент сразу бы попадал в выбранный им портфель и мог бы по очереди, нажимая на каждую бумагу, купить ее или одной кнопкой "Купить все" с возможностью указания суммы или пропорции от свободных денежных средств по каждой бумаге
4. Затем после покупки, было бы удобно смотреть динамику этого портфеля, как в целом, так и по вкладу в общую доходность каждой бумаги по отдельности. Можно сделать отдельную вкладку "Мой портфель".
![Скринер облигаций_меню](https://github.com/alor-broker/Astras-Trading-UI/assets/154803042/637740c7-734a-4df7-b792-fba74dd84852)
".

### Правила

- [X] Я согласен следовать правилам

**Comment by MorozovDen** [comment]
поддерживаю

**Comment by PilgrimViis** [comment]
4 пункт сделать не сможем, это весьма глобально. Остальные сделали

**Comment by Suastoye** [comment]
Константин, я по первым трем пунктам тоже не вижу никаких изменений в астрас.

По п.1 меню осталось тем же
![По п 1](https://github.com/user-attachments/assets/52232a52-7e48-43b1-a023-ab13d504d577)

**Comment by Suastoye** [comment]
По п.2 кол-во вкладок тоже не изменилось
![По п 2](https://github.com/user-attachments/assets/32834545-ff95-4a0e-bed3-0aade060b892)

**Comment by Suastoye** [comment]
ну п. 3 соответственно без п .2 тоже не сууществует
