### ISSUE TITLE
[FEATURE] Добавить таймфрейм 2М в виджет Тех анализ и график

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#1718]
### Опишите проблему, которую решает ваша фича

Поступило несколько запросов на 2 минутный таймфрейм в графиках. У tradingview этот таймфрейм в платной подписке. Введение повысит преимущество ASTRAS

### Опишите предлагаемое вами решение

Перенос функционала из tradingview

### Дополнительная информация

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/105856884/e64dcc79-47c4-4542-b326-5464d13b75f7)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Можно и 2 минуты, и 2.5 минуты и 76 секунд. Но зачем? Не вижу смысла плодить таймфреймы. Всем всё равно не угодим.
