### ISSUE TITLE
Выгрузка данных из виджета "Выбор инструмента", "Все инструменты" в Excel

### ISSUE THREAD

**Issue by NothernBaron** [alor-broker/Astras-Trading-UI#1723]
### Опишите проблему, которую решает ваша фича

Клиент работает на QUIK и готов перейти на Astras в случае наличие следующего функционала. В виджетах "Выбор инструмента", "Все инструменты" появиться возможность скопироватьд данные по бумагам в буфер обмена весь объем или сделать выгрузку в Excel для дальнейшей работы. 
То есть создать список инструментов, настроить сортировку можно, а вот выгрузка пока недоступна.

### Опишите предлагаемое вами решение

Клиент работает на QUIK и готов перейти на Astras в случае наличие следующего функционала. В виджетах "Выбор инструмента", "Все инструменты" появиться возможность скопироватьд данные по бумагам в буфер обмена весь объем или сделать выгрузку в Excel для дальнейшей работы. 
То есть создать список инструментов, настроить сортировку можно, а вот выгрузка пока недоступна.

### Опишите альтернативные решения, о которых вы думали

Клиент работает на QUIK и готов перейти на Astras в случае наличие следующего функционала. В виджетах "Выбор инструмента", "Все инструменты" появиться возможность скопироватьд данные по бумагам в буфер обмена весь объем или сделать выгрузку в Excel для дальнейшей работы. 
То есть создать список инструментов, настроить сортировку можно, а вот выгрузка пока недоступна.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@NothernBaron Напишите задачу нормально пожалуйста. 3 раза скопировать одно и то же это неуважение к нам.
