### ISSUE TITLE
[FEATURE] Выгрузка данных из виджета "Выбор инструмента", "Все инструменты" в exel

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1733]
### Опишите проблему, которую решает ваша фича

Позволит трейдеру, по необходимости, анализировать данные в сторонней программе. 

### Опишите предлагаемое вами решение

Прошу добавить возможность выгружать данные в эксель из таблиц: 
1. Выбор инструмента
2. Все инструменты

### Опишите альтернативные решения, о которых вы думали

.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
После обсуждения решили что лучше начать с виджета выбора инструментов. Кнопку выгрузки добавим сюда.

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/f1f80b41-a775-4bdc-af9e-a24ff1a92b4a)

-
