### ISSUE TITLE
[FEATURE] Улучшение контрасности

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#174]
### Опишите проблему, которую решает ваша фича

Очертания окон и графика не достаточно контрастные

### Опишите предлагаемое вами решение

Сделать очертания окон и фон более контрастными, чтобы удобно было визуально  выделять и раздвигать окна

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Вынесите пожалуйста "сделать возможность выбора темы (черная и белая)" в отдельный issue.

**Comment by LuzhbinV** [comment]
ок

**Comment by PilgrimViis** [comment]
Считаю, что после редизайна эта задача решилась. У нас и темная тема стала более контрастной и появилась светлая тема. @Tattydes что думаете?

**Comment by Tattydes** [comment]
Да, я прорабатывала новое цветовое решение, учитывая эту потребность
