### ISSUE TITLE
[BUG] Исправить Тип фьючерса

### ISSUE THREAD

**Issue by zlobinm** [alor-broker/Astras-Trading-UI#1744]
### Опишите баг

У некоторых фьючерсов некорректный тип : показывает Расчетный, а по факту должен быть Поставочный

### Воспроизведение

- создать виджет Инфо
- выбрать инструмент SBRF-9.24, ALRS-9.24
- сравнить со спецификацией инструмента на сайте мосбиржи (ссылки ниже)

### Среда.

- Фронтенд

### Ожидаемое поведение

Тип фьючерса определяется по CFI коду

Для фьючей SBRF-9.24, ALRS-9.24, CFI код: FFXPSX. Так отдает апи и это соответствует спецификации инструмента на сайте биржи.
По расшифровке стандарта, для типа Поставочный, четвертая буква означает **P - Physical**. Если фьючерс Расчетный, то четвертая буква будет C.
Трактовка происходит на фронте

### Дополнительная информация

Полезные ссылки:
https://www.isin.ru/ru/iso/iso3/
https://en.wikipedia.org/wiki/ISO_10962
https://www.moex.com/ru/contract.aspx?code=ALU4&utm_source=www.moex.com&utm_term=ALRS-9.24
https://www.moex.com/ru/contract.aspx?code=SRU4&utm_source=www.moex.com&utm_term=SBRF-9.24

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/6408195/18ba9e77-e75b-4fa5-bc91-1ff277da7e68)

**Comment by PilgrimViis** [comment]
P physical поставочный
C cash расчётный

Остальных на ММВБ нет, но можешь перевести на всякий случай тоже
