### ISSUE TITLE
[FEATURE] Совершение сделок в стакане

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#175]
### Опишите проблему, которую решает ваша фича

Хотелось бы чтобы стакан был как в алор-фасте, чтоб можно было с него сразу по bid/ask покупать/продавать

### Опишите предлагаемое вами решение

добавление возможности автоматизированной торговли из стакана, выставление заявок и совершение сделок по щелчку мыши или отдельными кнопками

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Эта возможность, выставлять заявки по клику на стакан уже есть. Нужны подробности.

**Comment by PilgrimViis** [comment]
Подробностей не получено, закрываю. Непонятно.
