### ISSUE TITLE
[FEATURE] Добавить светлую тему

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#176]
### Опишите проблему, которую решает ваша фича

Не всеми черный фон визуально хорошо воспринимается, кто-то привык к восприятию черного на белом фоне (четче графика и веселее картинка) 

### Опишите предлагаемое вами решение

Сделать возможность выбора темы (черная/белая и другие варианты (ручная настройка))

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Уже достаточно много людей это просили. Так как задаче не очень сложная, не будем пока ждать дизайнера и сделаем сами.
1. Сделать смену темы средствами ant-design. Это в принципе не очень сложно. Все выглядит неплохо просто если поменять дефолтную тему. Возможно ещё buy sell цвета сделать чуть поярче. Взять например как в нашем TV где светлая тема. 
2. Сделать настройку в общих, которая позволит выбрать тему.
