### ISSUE TITLE
[BUG] Пропущены данные на графике индекса

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1767]
### Опишите баг

Сегодня с утра заметил, что нет данных на графике по индексу IMOEX за 18 июля 

### Воспроизведение

Создать виджет тех анализ
включить инструмент IMOEX
Включить дневной тайм фрейм

### Среда.

Windows 10 
Chrome

### Ожидаемое поведение

График должен быть полным

### Скриншоты

![image](https://github.com/user-attachments/assets/6509198c-4173-427b-961d-052f5cd7d8b3)
![image](https://github.com/user-attachments/assets/984d18fd-c983-4610-a7dd-9993149b1700)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
По состоянию на 12.08.2024 данные присутствуют
![image](https://github.com/user-attachments/assets/32b9b3c0-5edd-4aa1-a710-601c379e0c7a)
