### ISSUE TITLE
[BUG] График в виджете тех анализ по Мечел

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1768]
### Опишите баг

На графике непонятное значение на акции Мечела в виджете тех анализ 

### Воспроизведение

Виджет Тех анализ
Акция Мечел
Дневной тайм фрейм 

### Среда.

Виндовс 10
Хром

### Ожидаемое поведение

Такого не может быть 

### Скриншоты

![image](https://github.com/user-attachments/assets/e0bdbd25-b158-4bb6-96e1-4ce8bde8ec6b)

### Правила

- [X] Я согласен следовать правилам

**Comment by uncrashable** [comment]
На часовике так же наблюдаются какие то данные по цене около 0

![image](https://github.com/user-attachments/assets/1dcdc8d9-a232-4be3-8319-bb9f9828730c)

**Comment by sbelashevskiy** [comment]
По состоянию на 12.08.2024 не наблюдаю никакого странного значения
![image](https://github.com/user-attachments/assets/1ac012d8-132f-447c-aea2-5ca18f2bfa57)

Битые данные могли придти только из API

**Comment by PilgrimViis** [comment]
Все эти баги это не баги Астраса @uncrashable Надо писать в тех. поддержку или бекендерам про них, это ошибки с выгрузкой истории.
