### ISSUE TITLE
[FEATURE] Отображение собственных сделок в сс

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1770]
### Опишите проблему, которую решает ваша фича

Будет полезно видеть "следы" в стакане по сделкам. 

### Опишите предлагаемое вами решение

Прошу добавить отображение личных сделок в СС. 
Отображать до закрытия сделки. 
Можно сделать опционально - отображать или скрыть
Пример на скрине ниже

### Дополнительная информация

![image](https://github.com/user-attachments/assets/519a9a98-df25-4227-abf1-fdeffc0eed1d)

Для примера: 
![image](https://github.com/user-attachments/assets/0df579f2-5281-47c0-a743-6ebff2ea628c)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@uncrashable 
совершенно непонятно как это работает в CScalp:
открываешь позицию - нет никакого маркера
проводишь еще 1-2-3 сделки - появляется маркер. Ближе к вечеру вообще никакие сделки не показываются. Такое ощущение что эти маркеры вообще рандомно отображаются
Цветовая индикация совершенно непонятная.

Как в итоге эта фича должна работать?

Просто при ненулевой позиции показываем все сделки по инструменту за торговую сессию?
Или показываем N последних сделок?
Или показываем сделки за последние N минут?

Какие цвета у собственных сделок должны быть? Цвета покупки/продажи?
Что если на одну цены была и сделка на покупку и сделка на продажу?

Собственные сделки показываются позади основных? или поверх или отображаются вместе?
Если послений вариант, что свои сделки будут занимать место и сдвигать остальные сделки, чоответственно для них будет меньше места

**Comment by uncrashable** [comment]
Да, в сискальпе реально непонятно xD 

> Как в итоге эта фича должна работать?

Фича отображает собственные сделки. По какой цене какой объем прошел. Если по одной цене прошло несколько сделок, то просуммировать. (примерно как работает панель кластеров, только тут учитываем одно направление , либо покупки либо продажи(сделка в шорт).  
Фича отображает только одно направление в сделках, если первая покупка, то показывать только покупки. 
Если сделка полностью закрывается, то очистить все. 
Цвета покупки и продажи нет смысл разделять, это понятно по направлению общей сделки. 
Цвет можно любой выбрать с учетом темы Астрас. На белом , к примеру , черный квадратик и черная цифра, на черной теме - белый квадратик и белая цифра. Примеры на скрине ниже

**Comment by uncrashable** [comment]
Примеры.
Выставил я в стакан заявки
![image](https://github.com/user-attachments/assets/0a6df90d-d188-4e83-a6dc-b78037d401f5)


После того как они исполнятся, они превратятся в сделки и отобразятся в стакане вот таким образом

![image](https://github.com/user-attachments/assets/49a35a94-1577-4042-8598-bee6bea207ff)
Можно сделать вообще без рамки.
