### ISSUE TITLE
[FEATURE] Функция создания и сохранения шаблонов для объектов рисования.

### ISSUE THREAD

**Issue by mkv-smr** [alor-broker/Astras-Trading-UI#1772]
### Please describe, is your feature request related to a problem?

В данный момент в терминале Астрас, отсутствует функция создания и сохранения шаблонов для объектов рисования. То есть для каждого нового добавленного объекта рисования, нужно каждый раз заново вручную настраивать параметры(цвет, степень прозрачности, толщина и тип линии и т.д.). 
![photo_2024-07-27_15-18-42](https://github.com/user-attachments/assets/85442db4-66b1-4491-aa3a-0e79a9bd43ec)

### Describe the solution you would like

Просьба добавить функцию создания и сохранения шаблонов для объектов рисования, как это реализовано в трейдингвью.
![photo_2024-07-27_15-16-20](https://github.com/user-attachments/assets/ba875bf5-5e20-44e0-9132-02eb3116173a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contribution guideline

**Comment by PilgrimViis** [comment]
Посмотрим, если найдем то сделаем

**Comment by sbelashevskiy** [comment]
Данная функция не доступна в версии тоьлко график:
https://www.tradingview.com/charting-library-docs/v27/saving_loading/#drawing-templates
![image](https://github.com/user-attachments/assets/a6b1d250-b7f5-4d55-ae79-a4086694901e)

**Comment by PilgrimViis** [comment]
К сожалению нереализуемо в данный момент =(
