### ISSUE TITLE
[BUG] Ошибка запроса истории

### ISSUE THREAD

**Issue by zlobinm** [alor-broker/Astras-Trading-UI#1773]
### Опишите баг

В терминале появляется ошибка 
Http failure response for https://api.alor.ru/md/v2/history/cluster?symbol=MTLR&exchange=MOEX&instrumentGroup=TQBR&from=NaN&to=1723099913&tf=300&format=simple: 400 Bad Request

### Воспроизведение

- Не воспроизводится

### Среда.

- Все браузеры

### Ожидаемое поведение

- 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Непонятно ни как этого добились, ни как это заметили, ни как это сказалось на работе виджета. Судя по всему никто даже не понял на что это влияет.
Совершенно пустое описание проблемы, никаким образом не позволяющее идентифицировать причину.

Судя по всему это могло произойти только на битых настройках скальперского стакана.
Каким образом это получили - описание не содержит.

Максимум, что можно сделать  - добавить дефолтные значения для запроса.

Создавая баги, пожалуйста, заполняйте хоть какую-нибудь информацию о проблеме, а не только, что ОДИН раз где-то как-то не прошел какой-то запрос. Тем более если баг не воспроизводится, то как он может повториться во всех браузерах. Без контеста такие "баги" вообще нет смысла пытаться исправить

**Comment by zlobinm** [comment]
@sbelashevskiy Сергей
Есть темные места, которые знают только программисты. history/cluster например. что то новое.
Мы в ЛС не общаемся с разработчиками, чтобы не дергать по 10 вопросам. оперативно не можем уточнить информацию.
В подобных ситуациях, чтобы не дергать разработчиков, заводим баг. 
С нас также спрашивают по каждому вопросу и обращению.
При таких признаках, типа подобных ошибок, оно все равно указывает на баг.

Воспроизвести и вправду не удалось. И нет вообще информации. 

Вам это для информации тогда. если что вспомните, и повторится, хотя бы будете в курсе, что такой момент есть.
Если бы могло повториться, я б докинул сюда кейсов. 
Если нецелесообразно по задаче работы вести, закрою тогда или Вы закройте.

**Comment by sbelashevskiy** [comment]
@zlobinm 
Да, темные места есть и что-то может быть понятно только разработчикам. history/cluster это не новое. Этот запрос относится к скальперскому стакану и **этому функционалу уже больше года.** Потому и странно, что
Но чтобы разобраться в проблеме разработчикам нужен ее контекст.
Контекст это необязательно шаги для воспроизведения.

Для примера контекст может включать в себя:
1. Проблема появилась у одного пользователя или сразу нескольких.
2. Периодичность повторения проблемы. Повторяется она регулярно, в какое-то определенное время, или возникла 1 раз и больше не возникает. 
Если это единичный случай и проблема больше не повторяется, то приоритет у этого один. Причиной этому мог быть сбой в сети, какой-то единичный баг в API и что-то одномоментное. 
Если же эта проблема постоянно появляется у пользователя, что это уже более высокий приоритет, ведь пользователь потому и обратился в поддержку, что его это беспокоит.
3. У какого пользователя возникла проблема. Astras содержит кучу персональных настроек  пользователя. И то, что проблема не повторяется на рабочей машине support не означает, что ее нет на машине пользователя. В конкретно этом случае проблема, скорее всего, как раз в настройках пользователя.
