### ISSUE TITLE
[FEATURE] ... Настройка цветовой гаммы

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#178]
### Опишите проблему, которую решает ваша фича

Настройка основного фона и цвета графиков в ручную с привязкой выбора палитры цветов.

### Опишите предлагаемое вами решение

Добавить панель настройки палитры цветов: 
Фона , графиков (свечей), шрифта. 

Или хотя бы сделать "темы"  

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/176 Закрою как дубликат.
