### ISSUE TITLE
[FEATURE] Добавить в терминал шаг цены интсрумента

### ISSUE THREAD

**Issue by gilimyura** [alor-broker/Astras-Trading-UI#1781]
### Опишите проблему, которую решает ваша фича

Для автоматической торговли необходимо узнать шаг цены

### Опишите предлагаемое вами решение

Добавить в терминал

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@agushasok добавь пожалуйста в виджет инфо. Приходит вместе с информацией об инструменте
