### ISSUE TITLE
[FEATURE] Доработать подсветку объемов в скальперском стакане

### ISSUE THREAD

**Issue by offvine** [alor-broker/Astras-Trading-UI#1782]
### Опишите проблему, которую решает ваша фича

Настраиваемую подсветку объемов в стакане вроде сделали, но, похоже, не до конца.

**Параметр "Заполнение полосы объема" вообще ни на что не влияет.** А этого очень не хватает - чтобы полосы объемов заполнялись/подсвечивались относительно этого значения, как это работает при выборе "Относительно наибольшего объема".

1 и 2 скрины - видно что ничего не заполняется даже при значении 200 в варианте "По границам"

3 скрин - как все хорошо заполняется в варианте "Относительно наибольшего объема"

<img width="405" alt="алор 1" src="https://github.com/user-attachments/assets/ea7e73e9-64aa-4dea-95c7-1be6301dc3c7">

<img width="146" alt="алор 2" src="https://github.com/user-attachments/assets/ff106955-856b-44cb-9adc-a095ae512ae2">

<img width="180" alt="алор 3" src="https://github.com/user-attachments/assets/ce706803-2380-4f03-8299-1640a718794c">

### Опишите предлагаемое вами решение

Предлагаю доделать так, чтобы полосы объемов заполнялись аналогично варианту "Относительно наибольшего объема", только относительно значения из параметра "Заполнение полосы объема".

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@offvine 
Подсветка работает как ожидается. 
В описании сказано:
![image](https://github.com/user-attachments/assets/c135e9de-edbf-4b39-92dc-b6665cbf8dcf)

Это значит, что по Вашим настройкам будут подсвечены ТОЛЬКО строки с объемами 2000 и 4000. Таковых в Вашем примере только одна - с объемом 10.85К

Про опцию "Заполненность полосы объема" сказано:
![image](https://github.com/user-attachments/assets/fecfd163-6529-497d-8dfa-408870328e1f)

10.85К значительно больше 200, поэтому ячейка заполнена полностью.
Вам нужно корректно настроить отображение в соответствии с выбранным инструментом, например:
![image](https://github.com/user-attachments/assets/a9fc8742-4bc6-4d38-b6ab-a1c8fb5ea7f9)
![image](https://github.com/user-attachments/assets/b4cb3d28-9ef3-4c6b-9470-d97497f89b4b)

**Comment by offvine** [comment]
Понятно. Вообще не удобный вариант. А с учетом того, что настройки в одном стакане не сохраняются для разных инструментов так совсем бесполезный.

**Comment by uncrashable** [comment]
> ### Опишите проблему, которую решает ваша фича
> Настраиваемую подсветку объемов в стакане вроде сделали, но, похоже, не до конца.
> 
> **Параметр "Заполнение полосы объема" вообще ни на что не влияет.** А этого очень не хватает - чтобы полосы объемов заполнялись/подсвечивались относительно этого значения, как это работает при выборе "Относительно наибольшего объема".
> 
> 1 и 2 скрины - видно что ничего не заполняется даже при значении 200 в варианте "По границам"
> 
> 3 скрин - как все хорошо заполняется в варианте "Относительно наибольшего объема"
> 
> <img alt="алор 1" width="405" src="https://private-user-images.githubusercontent.com/157825005/359644304-ea7e73e9-64aa-4dea-95c7-1be6301dc3c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDcxNjcsIm5iZiI6MTcyNDI0Njg2NywicGF0aCI6Ii8xNTc4MjUwMDUvMzU5NjQ0MzA0LWVhN2U3M2U5LTY0YWEtNGRlYS05NWM3LTFiZTYzMDFkYzNjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMzI3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWZlYWYxOTYyMWZlODQwNzJlNDJhZjQ1ZjhkNmQ3NWM4NzE0ZmU5ODgyNWQ0NDE3MmZmNTc4OGQyZGEwMmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l7QlnF2AIBKLReMDYnbF8JrVeDVSQyc_StWmfn8eMo0"> <img alt="алор 2" width="146" src="https://private-user-images.githubusercontent.com/157825005/359644352-ff106955-856b-44cb-9adc-a095ae512ae2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDcxNjcsIm5iZiI6MTcyNDI0Njg2NywicGF0aCI6Ii8xNTc4MjUwMDUvMzU5NjQ0MzUyLWZmMTA2OTU1LTg1NmItNDRjYi05YWRjLWEwOTVhZTUxMmFlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMzI3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODcyODIyODA0NTQyYzdjY2FlYjlmYmVmZDM2OTM4MzkzOWY0OTg5MjYzMGQ0OTM3ZDdkNzI5NDg1MTNlMDcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KClkM6le0w5ukQHtD3kEEF1KaCqSCC-4lYnImGwdGC0"> <img alt="алор 3" width="180" src="https://private-user-images.githubusercontent.com/157825005/359644393-ce706803-2380-4f03-8299-1640a718794c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDcxNjcsIm5iZiI6MTcyNDI0Njg2NywicGF0aCI6Ii8xNTc4MjUwMDUvMzU5NjQ0MzkzLWNlNzA2ODAzLTIzODAtNGYwMy04Mjk5LTE2NDBhNzE4Nzk0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMzI3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2ZhZTFkMDc1YzdjNDc3OGI0MDJlYTQyOTI5ZWQ3M2ZjMDRjY2NkMTIyZjNkNDE1NTI4MGYzODMwMDM3YjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.clJwG1dPXTPYjmv-SJm7hKheK1jc1UxytE2mIiioITQ">
> ### Опишите предлагаемое вами решение
> Предлагаю доделать так, чтобы полосы объемов заполнялись аналогично варианту "Относительно наибольшего объема", только относительно значения из параметра "Заполнение полосы объема".
> 
> ### Опишите альтернативные решения, о которых вы думали
> _No response_
> 
> ### Дополнительная информация
> _No response_
> 
> ### Правила
> * [x]  Я согласен следовать правилам

Если вам нужно, что бы мелкие объемы также заливались, то сделайте один из объемов равный "1". 
Тогда получится так 
![image](https://github.com/user-attachments/assets/b3b0328e-5277-48ed-857b-e1576c085c10)

**Comment by uncrashable** [comment]
![image](https://github.com/user-attachments/assets/d3a8fc1e-0236-41cd-b59c-19e46ad8b8e0)
Вот так будет отображаться в стакане. 

Хотя цель подсветки, отображать именно крупные объемы, а остальные чтобы меньше мешали. Но тут как вам удобно

**Comment by offvine** [comment]
Велосипед какой-то изобрели. Вообще не удобно.

> ![image](https://private-user-images.githubusercontent.com/105817664/359916508-d3a8fc1e-0236-41cd-b59c-19e46ad8b8e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDc0MzEsIm5iZiI6MTcyNDI0NzEzMSwicGF0aCI6Ii8xMDU4MTc2NjQvMzU5OTE2NTA4LWQzYThmYzFlLTAyMzYtNDFjZC1iNTljLTE5ZTQ2YWQ4YjhlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMzMyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDgzNmZiZTU5ZDY3ZGQ1M2Q4ZGVmYTI3NDk5ZjM4MGZjNzdkNWQ2YzRhYTRjZDA0MjgwMzBjMzNhOTJjZmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GhW6oWd3-BpXSioBftntjRJ7VcwAEMMogcTtEffI3OM) Вот так будет отображаться в стакане.
> 
> Хотя цель подсветки, отображать именно крупные объемы, а остальные чтобы меньше мешали. Но тут как вам удобно

О, это вариант! Большое спасибо! Вопрос снят
