### ISSUE TITLE
[TECHNICAL] Добавить настройку в конфиг для отключения чата 

### ISSUE THREAD

**Issue by ktochilkin** [alor-broker/Astras-Trading-UI#1789]
### Опишите проблему, которую решает ваша фича

Добавить в конфиг настройку для отключение aichat

### Опишите предлагаемое вами решение

Добавить в конфиг настройку для отключение aichat

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Добавлена настройка в environment.ts
![image](https://github.com/user-attachments/assets/bfa1c87a-c22a-4d48-a56f-b55c4fc5545b)

Для отключения чата нудно либо поставить aiChat: false, либо совсем удалить aiChat
