### ISSUE TITLE
[FEATURE] Вертикальный стакан

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#179]
### Опишите проблему, которую решает ваша фича

Большинство "стаканов" вертикальные. В один столбец. Думаю стоит и тут сделать такой же.
Добавить больше настроек в стакан.

### Опишите предлагаемое вами решение

Вертикальный стакан либо смена вариаций стакана (как например в Квике) 
Настройки стакана: разреженный стакан, отображение слева или справа объемов по одну сторону от цены
![image](https://user-images.githubusercontent.com/105817664/169138178-8b265de0-5e88-4a10-95b4-c01e415dac42.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/238 Закрою как дубликат более свежей задачи
