### ISSUE TITLE
[BUG] ... Горячие клавиши

### ISSUE THREAD

**Issue by Haliavschik** [alor-broker/Astras-Trading-UI#1794]
### Опишите баг

Добрый день.
Настроил работу горячих клавиш в Астрас. Секунд 15 работают и все. Далее горячие клавиши перестают работать.
Снова начинают работать только после обновления страницы в браузере.

### Воспроизведение

1. Настройка горячих кнопок (лимитные заявки).
2. Установка курсора мыши на стакан котировок.
3. Через секунд 15 горячие клавиши перестают работать. 
4. Могут самопроизвольно начать работать через какое то время, либо после обновления страницы бразера с Астрас.

### Среда.

Яндекс браузер - Версия 24.7.2.1098 (64-bit).

Стационарный компьютер.
Windows 11 Pro
Версия 23H2
Сборка ОС 22631.4112

### Ожидаемое поведение

Стабильная работа горячих кнопок.

### Скриншоты

![2024-09-03_12-30-57](https://github.com/user-attachments/assets/b62392c6-bcb1-43b9-a7d3-1705612ce991)
![Снимок экрана 2024-09-03 122956](https://github.com/user-attachments/assets/4a080147-1b04-44f0-8104-ea05dbc4c89c)
![photo_2024-09-03_12-21-45](https://github.com/user-attachments/assets/9099f93a-24f4-4996-9094-c79b0a6e6f6b)
![2024-09-03_11-53-04](https://github.com/user-attachments/assets/30b8b5aa-c65c-44fb-a88e-8572a8da145a)

### Правила

- [X] Я согласен следовать правилам

**Comment by agushasok** [comment]
@Haliavschik Горячие клавиши лучшую покупку/продажу могут не срабатывать, если аски ИЛИ биды пустые. Скажите, не было ли что-то из этого пустым при попытке выставления заявки?

**Comment by Haliavschik** [comment]
Здравствуйте! Нет, я выставлял заявки в нат.газе. Ликвидность там очень высокая.

**Comment by agushasok** [comment]
@Haliavschik в данный момент проблема продолжается? Если да, не могли бы вы открыть консоль (F12), выбрать вкладку "консоль" ("console"), воспроизвести баг и посмотреть, есть ли там ошибки,  и если да, то скинуть их сюда?
Пробую воспроизвести баг, но у меня всё корректно работает

**Comment by Haliavschik** [comment]
Через раз работают.
![2024-09-04_16-09-28](https://github.com/user-attachments/assets/e6c0266e-52a9-4769-a3f4-4a1168b9f773)

**Comment by agushasok** [comment]
@Haliavschik К сожалению, проблема никак не хочет воспроизводиться на моих устройствах. Попробуйте ещё проверить в другом браузере (желательно Chrome). Если проблема не возникнет, то попробуйте очистить кэш приложения в Яндекс-браузере (https://browser.yandex.ru/help/personal-data-protection/cache-memory.html#clearing-cache) и попробовать снова. Если проблема возникнет и в другом браузере, попробуйте обратиться в поддержку алора (https://t.me/alor_broker).

**Comment by Haliavschik** [comment]
К сожалению я попробовать уже не смогу, так как вывел все деньги.
Можете закрыть тикет
