### ISSUE TITLE
[BUG] Не работает выставление стоп-лосс заявок в СС

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1801]
### Опишите баг

В СС при зажатом shift и клике на цену из стакана - не выставляется стоп-лосс заявка, в консоли выходит ошибка [General Error] Cannot read properties of null (reading 'portfolio'):

https://github.com/user-attachments/assets/79909fea-e7d6-4b86-bd0a-45b608050652

### Воспроизведение

1. Открыть виджет Скальперский стакан по любой бумаге.
2. В настройках СС "включить горячие клавиши" и выбрать "Покупать по кликам без уведомлений".
3. Открыть консоль, вкл. Console.
4. Зажать Шифт и кликнуть на цену из СС.

### Среда.

Windows 10
Google Chrome v128.0.6613.120 

### Ожидаемое поведение

Нет ошибок в консоли. В СС ставятся стоп-лосс заявки по горячей клавише Shift

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
В приведенном случае и не должна ставится заявка. Должно быть оповщение, что позицияы пустая. Невозвожно поставить стоп-лосс на неоткрытую позицию

**Comment by uncrashable** [comment]
Так это не стоп лосс заявка ( в нашем случае стоп маркет), тут же выставляется SL заявки, а они могут существовать без открытия позиции. 
![image](https://github.com/user-attachments/assets/6caa965a-5942-4689-82e4-545697d98a59)

**Comment by sbelashevskiy** [comment]
В Скальперском стакане при нажатии клавиши шифтр ставится стоп-лосс заявка.
Стоп-лосс - это семантическое название. По факту ставится стоп-маркет с количеством лотов РАВНЫМ ТЕКУЩЕЙ ОТКРЫТОЙ ПОЗИЦИИ.
Каким образом эта команда может отработать без позиции?

**Comment by uncrashable** [comment]
Я перепутал , откомментил не ту задачу.  =(((
