### ISSUE TITLE
[BUG] ... Исчезают рисунки графиков теханализа

### ISSUE THREAD

**Issue by dozor54** [alor-broker/Astras-Trading-UI#1807]
### Опишите баг

На графиках от дня и до месяцев все рисунки технического анализа (каналы, уровни, отметки) сохраняются, а на часовых графиках они исчезают.

### Воспроизведение

Индикаторы: МА 200 и МА50, Полосы Боллинджера. Рисунки: каналы, стрелки, линии тренда, уровни фибоначчи, диапазон цен, метка цены. На инструмент IMOEХ все отображается и на младших таймах. На Газпром, Сбер, ММК, Магнит и т.д. на часовых все пропадает

### Среда.

GoogleChrome 129.0.6668.59, кэш почищен, через инкогнито проблема сохраняется

### Ожидаемое поведение

Сохранение рисунков и индикаторов на графиках теханализа при смене таймов

### Скриншоты

![1](https://github.com/user-attachments/assets/f63c1229-2e9f-4c5f-a1fc-d00a65e0e8bc)
![2](https://github.com/user-attachments/assets/2213dc44-bc21-4904-9d1b-95122c151950)

### Дополнительная информация

При тестах воспроизвести проблему не удалось.

### Правила

- [X] Я согласен следовать правилам

**Comment by agushasok** [comment]
@dozor54 возможно, в настройках рисунков скрыты интервалы менее дневных

https://github.com/user-attachments/assets/a899aa76-c15a-442f-aa3d-79fdccdc2f66

**Comment by PilgrimViis** [comment]
@dozor54 в таком случае я закрою? В случае если то что написал @agushasok не поможет, можете открыть снова с комментарием.
