### ISSUE TITLE
[BUG] Проблема с уведомлениями

### ISSUE THREAD

**Issue by independentimaginarium** [alor-broker/Astras-Trading-UI#1809]
### Опишите баг

Не выводятся уведомления 
- в иконке Колокольчика

Всплывающие уведомления работают.
- Уведомления в браузере включены
- Настройки в Профиль -> Уведомления включены

### Воспроизведение

- Проверить, включить / разрешить уведомления
- Выставить / изменить / снять заявку
- Проверить Блоттер -> Уведомления

### Среда.

- ОС Windows
- Яндекс.Браузер
- Google Chrome
- Устройства: смартфон, ноутбук, настольный ПК

### Ожидаемое поведение

Уведомления должны сохраниться модуле Уведомлений приложения (иконка колокольчика в верхнем правом углу терминала)

### Дополнительная информация

Для профилактики выполнено:
- сброс настроек в терминале.
- Включены уведомления в браузере для сайта https://astras.alor.ru
- Запущен терминал в режиме инкгогнито
- Переустановлен браузер.
- пересоздание дашборда, виджета

### Правила

- [X] Я согласен следовать правилам

**Comment by agushasok** [comment]
уведомления в блоттере и не должны приходить. Эта вкладка, чтоб посмотреть, на какие "события" настроены уведомления портфеля. Т. е., например, если в блоттере во вкладке уведомлений есть "заявка исоплнена" - это значит, что если в портфеле исполнится заявка, то на это событие придёт push-уведомление (либо уведомление внутри приложения, если оно активно (иконка колокольчика в верхнем правом углу терминала)). Соответственно, если в блоттере во вкладке увдомлений есть строчка с типом "цена изменилась", это значит, что когда данное событие произойдёт, то так же придёт уведомление в терминал.

**Comment by zlobinm** [comment]
@agushasok Добрый день. Спасибо за ответ.
отредактировал информацию в задаче. тогда остается только момент с Колокольчиком. Не удалось воспроизвести пока, но у каких то пользователей воспроизводится.

т.е. в Блоттер -> Уведомления, типы уведомлений должны соответствовать настройкам Уведомлений в Профиль -> Уведомлений. Список в Блоттер -> Уведомления, должен ли полностью или частично включать включенные опции из Профиль -> Уведомления?

Примечание. Про уведомления в виджете Заявка в курсе, там алерты на изменение цены настраиваются.

**Comment by agushasok** [comment]
@zlobinm В настройках терминала во вкладке уведомления в самом низу можно отключать уведомления для конкретных портфелей. Именно эта информация и отображается в блоттере по выбранному портфелю. Ну и плюс уведомления по изменению цены

**Comment by zlobinm** [comment]
> @zlobinm В настройках терминала во вкладке уведомления в самом низу можно отключать уведомления для конкретных портфелей. Именно эта информация и отображается в блоттере по выбранному портфелю. Ну и плюс уведомления по изменению цены

@agushasok Добрый день.
Там вот в Отключении push-ей пусто, и все переключатели синие, а уведомления в Колокольчике все равно не выводятся. А должны?

**Comment by YAV23** [comment]
Все включено, выключал, входил из другого браузера , уведомления не появляются....

**Comment by sbelashevskiy** [comment]
@zlobinm 
из описания не понятно о каких уведомлениях идет речь.
Под "Колокольчиком" отображаются только следующие уведомления:
1. Уведомления об обновлении приложения
2. Фидбэк
3. Уведомления об испольнении заявок (такие как PUSH уведомления)
4. Уведомления об измении цены (такие как PUSH уведомления)

Никакие другие уведомления (создание заявки, изменении заявки, изменение статуса и т.д) не показываются под колокольчиком и никогда не показывались. Таких уведомлений может быть слишком много и они будут просто создавать информационный шум. В результате у пользователя будет просто висеть куча уведормлений и понастоящему важные уведомления он попросту пропустит.

В настройках отключаются уведомления, которые КРАТКОВРЕМЕННО отображаются в правом верхнем углу. Вот там как раз отображаются ошибки и стататусы выставления заявок. Такие уведомления не хранятся где-то в истории потому что актуальные статусы заявок ВСЕГДА можно посмотреть в виджете блоттер (заявки, стопы, сделки, история сделок).
Эти уведомления отключаемые, потому что некоторые из них попросту мешают при активной торговле.

Уведомления в блоттере вообще не содержат какие-то конкретные уведомления - это список активных PUSH-уведомлений (исполнение заявки, изменение цены на инструмент). Причем уведомления "изменение цены на инструмент)" отображаются только для тех инструментов, которые есть в выбранном порфеле виджета

**Comment by YAV23** [comment]
Добрый день, ничего не происходит  при выполнении условий в окне выставлении заявки -закладка «уведомления»

  
>Понедельник, 30 сентября 2024, 15:09 +03:00 от Sergey Belashevsky ***@***.***>:
> 
> 
>@zlobinm
>из описания не понятно о каких уведомлениях идет речь.
>Под "Колокольчиком" отображаются только следующие уведомления:
>*  Уведомления об обновлении приложения
>*  Фидбэк
>*  Уведомления об исполнении заявок (такие как PUSH уведомления)
>*  Уведомления об измении цены (такие как PUSH уведомления)
>Никакие другие уведомления (создание заявки, изменении заявки, изменение статуса и т.д) не показываются под колокольчиком и никогда не показывались. Таких уведомлений может быть слишком много и они будут просто создавать информационный шум. В результате у пользователя будет просто висеть куча уведормлений и понастоящему важные уведомления он попросту пропустит.
>В настройках отключаются уведомления, которые КРАТКОВРЕМЕННО отображаются в правом верхнем углу. Вот там как раз отображаются ошибки и стататусы выставления заявок. Такие уведомления не хранятся где-то в истории потому что актуальные статусы заявок ВСЕГДА можно посмотреть в виджете блоттер (заявки, стопы, сделки, история сделок).
>Эти уведомления отключаемые, потому что некоторые из них попросту мешают при активной торговле.
>Уведомления в блоттере вообще не содержат какие-то конкретные уведомления - это список активных PUSH-уведомлений (исполнение заявки, изменение цены на инструмент). Причем уведомления "изменение цены на инструмент)" отображаются только для тех инструментов, которые есть в выбранном порфеле виджета
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you commented. Message ID:  <alor-broker/Astras-Trading-UI/issues/1809/2383009543 @ github . com> 
 
 
--
Алекс Яч
Отправлено из Почты  Mail

**Comment by sbelashevskiy** [comment]
Нужна проверка на стороне API - в приложение вообще не приходят пуш-уведомления

**Comment by YAV23** [comment]
Понял, уведомление об изменении цены, появляется только по инструменту, который есть в портфеле…
А так , чтобы выставлять , как в TV, не планируется?
  
>Понедельник, 30 сентября 2024, 15:09 +03:00 от Sergey Belashevsky ***@***.***>:
> 
> 
>@zlobinm
>из описания не понятно о каких уведомлениях идет речь.
>Под "Колокольчиком" отображаются только следующие уведомления:
>*  Уведомления об обновлении приложения
>*  Фидбэк
>*  Уведомления об исполнении заявок (такие как PUSH уведомления)
>*  Уведомления об измении цены (такие как PUSH уведомления)
>Никакие другие уведомления (создание заявки, изменении заявки, изменение статуса и т.д) не показываются под колокольчиком и никогда не показывались. Таких уведомлений может быть слишком много и они будут просто создавать информационный шум. В результате у пользователя будет просто висеть куча уведормлений и понастоящему важные уведомления он попросту пропустит.
>В настройках отключаются уведомления, которые КРАТКОВРЕМЕННО отображаются в правом верхнем углу. Вот там как раз отображаются ошибки и стататусы выставления заявок. Такие уведомления не хранятся где-то в истории потому что актуальные статусы заявок ВСЕГДА можно посмотреть в виджете блоттер (заявки, стопы, сделки, история сделок).
>Эти уведомления отключаемые, потому что некоторые из них попросту мешают при активной торговле.
>Уведомления в блоттере вообще не содержат какие-то конкретные уведомления - это список активных PUSH-уведомлений (исполнение заявки, изменение цены на инструмент). Причем уведомления "изменение цены на инструмент)" отображаются только для тех инструментов, которые есть в выбранном порфеле виджета
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you commented. Message ID:  <alor-broker/Astras-Trading-UI/issues/1809/2383009543 @ github . com> 
 
 
--
Александр Ячменев
Отправлено из Почты  Mail

**Comment by sbelashevskiy** [comment]
> Понял, уведомление об изменении цены, появляется только по инструменту, который есть в портфеле… А так , чтобы выставлять , как в TV, не планируется?  
> Понедельник, 30 сентября 2024, 15:09 +03:00 от Sergey Belashevsky ***@***.***>:     @zlobinm из описания не понятно о каких уведомлениях идет речь. Под "Колокольчиком" отображаются только следующие уведомления: * Уведомления об обновлении приложения * Фидбэк * Уведомления об исполнении заявок (такие как PUSH уведомления) * Уведомления об измении цены (такие как PUSH уведомления) Никакие другие уведомления (создание заявки, изменении заявки, изменение статуса и т.д) не показываются под колокольчиком и никогда не показывались. Таких уведомлений может быть слишком много и они будут просто создавать информационный шум. В результате у пользователя будет просто висеть куча уведормлений и понастоящему важные уведомления он попросту пропустит. В настройках отключаются уведомления, которые КРАТКОВРЕМЕННО отображаются в правом верхнем углу. Вот там как раз отображаются ошибки и стататусы выставления заявок. Такие уведомления не хранятся где-то в истории потому что актуальные статусы заявок ВСЕГДА можно посмотреть в виджете блоттер (заявки, стопы, сделки, история сделок). Эти уведомления отключаемые, потому что некоторые из них попросту мешают при активной торговле. Уведомления в блоттере вообще не содержат какие-то конкретные уведомления - это список активных PUSH-уведомлений (исполнение заявки, изменение цены на инструмент). Причем уведомления "изменение цены на инструмент)" отображаются только для тех инструментов, которые есть в выбранном порфеле виджета — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you commented. Message ID: <alor-broker/Astras-Trading-UI/issues/1809/2383009543 @ github . com>
>     -- Александр Ячменев Отправлено из Почты Mail

Вы можете поставить уведомление об изменении цены на любой инструмент черед диалог выставления заявки или через виджет. Там же вы можете посмотреть какие уведомления уже есть.
Но в блоттере такие уведомления показывают только если инструмент есть в портфеле.
Я понимаю, что это путает, но как это сделать удобнее у менч нет идей.
Показывать в блоттере все уведомления - вроде бы как нет смысла, потому что этот виджет ориентирован на конкретный портфель с конкретными инструментами.
Делать отдельный виджет для добавления уведомлений по изменению цены и отображать в нем все настроеные уведомления - вроде тоже не особо удобно - будет занимать лишнее место, да и в диалоге/виджете выставления заявки есть возможность не вписывать цену, а использовать текущие best bid ask.

https://github.com/user-attachments/assets/4f7552df-3760-48c9-ad12-821dc7d521b3

Как бы для Вас было удобнее организовать уведомления об изменении цены. Я имею ввиду добавления новых и просмотр уще установленных? Может быть есть опыт использования такой функциональности в других терминала?

**Comment by uncrashable** [comment]
У себя проверил , у меня тоже пуши не всплывают. 

Если трейдер в поисках позиции и выставляет уведомления по разным инструментам, ему нужно понимать где сработал алерт. Поэтому предлагаю отображать все уведомления в блоттере. Возможно сделать переключатель Показывать уведомления только для портфеля или все.

**Comment by sbelashevskiy** [comment]
Мне лично вообще не очень нравится оторажать список уведомлений в блоттере. Как-то он там не очень очевиден пользователей и судя по этой проблеме больше вводит в заблуждение. 
Лучше бы в заголовке отображать какой-нибудь индикатор и при клике по нему открывать модальное окно.
Если кто-то где-то видел удачнуб реализации организауции таких уведомлений, то хорошо бы в эту задачу прикрепить скрины. Со стороны доработки мы только за, но нужны идеи как это лучше сделать

**Comment by PilgrimViis** [comment]
Коллеги на бэкенде исправили. Теперь работает.
