### ISSUE TITLE
[FEATURE] Элементарные инструменты тех анализа. [График TV]

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#181]
### Опишите проблему, которую решает ваша фича

1. Хотелось бы получить инструменты рисования на графике
2. Автоматически прорисовывался макс и минимум на масштабируемом графике( как в ТВ), если график отдалять или приближать то эти значение бы изменялись. Т.е. они отображат макс и мин который сейчас отображен на графике. 
![image](https://user-images.githubusercontent.com/105817664/169141613-54e57d2d-0032-4c61-b69d-33e00eeb956a.png)
3. Не понятно в каких единицах изображены объемы и не видно их значений. 

### Опишите предлагаемое вами решение

1. Добавить элементарные инструменты рисования:
Горизонтальная линия 
Трендовая линия 
Лучи - горизонтальные и трендовые наклонные 
Канал - чертим по 2м точка линию и к ней привязывается параллель, что бы выделить "трейндовый канал" 
![image](https://user-images.githubusercontent.com/105817664/169142065-48a19dc4-0127-417e-bddb-7690c4a07a9e.png)

3. Добавить к левой шкале ед измерения объемов
 

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
https://github.com/tradingview/charting-library-examples Интегриговать эту либу. Кирилл работал с ней в нашем TV, если что может проконсультировать. Плюс можно посмотреть исходники как это сделано у нас в ТВ. Там интерфейс идентичный.

**Comment by PilgrimViis** [comment]
@sbelashevskiy по поводу этой задачи. Прошу тебя если увидишь что какие-то вещи, которые тут предложены, нельзя оперативно сделать в графиках от ТВ, то пиши мне. Мы разберемся.
