### ISSUE TITLE
[BUG] Отображение собственных сделок в сс

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1810]
### Опишите баг

Стакан отображает прошлые сделки. 

Открыли сделку , напротив цены отображается объем. - закрыли сделку отображение исчезло. 

Но когда я вхожу в следующую сделку, то объем от первой сделки также начинает отображаться. - так быть недолжно. 
Отображение сделок работает только в рамках одной сделки, после ее закрытия, все должно исчезнуть со стакана. 
И при следующем входе в сделку, индикатор отобразит только текущую. 

### Воспроизведение

Создать виджет скальперский стакан, выставить индикатор на отображение собственных сделок. 
Войти в сделку и закрыть ее. 
Повторно войти в сделку по другой цене  и увидим, что индикатор отображает и прошлую сделку. 

### Среда.

Виндовс 10 , Хром 

### Ожидаемое поведение

Описал выше

### Скриншоты

Тут все верно. 
https://github.com/user-attachments/assets/6c0ce39f-f5ab-4dbd-b30b-f08d5fb185c3
_________________________
Повторный вход в сделку отобразил и прошлую и текущую 

https://github.com/user-attachments/assets/e7d77551-3d8e-4ff7-80d3-22d7e5f0f32b

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@uncrashable 
отображаются ВСЕ сделки за текущую сессию.
Это программа, у нее нет понятия закрыли сделки или не закрыли. 
Суммировать объем по всем сделкам за день и если равен нулю не отображать - тоже не имеет смысла

**Comment by sbelashevskiy** [comment]
1. Так и не виду ответа на вопрос что если на момент первой сделки позиция была открыта. Ты опять описал простейший случай, который я уже описал в примере 1.
2. По поводу цветов. Каким образом пользователь будет эти зеленые крадратики отличать от других подобных обозначений?

**Comment by sbelashevskiy** [comment]
Итого я вижу два варианта фильтрации отображаемых сделок:
1. Сортируем все сделки по дате. Начиная с последней суммируем количество каждой сделки (с учетом знака в зависимости от покупки/продажи) пока не получим общий 0. 
Здесь текущая позиция не учитывается вообще

2.  Сортируем все сделки по дате. Начиная с последней от текущей позиции отнимаем количество каждой сделки (с учетом знака в зависимости от покупки/продажи и с учетом знака текущей позиции) пока не получим общий 0.
