### ISSUE TITLE
[FEATURE] ... Возможность изменить место окна ввода заявки или его сдвиг

### ISSUE THREAD

**Issue by lurihell** [alor-broker/Astras-Trading-UI#1817]
### Опишите проблему, которую решает ваша фича

Хотелось бы чтобы это окно с заявкой можно было сдвигать в сторону прежде чем нажать КУПИТЬ  / ПРОДАТЬ (чтобы видеть график)

### Опишите предлагаемое вами решение

Возможность сдвинуть окно или указать место его появления

### Правила

- [X] Я согласен следовать правилам

**Comment by uncrashable** [comment]
+
Возможность двигать модальное окно - нужная функция
