### ISSUE TITLE
[FEATURE] ... При смене таймфрейма график перезагружается

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#182]
### Опишите проблему, которую решает ваша фича

При смене таймфрейма график перезагружается. Занимает на каждое переключение  2  и более секунд ...иногда около 10 секунд... долго
Сравниваю с ТВ. Там при переключении  секунда паузы и сразу весь график, а тут еще смотришь "дискотеку" как график пляшет. 
Хотелось бы что бы этот процесс проходил быстрее.

### Опишите предлагаемое вами решение

Можно ли что бы график куда нибудь подгружался в память? 

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Да, мы знает и даже уже исправили. Сегодня опубликуем. https://github.com/alor-broker/Astras-Trading-UI/issues/58 Эту issue закрою как дубликат.
