### ISSUE TITLE
[BUG] Не сохраняются настройки при переключении дашборда

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1822]
### Опишите баг

В виджете "Выбор инструмента" можно использовать сортировку отображения. 
Если переключиться на другой дашборд, и вернуться обратно - сортировка "слетает", т.е. не сохраняется. 

### Воспроизведение

Создать виджет "Выбор инструмента" 
Настроить колонки и отсортировать например по проценту изменения от закрытия. 
Переключиться на другой дашборд
Вернуться обратно
Сортировка слетает. 

### Среда.

Виндовс 10
Хром

### Ожидаемое поведение

Все настройки должны сохраняться.

### Скриншоты

https://github.com/user-attachments/assets/3c1c2a6d-96ed-41b6-821e-30995ad22836

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Сортировка не сохраняется вообще ни в одной таблице приложения. И никогда не сохранялась

**Comment by uncrashable** [comment]
> Сортировка не сохраняется вообще ни в одной таблице приложения. И никогда не сохранялась. При переключении дашборда все его состояние сбрасывается по соображениям производительности

Это как минимум неудобно. Каждый раз настраивать приходится. Можем сохранять ?

**Comment by uncrashable** [comment]
> Технически реализуемо. Но тут вопрос: сохранять тоько пока приложение открыто (сбасывается после перезагрузки страницы) или постоянно. Какое именно состоние сохранять: тоько сортировку, или еще и фильтры. Сортировка выглядит безболезненно, но вот с сохранением фильтров польше вероятность, что пользователь постаит фильтры, забует и будет жаловаться, что у него какие-то данные не отображаются

Вообще конечно удобнее чтобы все сохранялось. Также как мы открыли бы Астрас в другом месте и уже все настроено. 
От части согласен с тобой, наверное будет и такое, но в целом, фильтрами уже пользуются более продвинутые пользователи, возможно вспомнят что включен фильтр.
