### ISSUE TITLE
[OTHER] Поправить опечатку в Тех анализе

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#1827]
В "Тех анализе" при включении тумблера "Отображать сделки" и выборе Маркер сделки: Стрелки - опечатка в фразе ниже "Цвет маркера на продажу", поправить на "Размер маркера":

![image](https://github.com/user-attachments/assets/9043410d-7814-44a6-8084-8526eb2b23bc)

**Comment by sbelashevskiy** [comment]
Исправлено в рамках другой задачи
