### ISSUE TITLE
[BUG] Выбор инструмента тормозит терминал

### ISSUE THREAD

**Issue by independentimaginarium** [alor-broker/Astras-Trading-UI#1828]
### Опишите баг

При добавлении виджета Выбор инструмента, и попытке выставить заявку, начинает тормозить весь дашборд + мигает индикатор подключения

### Воспроизведение

- Создать дашборд по умолчанию, или настроить свой
- Добавить Выбор инструмента
- Выставить заявку

### Среда.

- ОС Windows
- Google Chrome, Microsoft Edge, Mozilla Firefox
- Устройство: игровой ноутбук, интернет соединение по Wi-Fi, кабелю, мобильный интернет. Скорость 200 М/c
- Разные IP

### Ожидаемое поведение

Виджет, при пустом и не пустом списках инструментов, не должен тормозить весь терминал

### Дополнительная информация

- Пинг выполнялся. Возможны потери.
- Speed test не сделан
- Параллельно терминалу идет торговля по апи. Проблем не возникает
- Скальперский стакан не открыт

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Как определили что тормозит именно эттот виджет! Другие виджеты добавлены?
Сколько инструментов в списках?
Используется отображение нескольких спископ?
Как проявляются тормоза? Видео?

Вот открыты ВСЕ стандартные списки и ничего не мигает и не тормозит.

https://github.com/user-attachments/assets/34ee7b29-ad8d-42e5-8cba-ca45bd2af2fe

Как я уже упоминал ранее с таким набором входных данный найти причину проблем невозможно.
Даже времени нет

**Comment by independentimaginarium** [comment]
Куда можно направить видео? здесь не хотелось бы публиковать

**Comment by Che4ako** [comment]
Видео с тестом прикрепляю. На нем видно, что терминал при добавленном виджете "Instrument select" сильно лагает, после удаленяи виджета все начинает работать быстро. Добавление/удаление на видео повторил дважды, чтобы исключить случайность.

Проблема присутсвует не всегда, а только в часы с большой торговой активностью. Например, пол часа назад все периодически работало быстро даже с виджетом, также быстро работало на аукционе открытия и большую часть вечерней сессии. Все остальное время работает как на видео.

В виджет добавлены все тикеры акций (большая часть), тормозит как выставление заявок, так и потоки данных (заявка уже удалена, а в стакане несколько минут еще висит и тд, график тоже долго прогружается). То есть тормозит буквально все. Пробовал на 3-х ноутбуках и 2-х провайдерах, ноутбуки мощные (процессор Ryzen 7840H), скорость интернета по speedtest 200 Мбит/c

**Comment by Che4ako** [comment]
![Screenshot from 2024-10-10 14-43-44](https://github.com/user-attachments/assets/7a013438-e0de-40af-9437-3f6b7b5dee7f)
![Screenshot from 2024-10-10 14-43-48](https://github.com/user-attachments/assets/ed0fa06d-e679-435e-8507-1fefeb774393)
![Screenshot from 2024-10-10 14-44-21](https://github.com/user-attachments/assets/1ce91c30-62ae-4512-a771-eb6b09d8d175)
Настройки виджета "Instrument select"

**Comment by sbelashevskiy** [comment]
Вам нужно сократить список инструментов или разбить его на несколько списков и активировать их не все сразу.
Судя по скролу у Вас в списке > 100 инструментов. По каждому из них идет болшой поток данных. Поэтому в моменты активной торговли значительно возрастает нагрузка.

**Comment by sbelashevskiy** [comment]
@Che4ako
Еще момент: у Вас эти проблемы недавно проявились или всегда были?

При 150+ инструментах в списке таки проблемы были раньше. При таком объеме у них может быть только одно решение - пожертвовать скоротью обносления.
Либо как я ранее посоветовал разбить на небольшие списки.

Если же это началось недавно, то оэто может быть результатом последних изменений в виджете (отображение нескольких списков одновременно)

**Comment by Che4ako** [comment]
Альтернативное решение --- переписать этот виджет, чтобы он не ронял весь терминал, когда в списке всего 150 тикеров. Например, пересылать не сырые данные по всем акциям с последующе агрегацией в виджете (как, видимо, это реализовано сейчас), а стримить сразу агрегированные данные.

Пожалуйста, сообщите поддержке, что у вас есть такой забагованный виджет, потому что на поиск этой проблемы у меня ушло 2.5 дня, причем поддержка предложила миллион идей относительно проверки скорости интернета, мощности компьютера и надежности провайдера.

Виджет я с дашбордов удалил, буду пользоваться переключателем тикеров, встроенном в графики, а за информацией по тикерам буду следить у другого брокера.

**Comment by sbelashevskiy** [comment]
Будем рады если сможете привести пример терминала, который может одновременно отображать данные по 150+ тикерам с такой же  интенсивностью и при этом не оказывать влияния на другие функции

**Comment by Che4ako** [comment]
Другого такого нет.

**Comment by Che4ako** [comment]
Если что я не создавал никаких списков в этом виджете, и никаких тикеров не добавлял. Все это время был включен список "Default list", что бы это название ни значило.

Таким образом, встроенный сейчас в этот виджет список роняет терминал.

**Comment by sbelashevskiy** [comment]
Можете выполнить экспорт Вашего списка чтобы мы могли посмотреть в чем конкретно проблема?
Инструкция:
https://github.com/user-attachments/assets/0e4f2daf-a823-4882-ba84-288eecc9ef81


150+ инструментов в списке это лишь пример. Именно на такое число 2 года назад была жалоба от 1 пользователя.
Я сейчас добавил все стандартные списки, это где-то 100+ инструментов и не вижу каких-либо проблем.
При этом комп у меня вполне стандартный и скорость всего 90Мбит и я значительно удален от биржи географически
![image](https://github.com/user-attachments/assets/7f746033-e231-4296-835a-04bcd0cb04c7)
![image](https://github.com/user-attachments/assets/65668804-d884-482a-90a3-ca9b109d39a7)

От других ползователей жалоб также не поступало. Именно поэтому тех. поддержка в первую очередь обращает внимание на проблемы со скоростью сети.

Да, этот список формируется из запросов пользователей через данный виджет, чтобы не приходилось по несколько раз выполнять поиск интересующего тикера. Это сделано для их же удобства. Также работает https://tradingview.alorbroker.ru/ и https://ru.tradingview.com/.
Подразумевается, что пользователь сам будет удалять неинтересные ему тикеры.
И Вы верно заметили, что если тикер не нужен в списке, то, например для просмотра его графика, его можно выбрать через настройки соответствующего виджета или его заголовок

**Comment by Che4ako** [comment]
[Default list.txt](https://github.com/user-attachments/files/17328510/Default.list.txt)
