### ISSUE TITLE
[BUG] Отсутствует поле куда задавать время после бездействия

### ISSUE THREAD

**Issue by asan99** [alor-broker/Astras-Trading-UI#1835]
### Опишите баг

в настройках профиля отсутствует поле куда вносить значения, разлогина после бездействия

### Воспроизведение

- 1. Зайти в Астрас под своими кредами
- 2. Перейти в Профиль -> Общие -> кликнуть по чекбоксу "Выходить при бездействии"

### Среда.

- Браузер хром

### Ожидаемое поведение

могу ввести значения в минутах после бездействия пользователя

### Скриншоты

![image](https://github.com/user-attachments/assets/0af93e2b-810b-4cfe-80a0-a6df90e90344)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Исправлено в рамках другой задачи
