### ISSUE TITLE
[BUG] сброс бумаг при  нажатии на шестеренку в опционной доске

### ISSUE THREAD

**Issue by asan99** [alor-broker/Astras-Trading-UI#1838]
### Опишите баг

В опционной доске после того как выбраны бумаги нажимаешь на шестеренку и обратно на нее же, сбрасываются бумаги

### Воспроизведение

- 1. Открыть виджет опционная доска
- 2. Выбрать бумаги 
- 3. Нажать на шестеренку 

### Среда.

- Браузер. Chrome

### Ожидаемое поведение

Выбранные бумаги должны оставаться не сбрасываясь 

### Скриншоты

https://github.com/user-attachments/assets/d6220ddc-dbc4-4fdd-a540-2a3e4df75435

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Этот виджет в принципе без сохранения состояния.
Неверное ожидаемое состояние. 
Если пользователям нужна такая фича, то это должен быть фича реквест
