### ISSUE TITLE
[FEATURE] Корректировка поиска в виджете "Выбор инструмента"

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1847]
### Опишите проблему, которую решает ваша фича

При большом открытом списке инструментов, тяжело искать необходимый актив.
Прошу добавить возможность быстрого поиска. 

### Опишите предлагаемое вами решение

Опишу как реализовано это в Квике.

Есть сформированная таблица с инструментами, если я нажимаю Ctrl+F открывается меню поиска инструмента

![image](https://github.com/user-attachments/assets/0f0ae6f4-d108-4a4c-938b-286d6ba1e709)

![image](https://github.com/user-attachments/assets/7f664db3-fd15-43c2-9483-01e449ac1e68)
По запросу, в текущей таблице, система проверяет этот инструмент , если он есть, то моментально переключает на него, соответственно и все связанные графики так же начинают его отображать. 

Если в таблице такого инструмента нет, то система добавляет его и также сразу переключает. 

У нас сейчас почти также , но прошу сделать корректировку. 

По нажатию Ctrl+f откроется окно поиска  (ок)
Пишем инструмент нажимаем Enter (ок) 
Система не проверяет есть ли он в списке или нет (не ок ) 
Система не подсвечивает и не перелистывает список что бы показать где находится в списке этот инструмент ( не ок) 
Система добавляет этот инструмент в конец списка и не понятно по какой логике ... в маем случае система добавила в список Валюта, который был в самом низу. (не ок) 

### Опишите альтернативные решения, о которых вы думали

Как бы хотелось видеть работы поиска: 

При нажатии Ctrl+F в списке инструментов, открывается окно поиска(так есть сейчас), 
Вводим в строке интересующий инструмент и нажимаем Enter(так есть сейчас) 
Система ищет этот инструмент в текущих списках, если нужно, раскрывает этот список, временно выделяет(подсвечивает инструмент) и сразу как бы кликает по нему(выбирает его, чтобы сразу в связных графиках переключилось все). 

т.е. система не добавляет дубль по инструменту, если он уже есть в каких либо списках на панели. 

Если клиенту например понадобится , что бы один и тот же инструмент был в разных списках, он сможет это сделать через ПКМ "Копировать в список" 

Видео для примера

https://github.com/user-attachments/assets/5863976e-31d6-44fd-9237-07ebc8186d6b

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@PilgrimViis @uncrashable 

Я уже не первый раз встречаю такое поведение пользователя, когда он хочет осуществить поиск инструмента и выбрать его НЕ ДОБАВЛЯЯ в какой либо список. Либо сначала осуществить поиск и потом только добавить в какой-то определенный список.
 Из-за того, что пользователи используют выбор инструмента для поиска они просто формируют очень большие списки, которые потом тормозят терминал https://github.com/alor-broker/Astras-Trading-UI/issues/1828.
 Сейчас выбор инструмента просто не может сделать поиск без добавления инструмента в список.
 
 Предлагаю сделать диалог для поиска. он будет вызываться по Ctrl+F и божно еще какую-нибудь кнопку на верхнюю панель добавить.
 
 Диалог будет содержать несколько полей для фильтрации. Тикер, биржа, борд  - раздельные поля. Полю еще что-то еще.
 Для поиска будем использовать graphQl API - тот же самый, что сейчас используем во все инструменты.
 Результаты отображаем в виде таблицы с ключевыми столбцами. Не более 10 строк.
 
 Тут же возможно отображение более детальной информации при клике по строке.
 Правый клик - добавить с список.
В этом же диалоге выбранный по умолчанию переключатель - выбирать инструмент при клике (плюс нужен выбор цвета при включенной привязке к бэйджам).

Так мы решаем проблемы:
1. Пользователь получает расширенный удобный поиск
2. Мы избавляемся от проблемы длинных списков, которые формируются из-за поиска

**Comment by PilgrimViis** [comment]
@sbelashevskiy мне нравится твоя идея. Давай сделаем
