### ISSUE TITLE
[BUG] Старые данные на графике 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#186]
### Опишите баг

Был открыл график Сбербанка, переключал таймфреймы, заметил, что иногда, график подгружает непонятно какие данные. Стоимость Сбера 125 руб , а на графике показывает 300 .

### Воспроизведение

Окно "График" 
Переключение таймфрейма/
На след день была такая же проблема. Переключил тайм фрейм, потом даже ничего не делал, График менялся каждые 2-3 секунды  сам. 

### Среда.

OS Win7
Chrome Версия 101.0.4951.67 (Официальная сборка), (64 бит)
Время было 21-50

### Ожидаемое поведение

Так быть не должно ) 

### Скриншоты

![image](https://user-images.githubusercontent.com/105817664/169593517-2d475b41-dde7-400a-ac3a-addb4552214e.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Я думаю этот баг вызван тем, что график долго прогружается. Видите у вас на скрине 26 числа? Т.е. это какие-то старые данные. Возможно из-за скорости интернета ещё не прогрузились данные. Мы уже опубликовали фикс, провьте пожалуйста, действительно ли это так.
![image](https://user-images.githubusercontent.com/6408195/169754117-eedb3251-bd25-47e8-bef8-1ea39591bfd8.png)

**Comment by PilgrimViis** [comment]
linked #58
