### ISSUE TITLE
[BUG] Ошибки данных в виджете "Инфо"

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#1878]
### Опишите баг

Заметил, что по некоторым инструментам на фьючерсах , есть не верное отображание шага цены. 
К примеру SGZH-12.24  , по стакану видно, что шаг 0.001, а у нас в Инфо показывает 1
![image](https://github.com/user-attachments/assets/06bb60d7-1813-495b-8ae2-b18860381b80)

VTBR-12.24 тоже самое 

Проверил валютные, товарные , индексные - там вроде все верно. 

Трабла только с фьючами на акции. 

### Воспроизведение

Создать виджет Инфо. Покликать по инструментам. Можно  открыть стакан и сравнить сразу. 

### Среда.

Виндовс 10
Хром

### Ожидаемое поведение

Данные должны отображаться корректно. 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
У SGZH-12.24 шаг 1. Запятой отделяются тысячи
![image](https://github.com/user-attachments/assets/b4c29d87-bcad-4fa9-ad09-f5fe90eb1746)

**Comment by uncrashable** [comment]
Как смотрите на то, что бы не отделять запятыми тысячи, а разделять пробелом.
Путаница создается. . и , из далека сложно отличить. 

К примеру, запятыми отделять дробную часть. 
Тысячи отделять пробелом. 

или хотябы просто убрать запятую для отделения "тысячей"

**Comment by uncrashable** [comment]
![image](https://github.com/user-attachments/assets/c7d2f3b1-29f3-4bec-87fc-f32eedcf8e87)

**Comment by sbelashevskiy** [comment]
Создал задачу на унификацию отображения чисел и дат. По текущему описанию ошибки нет
