### ISSUE TITLE
[FEATURE] Добавить заполнение поля originator в cws

### ISSUE THREAD

**Issue by SpaceDandy406** [alor-broker/Astras-Trading-UI#1885]
### Опишите проблему, которую решает ваша фича

При установке веб-сокет соединения в Астрасе для отправки команд, не отправляется хедер originator (в силу отсутствия данного функционала у библиотеки веб-сокетов). Из-за этого на бэке невозможно определить, из Астраса ли отправлялись заявки или просто по апи.

### Опишите предлагаемое вами решение

В сообщении authorize у cws недавно добавили поле originator, прошу добавить заполнение этого поля значением, которое раньше проставлял Астрас, когда заявки работали через http

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Уже давно есть
![image](https://github.com/user-attachments/assets/25192f35-f10f-4dd3-ae6e-b997651c80e7)

**Comment by SpaceDandy406** [comment]
Благодарю
Смотрел на дев контуре, там не было заполнено
