### ISSUE TITLE
[BUG] Не корректно отражается текущая цена фьючерса и % изменение

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#189]
### Опишите баг

Не корректно отражается текущая цена фьючерса и % изменение

### Воспроизведение

скорректировать потоки данных

### Среда.

windows 7 Chrome

### Ожидаемое поведение

отражение текущей цены и % изменения

### Скриншоты

![Снимок](https://user-images.githubusercontent.com/99327222/169771502-f85d1ab7-692a-49b4-8c7a-7767447a4c93.JPG)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
А о каком фьючерсе идёт речь? В поиске вижу вы набрали индекс РТС. Уточните пожалуйста.

**Comment by PilgrimViis** [comment]
Ответа не получил. Закрываю задачу как невоспроизводимую.
