### ISSUE TITLE
[FEATURE] Добавить историю разработки терминала

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#191]
### Опишите проблему, которую решает ваша фича

Нет информации о внесенных изменениях в терминал

### Опишите предлагаемое вами решение

Отображать в терминале историю правок и добавления новых функций. Какие-то крупные изменения сразу, а мелкие, например, по мере накопления. Так и конечный пользователь будет видеть, что работа ведется, а тестировщикам видно, где потыкать по их запросам.
Что-то вроде:

> Дата:
> 
> Исправлено:
> 1. ...
> 2. ...  
> 3. ...
> 
> Добавлено:
> 1. ...
> 2. ...
> 3. ...

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Можно также ввести версии для релизов и показывать изменения если новая версия отличается от последней версии, которую видел пользователь

**Comment by sbelashevskiy** [comment]
В качестве текущего решения добавлена ссылка на перечень релизов
![image](https://user-images.githubusercontent.com/29191749/171123578-b2e2112b-0e9a-485b-99b0-5650184532b9.png)
