### ISSUE TITLE
[BUG] Смена пользователя 

### ISSUE THREAD

**Issue by OLGALEBs** [alor-broker/Astras-Trading-UI#194]
### Опишите баг

После смены пользователя неверно отображается договор.
Перелогинилась, пользователь поменялся, а договор остался прежний (даже не мой, т.к. перед этим заходила под другим клиентом)

### Воспроизведение

Сменить пользователя (выйти из одной учетной записи и войти в другую)

### Среда.

Браузер Microsoft Edge

### Ожидаемое поведение

Смена договора после смены пользователя

### Скриншоты

![image](https://user-images.githubusercontent.com/106099297/170217237-fd7444f4-b7bb-4357-8dd8-fd1ec2982641.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@OLGALEBs ,
спасибо за репорт!

К сожалению не удалось повторить в Microsoft Edge на тестовом окружении.
Проверьте, пожалуйста, что в текущей версии эта проблема все еще существует.
Если проблема еще есть, то уточните, пожалуйста в чем конкретно выражается проблема.
Для примера я попробовал воспроизвести проблему с двумя аккаунтами и визуально договор изменеяется при смене пользователя:

https://user-images.githubusercontent.com/29191749/171173409-7cb3ea12-2e45-4c66-9b3c-cb29f81752fd.mp4

И приложите, пожалуйста, версию браузера. Возможно, проблема наблюдается только в определенной версии:

https://user-images.githubusercontent.com/29191749/171173799-a1e986c7-4836-4bea-b147-d74b958a7b83.mp4

**Comment by OLGALEBs** [comment]
Проблема остается. При входе отображается окошко с ошибкой
![image](https://user-images.githubusercontent.com/106099297/171175173-04da0d17-c23e-44dc-a211-c1e04d0c19eb.png)

**Comment by PilgrimViis** [comment]
@OLGALEBs вы заходите через номер телефона? Можете попробовать через P0... зайти?

**Comment by OLGALEBs** [comment]
Да, с Р0... вошло корректно.
Наверное, надо тогда разнообразить варианты входа, раз мы декларируем, что вход "как в кабинет клиента"

**Comment by PilgrimViis** [comment]
Это ошибка, но не на Astras, а на API. Я передал коллегам. Вход как в кабинет клиента, от этого не отказываемся.
