### ISSUE TITLE
[FEATURE] Параметры свечи 

### ISSUE THREAD

**Issue by OLGALEBs** [alor-broker/Astras-Trading-UI#195]
### Опишите проблему, которую решает ваша фича

При наведении курсора на свечу отображается только цена закрытия свечи. 
Лучше добавить все данные по свече (откр, закр, макс, мин)

### Опишите предлагаемое вами решение

Добавить всплывающее окно с данными свечки

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
#chart
