### ISSUE TITLE
[BUG] В средней цене количество знаков после запятой должно совпадать с шагом цены

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#199]
### Опишите баг

В блоттере с портфелем во вкладке Позиции - в средней цене транслируется недостаточно знаков после запятой, как пример в скрине средняя цена по акциям втб из астрас и ТВ.
В заявка и стопах количество знаков после запятой транслируется нормально.

### Воспроизведение

открыть блоттер с портфелем, вкладка "позиции"

### Среда.

win 7 Firefox

### Ожидаемое поведение

увеличить количество знаков, аналогично как в столбце цены во вкладках Заявки и Стопы

### Скриншоты

![изображение](https://user-images.githubusercontent.com/105856884/170279675-964a0b23-ed51-4f7e-b559-e659ef33cdab.png)
![изображение](https://user-images.githubusercontent.com/105856884/170279857-a6fb89eb-3ab1-4d3c-bd32-1af3fc04aa66.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я хз почему это помечено как "Закрыто". В данный момент реальный баг, воспроизводится при торговле на валютном рынке.

**Comment by sbelashevskiy** [comment]
@PilgrimViis 
В заявках и стопах нет округления, т.к. по заявкам приходит четкая цена без необходимости какого-либо округления.
Средняя цена - величина расчетная. Округляется она очень странным образом:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/7cd77326-788c-4121-a1b1-3a8e8e237425)

Этот вопрос уже несколько раз поднимался.
По VTBR была другая проблема - там без всякого округления всегда отображалось только 3 знака после запятой. Это было исправления, видимо, потому эту задачу и закрыли.
Если делать округление по minStep, то для каждой позиции придется дополнительно запрашивать информацию по инструменту т.к. с позициями это поле не приходит
