### ISSUE TITLE
[BUG] Не считается коммиссия в другой валюте, кроме рублей

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#207]
### Опишите баг

Забиваю 10 мультов, комиссии 5тыс. 
![image](https://user-images.githubusercontent.com/6408195/171621154-09a2a3a0-7a1c-418d-8d29-873cc7d51638.png)
При этом:
от 10M $ - 5000 руб
от 1M руб - 5000 руб

### Воспроизведение

1. Открыть виджет выставления заявки
2. Менять цену и количество у рублевого инструмента
3. Выбрать валютный инструмент и менять там цену и количество
4. Смотреть на комиссию

### Среда.

Chrome 102, Windows

### Ожидаемое поведение

Комиссия должна корректно считатся и указыватся в зависимости от валюты

### Дополнительная информация

Первый раз о баге написал @[dzeron13](https://github.com/dzeron13) в #180 

### Правила

- [ ] Я согласен следовать правилам

**Comment by dzeron13** [comment]
Дополню. Вопрос даже больше, не что комиссия в зарубежных инструментах считается в рублях - тут как раз всё явно, это известная тема. А вот расчет ведется странно:
- Ставка. Для рублей она получается 0.005 (откуда такая?). Для доллара она 0.0005, и судя по тому, что суммы выходят ровными, доллары считаются рублями.
