### ISSUE TITLE
[BUG] Кривое форматирование

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#214]
### Опишите баг

![image](https://user-images.githubusercontent.com/6408195/172183832-bf500a2f-7e7d-42b2-817a-e242140b8663.png)

### Воспроизведение

1.  Выбрать инструмент RTS-6.22
2.  Создать заявку на покупку
3. Поехала вёрстка

### Среда.

Chrome 102

### Ожидаемое поведение

Не должно вылетать за границы. А если вылетает, то пускай будет по центру ориентация.

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Эта проблема должна быть исправлена  в https://github.com/alor-broker/Astras-Trading-UI/pull/213/

**Comment by PilgrimViis** [comment]
![image](https://user-images.githubusercontent.com/6408195/172328724-79cc896b-8ec0-4f75-8ec6-a89f54485eae.png)
@sbelashevskiy  А сейчас вообще вот так почему-то...

**Comment by ilya7am** [comment]
Проблема появляется при появлении 6 знаков после запятой в котировке инструмента. Например, на фондовом рынке для тикера VTBR размер модального окна меняется и кнопки смещаются (видео). Стоит учесть при исправлении ошибки.
https://user-images.githubusercontent.com/88287882/183299697-1f0ebe1d-7495-4702-bb59-34f392ffe3a2.mp4

**Comment by Tattydes** [comment]
![Кривое форматирование #214](https://user-images.githubusercontent.com/116548833/200592144-d0ac0ff7-29db-4a7e-b6f9-1582947d6c41.png)


Предлагаю сделать информацию по левому краю и перенести значения сразу под лого. В таком случае влезут длинные строки и верстка не поедет

**Comment by PilgrimViis** [comment]
А ничего что у нас много лишнего места справа?

**Comment by Tattydes** [comment]
Ничего страшного, главное, что всё аккуратно выравнено по левому краю. 

Вообще это классическое решение, если строки наверняка поедут при адаптиве. У нас как раз так и происходит.
Пример похожего решения:
![680f613f36](https://user-images.githubusercontent.com/116548833/200639109-0ea30191-bbbe-405a-ab1d-229e7855861d.jpg)

**Comment by Tattydes** [comment]
У меня ещё родились варианты) напишите, что думаете и выберите вариант, который больше нравится

![#214 Кривое форматирование - 3](https://user-images.githubusercontent.com/116548833/201087735-3a7a8e05-218c-4fa9-9a5f-b0ce954071d8.png)

![#214 Кривое форматирование - 4](https://user-images.githubusercontent.com/116548833/201087751-e6992aef-952d-4e5a-b99f-fd0dade32233.png)

![#214 Кривое форматирование - 5](https://user-images.githubusercontent.com/116548833/201087766-7fadd96b-2d91-418a-9f8a-24d18a5c57fb.png)

![#214 Кривое форматирование - 6](https://user-images.githubusercontent.com/116548833/201087813-f3e8102c-b1bf-4238-b58f-367d17193f7c.png)

**Comment by PilgrimViis** [comment]
Давайте возьмем вариант №3. 
![image](https://user-images.githubusercontent.com/6408195/201600877-6b203ba3-b4fc-400e-a2c9-077e75999554.png)
