### ISSUE TITLE
[FEATURE] Хранить последний открытый инструмент и биржу

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#221]
### Опишите проблему, которую решает ваша фича

При открытии терминала грузится SBER:MOEX.

### Опишите предлагаемое вами решение

Хранить последний активный инструмент и биржу. Открывать их при загрузке.
Если ничего не сохранено - открывать SBER:MOEX.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Это дубликат https://github.com/alor-broker/Astras-Trading-UI/issues/222
