### ISSUE TITLE
[BUG] Загрузка страницы и хранилище переменных

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#222]
### Опишите баг

При первоначальной загрузке страницы грузится SBER:MOEX.
Если в инструментах выбрать зарубежную бумагу, а потом обновить страницу, то виджеты снова переключаются на SBER, но график пытается рисоваться по прошлой бумаге. После этого терминал становится неработоспособным.

https://user-images.githubusercontent.com/99450543/172658569-fb0a882a-4ce1-418b-ab40-e729717f7fab.mp4

### Воспроизведение

1. Открыть начальную страницу. Загружена биржа MOEX, инструмент SBER
2. В инструментах открыть зарубежную бумагу. Все виджеты переключились на нее.
3. Обновить терминал по F5.

### Среда.

Windows 10, Chrome Canary 104.0.5108.0

### Ожидаемое поведение

При обновлении страницы не использовать данные от прошлого инструмента.
либо
При обновлении страницы брать последнюю бумагу и открывать ее (описал в #221)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
По ошибке видимо эту задачу закрыли. Сбер это состояния приложения по умолчанию.  Надо подумать, хотим ли мы это менять.

**Comment by sbelashevskiy** [comment]
Нет, все правильно. Там была проблема "После этого терминал становится неработоспособным".
Да и вообще после перезагрузки страницы график либо мог весить приложение, либо в заголовке писал SBER, а данные показывал от инструмента, который был до рефреша
сейчас зависаний нет, график корректно рефрешится на sber. Согласно ожидаемомоу поведению: "При обновлении страницы не использовать данные от прошлого инструмента."
