### ISSUE TITLE
[FEATURE] ... Таймаут сеанса авторизации в настройках пользователя

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#228]
### Опишите проблему, которую решает ваша фича

в терминале не предусмотрена возможность указания длительности сеанса авторизации.

### Опишите предлагаемое вами решение

необходимо в настройках пользователя предусмотреть возможность указания длительности сеанса авторизации.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
При бездействии дольше, чем указано в настройке, показывать уведомление и выходить из терминала.
