### ISSUE TITLE
[FEATURE] Добавить дополнительные ссылки на стандартные операции в КК 

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#229]
### Опишите проблему, которую решает ваша фича

При нажатии на кнопку профиля в правом верхнем углу отсутствуют ссылки на кабинет клиента и основные операции по счету.

### Опишите предлагаемое вами решение

При нажатии на кнопку профиля в правом верхнем углу отсутствуют ссылки на кабинет клиента и основные операции по счету.
1. Ссылка на личный кабинет
2. Поручений по переводу средств между площадками, портфелями, 
3. Конвертацию валюты, 
4. Отключение или включение 100% обеспечения. 
5. Пополнение счета (справочно реквизиты или ссылку на страницу с реквизитами). Для моментального пополнения в шапке профиля можно предусмотреть кнопку пополнения счета через СБП с целью получения брокером доп.комиссии)

### Правила

- [x] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Предлагаю добавить в раздел "Ссылки". @profull-art скиньте пожалуйста конкретные ссылки

**Comment by profull-art** [comment]
При наведении на кнопку профиля в правом верхнем углу.
1. https://lk.alor.ru/main
2. https://lk.alor.ru/operations/money
3. Конверсия пока не работает.
4. https://lk.alor.ru/products/services

**Comment by PilgrimViis** [comment]
Если 5 ссылку не скинут, то №5 просто не делать.

**Comment by profull-art** [comment]
Ссылка 5. https://lk.alor.ru/operations/money/money_input
