### ISSUE TITLE
[FEATURE] Добавить ссылки на раздел категоризации в КК

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#231]
### Опишите проблему, которую решает ваша фича

При появлении выпадающей ошибки о запрете торговли тем или иным инструментом в связи с отсутствием пройденных тестов

### Опишите предлагаемое вами решение

В ошибке указать ссылку где можно пройти этот тест согласно категоризации

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
В сообщении об ошибке вроде УЖЕ присылается ссылка. Надо попробовать её распарсить и привератить в кликабельную.

**Comment by PilgrimViis** [comment]
https://lk.alor.ru/agreement/categorization вот сюда давать ссылку.
