### ISSUE TITLE
[FEATURE] Кнопка обратной связи.

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#233]
### Опишите проблему, которую решает ваша фича

В терминале нет возможности получения обратной связи или обращения в чат с поддержкой

### Опишите предлагаемое вами решение

Сделать кнопку "Чат с брокером" или "Техподдержка" которая перебрасывала бы пользователя в телеграм чат с брокером или в чат открытой линии в битрикс.

### Правила

- [x] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Предлагаю добавить её в меню, там где отчёты.

**Comment by profull-art** [comment]
Отдельная кнопка левее ярлыка профиля.

**Comment by PilgrimViis** [comment]
Обсудили с рабочей группой. Считаем что плохое место. Основная причина в том, что на мобильной версии поедет вёрстка. Решили добавить сюда. 
![image](https://user-images.githubusercontent.com/6408195/176621321-7f79666a-acda-4c91-9f33-0e79272aeac4.png)

**Comment by PilgrimViis** [comment]
https://t.me/+-9DW77xLniA0NDRi вот такая ссылка

**Comment by PilgrimViis** [comment]
Ссылку отправил в чат.

**Comment by profull-art** [comment]
Хорошо
