### ISSUE TITLE
[FEATURE] Вертикальный стакан

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#238]
### Опишите проблему, которую решает ваша фича

Стакан, который сейчас добавлен в Астрас, не всем понятен. 

### Опишите предлагаемое вами решение

Добавить вертикальный (классический ) стакан заявок. 
Можно по аналогии взять стакан из трейдингвьюв. 
![image](https://user-images.githubusercontent.com/105817664/173797275-c3e807a8-9427-4441-9b9f-1dfc839908b1.png)

### Опишите альтернативные решения, о которых вы думали

Данный стакан(из ТВ)  стоит подправить для более удобного восприятия. 
Объемы покупок и продаж с одной стороны (экономит место) 

![image](https://user-images.githubusercontent.com/105817664/173817784-3584ce7c-fcc0-45f0-a2ba-333a2f4b8e58.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Вынес №2 и №3 в отдельные задачи.
#303 и #304

**Comment by PilgrimViis** [comment]
Выбор рабочих объемов #277 это вот в этой задаче. В рамках этой задачи делать не надо.
