### ISSUE TITLE
[FEATURE] Выставление заявок в скальперский стакан мышью

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#239]
### Опишите проблему, которую решает ваша фича

Использовать кнопки для выставления заявок занимает больше времени чем  нажатие горячих клавишь или управление мышью. 

### Опишите предлагаемое вами решение

Я описывал ранее скальперский стакан.
Хотелось бы добавить управление мышью, для более быстрого выставления заявок. 
Мышь должна реагировать на область над которой она находится:

Для начала выбираем "рабочий" объем.

Курсор мыши в зоне продавцов, наведён на зону объема или цены: 
ЛКМ - войти по рынку ( курсор мышь в любой области офферов)
ПКМ - выставить лимитную заявку на продажу по цене на которой установлен курсор

Курсор мыши в зоне покупателей:
ЛКМ - выставить лимитную заявку по цене на которой наведен курсор
ПКМ - продать по рынку

### Правила

- [ ] Я согласен следовать правилам

**Comment by LinaRitchie** [comment]
Предлагаю добавить возможность опциональной настройки логики ЛКМ и ПКМ, как удобно пользователю.
Например, мне и, наверное, многим пользователям популярного привода CScalp, было бы удобно, чтобы ЛКМ означал покупку, а ПКМ - продажу, независимо от того, был ли клик совершен в bid или в ask.

**Comment by sbelashevskiy** [comment]
@LinaRitchie ,
эта задача уже реализована и закрыта - ваши комментарии в ней никто не увидит.
Актуальная задача уже есть https://github.com/alor-broker/Astras-Trading-UI/issues/825.
Можете в ней оставить свой комментарий
