### ISSUE TITLE
[FEATURE] Светлая тема терминала

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#241]
### Опишите проблему, которую решает ваша фича

В терминале нет возможности менять цветовую тему 

### Опишите предлагаемое вами решение

Возможность переключение цветовой темы в настройках профиля.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/176 дубликат
