### ISSUE TITLE
[FEATURE]  Валюта отражения по умолчанию

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#243]
### Опишите проблему, которую решает ваша фича

В текущих настройках валюта отражения доллар. 

### Опишите предлагаемое вами решение

В настройках профиля по умолчанию настроить валюту отражения в соответствии с инструментами или площадками

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Нужно сделать настройку в профиле, выбор валюты отображения по умолчанию. При этом при создании нового блоттера, должна подхватываться нужная валюта. Валюта у нас показывается большом количестве виджетов. Но тут речь идет только о блоттере.

**Comment by PilgrimViis** [comment]
По умолчанию для портфелей на ММВБ сделать рубли, а на СПБ сделать доллары США,
