### ISSUE TITLE
[FEATURE] Виджет "Все сделки"

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#244]
### Опишите проблему, которую решает ваша фича

В терминале не отражаются все биржевые сделки по инструментам.

### Опишите предлагаемое вами решение

Создать виджет для отражения всех сделок по всем инструментам с возможностью фильтра по инструменту

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Уже сделано https://github.com/alor-broker/Astras-Trading-UI/issues/223
