### ISSUE TITLE
[FEATURE] Добавить столбцы в виджет "Выбор инструмента"

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#245]
### Опишите проблему, которую решает ваша фича

Недостаточно информации в виджете 

### Опишите предлагаемое вами решение

Добавить столбцы: 
-Максимум, 
- минимум, 
- объем, 
- предыдущее закрытие, 
- можно шортить, 
- приобретать с плечом, 
- изменение стоимости за день, за неделю, за месяц, за 6 мес, за год

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
И ещё Добавить колонку "Сокращенное наименование бумаг" или просто "Имя" с возможностью сортировки по столбцу
