### ISSUE TITLE
[FEATURE] Готовые списки бумаг в виджете "Выбор инструмента"

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#248]
### Опишите проблему, которую решает ваша фича

В виджете "Выбор инструмента" нет готовых списков акций. Пользователю необходимо каждый список создавать самому.

### Опишите предлагаемое вами решение

Реализовать готовые наборы списка акций. "Тор 30" или "Голубые фишки" или "ТОП мосбиржи", "Топ-30 СПБ",

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@sbelashevskiy а ты подкрутил API вызовы для получения готовых списков в свою форму?

**Comment by sbelashevskiy** [comment]
Да. Чтобы список отображался он должен быть непустым.
![image](https://user-images.githubusercontent.com/29191749/174523398-ebec98e5-1a48-4e42-a79a-2851aa382984.png)

**Comment by PilgrimViis** [comment]
Сделано. Списки можно менять через hub.
