### ISSUE TITLE
[FEATURE] Пользовательские списки акций в виджете "Выбор инструмента"

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#249]
### Опишите проблему, которую решает ваша фича

Нет возможности сохранить свой список. К примеру акции российских компаний отдельно, акции спб отдельно, фьючерсы отдельно

### Опишите предлагаемое вами решение

Реализовать возможность сохранения  пользовательских списков инструментов. 
Настроил пользователь нужные акции - сохранил под своим названием. Количество списков можно не ограничивать. Отражение в виде выпадающего меню.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/224 Уже сделано
