### ISSUE TITLE
[FEATURE] Отражение сокращенных наименований в виджете "Выбор инструмента"

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#250]
### Опишите проблему, которую решает ваша фича

В виджете "Выбор инструмента" не отражаются сокращенные наименования бумаг, только тикеры. Не удобно пользователю постоянно помнить тикеры или сортировать бумаги по алфавиту.

### Опишите предлагаемое вами решение

Добавить колонку "Сокращенное наименование бумаг" с возможностью сортировки по столбцу

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
https://github.com/alor-broker/Astras-Trading-UI/issues/245 Считаю что это дубликат. Добавил туда комментарий с добавленией колонки с названием.
