### ISSUE TITLE
[FEATURE] В стакане по облигациям показывать доходность

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#260]
### Опишите проблему, которую решает ваша фича

Когда торгуешь облигациями тебе не нужна цена в %. Гораздо наглядней торговать доходности.

### Опишите предлагаемое вами решение

Сделать настройку переключения и показа стакана для облигаций либо в % цены, либо в % доходности.

### Правила

- [ ] Я согласен следовать правилам

**Comment by MorozovDen** [comment]
Лучше не делать "либо, либо", одновременно интересна и цена и доходность. Лучше как у Quik, если система видит, что этот инструмент облигация, то выводит стакан с доходностью. Край - добавление в настройках стакана флажок "показывать доходность"
![изображение](https://user-images.githubusercontent.com/105856884/174982628-1e123808-5d6d-44a6-a1d2-2fa0231f4997.png)

**Comment by PilgrimViis** [comment]
У нас дургой стакан. Ещё 2 колонки в эту таблицу не поместятся по нормальному.

**Comment by MorozovDen** [comment]
ок. Тогда как вариант - будем советовать два стакана открывать. один с ценой, другой с доходностью.
