### ISSUE TITLE
[FEATURE] Добавить в стакан над графиком объема показатели совокупного спроса и предложения

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#268]
### Опишите проблему, которую решает ваша фича

Необходимо для анализа - кого в данный момент больше на рынке, покупателей или продавцов, и определение возможного направления движения рыночных цен по этим показателям.

### Опишите предлагаемое вами решение

В ТрейдингВью это реализовано в конце стакана (в прилагаемом скриншоте), но я предложил бы вверху стакана, и в настройках предусмотреть возможность опционально включать или отключать отображение (на скриншоте, аналогично как по графику и таблице)

### Дополнительная информация

![изображение](https://user-images.githubusercontent.com/105856884/174821078-370ac1c7-2a00-4423-820d-5c16b93d22f2.png)
![изображение](https://user-images.githubusercontent.com/105856884/174821145-9f6e6105-e887-49f1-baf7-0b4486e1f73d.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Давайте сделаем. Только по умолчанию выключено! Включается в настройках.
Можно взять компонент с скальперсого стакана и его переиспользовать. Чтобы визуально было одинаково.
