### ISSUE TITLE
[FEATURE] Горячие клавиши в скальперском стакане

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#269]
### Опишите проблему, которую решает ваша фича

Для более быстрого управления заявками, предлагаю добавить "горячие" клавиши для управления торговлей. 
Либо по умолчанию, либо с возможностью настроек. 

### Опишите предлагаемое вами решение

Клавиши для торговли:
Общие на все стаканы:
Снять все лимитные заявки    ~ (тильда) 
Закрыть по рынку все позиции  ESC 
Центровка всех стаканов по спреду Space (пробел) 

Действующие только на 1 стакан, на который наведена мышь:

Выбрать рабочий объем   1,2,3,4  
Выставить лучшую заявку на продажу  W  // выставляется в спред, если спреда нет то выставляется лимитка сверху по лучшему офферу
Выставить лучшую заявку на покупку Q  // выставляется в спред, если спреда нет то выставляется лимитка сверху по лучшему аску
Снять лимитные заявки E 
Закрыть позицию по рынку R 
Переворот позиции по рынку T
Купить по рынку S
Продать по рынку A 
Установка стоплосс left shift
Условная заявка left ctrl 

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Всё это мы ещё раз посмотрим, когда будем реализовывать. Если не будет проблем, то постараемся сделать указанные хоткеи.

**Comment by agushasok** [comment]
по пунктам "снять все лимитные заявки" и "закрыть по рынку все позиции": это будет относиться к открытым стаканам, активному портфелю или ко всем позициям/заявкам у пользователя?

**Comment by uncrashable** [comment]
> по пунктам "снять все лимитные заявки" и "закрыть по рынку все позиции": это будет относиться к открытым стаканам, активному портфелю или ко всем позициям/заявкам у пользователя?
К открытым стаканам
