### ISSUE TITLE
[FEATURE] Выборки портфелей

### ISSUE THREAD

**Issue by OLGALEBs** [alor-broker/Astras-Trading-UI#270]
### Опишите проблему, которую решает ваша фича

Добавить возможность фильтровать текущий портфель по инструментам и выгружать выборку в excel
С суммированием по выборке в терминале
Будет давать аналитический срез портфеля по классам активов, диверсификации. 

### Опишите предлагаемое вами решение

Добавить фильтр в таблице Портфель. В выпадающем списке сделать доступными все инструменты, находящиеся в моменте в портфеле и классы инструментов.
Например, в портфеле 5 эмитентов ИЦБ, 3 евроблигации, 4 РЦБ. В выпадающем меню: ИЦБ, евробонды, РЦБ, 12 эмитентов. Можно быстро выбрать по классу актива, можно вручную поставить галочки по тем эмитентам, которые хочешь добавить в  выборку
При формировании выборку автоматическое суммирование:  строка оценки в руб., долл
Возможность экспорта в excel построенной выборки

### Опишите альтернативные решения, о которых вы думали

-

### Дополнительная информация

-

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Выгрузка у нас уже есть, а срезы уже реализованы в кабинете клиента. Мы в рамках отдельного виджета возможно повторим то что есть КК, но эту задачу думаю можно закрыть.
