### ISSUE TITLE
[FEATURE] Дневник трейдера и Заметки

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#273]
### Опишите проблему, которую решает ваша фича

Помогает решить проблемы с повторяющимися ошибками в торговле, дисциплинирует трейдера, отображает статистику торговли, систематизирует торговлю, убирает сумбур и спонтанность в торговле.  можно рассчитать результат по каждой сделке (не по FIFO), используют как начинающие трейдеры, так и опытные. Если лень вести дневник, значит лень зарабатывать))

### Опишите предлагаемое вами решение

Можно сделать отдельную таблицу и через виджеты (приложены скрины), которые описывают сделки, вносить в нее данные
![изображение](https://user-images.githubusercontent.com/105856884/175019072-18c4cc9c-4b62-4fd7-9d46-18d49cce1987.png)

![изображение](https://user-images.githubusercontent.com/105856884/175019569-271e1cc9-4b05-4e15-bf5a-a886472ad0db.png)

Так же интересен функционал Заметки - окно, на каждом графике или инструменте, чтобы нажал, открылось окно и там свои пометки можно сделать, например сильный уровень, или робот по такой цене стоял, и т.п.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Эту задачу руководство отклоняло уже 2 раза. Чтобы привести гитхаб в порядок, я её всё таки закрою, так как не вижу возможности что её согласуют
