### ISSUE TITLE
[FEATURE] Рабочий объем в новой заявке

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#277]
### Опишите проблему, которую решает ваша фича

Очень многие клиенты используют функцию рабочий объем заявки, чтобы сэкономить время и не вводить этот параметр. В текущей версии, при выводе новой заявки подставляется единица, предлагается в настройки стакана добавить возможность выбора этого значения, аналогично как в  Алор-Трейде (пустое, автоматическое из той строки стакана, по которому кликнули при вызове заявки, и фиксированное), и соответственно поле под ввод значения, которое будет фиксированным, причем по умолчанию поставить туда количество равное единице. Скрины Алор-Трейда прилагаю

### Опишите предлагаемое вами решение

![изображение](https://user-images.githubusercontent.com/105856884/175274887-8ede99cb-9af5-4717-ad9e-86015b4fac29.png)
![изображение](https://user-images.githubusercontent.com/105856884/175275024-35e819db-7084-4e5b-ba91-ac9c770053d0.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Возможно связана с задачей по объемам у скальперов. Надо обсудить в рабочей группе.

**Comment by PilgrimViis** [comment]
@MorozovDen #613  мы сделали вот так (ещё не опубликовано). Я думаю это решает ту проблему которую ты озвучил. Задачу закрою.

**Comment by MorozovDen** [comment]
а в модальном виджете заявки тоже добавятся эти кнопки быстрого объема? если нет, то все же задача актуальная

**Comment by PilgrimViis** [comment]
@sbelashevskiy в модалку можно эти кнопки тоже засунуть?

**Comment by sbelashevskiy** [comment]
А как в модалке настраивать объемы?

**Comment by sbelashevskiy** [comment]
Открытые вопросы:
1. Нужна ли настройка в виджете стакан "Использовать виджет заявок". Нужно ли пользователям при наличии виджета выставлении заявки открывать модалку?
2. Если виджет выставления заявки привязан к инструменту отличном от инструмента стакана, обновлять ли в нем цену
3. Нужны ли объемы в модалке если есть виджет выставления заявки с объемами, который реагирует на клики в стакане
