### ISSUE TITLE
[BUG] Самопроизвольное переключение табов в блоттере

### ISSUE THREAD

**Issue by Extred** [alor-broker/Astras-Trading-UI#280]
### Опишите баг

![astras_selfswitch](https://user-images.githubusercontent.com/3522038/175302812-2c845d71-72d9-41c4-b58a-1377e2c270d1.gif)
(на записи выше никаких действий и кликов пользователь не совершает)

### Воспроизведение

1. Открыть "блоттер"
2. Пощелкать табы (например, "стопы" и "заявки") несколько раз
3. Табы самопроизвольно начинают переключаться
4. Тормозит терминал целиком
5. Через некоторое время зависает совсем

### Среда.

Windows 11
Chrome v102

### Ожидаемое поведение

- Табы не переключаются самостоятельно
- Не тормозит терминал целиком

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@Extred проверь пожалуйста, проблема ещё актуальна?
