### ISSUE TITLE
[BUG] При переходе по ссылке терминала выводит ошибку.

### ISSUE THREAD

**Issue by profull-art** [alor-broker/Astras-Trading-UI#281]
### Опишите баг

При переходе по ссылке терминала https://astras.alor.ru/ вываливает ошибку и переадресовывается на страницу авторизации.

### Воспроизведение

Без ошибки

### Среда.

Windows chrome 

### Ожидаемое поведение

Без ошибки

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Это поведение по умолчанию. Ваш токен экспирировался, надо залогинится ещё раз. Время жизни 30 или 60 дней.
