### ISSUE TITLE
[FEATURE] Изменение цвета индикатора отмененной заявки 

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#289]
### Опишите проблему, которую решает ваша фича

Интуитивно понятное и наглядное отображение отмененной заявки.

### Опишите предлагаемое вами решение

Предлагается поменять в блоттере, в таблице заявок, в начале строки, индикацию отмененной заявки на серый индикатор (активные и исполненные остаются так же красными и зелеными, по продажам и покупкам соответственно)

### Дополнительная информация

![изображение](https://user-images.githubusercontent.com/105856884/176179176-063cda95-438b-4b7b-9578-58037db7e16d.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
То есть ставим условие. Если заявка (или стоп-заявка) отменена (статус cancelled), до показываем эту полоску серым цветом.
