### ISSUE TITLE
[FEATURE] Перенести возможность выбора Списка инструментов из настроек на основную таблицу Инструменты 

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#306]
### Опишите проблему, которую решает ваша фича

Из общения с пользователями такая информация - списки инструментов идея классная, но пользоваться ей не очень удобно, потому что приходится каждый раз заходить в настройки таблицы Инструменты, менять список и дополнительно сохранять настройки.

### Опишите предлагаемое вами решение

Предлагается в виджете Инструменты перенести из настроек строчку выбора Списка инструментов (первый скрин) на основную таблицу виджета (второй скрин). В настройках останется только выбор колонок таблицы и создание своего списка предпочтения по Спискам инструментов. Поиск и добавление инструментов (третий скрин) сделать все в одну строчку, чтобы минимизировать занимаемое место.

### Дополнительная информация

![изображение](https://user-images.githubusercontent.com/105856884/177290248-24509d73-09d2-40be-92c5-4baddde1d5a2.png)
![изображение](https://user-images.githubusercontent.com/105856884/177290354-e6abcddf-0eb2-4353-ab75-7ad4e788adcf.png)
![изображение](https://user-images.githubusercontent.com/105856884/177303652-afbb5bfc-c2bb-4ea6-aa06-76f78b461578.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Давайте сделаем так. Добавим справа от поля поиска иконку для быстрого выбора группы инструмента. При клике на нее должен появится дропдаун с выбором существующих списков. Таким образом переключение между списками станет быстрее и станет чуть удобней добавлять новые. При этом это не сожрен много места, как если бы мы переносили целую строчку как предлагешь ты.

![image](https://user-images.githubusercontent.com/6408195/189513811-d18cc72c-b50a-47e1-a0fa-381a1e77351b.png)
