### ISSUE TITLE
[BUG] Не работают кнопки перехода в таблице новости

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#309]
### Опишите баг

В правой части виджета новости есть кнопки "вверх" "вниз", предполагаю, что они сделаны для того, чтобы через них можно было пролистывать новость по одной, по факту при нажатии на них ничего не происходит.  По факту сейчас просмотреть новость, которая не отображается в таблице можно только мышкой через полосу прокрутки, что не совсем удобно.

### Воспроизведение

Открыть виджет "новости" и нажать на кнопки вверх/вниз в правой верхней части виджета

### Среда.

windows 7 Проф, Firefox

### Ожидаемое поведение

Сделать, чтобы при нажатии на эти кнопки была возможность пролистывать новость  по одной. Так же стоит их запаралелить с кнопками курсора на клавиатуре (вверх/вниз), чтобы пролистывать новости можно было и клавиатурой. По факту сейчас просмотреть новость, которая не отображается в таблице можно только мышкой через полосу прокрутки, что не совсем удобно.

### Скриншоты

![изображение](https://user-images.githubusercontent.com/105856884/177515004-d5f767ea-777e-4922-adc4-8076d33aba5b.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Ни в firefox ни в chrome таких кнопок нет. Предполагаю, что это какое-то расширение у вас установлено. Прикладываю скрин из фаерфокса.
![image](https://user-images.githubusercontent.com/6408195/177733281-4823b47a-19e7-4ae6-afbb-fb9bbbf81a37.png)

**Comment by MorozovDen** [comment]
![изображение](https://user-images.githubusercontent.com/105856884/177734423-28de423f-e691-40bc-b4e8-f351a46e20f4.png)

![изображение](https://user-images.githubusercontent.com/105856884/177734746-db18b0ce-e5cf-4289-8cd2-b350591f4b54.png)

Тоже фаерфокс. вроде ничего из расширений, что это делает, не установлено. Попробовал на Edge, там действительно нет таких кнопок. Но проблема перелистывания новости по одной остается. Может тогда баг закрыть, а в Feature request написать предложение по переходу в новостях через курсор на клавиатуре?
