### ISSUE TITLE
[BUG] Устранить проблему высвечивания в стакане отсутствующих заявок

### ISSUE THREAD

**Issue by MisterTINWIS** [alor-broker/Astras-Trading-UI#312]
### Опишите баг

Поставил 1000 лотов на покупку в одну акцию, 5000 в другую.
Так совпало, что цена была одна и та же.
Стакан начал отображать, как будто стоит 6000 акций. 

### Воспроизведение

Поставить заявки на одну цену в разные акции

### Среда.

Mac OS, последней версии
Браузер - Хром последней версии

### Ожидаемое поведение

Все понеятно из описания.)

### Скриншоты

<img width="693" alt="image" src="https://user-images.githubusercontent.com/108877586/177775306-254088d8-9f92-4ea6-bf63-c071c9d6b32b.png">

### Правила

- [x] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Да, есть такая проблема - заявки ищутся для текущего портфеля = не фильтра по инструментам.
Будет исправлено вместе с https://github.com/alor-broker/Astras-Trading-UI/issues/238
