### ISSUE TITLE
[Tests] Покрыть тестами горячие клавиши и сервис выставления заявок

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#324]
Подумал что после последних наших правок, имеет смысл покрыть тестами и это. Т.к. там появилась какая-то логика типо "перевернуть позицию" или "закрыть все позиции".

**Comment by sbelashevskiy** [comment]
Рамках данной задачи будуьт добавлены тесты для базового функционала выставления заявок и выставления заявок через диалог.

Покрытие тестами хоткеев будет выполнено после рефакторинга https://github.com/alor-broker/Astras-Trading-UI/issues/355
