### ISSUE TITLE
[BUG] При выставлении стоп-заявки информация в вертикальный стакан не добавляется

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#332]
### Опишите баг

**Precondition:**
Открыта страница авторизированного пользователя [https://astras-dev.alor.ru/dashboard](url). Выставлены виджеты: Инструменты, График, Вертикальный стакан. Включено слежение на всех виджетах (кнопка замок).

Вне зависимости от включенного Блоттера не добавляется заявка в вертикальный стакан.

### Воспроизведение

1. Выбрать срочный порфтель 7500GHC.
2. В панели "Выбор инструмента" указать SI-9.22.
3. В правом левом углу нажать на кнопку "Выставить заявку".
4. В модальном окне перейти во вкладку "Условная".
5. Указать кол-во лотов, равное 1, сигнальную цену - "58250".
6. Нажать "Купить".

### Среда.

Windows 10

### Ожидаемое поведение

- Уведомление "Заявка выставлена".
- Заявка отображена в соответствующем блотере во вкладке "Стопы".
- В вертикальном стакане появилась только что выставленная заявка.

### Скриншоты

https://user-images.githubusercontent.com/88287882/179676040-effc0677-4270-4c0f-869b-d513a1f4af46.mp4

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Так и задумано. Считаем, что стоп-заявки подсвечивать не нужно, чтобы не вводить в заблуждение.
