### ISSUE TITLE
[BUG] Не отображается подсказка в виджете «Вертикальная заявка» 

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#333]
### Опишите баг

При нажатии на подсказку в виджете «Вертикальная заявка» появляется ошибка: Http failure response for https://apidev.alor.ru/astras/helptopics/vertical-order-book: 500 Internal Server Error  

### Воспроизведение

1. Выбрать срочный порфтель 7500GHC.
2. В шапке виджета "Вертикальный стакан" нажать на знак вопроса.
3. Прочитать подсказку о виджете.

### Среда.

Любая

### Ожидаемое поведение

Корректно отображается информация о виджете, возможностях и описание основных действий.

### Скриншоты

![Подсказка](https://user-images.githubusercontent.com/88287882/179677262-2364f234-be78-4e7c-b925-4edcfabcb089.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@uncrashable обещал сделать.
