### ISSUE TITLE
[BUG]  "Горячие" клавиши для управления торговлей в стакане

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#337]
### Опишите баг

**Precondition:**
Открыта страница авторизированного пользователя [https://astras-dev.alor.ru/dashboard](url). Выставлены виджеты: Инструменты, График, Блоттер, Вертикальный стакан. Включено слежение на всех виджетах (кнопка замок).

Не работают клавиши быстрой торговли (W/Q, E, R, T, S, A, left shift, left ctrl), применяемые в скальперском стакане.

### Воспроизведение

1. Выбрать срочный порфтель 7500GHC.
2. В панели "Выбор инструмента" указать SI-9.22.
3. Проверить горячие клавиши W/Q, E, R, T, S, A, left shift, left ctrl.

### Среда.

Любая

### Ожидаемое поведение

- Выставляется лучшая заявка на продажу и покупку (W/Q).
- Снимаются лимитные заявки (Е).
- Закрываются позиции по рынку (R).
- Переворачиваются позиции по рынку (Т).
- Происходит покупка по рынку (S).
- Происходит продажа по рынку (А).
- Устанавливается стоплосс (left shift).
- Выставляется усовная заявка (left ctrl)

### Дополнительная информация

 Возможно горячих клавиш слишком много, нужна памятка (попап) трейдеру или следует ограничить их число до наиболее важных: W/Q и T.

### Правила

- [ ] Я согласен следовать правилам

**Comment by agushasok** [comment]
горячие клавиши работают. Возможно, проблема в том, что мышь не была наведена на стакан
