### ISSUE TITLE
[FEATURE] Валидация полей режима торгов

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#350]
### Опишите проблему, которую решает ваша фича

При выборе режима торгов по выбранному инструменту нет валидации полей. Можно указать любой режим, даже которого не существует.  Пользователю не появится уведомления о некорректности ввода данных.

### Опишите предлагаемое вами решение

Для удобства можно предложить настраивать регистрозависимые поля на автоматическую конвертацию в верхний регистр или предложить выпадающий список с доступными вариантами режимов торгов. Это облегчит выбор и избавит от возможных ошибок при торговле.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Необходимо реализовать следующее. Подтягивать с бекенда все доступные режимы торгов. И делать поиск как в этой задаче https://github.com/alor-broker/Astras-Trading-UI/issues/587

**Comment by sbelashevskiy** [comment]
@PilgrimViis я не вижу какого-либо API на нашей стороне, чтобы получить список всех возможных режимов для инструмента. Что ты имел ввиду?

**Comment by PilgrimViis** [comment]
Насколько я помню, есть непубличный вызов. Надо спросить у бекендеров.

**Comment by PilgrimViis** [comment]
@sbelashevskiy на беке сделано. Вернись пожалуйста и чекни.
