### ISSUE TITLE
[BUG] Некорректное отображение содержимого скачанного файла в Excel

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#351]
### Опишите баг

**Precondition:**
Открыта страница авторизированного пользователя [https://astras-dev.alor.ru/dashboard](http:) Выставлены виджеты: Инструменты, График, Блоттер, Стакан, Вертикальный стакан, Инфо. Включено слежение на всех виджетах (кнопка замок). В порфтеле есть неисполненные биржевые и условные заявки. 

При скачивании и просмотре данных по заявкам в Эксель возникают проблемы с кодировкой.

### Воспроизведение

1. Перейти на виджет "Блоттер".
2. Перейти на одну из вкладок блоттера: Заявки, Стоп, Позиции, Сделки.
3. Нажать на кнопку "Сохранить в файл".
4. Открыть скачанный файл в Эксель.

### Среда.

Любая

### Ожидаемое поведение

- Файл с данными выбранной вкладки успешно загружается пользователю.
- Понятно отображена информация внутри файла.

### Скриншоты

![Кодировка](https://user-images.githubusercontent.com/88287882/179987239-b2b7c241-e76e-4cc5-9868-628fa8563aa2.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
В общем я понимаю, что это проблема Екселя из-за кодировки, а не проблема нашего приложения. Но делать нечего, excel это де факто стандарт. Надо придумать work around.

**Comment by sbelashevskiy** [comment]
Пофиксил отображение кириллицы и дефолтный разделитель значений - excel по дефолту он пытается читать содержимое как UTF-8, а в качестве разделителя использует ;
в то время как другие редакторые типа libreOffice всегда csv открывают с мастера конфигурации и позволяют поменять.

Но я рекомендовал бы вообще сменить формат на xlsx. Сsv не содержит никаких модификаторов для указания формата значения. Excel пытается угадать и без явного импорта данных периодически косячит. Например сейчас значение 1.1944 exel отображает как 1 января 1944. Т.е. в любом случае пользователям придется совершать дополнительные действия, чтобы убедиться, что excel все значения распознал корректно. C csv невозможно это гарантировать
