### ISSUE TITLE
[BUG] При написании биржи через нижний регистр (moex) в настройках графика появляется ошибка

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#352]
### Опишите баг

**Precondition:**
Открыта страница авторизированного пользователя [https://astras-dev.alor.ru/dashboard](http:) Выставлены виджеты: Инструменты, График, Блоттер, Стакан, Вертикальный стакан, Инфо. Включено слежение на всех виджетах (кнопка замок). 

При написании биржи строчными буквами график перестает показывать информацию об инструменте и возникает ошибка «Http failure response. 500 Internal Server Error».

### Воспроизведение

1. Нажать на значок шестерёнки в виджете «График».
2. Указать в поле Биржа значение «moex» (строчные буквы).
3. Закрыть панель "Настройки".

### Среда.

Любая

### Ожидаемое поведение

Один из возможных вариантов:
- Предупреждение: «Введите верное название биржи»;
- Автоматическая конвертация в верхний регистр;
- Выпадающий список с биржами;
- Неактивная кнопка "Сохранить".

### Скриншоты

![Регистр биржи (1)](https://user-images.githubusercontent.com/88287882/179988128-734050c2-3701-46ac-8905-f6d5fae44650.jpg)

### Дополнительная информация

Такая же ситуация и для SPBX. Ситуация дублируется и для виджета "Стакан".

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Сделать выпадающее окно во всех виджетах с выбором биржи из 2 пунктов. SPBX and MOEX
