### ISSUE TITLE
[BUG] Небольшие опечатки в подсказках

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#353]
### Опишите баг

В разделе «Справка» для некоторых виджетов присутствуют небольшие опечатки.

### Воспроизведение

1. Нажать на значок "Справка" для виджетов Блоттер, График и Стакан
2. Прочитать содержимое каждого из них.

### Среда.

Любая

### Ожидаемое поведение

Текст не содержит опечатки.

### Скриншоты

![Справка Блоттер (1)](https://user-images.githubusercontent.com/88287882/179991456-ab955d5a-2565-4f9e-b294-d3e915947336.png)
![Справка  Блоттер (1)](https://user-images.githubusercontent.com/88287882/179991584-1b295012-5867-4dde-a772-ae60634153a5.png)
![Справка График (1)](https://user-images.githubusercontent.com/88287882/179991476-c9ac6c80-faa1-4aa7-ae35-6b5d7308d919.png)
![Справка Стакан (1)](https://user-images.githubusercontent.com/88287882/179991489-20c7a130-4239-43a6-a886-ebf2d481026f.png)
![Подсказки  Опечатка](https://user-images.githubusercontent.com/88287882/179991599-8e2e640b-010a-4a98-b372-477dd93bddcf.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Исправили.
