### ISSUE TITLE
[FEATURE] Перетаскивание инструмента из панели "Выбор инструмента" 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#358]
### Опишите проблему, которую решает ваша фича

При необходимости выбора инструмента, в стакане PRO поиск инструмента отсутствует или затратный по времени  

### Опишите предлагаемое вами решение

https://user-images.githubusercontent.com/105817664/180859690-ed2e33c0-ae89-4d43-9b10-b42f1a787604.mp4

Предлагаю добавить возможность перетягивание инструмента из панели "Выбор инструмента"  на **стакан** и на **график**

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я думаю это ненужная фича. Переход на новый инструмент это буквально один клик. Скоро добавим возможно прявязки разных виджетов к разным потокам и даже если у тебя открыто 5 стаканов это будет быстро.
