### ISSUE TITLE
[FEATURE] Автоматическое расположение виджетов на одном экране

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#362]
### Опишите проблему, которую решает ваша фича

Количество виджетов растет. При добавлении виджета, размер остальных изменяется, чтобы новый "влез" на экран.
Таким образом, если какой-то виджет не нужен постоянно на рабочей области, то нельзя его открыть и переместить вправо или вниз за границы экрана, чтобы возвращаться к нему через горизонтальный-вертикальный скролл. 

### Опишите предлагаемое вами решение

Реализовать (по возможности) опцию отключения автоматического расположения всех виджетов на одном экране.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
В общем подумали и обсудили. Не видим больших проблем, чтобы просто закрывать ненужные виджеты. Плюс у нас скоро появится сохранение и загрузка дашборда. С её помощью можно будет быстро закрывать ненужное и потом в пару кликов возвращаться к старому. Поэтому задачу закрываю.
