### ISSUE TITLE
[FEATURE] Панель кластеров и сделок в стакане PRO [1] [2]

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#363]
### Опишите проблему, которую решает ваша фича

Стакан PRO в основном  нужен для скальпинга и интрадея, для более объективной картины происходящего на рынке в стакан можно добавить пару панелей. 

### Опишите предлагаемое вами решение

1. Добавить в стакан панель сделок. На скриншоте сделки выделены кружками. Можно квадратиками сделать или просто цифрами. Эти данные сейчас в Астрас отображаются в виджете "Все сделки". На скриншоте - по какой цене прошла сделка возле того ценового уровня и отображается этот объем.  Если сделка прошла на покупку то цвет кружка или квадратика должен быть одного цвета (лучше зеленый(на скриншоте он синий)) , если прошла продажа, то красный.  Здесь панель сделок очень большая достаточно будет места шириной как панель кластеров на скриншоте. 
2. Добавить панель кластеров , где фиксируется общий объем сделок по конкретной цене
На скриншоте сейчас на покупку выставлена лимитная заявка на 531 лот по цене 5500. Если этому покупателю продадут 100 лотов, то в панели сделок появится кружок/квадратик 100 и в панели кластеров отобразиться 5300 (сейчас там 5200).
Панель кластеров отображается по таймфрейму. т.е. можно выставить что бы она была например  5 минутная , часовая или дневная. 
В идеале, постоянно видим  1 панель кластеров, с возможностью разворачивания до  хотя бы 5ти панелей.   2ым кликом мыши по панели
Снизу в панели кластеров отображать суммарный объем в кластере ( в столбике) 

з.ы. крайнюю правую панель, где отображаются наши выставленные лимитки можно сильно уменьшить. 

![image](https://user-images.githubusercontent.com/105817664/181619813-c9898b0e-de60-41f6-9f3e-d6c689a7c8bf.png)

![image](https://user-images.githubusercontent.com/105817664/181623378-c341868d-c66e-48b1-b7e4-a0d87cf68af5.png)

![image](https://user-images.githubusercontent.com/105817664/181626377-97f5de7d-e63b-47e9-81b0-ca981b97cc90.png)

![image](https://user-images.githubusercontent.com/105817664/181632878-2baccad2-7f31-445f-9c21-e66c17f09a1a.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Панель кластеров будет реализована отдельно https://github.com/alor-broker/Astras-Trading-UI/issues/821
