### ISSUE TITLE
[BUG] Не прогружается информация по портфелям, при выставлении заявок

### ISSUE THREAD

**Issue by zlobinm** [alor-broker/Astras-Trading-UI#369]
### Опишите баг

В окне "Выставить заявку" должны отображаться данные для полей:
- Стоимость
- К покупке
- Комиссия
- К продаже

По факту: поля пустые.

### Воспроизведение

Авторизация выполнена по логину (номер договора).

Проблема была связана с инструментом EAR (SPBX):

Где:
- Виджет "Стакан"
- клик ЛКМ по котировке

### Среда.

- Браузер Google Chrome
- Браузер Microsoft Edge

### Ожидаемое поведение

Поля:
- Стоимость
- К покупке
- Комиссия
- К продаже

должны быть не пустыми.

### Скриншоты

![photo_2022-08-05_09-10-13](https://user-images.githubusercontent.com/104907168/183012985-31116cf4-5ada-4aaa-b729-90ca777e4c97.jpg)
![photo_2022-08-05_09-10-39](https://user-images.githubusercontent.com/104907168/183013009-adba8bd2-f800-443d-bfbb-04cbd998bea0.jpg)
![photo_2022-08-05_09-10-45](https://user-images.githubusercontent.com/104907168/183013016-8d447ef7-0c3a-4871-ab26-a5ab808741e2.jpg)

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Исправлено на backend.
Публикации не требуется
