### ISSUE TITLE
[BUG] Справка виджета «Все сделки» дублируется со справкой в «Инфо»

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#370]
### Опишите баг

**Precondition:**
Открыта страница авторизированного пользователя [https://astras-dev.alor.ru](http:) Выставлены виджеты: Инструменты, График, Блоттер, Инфо, Все сделки.

### Воспроизведение

1. Нажать на справку (знак вопроса) в виджете "Инфо".
2. Прочитать текст.
3. Нажать на справку (знак вопроса) в виджете "Все сделки".
4. Сравнить текст с предыдущим.

### Среда.

Любая

### Ожидаемое поведение

Текст в каждом виджете уникален и не повторяется.

### Скриншоты

https://user-images.githubusercontent.com/88287882/183299484-f09ceaf9-4be9-47a2-8ea0-935f47f0ddf7.mp4

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
исправлено в https://github.com/alor-broker/Astras-Trading-UI/pull/354
