### ISSUE TITLE
[BUG] Лишняя строка в выпадающем списке таймфреймов

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#374]
### Опишите баг

**Precondition:**
Открыта страница авторизированного пользователя [https://astras-dev.alor.ru](http:) Выставлен виджет "График".

В настройках Графика в выпадающем списке таймфреймов после M (месяц) - лишняя строка.  

### Воспроизведение

1. Перейти в настройки виджета "График" (значок шестеренки)
2. В поле "Таймфрейм" развернуть выпадающий список.
3. Проверить все строчки с таймфреймами.

### Среда.

Любая

### Ожидаемое поведение

Представлены значения: 1m, 5m, 15m, H, 4H, D, M. Нет лишних, повторяющихся или пустых строк.

### Скриншоты

![Лишняя строчка](https://user-images.githubusercontent.com/88287882/183300709-97d333c0-5169-489a-9e90-1c219413659a.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Это не лишняя строка. Это заполнитель пространства. См. примеры https://ng.ant.design/components/select/en
![image](https://user-images.githubusercontent.com/29191749/183349594-8eafd298-47a6-492e-a569-0252c6f1010e.png)
![image](https://user-images.githubusercontent.com/29191749/183349620-19e94622-139c-47f7-9255-acfd967dea8d.png)
![image](https://user-images.githubusercontent.com/29191749/183349640-8b9468e8-0cc3-4b47-8dc4-71e5c230944f.png)
![image](https://user-images.githubusercontent.com/29191749/183349660-0c270456-8be7-4cb5-8f5a-68386d71650d.png)

**Comment by PilgrimViis** [comment]
Понятно. Тогда это не баг, а на стороне либы проблема.
