### ISSUE TITLE
[BUG] Нет возможности изменять ширину столбцов, в таблицах.

### ISSUE THREAD

**Issue by PullPlus** [alor-broker/Astras-Trading-UI#380]
### Опишите баг

Нет возможности изменять ширину столбцов, в таблицах.

### Воспроизведение

1. Авторизоваться в терминале.
2. Создать/выбрать виджет с табличной частью.
3. Попробовать изменить ширину столбца.

### Среда.

Основные поддерживаемые платформы.

### Ожидаемое поведение

Возможность изменения ширины столбцов. Хранение значений в px, а не в %. Во избежание масштабирования при изменении размеров страницы.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Дубликат #97 и вообще это не баг же. Это новый функционал, значит фича.
