### ISSUE TITLE
[BUG] Все инструменты. Сохранение настроек

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#388]
### Опишите баг

После сохранения настроек, данные перестают отображаться и требуется обновление страницы

### Воспроизведение

Uploading Сохранение_настроек.mp4…

### Среда.

windows 10, chrome 104.0.5112.81

### Ожидаемое поведение

После сохранения настроек, данные не исчезают

### Правила

- [ ] Я согласен следовать правилам

**Comment by agushasok** [comment]
Исправлено в рамках #396
