### ISSUE TITLE
[FEATURE] TradingView, смена инструмента

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#394]
### Опишите проблему, которую решает ваша фича

При выборе инструмента в виджете "Тех.Анализ" (например, ручным вводом) - на графике инструмент меняется, но в целом активный инструмент остается прошлый, поэтому и во всех привязанных виджетах ничего не меняется.

https://user-images.githubusercontent.com/99450543/184623861-51ce7ee7-c470-4a9c-b8b0-90f0d7676e45.mp4

### Опишите предлагаемое вами решение

При выборе инструмента в TV, нужно чтобы этот инструмент становился активным и менялся во всех привязанных виджетах.

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Возможно менять инструмент через график  с использованием хоткеев не предусмотрена. Данная возможность будет отключена

**Comment by dzeron13** [comment]
Эх, жалко. Так-то удобная штука. Смену ТФ с хоткеев только не урежьте - к ним вопросов нет)

**Comment by PilgrimViis** [comment]
@dzeron13 а можете создать предложение фичи с описанием того как оно там работает? Мы может реализуем, только уже через наш выбор инструмента.

**Comment by dzeron13** [comment]
> @dzeron13 а можете создать предложение фичи с описанием того как оно там работает? Мы может реализуем, только уже через наш выбор инструмента.

Завел:
https://github.com/alor-broker/Astras-Trading-UI/issues/417
