### ISSUE TITLE
[BUG] Блоттер. Рыночные заявки с неверными ценами

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#404]
### Опишите баг

В блоттере заявки, совершенные по рыночной цене, отображаются со странными ценами. Причем на покупку - одна цена, на продажу - другая, в другом инструменте аналогично две повторяющиеся цены, но далекие от реальности. Лимитные заявки отображаются корректно.
![image](https://user-images.githubusercontent.com/99450543/184922261-228f06f8-fa35-434d-a274-69dce8715096.png)

### Воспроизведение

Совершить покупку по рыночной цене

### Среда.

win 10, chrome 104.0.5112.81

### Ожидаемое поведение

Отображение реальной цены, по которой совершена заявка

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Я разобрался в чем дело. Для рыночных заявок в цене указывается верхий и нижний лимит на бекенде. Мы подумали и решили, что будем скрывать для рыночных заявок поля объема и цены на фронте.
@sbelashevskiy сделай пожалуйста, чтобы для всех рыночных заявок, вместо объема и цены показывалась пустая строчка.

**Comment by dzeron13** [comment]
Т.е. на вкладке "Заявки" не будет видно по какой цене исполнилась заявка, только в "Сделках"? А почему нельзя брать ту же цену?

**Comment by PilgrimViis** [comment]
> Т.е. на вкладке "Заявки" не будет видно по какой цене исполнилась заявка, только в "Сделках"? А почему нельзя брать ту же цену?

Потому что цена в заявке это не то же самое что цена в сделке. Вот допустим вы выставляете лимитку на покупку по 100. В Стакане сейчас есть только по 90 и ваша заявка по 90 удовлетворяется. Но саму то заявку вы вытаставили по 100. Поэтому в том поле надо писать 100. Для рыночных логика похожая, цены её выставления нет, поэтому этого поля быть не должно. Можно было бы сделать что-то типо "Средняя цена удовлетворения данной заявки", но тут нам нужны доработки на бекенде и я сильно сомневаюсь что их сделают в разумное время, скорее всего в следующем году.

**Comment by dzeron13** [comment]
Всё, понял (пусть не сразу) о чем идет речь) Отображение рыночных заявок во вкладке "Заявок" - и без того уже избыточно. Вижу, что и объем тоже убрали - отлично. Тогда может еще добавить строчку в справку, чтобы народ не пугался пустым значениям?
