### ISSUE TITLE
[FEATURE] Горячие клавиши на покупку из АСК\ продажу из БИД

### ISSUE THREAD

**Issue by nnnavi04** [alor-broker/Astras-Trading-UI#407]
### Опишите проблему, которую решает ваша фича

+ 100 при активном скальпинге 

### Опишите предлагаемое вами решение

Сейчас в стакане ПРО есть горячие клавиши на выставление заявок на покупку по лучшей цене из БИД\ продажу по лучшей цене из АСК.
При активном скальпинге было удобно иметь быстрые клавиши на покупку по лучшей цене из АСК и продажу по БИД

### Правила

- [ ] Я согласен следовать правилам

**Comment by uncrashable** [comment]
Вы имеете ввиду рыночные заявки ?   
S и A выполняют эту функцию.

**Comment by PilgrimViis** [comment]
Похоже правда то о чем вы говорите делает S и A... Поэтому закраю эту задачу пока. Если мы вас неправильно поняли, пожалуйста распишите подробней и я открою заного.

**Comment by nnnavi04** [comment]
![image](https://user-images.githubusercontent.com/107504167/190927168-309127ec-02ca-42fb-8c53-1fbf63e45134.png)

смотрите на примере приложенного скрина стакана ПРО.
выставляя рыночную заявку на покупку 10 000 бумаг  я тем самым выкупаю все, что сейчас доступно в стакане, т.е. 20 ордеров по 4.84, а также 2000 ордеров по 4.99.
Ну и в придачу забираю остальные 7980 ордеров, которые найдутся по рыночной цене.
Таким образом, моя средняя позиция получится по цене выше 4.99 точно.
Предложение заключается в том, что бы выставить лимитный ордер по лучшей цене, доступной в Аске, т.е. 10 000 бумаг за 4.84

**Comment by PilgrimViis** [comment]
Спасибо за пояснение. Задачу открыл снова. Думаю сделаем.
