### ISSUE TITLE
[BUG] не работаю горячие клавиши в ПРО

### ISSUE THREAD

**Issue by nnnavi04** [alor-broker/Astras-Trading-UI#408]
### Опишите баг

Не работают горячиеклавиши в стакане ПРО (клавиши отмены активных заявок, закрытия по рынку

### Воспроизведение

1. навести курсор на стакан ПРО
2. нажать горячую клавишу

### Среда.

- win 10
- chrome\edge последние версии

### Ожидаемое поведение

рабочие клавиши

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@nnnavi04, в скальпеском стакане по-умолчанию горячие клавиши выключены - раз мы имеем дело с финансовыми операциями пользователь должен четко понимать, что заявки буду выставляться без потверждения. Включение этой опции - это потверждение, что пользователь понимает это:
![image](https://user-images.githubusercontent.com/29191749/185300364-85f9e49b-1058-4145-9520-5fbfbb37b42e.png)

Вы включили горячие клавиши?

**Comment by PilgrimViis** [comment]
@nnnavi04 Ваша проблема с горячими клавишами разрешилась после включения галочки?

**Comment by nnnavi04** [comment]
Клавиши были включены. Работала клавиша покупки. Однако не работали клавиши отмены активных заявок, закрытия по рынку

**Comment by PilgrimViis** [comment]
@nnnavi04 ни у разработчиков, ни у тестера не получилось воспроизвести ситуацию. Мы либо это уже исправили вместе с другими фиксами, либо есть какая-то дополнительная информация. Вы можете подтвердить что ситуация стабильно воспроизводится сейчас?

**Comment by dzeron13** [comment]
Имею аналогичную проблему. Опция в настройках включена
https://user-images.githubusercontent.com/99450543/190101315-c3669d4c-ef21-45d1-b797-8dc193775fba.mp4

**Comment by sbelashevskiy** [comment]
@dzeron13 Вы курсор держите на заголовке - так не работает, курсор должен быть на области контента виджета

**Comment by dzeron13** [comment]
> @dzeron13 Вы курсор держите на заголовке - так не работает, курсор должен быть на области контента виджета
Нет, реакции нет в любом месте виджета:

https://user-images.githubusercontent.com/99450543/191190016-4c7219b2-1ea7-46a7-a6c0-a2f9e0f9ace7.mp4

**Comment by sbelashevskiy** [comment]
Да, почему-то то срабатывает, то нет. Будем разбираться

**Comment by sbelashevskiy** [comment]
Для вопроизведения этого бага не достаточно выполнить описанные шаги.
Баг проявляется исключительно после клика по табу в каком-либо виджете (фокус смещается на таб и события нажатия клавиш исходят от таба, а не от документа).
Например, нужно переключить табы в виджете "Блоттер".

**Comment by sbelashevskiy** [comment]
fixed
