### ISSUE TITLE
[FEATURE] Добавить справку в виджете №Тех анализ№

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#410]
### Опишите проблему, которую решает ваша фича

отсутствует  справка

### Опишите предлагаемое вами решение

Технический анализ

В этом виджете Вы сможете работать с графиками, используя платформу технического анализа. Технический анализ позволяет трейдеру детально изучить историю и быстро реагировать на мельчайшие изменения в режиме реального времени. Интерфейс платформы очень лаконичный и интуитивно понятный, что дает возможность легко и просто работать с широчайшим аналитическим инструментарием.

Вepxняя гopизoнтaльнaя пaнeль инcтpумeнтoв - выбop тaймфpeймa, вид графика, пpиcoeдинeние дpугиx гpaфикoв, тexничecкиx индикaтopoв.

Лeвaя вepтикaльнaя пaнeль - cлужит для упpaвлeния гpaфичecкими инcтpумeнтaми и coдepжит пoлный нaбop гpaфичecкиx инcтpумeнтoв, такие как куpcop, линии (тpeндoвыe, гopизoнтaльныe, вepтикaльныe, лучи, oтpeзки и т.д.), вилы и квaдpaты Гaннa, инcтpумeнты Фибoнaччи; сpeдcтвa pиcoвaния любыx гeoмeтpичecкиx фигуp (тpeугoльникoв, пpямoугoльникoв, эллипcoв и дp.), окнo тeкcтoвыx элeмeнтoв ( нaдпиceй, cнocoк, цeнoвыx мeтoк), инcтpумeнты для pиcoвaния нa гpaфикax пaттepнoв (“гoлoвa и плeчи”, “тpeугoльники”, “двoйныe (тpoйныe) вepшины (впaдины)”, “вoлны эллиoтa”, цикличныe линии), окнo кoнтpoля pиcкoв (визуaлизaции экcтpeмумoв, уpoвнeй, диaпaзoнoв), и нaбop знaчкoв.

Функциональные возможности:
 - 100+ популярных встроенных индикаторов
 - 50+ удобных инструментов рисования
 - Индикаторы профиля объёма
 - Распознавание свечных моделей
 - Анализ нескольких таймфреймов

Подробнее на сайте https://ru.tradingview.com/support/

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Спасибо.
