### ISSUE TITLE
[FEATURE] Тех.анализ. Сохранять ТФ при смене иснтрумента

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#415]
### Опишите проблему, которую решает ваша фича

При смене инструментов на виджете "График" остается ТФ, который был выбран на прошлом инструменте.
Для виджета "Тах.анализ" - при смене инструмента - ТФ выставляется по-умолчанию в дневной.

### Опишите предлагаемое вами решение

Не менять ТФ в "Тех.анализе" при смене инструмента.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Мы думали над тем, чтобы сделать глобальные настройки по умолчанию для виджетов. Мне кажется эти задачи пересекаются. Мы подумаем как можно эту проблему решить.
