### ISSUE TITLE
[FEATURE] Смена инструмента при вводе, "a la" TradingView 

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#417]
### Опишите проблему, которую решает ваша фича

В том же TradingView есть удобная фишка, что поменять инструмент можно просто вводя тикер - такой себе режим горячих клавиш.

https://user-images.githubusercontent.com/99450543/185874557-8c80f6a7-039d-4c56-a3a5-261740e58395.mp4

В ASTRAS чтобы быстро перейти на другой инструмент, нужно пойти на "Все инструменты" и ввести тикер в соответствующем поле.

### Опишите предлагаемое вами решение

Реализовать что-то похожее на TradingView - поиск инструмента сразу при вводе.
Возможно при вводе активировать поле поиска в инструментах. Правда это пересечется с горячими клавишами на про-стакане - возможно придется сделать это взаимоисключающими опциями.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Давайте мы сделаем по другому. Мы добавим комбинацию при которой поле ввода для поиска тикера автоматически фокусируется. Т.е. вы нажимаете что-то типо CTRL\CMD-F (надо подумать что именно), у вас фокусируется поле поиска тикера, вы нажимаете SBER + Enter и вуаля, инструмент активен.
