### ISSUE TITLE
[FEATURE] Сворачивать настройки горячих клавиш

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#422]
### Опишите проблему, которую решает ваша фича

Настроки горячих клавиш занимают слишком много место. Из-за них трудно ориентироваться в других настройкам., а до кнопки "Сохранить" много скроллить
![image](https://user-images.githubusercontent.com/29191749/187126319-811d1fd0-266b-41a7-b794-ebed40cfc504.png)

### Опишите предлагаемое вами решение

Как минимум сделать настройки горячих клавиш collapsed.
Как максимиу пересмотреть дизайн настроек и все группы сделать свернытуми по умолчанию ( некоторые развернутые)
Или сделать как в IDE или Chrome:
![image](https://user-images.githubusercontent.com/29191749/187126751-90cb9bdb-e0e9-4cac-b152-4fc66eb122a3.png)
![image](https://user-images.githubusercontent.com/29191749/187126865-2dd4876a-d4e4-4530-a2db-57fea226cb5b.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Спасибо что завел тикер. Да ты прав, есть проблема что настроек много. Надо подумать как их организовать. Я думал дизайнера подрядить под это дело, так что отложим немного эту таску.

**Comment by PilgrimViis** [comment]
![image](https://user-images.githubusercontent.com/6408195/188302925-227a6fcc-da69-407f-869d-0543eba84f9a.png)
Давайте сделаем вот так. Перенесем Горячие клавиши в отдельную вкладку в табах. "Настроки" можно переименовать в "Общие настроки", "Общие" ну или оставить просто "Настройки". По вашему желанию.

@agushasok возьмешь на себя, ок?

**Comment by sbelashevskiy** [comment]
Может стоить завести отдельную страницу?
Не особо удобно что-то редактировать в модальном окне. Кроме того, если кликнуть мимо его, то оно закроется без подтверждения. Пролистывать до кномки сохрнаить тоже так себе. А наличие одновременно кномпки сохранить и OK вообще смотрится не очень
