### ISSUE TITLE
[FEATURE] Перейти на новую версию angular 14

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#424]
### Опишите проблему, которую решает ваша фича

https://github.com/NG-ZORRO наконец-то зарелизили версию для angular 14. Теперь можно перейти на нее

### Опишите предлагаемое вами решение

Обновить Angular и прочие зависимости в проекте

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Давайте перейдем. Только отложим на пару месяцев.

**Comment by PilgrimViis** [comment]
@sbelashevskiy уже оказывается есть задача.
