### ISSUE TITLE
[FEATURE] Информация об обновлениях и новшествах

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#446]
### Опишите проблему, которую решает ваша фича

Ранее я подавал запрос о том, чтобы была информация о закрытых багах и новых функциях.
https://github.com/alor-broker/Astras-Trading-UI/issues/191
В итоге появился https://warp.alor.dev/ru/releases/astras

Плюс я заметил запрос
https://github.com/alor-broker/Astras-Trading-UI/issues/347

Но, думаю, тут нужно что-то глобальнее. Поначалу краткой информации об исправлениях хватало, но сейчас терминал развивается, добавляются новые функции и настройки и теперь не всегда сразу удается понять, что изменилось и как это работает.
Хороший пример - добавление системы связи виджетов между собой. В warp это отразилось, как "Новая система связки виджетов", а на деле это было "... для использования, которой в настройках профиля нужно активировать опцию [Включить привязку инструментов к лейблам] и тогда слева от заголовка виджета появятся цветные кружки"

### Опишите предлагаемое вами решение

Идея выводить пользователю сообщение о релизах (и факт ознакомления) - хороша, но краткого описания недостаточно. Нужно расписывать новые функции, информацию, как они настраиваются, а для наглядности с картинками или даже с gif анимацией.
Не хотелось бы умничать, но вы же делаете товар и тут кроме четкой работы нужна и красивая упаковка)

А еще когда речь идет об исправленных багах, предлагаю указывать ссылку на конкретную задачу в Github, чтобы пользователи видели, что это не какие-то мифические исправления, а предложения таких же живых клиентов.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Добавлять GIF и правда было бы неплохо. Про цветную привязку согласен, что непонятно было. Ещё есть в планах показывать модалку с информацией про релиз. 

@agushasok По этой задаче надо добавить возможность, чтобы на странице релизом можно было выкладывать гифки.
