### ISSUE TITLE
[FEATURE] Показывать позиции и заявки на графике тех анализа

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#447]
### Опишите проблему, которую решает ваша фича

Понять когда ты вошел в позицию и как текущая рыночная ситуация влияет на твои позиции и заявки достаточно сложно, если их много. 

### Опишите предлагаемое вами решение

Если сделать так, чтобы позиции и заявки отображались прямо на графике, как в tradingview.alorbroker.ru то будет гораздо удобней.

### Правила

- [ ] Я согласен следовать правилам

**Comment by dzeron13** [comment]
Дополню:
- Разделять заявки по операции (покупка/продажа) - по цветам, и по типу (лимитная/стоп) - например, типом линии
- Позицию в бумаге - брать среднюю

**Comment by uncrashable** [comment]
Поддерживаю, хорошая вещь
