### ISSUE TITLE
[FEATURE] Привязка инструментов по цветным бейджам

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#449]
### Опишите проблему, которую решает ваша фича

По вот этой штуке (https://github.com/alor-broker/Astras-Trading-UI/issues/429), да и в целом по цветам опишу в одном, чтобы общая концепция не распадалась:
1. Смена цвета у виджета переключает виджет на тот инструмент, который сейчас "числится" за этим цветом - но неизвестно какой
![image](https://user-images.githubusercontent.com/99450543/189550170-8ff38cd3-3cdd-43f9-b2b7-646895ec6747.png)
2. На SBER по умолчанию "висят" все цвета - не самая очевидная вещь, если он не добавлен в список инструментов.
Подозреваю, что так и задумано, т.к. SBER - дефолтный инструмент и после включения опции в настройках, виджеты отображают инструмент по цвету бейджа. Но по факту мы получаем, что пока мы не переназначим по цветам другие инструменты, при смене цвета бейджа - виджет переходит на SBER.
![image](https://user-images.githubusercontent.com/99450543/189550187-a9ca280d-9dfe-4140-b3d4-e291cfd12b01.png)
А еще при сужении виджета - ползет высота строки
![image](https://user-images.githubusercontent.com/99450543/189551033-dd857191-c049-46ae-b3d4-cd7f9deec205.png)
3. Если за инструментом "числится" цвет, то после удаления его из списка - цвет так и остается привязанным
https://user-images.githubusercontent.com/99450543/189550507-f2562a8a-531c-4747-9d3e-cd4e0348be6d.mp4
4. После активации опции, чтобы исключить виджет из "цветовой дифференциации" нужно отключить "цепочку" (только для зависимых виджетов (кружок). Для Блоттера - "цепочка" не влияет на переключение. Т.е. если, например, я не хочу чтобы выбор строк в Блоттере менял мне другие виджеты - нужно переключить его на неиспользуемый цвет (если они еще остались свободные). 
https://user-images.githubusercontent.com/99450543/189552685-ef343bbc-03f3-440c-b995-986d73ad3b98.mp4
Получается, что управление привязкой выполняется двумя элементами - кружок и цепочка. Уильям Оккам медленно достает свою бритву :)
5. Элемент привязки (цветной кружок) плохо различим

### Опишите предлагаемое вами решение

1. Рядом с выбором цвета бейджа отображать тикер инструмента, который к нему сейчас привязан
![image](https://user-images.githubusercontent.com/99450543/189550653-27d5a110-3178-4d0e-acaf-925c25ebf9be.png)

2. Убрать у SBER всю привязку (или хотя бы оставить первый цвет)

3. Снимать привязку цвета к инструменту, если выполняются **все** условия:
- Он удален из всех списков в "Выбор инструмента"
- Не осталось виджетов с этим цветом, где открыт этот инструмент
- Инструмент не привязан к цвету во "Всех инструментах"

4. Вообще с реализацией цветных бейджей предлагаю рассмотреть вопрос о переходе к одной настройке. Сейчас по сути два режима: опция отключена - "цепочка" работает, как [один цвет || отсутствие привязки виджета] и опция включена - "цепочка" [добавляет || исключает] привязку виджета. Если в список цветов добавить режим "без привязки" (отдельный цвет или символ), то элемент "цепочка" будет уже не нужен. Кроме того решение должно быть единым, чтобы отвязывать можно было любой виджет (в т.ч. Блоттер и Все инструменты)

6. Увеличить размер бейджей. Закрепить расположение бейджа справа от настроек (шестеренка)

### Дополнительная информация

P.S. Если нужно - какие-то пункты вынесу в отдельные задачи.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@Tattydes нужен твой комментарий.

**Comment by dzeron13** [comment]
> По проблеме с несколькими цветами, предлагаю следующий вариант ![image](https://user-images.githubusercontent.com/6408195/205027764-b1a48fbd-6e3a-47cd-92f1-bac10f3e541b.png)

Не совсем понял, о какой проблеме речь?)

**Comment by Tattydes** [comment]
По цветам предлагаю такое решение, чтобы не было схожих оттенков.
И думаю да, стоит написать обозначение каждого цвета.

![#449 Привязка инструментов по цветным бейджам](https://user-images.githubusercontent.com/116548833/205592160-2f688cb6-34f7-4796-9fed-7814caceff0c.png)

**Comment by uncrashable** [comment]
Если в дальнейшем понадобится увеличить кол-во цветов, будет проблема с оттенками. 
Предлагаю рассмотреть не цвета, а например алфавит(англ), либо вообще можно использовать фигуры и символы, их больше.
Что бы избежать большого количества символов в выпадающем списке с якорями, можно меню с якорями разворачивать постепенно. т.е.
Открываешь список, в начале будет только 1 якорь например с символом  " ° " , активируем его. Т.к. мы его активировали , то он попадает во все остальные виджеты где и можно будет заякориться с ним.
Помимо этого символа , теперь в меню добавляется еще 1 "свободный" якорь например "╞ " , т.е. в любом виджете теперь появляется первый символ, к которому можно приякориться и предлагаемый новый.

**Comment by Tattydes** [comment]
> Если в дальнейшем увеличиваться кол-во цветов, будет проблема с оттенками. Предлагаю рассматривать не цвета, а например алфавит(английский), либо вообще можно использовать фигуры и символы, их больше. Что бы избежать большого количества символов в выпадающем списке с якорями, можно меню с якорями расширять постепенно. т.е. Открываешь список, в начале будет только 1 якорь например с символом "°", активируем его. Т.к. мы его активировали, то он наблюдал во всех остальных виджетах, где и можно будет заякориться с ним. Помимо этого символа , теперь в меню появляется еще 1 "свободный" якорь например "╞" , т.е. в любом виджете теперь появился первый символ, к которому можно приякориться и предлагаемый новый.

Как вариант, но всё таки цвета проще запомнить, они визуально заметней, чем буквы или символы одного цвета.
