### ISSUE TITLE
[FEATURE] Выставление и снятие заявок с графика

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#451]
### Опишите проблему, которую решает ваша фича

В AlorTradingView на графике возле шкалы есть элемент для выставления заявки по цене курсора
![image](https://user-images.githubusercontent.com/99450543/189555073-40068a00-b930-4c2c-b707-20eea899f162.png)

### Опишите предлагаемое вами решение

При наличии привязанного виджета "Выставление заявки", по нажатию такого элемента, вставлять значение в поле "Цена" если выбрана вкладка "Лимитная" или в "Сигнальная цена", если "Условная". Цену соответственно брать по курсору на графике.
Если связанного виджета нет - выводить модальное окно "Выставить заявку". Поведение полей - аналогичное.
Наверное, стоит это сделать опцией, вдруг кому-то нужно именно модальное окно для заявок.

После реализации https://github.com/alor-broker/Astras-Trading-UI/issues/447, рядом с ценой заявки отображать кнопку снятия заявки.

Реализовать для Графика и Тех.Анализа

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@sbelashevskiy можешь посмотреть по докам плиз, сможем ли это сделать в Астрас?

**Comment by sbelashevskiy** [comment]
Для tech chart нужно включить фичу chart_crosshair_menu и добавить обработку события onPlusClick. Аргументы события включают цену курсора

**Comment by sbelashevskiy** [comment]
Для light chart возможности показать кнопку я не вижу. Но можно обработать просто клики мыши https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#subscribeclick.
При этом доступна следующая информация:
`{
    "open": 0.02003,
    "high": 0.02015,
    "low": 0.01989,
    "close": 0.020035
}`

**Comment by PilgrimViis** [comment]
> Для light chart возможности показать кнопку я не вижу. Но можно обработать просто клики мыши
Не очень идея наверное... Давай пока остановимся на tech chart.
