### ISSUE TITLE
[FEATURE] Добавить колонку "Название" в виджете Выбор инструмента и дополнить в заголовок виджетов после "Тикера" еще и "Название" инструмента ... 

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#456]
### Опишите проблему, которую решает ваша фича

Клиент торгует облигациями, в основном их смотрит через виджет "Выбор инструмента", в котором транслируется только "тикер" инструмента. У облигаций он числовобуквенный код, который сложно идентифицировать (можно толь через открытие виджета Инфо, что занимает место). 

### Опишите предлагаемое вами решение

Необходимо добавить в виджет ""Выбор инструмента" дополнительную колонку "Название", такую же как в виджете "Все инструменты".
Дополнительно добавить в заголовки виджетов (Стакан, Скальперский стакан, График, Тех. анализ, Инфо) после тикера инструмента его "Название".
В прилагаемом скрине с примерами заголовков инструмент ОФЗ 29017

### Дополнительная информация

![изображение](https://user-images.githubusercontent.com/105856884/189664995-44843f06-e6f0-42a4-a34e-0bb0e08236e8.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by dzeron13** [comment]
С заголовками виджетов тут надо осторожней. При сужении виджета, заголовок "ползет" на вторую строку вместе с кнопками
![image](https://user-images.githubusercontent.com/99450543/189687665-8f311f89-1343-4e53-a457-4f6839d62ade.png)
