### ISSUE TITLE
[FEATURE] Уменьшить размер ячейки сетки для виджетов

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#457]
### Опишите проблему, которую решает ваша фича

Старый добрый вопрос, о том, что ячеистая система расположения виджетов не позволяет оптимально для себя располагать виджеты и менять их размеры.

### Опишите предлагаемое вами решение

Провел некоторый эксперимент. Взял виджет и утащил за пределы экрана, чтобы увеличилось количество ячеек по вертикали и горизонтали, а размер ячейки стал достаточно малым. Оставил этот виджет в углу, чтобы не "скукоживалось" обратно.
Добавил виджеты, расположил, как нужно (для примера), подогнал размеры. Работает и вроде не тормозит.

Поэтому предлагаю рассмотреть возможность по умолчанию делать сетку не 5x2, а побольше (на скриншоте - примерно 55x30).

Мысли:
1. Размер поля делать делать переменным, возможно, в зависимости от разрешения экрана. Ячейку делать квадратной - чтобы смотрелось сеткой, а не подложкой в стиле Excel.
2. Или может задавать размер в настройках, в пределах ограниченного диапазона.
3. Чем мельче сетка, тем "белее" будет фон. Плюс мы помним, что манипуляции с виджетами (любые щелчки по нерабочим областям) приводят к тому, что сетка отображается. Вот если бы цвет линий совсем убрать, или хотя бы сделать еле заметными, тогда это не так бы сильно бросалось в глаза. А если еще и в настройки вынести отображение сетки...
4. Потребуется изменение системы добавления виджетов. Сейчас они встают в одну единицу ячейки. Если будет сетка - нужно будет высчитывать область (скажем в процентах от размеров сетки) и растягивать на нее виджет.
5. Плюс, в текущей реализации, сетка уменьшается (справа, снизу), если по краям есть ряды пустых ячеек, а виджеты автоматически перестраиваются. От этого придется уйти, чтобы пользователь сам располагал виджеты на местах, где удобно.
![image](https://user-images.githubusercontent.com/99450543/189685418-e1a213a1-1141-4920-adca-c86c0f4d761b.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Хорошо, давайте попробуем. Начнем с того, что сделаем в сетке побольше ячеек и при этом чтобы новые виджеты создавались корректных размеров. Другие предложения реализовывать пока не будем, а автоматическое распределение виджетов вероятно отключать не будем вообще, так как это создаст другие проблемы пользователям.

**Comment by PilgrimViis** [comment]
А, ещё не забудьте переделать дашборд по умолчанию на новые размеры!!
