### ISSUE TITLE
[FEATURE] Убрать оповещение о сделках [21]

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#478]
### Опишите проблему, которую решает ваша фича

При выставлении лимитных заявок появляются уведомления , если заявок много , то они закрывают часть экрана - мешает очень

### Опишите предлагаемое вами решение

Оставить только критические уведомления , остальные спрятать под колокольчик 

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
а какой смысл прятать такие уведомления под колокольчик?
Т.е. пользователю они фактически не нужны. Если их так много, то и под колокольчиком будет висеть куча непрочитанных и пользователь вряд ли их вообще прочитает и в результате какое-то важное уведомление просто затеряется среди остальных. Я считаю это очень плохая идея помещать эти уведомления с остальными уведомлениями типа фидбэка или релиза.
Это очень плохой UX - когда будет куча уведомлений, пользователи просто попросят кнопку - пометить все прочитанными или удалить все и никто эти уведомления читать не будет.

Фактически эта информация есть в блоттере в разделах сделки и заявки. Зачем ее еще в уведомлениях дублировать и хранить?

**Comment by daleburunduk** [comment]
> а какой смысл прятать такие уведомления под колокольчик? Т.е. пользователю они фактически не нужны. Если их так много, то и под колокольчиком будет висеть куча непрочитанных и пользователь вряд ли их вообще прочитает и в результате какое-то важное уведомление просто затеряется среди остальных. Я считаю это очень плохая идея помещать эти уведомления с остальными уведомлениями типа фидбэка или релиза. Это очень плохой UX - когда будет куча уведомлений, пользователи просто попросят кнопку - пометить все прочитанными или удалить все и никто эти уведомления читать не будет.
> 
> Фактически эта информация есть в блоттере в разделах сделки и заявки. Причем в блоттере эта информация более структурировна т.к. привязана к конкретному инструменту. Там сразу есть параметры заявки/сделки Зачем ее еще в уведомлениях дублировать и хранить при том что ничего полезного кроме номера заявки в уведомлении не будет? Пользователю в любом случае придется брать номер заявки, идти в блоттер и искать ее там, если понадобится что-то проверить.
> 
> Больше смысла имеет либо вообще не показывать такие уведомления (вынести это в настройку), либо уменьшить длительность показа таких уведомлений

Тоже мешают уведомления, степень мешабельности от пользователя к пользователю будет зависеть от предпочтений в расположении виджетов. Поэтому дополню последнее предложение: "...либо вывести в настройку угол отображения уведомлений".

**Comment by sbelashevskiy** [comment]
@PilgrimViis ,
по этой задче так и не принято решения:
1. Скрывать уведомления вообще?
2. Показывать с системынмы уведомлениями?
3. Что-то другое?

**Comment by PilgrimViis** [comment]
> @PilgrimViis , по этой задаче так и не принято решения:
> 
> 1. Скрывать уведомления вообще?
> 2. Показывать с системынмы уведомлениями?
> 3. Что-то другое?

Давай пока сделаем настройку в профиле, которая будет пока полностью скрывать уведомления от выставленных заявках и исполненных сделках. В последствии вернемся к этой задаче, когда на беке сделают систему уведомлений. Я хотел посылать пуши на само устройство для уведомлений. Вернемся к этой задаче когда они закончат.
