### ISSUE TITLE
[BUG] Отображение сред знач при входе в позицию

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#484]
### Опишите баг

При усреднении позиции в скальперском стакане точка входа отображается с большим количеством знаков после точки 
![image](https://user-images.githubusercontent.com/105817664/191971930-1d2abdd9-d778-4d59-b02c-6bd1af315d9f.png)

Возможно стоит сделать кратно шагу цены

### Воспроизведение

Усреднение при входи в позицию

### Среда.

Виндовс 7  Хром 

### Ожидаемое поведение

Какой шаг цены в стакане , такое и отображение кол-ва символов при усреднении 

### Правила

- [ ] Я согласен следовать правилам

**Comment by agushasok** [comment]
усреднение в бОльшую, меньшую сторону, или по математическим правилам?

**Comment by PilgrimViis** [comment]
По математическим правилам, т.е. 0.55 округляется до 0.6
