### ISSUE TITLE
[BUG] Ложное отображение в стакане 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#485]
### Опишите баг

![image](https://user-images.githubusercontent.com/105817664/191986033-e41d377a-20fc-407c-946c-3b8b846f1c5c.png)
Купил 2 лота по нефти и продал 2 лота по нефти ,  а в стакане показывает что позиция есть. 

### Воспроизведение

Открыть стакан про
Купить нефть - продать нефть 

### Среда.

Виндовс 7 Хром 

### Ожидаемое поведение

Позиция не должна отображаться если ее нет 

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте, это проблема на бекенде. Тут мы ничем не сможем помочь
