### ISSUE TITLE
[FEATURE] наименование стакана

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#489]
### Опишите проблему, которую решает ваша фича

![image](https://user-images.githubusercontent.com/105817664/191994342-f51d4661-e175-425c-b14a-f4b042771a8e.png)
Ввехней части стакана , много ненужных надписей. 
И так понятно что это скальперский стакан.  RFUD тоже лишнее 

### Опишите предлагаемое вами решение

Оставить только краткое название инструмента , например GOLD12.22  или SI 12.22

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Нет не лишнее, это полезная информация. Убирать не будем.

**Comment by PilgrimViis** [comment]
В итоге мы это сделали. Ребята придумали прикольную идею, заменить "Скальперский стакан" иконкой.
