### ISSUE TITLE
[BUG] Не показывается текст ошибки при выставлении заявки

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#495]
### Опишите баг

Не показывается ошибка с самой сутью проблемы. И показывается ненужная ссылка на которую клиенты кликают. Если не сложно, то её бы тоже убрать.
![image](https://user-images.githubusercontent.com/6408195/192975263-43bbe986-a5a5-49b4-84f1-51033ecb08fc.png)

### Воспроизведение

- 1. Выставить заявку которая должна отклониться
- 2. Посмотреть что ошибка 400 и ссылкой, но без текста.

### Среда.

- Windows
-  Chrome

### Ожидаемое поведение

Надо чтобы в уведомлении об ошибки сразу показывался текст ошибки пришедший с бекенда. Т.е. чтобы писать не 400 Bad Request, а "Недостаток средств". Хотя сам 400 не обязательно удалять, тоже может полезная инфа быть.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
При удалении добавить jsonResponse=true в query, чтобы получить json ответ.

**Comment by dzeron13** [comment]
Вообще тут бы глобальнее подойти к вопросу. Отрабатывать не только 400 ошибку, но и "очеловечить" другие: попытки выставить заявку вне рабочей сессии, выставление не в том рынке и т.п.

**Comment by sbelashevskiy** [comment]
Тут же какие-то конкретные условия должны быть - при наличии объяснения в чем проблема он и так показывается:
![image](https://user-images.githubusercontent.com/29191749/193004729-444f0d98-4f3a-425f-bf4d-eba08b611426.png)

**Comment by PilgrimViis** [comment]
Я эту проблему с Даней обсуждал, хотел чтобы он эту задачу взял. Если
коротко, то скорее всего проблема по одному конкретному сценарию.

**Comment by PilgrimViis** [comment]
> Вообще тут бы глобальнее подойти к вопросу. Отрабатывать не только 400 ошибку, но и "очеловечить" другие: попытки выставить заявку вне рабочей сессии, выставление не в том рынке и т.п.

@dzeron13 тексты ошибок присылает бекенд (и мы имеем мало власти со стороны Астрас над этим) да и они в целом нормальные. Если есть какие-то конкретные случаи, когда ошибки без текста или с непонятным текстом, пожалуйста скиньте сюда, мы посмотрим.

**Comment by dzeron13** [comment]
> > Вообще тут бы глобальнее подойти к вопросу. Отрабатывать не только 400 ошибку, но и "очеловечить" другие: попытки выставить заявку вне рабочей сессии, выставление не в том рынке и т.п.
> 
> @dzeron13 тексты ошибок присылает бекенд (и мы имеем мало власти со стороны Астрас над этим) да и они в целом нормальные. Если есть какие-то конкретные случаи, когда ошибки без текста или с непонятным текстом, пожалуйста скиньте сюда, мы посмотрим.

@PilgrimViis, что они с бека пришли в таком виде - понятно, но выводить их напрямую пользователю - как-то не очень юзерфрендли. Смотрится, как debug режим какой-то) Вот для примера, 145 - invalid account - еще можно понять. А вышеуказанную 133 - Security... - уже не очень.
![image](https://user-images.githubusercontent.com/99450543/193017403-ffcc835a-7448-46e8-850b-e59ea0a74bbc.png)

Я тогда пособираю "непонятных" ошибок и оформлю отдельно.
