### ISSUE TITLE
[BUG] График на Тех.Анализе замирает на младших ТФ

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#497]
### Опишите баг

При выставлении на графике Тех.Анализ ТФ 15/5/1 мин, через какое-то время график перестает рисоваться и замирает. После этого помогает смена ТФ (не всегда) или перезагрузка страницы.
На часовике вроде не замечено.

### Воспроизведение

1. Открыть виджеты График и Тех.Анализ
2. Выставить одинаковый инструмент
3. Выставить ТФ 1мин || 5мин || 15мин.
4. Понаблюдать какое-то время.
5. Данные на Графике отображаются корректно, на Тех.Анализе зависли.

### Среда.

win 10, chrome 105

### Ожидаемое поведение

График на Тех.Анализе отображается корректно на всех ТФ

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@dzeron13 данных недостаточно - промониторил поведение в течении 20 мин и не увидел зависания
Баг стабильно воспроизводится? 
В какой-то определенный период времени?
Как долго ждать зависания?
Какие действия выполнялются перед появлением бага? Переключение разных инструментов, переключение ТФ, сдвиги временной шкалы...

В консоли браузера после зависания есть какие-то ошибки?

**Comment by sbelashevskiy** [comment]
получилось воспроизвести - ключевой момент здесь:** нужно переключать ТФ**. Сторонний компонент реализует какую-то собственную логику по закрытию стримов от предыдущего ТФ c разной задержкой
