### ISSUE TITLE
[FEATURE] Стиль кнопок верхней панели при наведении

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#509]
### Опишите проблему, которую решает ваша фича

У кнопок на верхней панели разное поведение на курсор. Выставление заявки, виджета, очистка - подсвечиваются
![image](https://user-images.githubusercontent.com/99450543/193754748-569a3e49-f539-4b8b-af91-61cb9a53446d.png)
Уведомления и профиль - нет.
![image](https://user-images.githubusercontent.com/99450543/193755422-b1a16fc1-56bb-4516-a234-06a2b30f0a39.png)
Кроме того, у "плюса" и "корзинки" при наведении сверху остается пустая полоска, тогда, как у добавления виджета, такого нет, что визуально кажется, что они смещены немного вниз
![image](https://user-images.githubusercontent.com/99450543/193755160-ce42925e-3243-480d-b37f-3791cf946f41.png)

### Опишите предлагаемое вами решение

Для всех кнопок на верхней панели сделать одинаковое поведение при наведении курсора.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Уже пофикшено в рамках https://github.com/alor-broker/Astras-Trading-UI/issues/498
