### ISSUE TITLE
[FEATURE] В виджете "Выставить заявку" отображать позицию по бумаге

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#513]
### Опишите проблему, которую решает ваша фича

В модальном окне выставления заявки рядом с логотипом бумаги отображается сколько лотов сейчас на балансе.
![image](https://user-images.githubusercontent.com/99450543/193810588-d49292a7-cd0a-4f18-ab08-93aaeba37b4f.png)
Еще количество лотов отображается в скальперском стакане
![image](https://user-images.githubusercontent.com/99450543/193810929-37464fac-df34-4357-9df7-f4fb56024580.png)

Если не используется скальперский стакан, то следить за позицией сложновато, т.к. в том же блоттере подсчет идет в штуках.

### Опишите предлагаемое вами решение

Добавить на виджет "Выставить заявку" информацию о позиции, по аналогии с модальным окном (без логотипа)

### Правила

- [X] Я согласен следовать правилам

**Comment by dzeron13** [comment]
Добавлю еще момент, раз речь про виджет:
Лотность бумаги отображать сразу, а не через всплывающую подсказку
![image](https://user-images.githubusercontent.com/99450543/193822959-f0bb1ea6-ff09-43a8-9cd1-eb48b2abf700.png)

**Comment by sbelashevskiy** [comment]
Проблема в том, что виджет значительно меньше, чем диалог и лотность просто не помещается.
Единственное место, куда можно добавить лотность и количнество позиций это верх виджета (гле отображается портфель, 
 ASK и BID), но это увеличивает высоту виджета

**Comment by dzeron13** [comment]
> Проблема в том, что виджет значительно меньше, чем диалог и лотность просто не помещается при стандартной сетке. Единственное место, куда можно добавить лотность и количнество позиций это верх виджета (гле отображается портфель, ASK и BID), но это увеличивает высоту виджета.

Ну, с лотностью тут попроще, кмк, всплывающее сообщение вполне помещается вместо значка (i)
![image](https://user-images.githubusercontent.com/99450543/194000043-1eadc384-ade9-49aa-bf0d-e2e770d81357.png)

Верхняя строчка 20 пунктов, в модальном окне область с бумагами, тоже порядка 20-25
![image](https://user-images.githubusercontent.com/99450543/194001772-d65e5343-66cd-4376-8190-4da6c5530af3.png)

**Comment by sbelashevskiy** [comment]
Вы рассматриваете только 1 кйс на 1 мониторе. 
Даже 10К лотность уже не влезет. Тем более не влезет не кратная 1000 лотность

**Comment by sbelashevskiy** [comment]
@PilgrimViis нужно определиться как отображать кол-во позиций.
Предложенный вариант просто в виде бэйджа не соответствует нормам UX: непонятно что это за поле, почему у него нет подписи, когда у Ask b Bid они есть, почему оно выделено цветом. В случае с отображением рядом с лого (как в диалоге) это поле в таком виде еще смотрится, но тут отображение в виде бэйджа неуместно, т.к. вообще не вписывается в общий стиль виджета. Если отображать в виде бэйджа, то уместнее его разместить рядом с портфелем, а не после ASK BID

Кроме того, на моих скринах видно, что например для VTBR это поле уже не будет влезать (не у всех мониторы от 20 дюймов) в одну строку с обозначением портфеля, полями ASK BID. В итоге мы опять получим проблему с отображением как эта https://github.com/alor-broker/Astras-Trading-UI/issues/214

Уместнее лотность и кол-во позиций показывать в отдельной строке и увеличить дефолтный размер этого виджета https://github.com/alor-broker/Astras-Trading-UI/issues/547

**Comment by PilgrimViis** [comment]
@sbelashevskiy я написал нашему дизайнеру и попросил придумать куда воткнуть можно лотность. Подождем.

**Comment by Tattydes** [comment]
Предлагаю такое решение для поп-апа:
![#513 В виджете _Выставить заявку_ отображать позицию по бумаге 2](https://user-images.githubusercontent.com/116548833/201091777-89b9707d-7f4b-4221-8bdb-4bd363a8c8b0.jpg)


А для виджета можно внизу сделать маленькую пометку:
![#513 В виджете _Выставить заявку_ отображать позицию по бумаге](https://user-images.githubusercontent.com/116548833/201091932-60f6456b-5619-4389-86ab-635884e93ca8.png)

**Comment by PilgrimViis** [comment]
Слово "акций" там не нужно с точки зрения бизнес логики оно неправильное. В остальном может сработать. Давайте попробуем.

**Comment by sbelashevskiy** [comment]
@PilgrimViis @Tattydes 
отображение лотности только часть вопроса.
Основной вопрос здесь был по отображению текущего кол-ва позиций

**Comment by Tattydes** [comment]
Доработала основной вопрос. Два варианта на выбор:
![#513 - 1](https://user-images.githubusercontent.com/116548833/201998320-5107c860-1b85-4046-b890-70a9060b4dd9.png)

![#513 - 2](https://user-images.githubusercontent.com/116548833/201998333-d8739a59-4433-4be5-a269-dcb62baf4cbb.png)

**Comment by dzeron13** [comment]
я на втором варианте, если честно, не сразу увидел, где отображается количество))
как по мне, количество должно визуально выделяться, чтобы считывалось даже при мимолетном взгляде, поэтому первый вариант - очень даже

**Comment by sbelashevskiy** [comment]
Что-то я не очень понимаю почему скрин для модального окна если речь о виджете.
Не совсем понятно для чего так много дублирующийся информации:
1. В заголовке виджета уже отображается тикер инструмента
2. D39004(MOEX) это уже целевой портфель, для чего еще у инструмента отображать MOEX?
3. Опять приходим к проблеме с переносами строк - если цена будет с большим количеством знаков, то вижет придется растягивать. При этом шрифт у текущей цены очень крупный
4. В итоге высота виджета значительно увеличилась

Если оставлять тикер, то тогда уже лучше  тикер с количеством позиций отображать в одной строке,
а все цены в отдельной

**Comment by Tattydes** [comment]
Это не модальное окно) соседние виджеты специально затемнены, для фокусировки на главном.

Вопросы 1-4 решаются очень легко, удалением строки с тикером, которая на самом деле оказалась там случайно, как раз из модального окна

![#513 - 3](https://user-images.githubusercontent.com/116548833/202089906-e8df4030-98ae-473a-9a62-c3066d35e444.png)
