### ISSUE TITLE
[BUG] Ошибка 500 при заявке SPBX бумаги на MOEX

### ISSUE THREAD

**Issue by dzeron** [alor-broker/Astras-Trading-UI#516]
### Опишите баг

Если портфель выбран MOEX и при этом текущая бумага та, что торгуется на SPBX, то виджет выставления заявки или модальное окно выдают 500 ошибку на метод https://api.alor.ru/commandapi/warptrans/FX1/v2/client/orders/estimate.
Я так понимаю, он дергает количество бумаг на данном портфеле.
![image](https://user-images.githubusercontent.com/99450543/193825074-314d1cf1-dc82-4d51-89c7-1a5cd560beaa.png)

Если переключиться на SPBX портфель, то подобные действия с разными бумагами не приводят к ошибке.
При этом если потом вернуться обратно на MOEX, то ошибка уже не повторяется.

https://user-images.githubusercontent.com/99450543/193828446-88646e20-0c56-46bd-a87f-31ada3138817.mp4

### Воспроизведение

1. Добавить в список инструментов бумаги MOEX и SPBX
2. Активной выбрать MOEX
3. Выбрать портфель MOEX
4. Добавить виджет "Выставить заявку"
5. Выбрать бумагу SPBX

### Среда.

win 10, chrome 105

### Ожидаемое поведение

Не выдавать ошибку)

### Правила

- [X] Я согласен следовать правилам

**Comment by dzeron13** [comment]
Тю, мы же ее уже чинили #70

**Comment by PilgrimViis** [comment]
B
