### ISSUE TITLE
[BUG] При изменении глубины стакана пропадает привязка по цвету

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#517]
### Опишите баг

При изменении настроек. Глубины стакана. Пропадает значек привязки инструмента в тайтле.

### Воспроизведение

- 1. Включить настройку с цветами
- 2. Открыть виджет стакана
- 3. Изменить глубину стакана
- 4. Точка пропадет

### Среда.

 Windows 11
Chrome last

### Ожидаемое поведение

Квадрат и круг не должны пропадать при изменеии настроек.

### Скриншоты

![image](https://user-images.githubusercontent.com/6408195/194258394-a716bd84-a7c8-4cdd-b4d8-4e41aeada299.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by dzeron13** [comment]
Когда-то давно я спрашивал про это, что любое изменение настроек снимает с виджета замок. Сказали так и задумано.
Концепция изменилась?)

**Comment by sbelashevskiy** [comment]
@PilgrimViis 
Значек пропадает, потому что после изменения настроек linkToActive = false.
Тоже самое, если вручную снять привязку.
Если виджет не привязан к активному инструменту, то он сотвтетствнно и не в группе, Это при реализации фичи с группами обсуждалось. Если вернуть привязку, то и индиктор вернется

https://user-images.githubusercontent.com/29191749/194490708-0d188607-392d-402b-8dff-aa076170132a.mp4

**Comment by PilgrimViis** [comment]
Получается снимать привязку нужно только если поменялся инструмент или биожа или режим торгов.

**Comment by sbelashevskiy** [comment]
Это для всех виджетов или только для стакана?
Эта логика прописана вообще во всех виджетах
