### ISSUE TITLE
[FEATURE] Меню профиля. Область нажатия на элементы.

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#535]
### Опишите проблему, которую решает ваша фича

В меню профиля, подсвеченные пункты (Отчеты, Релизы, Техподдержка) срабатывают только при нажатии на саму надпись. При щелчках рядом не реагируют.
Для пунктов "Профиль" и "Выход" область нажатия - вся ячейка.

https://user-images.githubusercontent.com/99450543/196263231-8348033f-353a-4020-982f-d405ab3b4bec.mp4

### Опишите предлагаемое вами решение

Изменить область нажатия для "подсвеченных" (Отчеты, Релизы, Техподдержка) пунктов на всю ячейку.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Думаю что это все таки баг. Поменял тэг. Спасибо, посмотрим.
