### ISSUE TITLE
[BUG] Текст наслаивается друг на друга при сужении виджетов

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#537]
### Опишите баг

Сейчас есть пять виджетов - Выбор инструмента, Инфо, Все сделки, Курс валют и Выставить заявку - в которых при уменьшении размеров текст наслаивается или переносится посимвольно, что затрудняет понять содержимое виджета. 

Для сравнения, в Блоттере и Все инструменты есть фиксированный размер столбцов, а при изменении масштаба появляется горизонтальный скролл для смещения влево/ вправо. В связи с этим, текст внутри таблиц не съезжает и читаем (см. видео)

### Воспроизведение

1. Выставить виджеты: Выбор инструмента, Инфо, Все сделки, Курс валют и Выставить заявку.
2. Немного уменьшить размер виджетов.
3. Посмотреть на отображение данных.

### Среда.

Windows 10

### Ожидаемое поведение

Текст не наслаивается друг на друга и понятен, появляется горизонтальный скролл для смещения влево/ вправо

### Скриншоты

![2022-10-18_12h31_12](https://user-images.githubusercontent.com/88287882/196394581-7768daf1-bd3c-43f1-b2a3-b7982c07ab34.png)

https://user-images.githubusercontent.com/88287882/196394603-dfbbb175-9a56-43b1-af7e-e3062948b10c.mp4

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Это не баг, а наш выбор. Мы можем либо сделать скрол, либо обрезать текст, либо так. По моему мнению это меньшее из всех зол.
