### ISSUE TITLE
[BUG] При смене темы фон в "Тех. анализе" не всегда автоматически переключается на нужный

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#542]
### Опишите баг

Не всегда фон на графиках меняется в зависимости от выбранной темы в приложении. Если выставить виджет "Тех анализ" и перезагрузить страницу, а потом поменять тему, то фон на графике останется, как после перезагрузки страницы. Остальные виджеты такого поведения не повторяют.

### Воспроизведение

1. Выставить несколько виджетов "Тех анализ".
2. Переключиться между темами.
3. Перезагрузить страницу.
4. Переключить тему.

### Среда.

Windows 10

### Ожидаемое поведение

Переключение фона графиков в зависимости от выбранной темы (для темной темы в приложении- темный фон графиков и наоборот)

### Скриншоты

https://user-images.githubusercontent.com/88287882/196452120-5286e411-5639-4cc1-818d-597461114414.mp4

![2022-10-18_17h04_38](https://user-images.githubusercontent.com/88287882/196452465-f153e580-65f2-415b-b606-60aba5a020f6.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Я не вижу каких-либо проблем с переключением темы:

https://user-images.githubusercontent.com/29191749/197751870-6485fa2d-4193-42b4-917a-f36d9e8d1ddd.mp4

**Comment by ilya7am** [comment]
При перезагрузке страницы без смены темы приложения 4 раза (при активной темной теме иногда достаточно трех раз), а потом смене темы приложения - графики отображаются по предыдущей теме. Для каждого нового тех. анализа ситуация повторяется через 4 перезагрузки.
Не зависит от числа выставленных виджетов тех. анализа. Для устранения появившейся ошибки помогает только удаление виджета и добавление нового.

https://user-images.githubusercontent.com/88287882/198058775-36635912-4ccd-41fc-8858-0f56541d6e3d.mp4

**Comment by PilgrimViis** [comment]
Тут проблема скорее всего и с самой либой и с тем что ты через ремоут или слабый комп сидишь. Это будет слишком сложно пофиксить, но сам баг вполне безобидный. Вряд ли вообще клиенты будут 4 раза делать рефреш. Поэтому приняли решение, что не будем фиксить. Сергей отписал авторам либы, если они сделают правки и пофиксят в своей либе, мы вернемся к этому.
