### ISSUE TITLE
[DOCS] Подправить справки для виджетов

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#543]
![2022-10-18_16h25_01](https://user-images.githubusercontent.com/88287882/196470368-10635f74-1746-4e50-8af1-8407977f09e7.png)
![2022-10-18_16h27_30](https://user-images.githubusercontent.com/88287882/196470455-9a762d13-9c3b-4d1c-a540-adf20ee0b2af.png)
![2022-10-18_18h08_28](https://user-images.githubusercontent.com/88287882/196470947-d9ff5d08-1f98-4d85-ab01-220e0acb2094.png)
Модальное окно уведомлений:
![2022-10-20_13h58_341](https://user-images.githubusercontent.com/88287882/196977507-bf828c4b-965a-48f2-933e-e222ae79ddb5.png)

**Comment by MorozovDen** [comment]
подправил ошибки из первых трех скринов. Нужно сделать последний
