### ISSUE TITLE
[BUG] При фильтрации в виджете "Все инструменты" не все символы отправляются вместе с запросом

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#549]
### Опишите баг

В виджете "Все инструменты" при установке фильтров для полей "Валюта", "Рост за сегодня", "Объем торгов" и "Цена" часть символов не отправляется вместе с запросом, что в результате влечет за собой ошибку отображения данных.

Это зависит от скорости ввода данных: при более медленном вводе, а также указании десятичных чисел, ошибка воспроизводится. Кроме того, при удалении значения в поле и вводе нового фильтр по параметру может вообще не применяться (видео).

### Воспроизведение

1. Выставить виджет "Все инструменты".
2. Открыть консоль разработчика-  F12.
3. Поочередно ввести значения в поля "Валюта", "Рост за сегодня", "Объем торгов" и "Цена". 
4. Проверить отсылаемые параметры во вкладке Payload в консоли.
5. Проверить загрузку данных в виджете.

### Среда.

Любая

### Ожидаемое поведение

Данные отсылается те, которые указаны пользователем в фильтре. Загружаются валидные данные в "Все инструменты".

### Скриншоты

https://user-images.githubusercontent.com/88287882/196984735-aa68c96d-df78-4b75-9c6d-5dd80044ed84.mp4

![Рост за сегодня](https://user-images.githubusercontent.com/88287882/196984786-a0af73fb-ea19-44bb-a501-6f88b69ef55e.png)
![Валюта](https://user-images.githubusercontent.com/88287882/196984797-65e2b180-71d9-4fd2-9eda-0e8cc7474bb7.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@agushasok посмотри пожалуйста
