### ISSUE TITLE
[BUG] Рисование на графике TV снимает привязку виджета

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#550]
### Опишите баг

При попытке установить на графике TV какой-нибудь элемент из панели рисования (линию, надпись и т.д.) - снимается привязка. Не зависит от использования цветных бейджей. Снимается сама "цепочка"

https://user-images.githubusercontent.com/99450543/197033217-04099847-bd56-4e87-98ed-57c299d55793.mp4

### Воспроизведение

1. Открыть виджет "Тех.анализ"
2. Выполнить привязку виджета через цепочку
3. Выбрать элемент рисования и разместить на графике.

### Среда.

win 10, chrome canary 109.0.5371.0

### Ожидаемое поведение

Размещение элементов не снимает привязку

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Это ожидаемое поведение. Если пользователь что-то нарисовал, а потом случайно переключил инструмент, то все пропадет. Элементы рисования не сохраняются и вообще не понятна их целесообразность, если они были наросованы для одного инструмента, а накладываются на совершенно другой

**Comment by dzeron13** [comment]
Вопрос ожидаемости - тут как раз спорный. Раз это часть от TV, то и поведение виджета ожидаешь аналогичное, как было в AlorTradingView. А в нем индикаторы и рисование сохраняется при переключении инструментов и ТФ. Поэтому предложение @PilgrimViis #525 о том, что рисование не нужно хранить - не совсем понял. Возможно дело, в избыточности хранения всего этого на клиенте. 
А так получается, что виджет от TV есть, но логика у него своя и настройками это не регулируется.

Что касается отвязки, тут две стороны:
1. Привязка не снимается. Человек нарисовал, сменил инструмент, рисование пропало. Т.е. получаем неудобство пользователя, что ничего не сохранилось, если он сменил инструмент случайно или он ожидал, что оно сохранится, как это было в TV. Тут возвращаемся к логике, отличной от TV.
2. Привязка снимается. Человек нарисовал, виджет отвязался, сменил инструмент, виджет остался на прошлом инструменте. Если отвязывать виджет не планировалось, это аналогично приводит к недовольству. Т.е. здесь мы сами решили за пользователя, что он хотел оставить этот виджет отвязанным и дальше рисовать на нем. Но не является ли это избыточной заботой?

Поэтому варианта вижу два:
1. Хранить рисование для инструмента. Сохранять при смене ТФ. Люди использующие ТехАнализ, думаю, в курсе про кнопку очистки.
2. Не отвязывать виджет при рисовании, оставляя это решение за пользователем.

Вообще менять что-то у пользователя без его ведома, а уж тем более что-то удалять - так себе затея для дружественного интерфейса ))

**Comment by sbelashevskiy** [comment]
1. Задача по полному копирования виджета и поведения TV не ставилась https://github.com/alor-broker/Astras-Trading-UI/issues/181
2. Мы лишь используем 1 виджет из TV и только часть его функционала.
3. Я описал, что текущее поведение было реализовано целенаправлено, чтобы минимизировать вероятность ошибки со стороны пользоваля. Так что это не баг.
4. Если текущее поведение требуется изменить, что это нужно оформить в виде Feature с описанием требуемого поведения

**Comment by dzeron13** [comment]
Ну, в общем-то согласен  - с точки зрения разработки, это новый функционал.
Тогда данный таск закроем, а я оформлю новый.

**Comment by PilgrimViis** [comment]
> Ну, в общем-то согласен - с точки зрения разработки, это новый функционал. Тогда данный таск закроем, а я оформлю новый.

Да можно этот переделать как feature request.

**Comment by dzeron13** [comment]
Тут бы привлечь живых теханальщиков изнутри компании и рассказать им, что уровни рисовать надо каждый раз заново))

**Comment by PilgrimViis** [comment]
Хорошо, задам вопрос.

**Comment by PilgrimViis** [comment]
Спросил у рабочей группы. Предложили такой вариант
_В идеале сохранять фигуры с привязкой к инструменту, если технически реализуемо. Сейчас получается что наш теханализ полезен только для тех клиентов, кто на одном-трех тикерах торгует_
@sbelashevskiy что думаешь?

**Comment by sbelashevskiy** [comment]
Я не очень понимаю, что значит "сохранять фигуры с привязкой к инструменту" 
Посмотрим TV:

https://user-images.githubusercontent.com/29191749/198960995-2346ff69-92b8-4cfa-bede-37db1c502128.mp4

Нарисованные фигуры сохраняются только то тех пор, пока не перезагружена страница. Также мы сделали тут https://github.com/alor-broker/Astras-Trading-UI/issues/525 с индикаторами

При перезагрузке страницы все пропадает. Вроде вполне логично. Такое же поведение мы можем реализовать для фигур.

Если разговор идет о постоянном сохранении фигур, чтобы они появлялись и после перезагрузке страницы, то возможно мы и можем что-то придумать, но целесообразность этого под вопросом - фигуры привязаны ко времени, на следующий день и малых таймфрэймах они уже будут просто не видны. При этом место localStorage они занимают, а это уже становится важным, учитывая появившиеся проблемы с производимостью

**Comment by dzeron13** [comment]
Хм, мне казалось в AlorTV фигуры сохраняются, как в оригинальном TV - не заметил, что они держатся до перегрузки страницы. Тогда всё гораздо печальней.

Даже если реализовать аналогичное поведение, т.е. сохранение фигур при переключении между инструментами, и хранение в рамках одной сессии, то по сути это только чуть-чуть улучшит положение. Все таки тех.анализ - это не на один день. Те же уровни ставятся, как правило, через "горизонтальную линию", а каналы на 1H и выше, поэтому забытые фигуры день-два назад на младших ТФ вряд ли будут - они там особо бессмысленны.

Но если LocalStorage - единственное место, где можно подобное хранить, то это уже большой вопрос. Начиная от уже упомянутой "нерезиновости" его и заканчивая, что при некоторых обновлениях, его приходится сносить.

**Comment by sbelashevskiy** [comment]
в TV если состояние графика имеет значение есть возможность сохранить / загрузить график
![image](https://user-images.githubusercontent.com/29191749/199011616-26e674b1-204f-45bc-a7a5-9c69bc2e1819.png)
но состояние графика хранится точно не на стороне браузера пользователя - у них для этого облачный сервис.
Насколько помню их документацию там есть возможность реализовать свой сторадж для этого. Но это значит, что нам нужен бэк для этого

**Comment by PilgrimViis** [comment]
@sbelashevskiy не обязательно устаревают. Фигуры могут рисовать и на дневных свечках. Но речь не об этом, речь о том, что люди теряют все что нарисовано когда переключают инструмент. Я вполне понимаю, что для тех кто активно пользуется теханализом это может быть не удобно. Если же мы сделаем настройку которая меняет поведение, чтобы при смене инструмента у нас происходило сохранение всего нарисованного, а при повторном выборе этого же инструмента загрузка, то людям понравится.

**Comment by sbelashevskiy** [comment]
@PilgrimViis 
вопрос не в том хранить или не хранить, а в том - хранить ли только до перезагрузки страницы или хранить постоянно.
Я выше расписал в чем проблема
