### ISSUE TITLE
[FEATURE] Наименование стакана PRO 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#551]
### Опишите проблему, которую решает ваша фича

![image](https://user-images.githubusercontent.com/105817664/197159775-69b3a540-9638-4d3e-9cfc-6888da027b8f.png)
При открытых стаканах , не понятно где какой инструмент. 

### Опишите предлагаемое вами решение

1. Возможность самому переименовывать стакан
2. Убарть надпись "Скальперский стакан"  - оставить наименование инструмента. 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@sbelashevskiy Мы можем для этого стакана перенести имя инструмента в начало названия?

**Comment by sbelashevskiy** [comment]
@PilgrimViis  Сейчас такого нет - названия стандартизованные, но что-нибудь можем придумать

**Comment by sbelashevskiy** [comment]
А может вообще убрать явные названия виджетов. Вместо текста показывать иконки, такие же как в меню создания виджетов и по наведению на иконку показывать полное название самого виджета.
Потому что сейчас  не особо понятно для чего выводить полное название виджета.
Суффикс в виде наименования инструмента или порфеля оставить как есть

**Comment by sbelashevskiy** [comment]
@PilgrimViis сделал два варианта:
1. название инструмента перед названием скальперского стакана ([sb-master/551-1](https://github.com/alor-broker/Astras-Trading-UI/tree/sb-master/551-1))
![image](https://user-images.githubusercontent.com/29191749/198573050-94b399c1-95f6-412e-b514-1497606e9a29.png)
2. Вариант, когда названия виджетов не отображаются, а заменены иконками ([sb-master/551-2](https://github.com/alor-broker/Astras-Trading-UI/tree/sb-master/551-2))
![image](https://user-images.githubusercontent.com/29191749/198577873-b7f0d973-8c9f-4a5f-bc5e-41835d525b58.png)
![image](https://user-images.githubusercontent.com/29191749/198577875-5601d7d6-a262-4c1b-8d2f-d248ca567c1f.png)
![qVrsgOAtRo](https://user-images.githubusercontent.com/29191749/198578145-ebc10c46-8f8b-4ffa-9802-6c2fd8532065.png)
![DOjOYegyct](https://user-images.githubusercontent.com/29191749/198578272-6a547337-ad6c-4d63-88a5-10dfd482cc34.png)

**Comment by uncrashable** [comment]
Это можно будет переключаться , или какой то один вариант оставить ?

**Comment by PilgrimViis** [comment]
@sbelashevskiy круто. Я напишу у рабочей группы спрошу. Я думаю с иконками вообще огонь.

**Comment by sbelashevskiy** [comment]
> 
только один вариант

**Comment by sbelashevskiy** [comment]
> Это можно будет переключаться , или какой то один вариант оставить ?

только один вариант

**Comment by PilgrimViis** [comment]
Оставим вариант с иконкой

**Comment by dzeron13** [comment]
@PilgrimViis, а виджеты, которые "но для виджетов без суффикса типа "Все инструменты" и т.д одной иконки не хватит" без иконки в итоге будут? Может тогда в них выводить и иконку и название? А то они выбиваются теперь из общего стиля.
![image](https://user-images.githubusercontent.com/99450543/200511435-d748e627-d7b2-45ca-abf5-0d077f39a627.png)

**Comment by PilgrimViis** [comment]
@dzeron13 да, согласен. Можете фич реквест повесить, пожалуйста?
