### ISSUE TITLE
[BUG] Не работает  выставление стоп лосса в стакане PRO

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#553]
### Опишите баг

![image](https://user-images.githubusercontent.com/105817664/197166599-3584f893-f0ba-4396-b117-c6aca1f4d57d.png)
Пробую выставить через горячие клавиши стоп лосс , пишет ошибку , нет позиции 

стою по РТС -6 лотов 

### Воспроизведение

Стакан про 
Шортовая позиция 
Мышь в зоне продавца 
зажат шифт  и левой кнопкой мыши по ценовому уровню , где должен быть стоп 

### Среда.

винда 7 
хром 

### Ожидаемое поведение

Выставление стоп  лосса на указанном ценовом уровне 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@uncrashable по коду я вижу, что изначально эта функкция была реализована именно так - при значении кол-ва позиций <= 0 выводится данное сообщение и команда не выполняется.

при кол-ве > 0 создается стоп заявка на ПРОДАЖУ с условием БОЛЬШЕ указанной цены

Что-то изменилось или требования были сформулированы некорректно?
как эта команда должна работать?

**Comment by uncrashable** [comment]
> @uncrashable по коду я вижу, что изначально эта функкция была реализована именно так - при значении кол-ва позиций <= 0 выводится данное сообщение и команда не выполняется.
> 
> при кол-ве > 0 создается стоп заявка на ПРОДАЖУ с условием БОЛЬШЕ указанной цены
> 
> Что-то изменилось или требования были сформулированы некорректно? как эта команда должна работать?


При условии что позиция = 0, то так и должно быть. 
Мне не понятно что значит <0 , если я захожу в **шорт** у меня значение позиции будет отрицательная  , т.е. меньше 0.
В шортах СЛ так же должен работать. Поэтому если код работает именно так , то нужно внести поправку. 
СЛ должен работать как в шорт так и в лонг.  

Опишу:  если позиция =0 , то должно высвечиваться данное сообщение " Нет позиции" 

Если я купил актив , то стоп лосс должен выставляться ниже текущей цены
![image](https://user-images.githubusercontent.com/105817664/197982830-c0622444-2d93-43f0-a4a1-456953b0625d.png)


Если я продал актив ( зашёл в шорт), то стоп лосс должен выставляться выше текущей цены. 
![image](https://user-images.githubusercontent.com/105817664/197983432-6f634e6c-47e0-4d7c-9431-0b00d24e8895.png)

**Comment by sbelashevskiy** [comment]
@uncrashable  Итого. 
Если позиция > 0, то должна выставиться stop market заявка с условием LESS с ценой  выбранной ячейки на ПРОДАЖУ.
Если позиция < 0, то должна выставиться stop market заявка с условием MORE с ценой  выбранной ячейки на ПОКУПКУ.

Так?

Почему эта команда срабатывает только на клики в области продавцов?

**Comment by uncrashable** [comment]
https://user-images.githubusercontent.com/105817664/197987859-102b89b7-77d7-41aa-8288-2f594b895b09.mp4

Вот тут на видео посмотрите , сперва стою в шорт , стоп ставлю выше по цене  ( Если позиция < 0, то должна выставиться stop market заявка с условием MORE с ценой выбранной ячейки на ПОКУПКУ. ) - думаю да . 


и потом перевернул позицию зашел в лонг , стоп ставлю ниже по цене ....

**Comment by sbelashevskiy** [comment]
Подытожу.
1. Стоп-лосс должен выставляться при зажатой клавише SHIFT левой клавишей мыши по ЛЮБОЙ строке таблицы (а не как сейчас только при клике по строке в области продаж)
2. Если кол-во позиций БОЛЬШЕ 0, то нужно создать заявку типа СТОП на  ПРОДАЖУ по РЫНКУ при выбранной цене с условием  МЕНЬШЕ
3.  Если кол-во позиций МЕНЬШЕ 0, то нужно создать заявку типа СТОП на ПОКУПКУ по РЫНКУ при выбранной цене с условием  БОЛЬШЕ
4. Если кол-во позиций РАВНО 0, то команда не выполняется, отображается ошибка "Позиции для установки стоп-лосс отсутствуют"

так?

**Comment by uncrashable** [comment]
Да всё верно. 

И еще стоит учесть. Если кол-во позиций БОЛЬШЕ 0, то заявка типа СТОП на ПРОДАЖУ по РЫНКУ  при выбраной цене должна выставляться только НИЖЕ точки входа в позицию. 

т.е. если я купил по 100 , то стоп лос я не могу поставить выше этого значения. Только ниже 99...98 и т.д. 
если будет попытка выставить СТОП выше цены входа , то ничо не должно происходить.
