### ISSUE TITLE
[FEATURE] Отсутствие какого либо обозначение стоп заявок в стакане PRO [18]

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#555]
### Опишите проблему, которую решает ваша фича

При выставлении условной заявки и стоп лосса в стакане нет никакого обозначения 

### Опишите предлагаемое вами решение

При выставлении заявки нужно добавить в стакан обозначение стоп лосса SL  в панели где отображаются лимитки например. 
И условных заявок.   Условные заявки нужно выделить что бы понимать что это именно стоп заявка и на какой объем. 

### Правила

- [X] Я согласен следовать правилам

**Comment by uncrashable** [comment]
Зажали шифт, появилась надпись как на скрине . 
Нажали мышкой , появился в стакане стоп лосс на определенной цене.
Будет понятно , что кнопка зажата. И где будет установлен SL

**Comment by uncrashable** [comment]
![image](https://user-images.githubusercontent.com/105817664/197408026-8c4b9a65-9492-4fe6-a56f-e106d275d2bb.png)

**Comment by uncrashable** [comment]
Условная заявка у нас выставляется по левому контролу. 
При нажатии , необходимо подсветить Режим: условная заявка. 
Так мы понимаем что клавиша зажата и включен данный режим для выставления.
![image](https://user-images.githubusercontent.com/105817664/197408211-dd91c83b-a6ab-46d9-97bf-51c46cb1bbe5.png)
Далее кликаем мышкой , если в верхней части стакана, то выставится Buy Limit с объемом 10 (текущий рабочий объем), т.е. как только цена доходит до

**Comment by uncrashable** [comment]
Плюс фичи, выставляем такие заявки перед новостями ,  дернулся рынок наверх , мы вошли в лонг , дернулся вниз , вошли в шорт

**Comment by sbelashevskiy** [comment]
@uncrashable , @PilgrimViis ,
в ASTRAS нет заявки типа Stop loss. Есть stop market. StopLoss с точки зрения ASTRAS  это всего лишь логика установки stop market c текщим значением позиции и ее средней ценой. Сейчас в скальперском стакане отображаются stop limit (SL) и stop market (SM) заявки. После установки stop заявки мы никаким образом не можем понять stop loss это или take profit или что-то еще и чем они отличаются от обычных stop заявок т.к ставятся такие заявки в зависимости от текущей позиции и ее средней цены. Соответственно если позиция поменялась (изменилось кол-во лотов или средняя цена), то мы по обычному stop уже никаким образом не поймем какую семантику эта заявка носит. 

Если нам нужно отличать одну stop заявку от другой по какой-то метке, то нужно модифицировать API чтобы у заявки можно было указывать текстовую метку и потом ее читать

**Comment by PilgrimViis** [comment]
@sbelashevskiy я думаю @uncrashable имел ввиду подсветку всех стоп заявок. По поводу того, что сказал ты подтверждаю. У нас условные заявки. Конкретно stoploss\takeprofit нет. Мы можем помечать что это просто стоплимит (SL)

**Comment by uncrashable** [comment]
Тут нюанс, который я не сильно понимаю. Обычно под стоп лосом обозначают ордер на закрытие позиции. Тэйкпрофит по сути не нужная функция , и ее можно вообще не использовать. 
 Но если я правильно понял теперь. То стоп маркет и стоп лимит , это ордера на закрытие позиции, только маркет ударит по рынку , и лимит выставит лимитную заявку , которая может вообще не исполнится при резком проливе цены. 



и да , я в этой ветке описал проблемы именно обозначения в стакане , а не исполнения.

**Comment by PilgrimViis** [comment]
SL означает не StopLoss, а StopLimit.
