### ISSUE TITLE
[BUG] Частые ошибки с соединением

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#556]
### Опишите баг

![image](https://user-images.githubusercontent.com/105817664/197219918-31ca68d5-5cf7-4d52-a2a2-5b68ff231ed3.png)
![image](https://user-images.githubusercontent.com/105817664/197220312-5ef409e9-5421-4b24-8386-e0b3a01a56bb.png)
Часто дисконектит ,  проверяю сразу интернет - работает. Но вылетают вот такие ошибки

### Воспроизведение

Просто при работе  страницы 

### Среда.

Винда 7
хром 

### Ожидаемое поведение

Стабильная работа

### Правила

- [X] Я согласен следовать правилам

**Comment by uncrashable** [comment]
Опять .... окно причем астраса было открыто, делал настройки. 

![image](https://user-images.githubusercontent.com/105817664/197478024-7524258c-b578-40d0-bafc-8d56fd1ed172.png)

**Comment by uncrashable** [comment]
После этой ошибки , обновил страницу , всё как бы заработало . Но, пытаюсь снять лимитку  - пишет 
![image](https://user-images.githubusercontent.com/105817664/197479202-7c76c8cd-63f7-4033-8d1a-7e6d2a1afbbd.png)

**Comment by uncrashable** [comment]
Обновление страницы не помогло 
Перелогинился - не помогло. 
Закрыл вкладку и зашел по новой - не помогло.

**Comment by PilgrimViis** [comment]
Цитирую переписку. Так как проблемы на бекенде, то на github это задачу закрою. Это не в наших силах поправить, а коллеги уже в курсе проблем. Будем ждать фикса на их стороне.

------------------------------------------------------
Бормотов Константин [24.10.2022 09:50:42]
Есть баг на Астрас вот тут описание https://github.com/alor-broker/Astras-Trading-UI/issues/556 считает что проблема на стороне бэка.
------------------------------------------------------

------------------------------------------------------
Филин Александр [24.10.2022 09:55:27]
Первый 99% что на бэке. Есть плавающая проблема на срочке, пока не смогли исправить
ВТорой пункт больше на фронт похож
------------------------------------------------------

------------------------------------------------------
Белашевский Сергей [24.10.2022 10:19:35]
ну там вот в issue описывают вообще три разных проблемы. Первая - при выставлении заявки бэк отвечает, но отвечает с ошибкой timeout.
Вторая - при выставлении заявки бэк отвечает и говрит - 400 Bad request. Почему Bad request непонятно, т.к. бэк ничего по этому поводу не сказал. Если бы он прислал code и message, то мы бы их отобразили, но что-то из них приходит пустое
Третья - якобы падения коннекшена, но как это связано с предыдущими проблемами непонятно, потому что в обоих случаях респонз от бэка приходит
------------------------------------------------------

------------------------------------------------------
Филин Александр [24.10.2022 10:59:44]
[Цитата]
В общем, по первой проблеме работаем. По второй и третьей нужно больше инфы
------------------------------------------------------

**Comment by sbelashevskiy** [comment]
[astras.alor.ru (1).zip](https://github.com/alor-broker/Astras-Trading-UI/files/9887722/astras.alor.ru.1.zip)
Записали логи. Почему то отправляются limit запросы, успешно выполняются, а потом они повторяются снова
