### ISSUE TITLE
Как сделать авторизацию через refresh token?

### ISSUE THREAD

**Issue by exvion** [alor-broker/Astras-Trading-UI#560]
Склонировал репо Astras. Выписал себе токен на https://alor.dev/open-api-tokens. Только не могу понять куда в проекте его добавлять, чтобы не приходилось через sso вводить логин и пароль при авторизации?

**Comment by exvion** [comment]
В коде вижу clientDataUrl: 'https://lk-api-dev.alorbroker.ru', ssoUrl: 'https://login-dev.alor.ru' Где найти документацию по api для доступа к этим серверам? На сайте только описание https://alor.dev/tools

**Comment by PilgrimViis** [comment]
@exvion здравствуйте. Не уверен, что токен оттуда будет полностью совместим. Но можете попробовать. Сам токен мы храним в переменной user в local storage в поле jwt.

**Comment by PilgrimViis** [comment]
> В коде вижу clientDataUrl: 'https://lk-api-dev.alorbroker.ru', ssoUrl: 'https://login-dev.alor.ru' Где найти документацию по api для доступа к этим серверам? На сайте только описание https://alor.dev/tools

В данный момент документации нет. Это SSO Алора, принцип работы примерно следующий. С Астраса когда мы видим что токен рефреш экспирировался или его нет, мы делаем редирект на ssoUrl. Там пользователь авторизуется с его логином и паролем и делается обратный редирект на Астрас. В URL обратного редиректа передаются JWT и refresh токены. Которые Астрас сохраняет уже к себе и потом работает с ними.

**Comment by PilgrimViis** [comment]
P.S. Все URL в которых есть слово 'dev' скорее всего на тестовый контур. Часть их них даже не будет пинговаться, т.к. доступна только из нашей локальной сети. Поэтому смотрите на url без dev и в прод конфигурации.

**Comment by PilgrimViis** [comment]
Так как вопросов по теме больше не было, то задачу закрою.
