### ISSUE TITLE
[BUG] Центровка в стакане PRO

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#561]
### Опишите баг

При нажатии Пробел - центровка стакана, у меня наблюдается "задёрг". Стакан сперва смещается вниз, а потом центририруется. 

### Воспроизведение

Стакан PRO 
Центровка активного стакана по пробелу

### Среда.

Винда 7
Хром

### Ожидаемое поведение

Стакан должен центрироваться , без "подскакивания" 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@uncrashable прикрепите, пожалуйста, виде что и куда и на каком инструменте у вас наблюдается "задёрг. Я не вижу ничего аномального

https://user-images.githubusercontent.com/29191749/197466680-34dbeaff-2700-44ad-a768-683cefa7a3aa.mp4

**Comment by uncrashable** [comment]
https://user-images.githubusercontent.com/105817664/197495492-60d673c0-22db-4993-b50e-0d0fd017db63.mp4

Не всегда есть такое , только когда начинаешь выставлять лимитки ,

**Comment by uncrashable** [comment]
такое было и по другому инструменту. Вот сейчас торговал сишку и появилось.

**Comment by sbelashevskiy** [comment]
Понял. Видимо после клика по кнопке ячейка остается активной и при нажатии пробела применяется дефолтное поведение - браузер пытается проскроллить до ячейки, а потом скроллит уже до центра стакана
