### ISSUE TITLE
[BUG] Не верные цены в стакане PRO

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#567]
### Опишите баг

![image](https://user-images.githubusercontent.com/105817664/197493510-943df7fc-153c-418c-ae1c-7dff5a460ca5.png)
Поставил лимитку на открытие позиции по нефти. 
Мне тут же показывает , что у меня + 100п. 
Начал разбираться, сейчас нефть торгуется на 92,5 а у меня в стакане показывает  93,7
Закрыл виджет и открыл по новой , почему то в нефти , показывает не верные цены в стакане. 

### Воспроизведение

саздать виджет стакана PRO по br 11.22 фьючерс

### Среда.

Винда 7
Хром

### Ожидаемое поведение

Корректные цены 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
похоже на проблемы со стороны сервера. На TV также

**Comment by uncrashable** [comment]
https://user-images.githubusercontent.com/105817664/197498386-60535ebb-58fb-43cf-81f1-2632d08b9ccf.mp4

и в обычном стакане то же баг

**Comment by sbelashevskiy** [comment]
Проблема была на сервере - стаканы зависли. Сейчас уже поправили
