### ISSUE TITLE
[FEATURE] Внести изменение в исполнение заявок по клику мыши в PRO [11]

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#574]
### Опишите проблему, которую решает ваша фича

В данный момент если на офферах нажать правую кнопку мыши , то заявка у нас полностью исполнится (весь рабочий объем). Ровно как бы мы нажали на клавиатуре S (купить по рынку). 
Здесь стоит внести поправку.
Если у меня выбран рабочий объем 1000 лотов. И я сейчас навожу курсор  на 98,61 и нажимаю ПКМ.  
То должно произойти следующее. 
Покупается оффер  по 98.6    253 лота , а остальная часть заявки моей ставится в стакан в виде лимитки 

![image](https://user-images.githubusercontent.com/105817664/197776191-5a025a79-5e68-4467-a49e-c24874039203.png)

### Опишите предлагаемое вами решение

внести корректировку

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Почему нельзя ставить лимитку сразу?
