### ISSUE TITLE
[BUG] Блоттер. Неправильное округление цены в сделках 

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#575]
### Опишите проблему, которую решает ваша фича

В совершенных сделках, цена округляется, хотя по объему видно, что она была иной
![image](https://user-images.githubusercontent.com/99450543/197850728-8737a2d7-260b-4911-8da8-57da3d5c8410.png)

### Опишите предлагаемое вами решение

Выводить реальную цену сделки.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Да, похоже что есть округление и оно неправильное. Надо бы округлять в соотвествии с шагом цены. Думаю это баг.

**Comment by PilgrimViis** [comment]
Надо проверить и поправить. Мы вроде делали это уже, но может тут какой-то граничный случай.
