### ISSUE TITLE
[BUG] Автовключение привязки инструмента в стакане PRO

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#579]
### Опишите баг

После того, как вносишь любые изменение в стакан, сохраняешь, при выходе включается автоматески привязка инструмента  
![image](https://user-images.githubusercontent.com/105817664/198266661-403c5de3-0f9f-47b8-8da8-a24066af74cc.png)

### Воспроизведение

Создать виджет стакан PRO 
Отключить привязку инструмента
Зайти в настройки , что нибудь сделать - сохранить. 

### Среда.

Винда 7 
Хром

### Ожидаемое поведение

Отключил, значит отключил ) 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Это не баг, так и задумано. Стакан должен настриваться один раз. А так как можно в настройках ещё поменять инструмент, группу торгов и т.д., то надо отвязывать от старого инструмента.

**Comment by sbelashevskiy** [comment]
это побочный результат https://github.com/alor-broker/Astras-Trading-UI/issues/517.
Такой кейс не учитывался.
Можно починить, поправив условие 
это условие
`newSettings.linkToActive = isInstrumentEqual(initialSettings, newSettings)`
заменить на это
`newSettings.linkToActive = initialSettings.linkToActive &&  isInstrumentEqual(initialSettings, newSettings)`

тогда должно работать как описано

**Comment by uncrashable** [comment]
Попровьте по возможности. 
Приходится иногда рабочие объемы подстраивать , цвета объмов. Стаканы переключать , так как нужно смотреть больше инструментов, а у нас при переключении инструмента в одном стакане , остаются все настройки. Стакан я переключил, и сразу нужно его немного подстроить.
