### ISSUE TITLE
[FEATURE] Снимать все заявки после закрытия сделки  в стакане PRO

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#586]
### Опишите проблему, которую решает ваша фича

При активной торговли выставляется множество заявок, которые в случае закрытия "висят" уже не нужными.
Т.к. идея сработала/ не сработала.

### Опишите предлагаемое вами решение

Добавить в меню настроек стакана или по умолчанию, что бы все заявки/ стоп заявки снимались после закрытия позиции. 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@uncrashable распиши пожалуйста подробней свою идею.

**Comment by uncrashable** [comment]
Вошел в рынок в покупку по цене 100 на 5 лотов. 
Поставил стоп лосс по цене 90. 

Ждешь прибыли, расставил лимитки по 1 лоту на закрытие  по 105 , 110,  120  ... 

цена пошла вниз, тебя выбило по стопу....а лимитки  всё еще весят вверху. Они уже не нужны , потому что они были для закрытия позиции.

и если их не снять , то когда цена дойдет до этого уровня, то тебя откроет в шорт. 

На рынке бывает что резко прольют вниз (тебя закрыли) и резко стрельнули вверх , ты уже в шортах ( но этого не планировал) 


а еще может быть такое, что ты торгуешь НЕ шортовой бумагой.  тебя зырквает по стопу , а лимитки на продажу висят еще выше цены входа. Шортов нет , как поведет себя система ? Выдаст ошибку ?

**Comment by PilgrimViis** [comment]
А что если цена скакнет и лимитки выполнятся? Думается мне, что такого рода вещи надо делать на бекенде.

**Comment by PilgrimViis** [comment]
На бекенде будут делать связанные заявки. Когда сделают, то можно будет рализовать корректно.
