### ISSUE TITLE
[FEATURE] Сделать поиск инструмента по названию инструмента во всех виджетах где есть выбор инструмента

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#587]
### Опишите проблему, которую решает ваша фича

Трудность в переключении инструмента в стакане и графике.

### Опишите предлагаемое вами решение

В настройках стакана и графика, есть возможность выбора инструмента, но только при точном вводе тикера.
Поиска там нет. 
Предлагаю добавить поиск инструмента в меня самого стакана 

![image](https://user-images.githubusercontent.com/105817664/198883307-2938f8f6-ddc3-4ee7-a23b-4d32760aae17.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by scarletcloak** [comment]
Переписал задачу. Думаю надо сделать во всех виджетах где есть выбор инструмента.
1. Стакан.
2. Скальперский стакан
3. График
4. График ТВ.
Что забыл?

**Comment by PilgrimViis** [comment]
Переписал задачу. Думаю надо сделать во всех виджетах где есть выбор инструмента.

Стакан.
Скальперский стакан
График
График ТВ.
Что забыл?
