### ISSUE TITLE
[BUG] Не ставится заявка в спред в стакане PRO

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#588]
### Опишите баг

Пробовал ставить заявку в спред мышью. 
Она просто не ставится , ничего не происходит

### Воспроизведение

Создать стакан PRO 
Найти большой спред попробовать выставить заявку мышью

### Среда.

Винда 7
Хром

### Ожидаемое поведение

Заявки должны мышью ставится в спред

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
В спред заявка не ставится потому что при текущем виде стакана мы не можем без запроса дополнительной информации определить ставить заявку на ПОКУПКУ или ПРОДАЖУ

**Comment by uncrashable** [comment]
Когда описывал клавиши мышью , изначально было что лкм в бидах или в спреде - покупка , правая продажа по рынку. а в офферах правая кнопка ставила лимитки и в спред так же можно было выставиться.  

Но с вашей стороны посчитали что так не удобно и сделали по другому.  

При такой работе мышью, как сейчас , лимитку выставить не возможно.

**Comment by uncrashable** [comment]
в ТВ очень большой стакан , нам место важно. Чем больше стаканов в момент тем лучше. 

можем оставить так как есть , будем по клавишам заходить ( хотя может это будет и не удобно кому-то)

**Comment by sbelashevskiy** [comment]
Вот задача по кликам https://github.com/alor-broker/Astras-Trading-UI/issues/239.
Переделана была только логика чтобы за один тип заявки отвечали одинаковые кнопки мыши, а не переворачивались в зависимости от зоны продавцов и покупателе.

Про спред речи не было. Если будет полное описание какую заявку выставлять при клике по спреду на ПОКУПКУ или ПРОДАЖУ, то мы и при текущей реализации это можем сделать.
Однако 95% появятся пользователи, которые скажут, что им неудобно при клике выставлять заявку только на продажу или только на покупку

**Comment by sbelashevskiy** [comment]
У виджета есть предел ширины, когда он еще читается, например такой
![image](https://user-images.githubusercontent.com/29191749/198971533-734d8136-3631-4f17-8d76-297b460e290e.png)
даже при таком сжатом состоянии ячейки занимают 20px ширины - вполне достаточно, чтобы при наведении на левую/правую часть строки подсветить надписи Sell/BUY и усранить неопределенность. Такое можно сделать хотя бы для спрэда. И тогда проблема будет устранена

**Comment by uncrashable** [comment]
Я вообще за экономию места, очень мало стаканов помещается в данный момент на экране. 

Если реализовывать подобное , то например если навести на панель объема это лимитка на покупку в спреде, а если навести на панель собственных заявок (которою очень хочется уменьшить)  то лимитка на продажу. Так наверное будет нормально

**Comment by PilgrimViis** [comment]
Это совершенно точно не баг, поэтому надо открывать задачу, подробно описать как новую фичу и уже там продолжить обсуждение.
