### ISSUE TITLE
[FEATURE] Внести изменения в цветовое отображение лимиток в скальперском стакане

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#589]
### Опишите проблему, которую решает ваша фича

В стакане выделяются только лучшие цены на покупку и продажу полной строкой. (заливкой) 
Когда меняется отображение лимитных заявок в стакане отображаются только объемы. Очень сложно воспринимать данные. 
![image](https://user-images.githubusercontent.com/105817664/198900997-74b84b33-1954-4b82-90b2-002554a36154.png)

### Опишите предлагаемое вами решение

![image](https://user-images.githubusercontent.com/105817664/198900933-46a7b633-05ef-4f99-a993-4c59bfdde8dc.png)
При условии , что в стакане есть лимитная заявка залить цветом полностью объем и цену
если это лучший бид или оффер то залить полностью строку , включая место где отображается выставление собственных заявок(залить цветом полностью строку). 
Так гораздо нагляднее видно заявки , особенно при резких изменениях цен
Лучший бид/оффер залить более интенсивным цветом

p/s/ на красную стрелку внимание не обращайте 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
"Когда меняется отображение лимитных заявок в стакане отображаются только объемы. Очень сложно воспринимать данные."

Не понятно о чем идет речь. Скрин сверху ничего не показывает. При выставлении лимитной заявки в стакане явно появляется синяя кнопка с количеством лотов в заявке, при клике на которую она снимается. Вроде это должно быть гораздо понятнее, чем просто выделение цветом.

**Comment by uncrashable** [comment]
![image](https://user-images.githubusercontent.com/105817664/198956294-a619acf2-1a97-410c-9b4f-a6c332cc32b9.png)

**Comment by uncrashable** [comment]
Тут речь не о собственных заявках. А именно о чужих
