### ISSUE TITLE
[BUG] Профиль-Отчеты. Неактуальная ссылка

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#59]
### Опишите баг

Кнопка "Отчеты" из иконки профиля ведет на страницу: "https://lk.alor.ru/broker/reports"

### Воспроизведение

1. Нажать на иконку профиля
2. Выбрать "Отчеты"

### Среда.

- ОС Windows 10
- Браузер Chrome
- Версия 100.0.4896.127

### Ожидаемое поведение

Переход на страницу "https://lk.alor.ru/reports/broker"

### Правила

- [x] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Спасибо. Исправим.
