### ISSUE TITLE
[FEATURE] Корректировка по исполнению стоп заявки

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#591]
### Опишите проблему, которую решает ваша фича

Была ситуация. Вошел 1 лимиткой, поставил стоп лосс , выше еще наставил лимитки.
Цена доходила до меня и я набрал позицию. 
После того, как сработал стоп , то у меня позиция закрылась не полностью, а только на 1 лимитку , по которой я первой заходил

### Опишите предлагаемое вами решение

Прошу внести корректировку по исполнению стоп лосса.

Нужно что бы стоп лосс учитывал всю мою текущую позицию, и закрывал не только часть а всю сделку , не важно где и как я заходил в нее. 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Ничего не понял. Можешь по нормальному описать.
Как есть сейчас по шагам. 
1. Выставляю лимитную заявку на объем 10
2. Выставляю стоп-лосс... 
и так дажее и тоже самое про
Как должно быть. Тоже по шагам.

**Comment by uncrashable** [comment]
У нас сейчас. 
1. Выставляю несколько лимитных заявок на покупку в диапазоне (по разным ценам) 
2. У меня исполняют 1 заявку 
3. Ставлю стоп лосс. 
Вот этот стоп лосс будет работать именно для этой 1 заявки. Если потом рынок пойдет против меня(собирая остальные мои лимитные заявки) и сработает стоп лосс, то у меня по стопу закроется только часть моей позиции.  


Как должно быть: 

![image](https://user-images.githubusercontent.com/105817664/201350057-1b6b880b-b95a-4323-b024-417e9da392a6.png)
Стоп должен закрыть всю позицию полностью.  

Зашел в рынок , поставил стоп , потом можно докупаться или скидывать часть позиции, а стоп должен понимать сколько у меня сейчас на руках лотов и закрывать все при срабатывании

**Comment by sbelashevskiy** [comment]
@PilgrimViis ,
насколько я понимаю это задача для backend

**Comment by PilgrimViis** [comment]
Это связанные заявки. Их делать надо на бекенде и в планах на этот этап их нет. Так как задача на 99% бекенд, то на гитхабе я её закрою. Когда реализуем связанные заявки вернемся. Но это будет уже в середине-конце года.
