### ISSUE TITLE
[FEATURE] Улучшение визуализации стакана [1]

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#592]
### Опишите проблему, которую решает ваша фича

В скальперском стакане очень важна минимизация. Экономия пространства.

### Опишите предлагаемое вами решение

![image](https://user-images.githubusercontent.com/105817664/199091193-b9cf6ac0-05d6-456c-b4e3-6f15299fb8f5.png)

Предлагаю сделать центровку: 

- панель объемов отцентрировать по нижней границе и по правому краю. 
- панель цен отцентрировать по нижней границе  и правому краю
В целом уменьшить высоту ячеек 

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@sbelashevskiy Что думаешь?
