### ISSUE TITLE
[FEATURE] Индиктор сделки внизу стакана. Коррекция визуализации

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#593]
### Опишите проблему, которую решает ваша фича

Улучшить вид

### Опишите предлагаемое вами решение

![image](https://user-images.githubusercontent.com/105817664/199092758-59eb0ab5-9fc6-416a-9db5-a37bec7c48d0.png)
Предлагаю в нижней части стакана про, улучшить вид.  Сделать рамку, отцентрировать

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Это выглядит даже как-то не очень. Понимаю, что ты в пеинте рисовал, но не понимаю зачем там рамка вообще. @Tattydes  (это дизайнер, Жень) что думаешь? Нужна там рамка или нет?

**Comment by uncrashable** [comment]
Тут вопрос больше вневшнего вида. Можно и так оставить

**Comment by Tattydes** [comment]
@PilgrimViis подскажи, какая вообще задумка выделить этот элемент? какие там показатели?
Если хотите выделить, то можно рамку сделать зеленым (если это только для покупки), желтый слишком выбивается из общего стиля.

**Comment by PilgrimViis** [comment]
Это не ко мне вопрос, а к @uncrashable

**Comment by uncrashable** [comment]
@Tattydes  рамка облегчает восприятие,  вот для примера , у нас и по сравнению с аналогами

![image](https://user-images.githubusercontent.com/105817664/200797722-2c2e1a7e-d539-447b-81d0-1fbc6cc244ce.png)
![image](https://user-images.githubusercontent.com/105817664/200797789-74ed8466-41a7-42eb-899f-10d36f4d4261.png)
