### ISSUE TITLE
[FEATURE] Блоттер, стопы. Названия в фильтре статуса

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#596]
### Опишите проблему, которую решает ваша фича

В таблице стопов статус отображается как "Отменен", "Активен", "Исполн". При этом в фильтре значения "Отменена", "Исполнена", "Активна" - видимо от заявок осталось.
![image](https://user-images.githubusercontent.com/99450543/199182269-976e7ab9-5c75-44f4-a548-84473e6f7323.png)

### Опишите предлагаемое вами решение

Поправить наименования в фильтре

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я думаю можно и так и так. Ведь это или Стоп (т.е. он). Или Стоп-заявка (т.е. она). Поэтому не будем менять.
