### ISSUE TITLE
[BUG] Профиль-Настройки. Не сохраняется опция "Вертикальная прокрутка"

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#60]
### Опишите баг

В настройках профиля не сохраняется опция "Вертикальная прокрутка"

### Воспроизведение

1. Нажать на иконку профиля
2. Выбрать "Настройки"
3. Изменить опцию "Вертикальная прокрутка"
4. Нажать "Ок"
5. Повторно зайти в настройки.

### Среда.

- ОС Windows 10
- Браузер Chrome
- Версия 100.0.4896.127

### Ожидаемое поведение

Сохранение состоянии опции после нажатия "Ок"

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Спасибо. Эту настройку мы забыли убрать. Исправим.
