### ISSUE TITLE
[FEATURE] Добавить автоматическое заполнение поля "Цена" для условных заявок

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#601]
### Опишите проблему, которую решает ваша фича

Сделать динамическое заполнение поля "Цена" во вкладке "Условная" при разных ситуациях:
1) При включенных "горячих клавишах" если выбрать уровень цены в Скальперском стакане, нажав left shift (выставление стоп-лосса), а затем в модальном окне заявки указать тип стопа -  "Limit", то в поле "Цена" не указывается та цена, по которой был совершен клик пользователем. Приходится указывать ее вручную, вспоминая цену, а это не совсем удобно (видео 1).

2) Для виджета "Выставление заявки" во вкладке "Условная" для Цены аналогичная ситуация. По умолчанию указывается 0, хоть цена была уже выбрана в Стакане. Причем, при смене типа стопа на "Limit" и кликах на уровни цен в обычном стакане поле заполняется корректно. Кроме того, при указании "market", а потом снова "Limit" сохраняется не последняя выбранная цена по инструменты, а предыдущая для этого поля (видео 2). На видео из-за этого видна разница в ценах во вкладках "Лимитная" и "Условная".

3) В виджете "Выставление заявки" при клике на лучшие цены ask и bid - для условных заявок поле "Цена" заполняется указанным значением. Но для модального окна выставления заявки такого не наблюдается, поле "Цена" равно 0 и не меняется (видео 3).

### Опишите предлагаемое вами решение

Сделать динамическое заполнение поля "Цена" для условных заявок в описанных выше кейсах. Такое поведение уже реализовано при обычном клике ЛКМ на уровень цены в Скальперском Стакане: в поле "Цена" проставляется корректное значение.

### Дополнительная информация

1) Проверить сначала через ЛКМ, а потом через left shift:
https://user-images.githubusercontent.com/88287882/199484853-0b1c33e3-1d22-4642-a797-f43e0b9f6f0e.mp4

2) Заполнение цены через клик по стакану:
https://user-images.githubusercontent.com/88287882/199486585-b3f044a9-40a2-4287-bff4-5cc62f664819.mp4

3) Заполнение цены через клик по ask и bid:
https://user-images.githubusercontent.com/88287882/199489664-ba6fd510-3e3a-4a78-8035-bfa69b628066.mp4

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@sbelashevskiy что думаешь?

**Comment by sbelashevskiy** [comment]
Описанные проблемы уже неактуальны. Все обозначенные кейсы уже исправлены в рамках https://github.com/alor-broker/Astras-Trading-UI/issues/1108
