### ISSUE TITLE
[BUG] При отключении в стакане "горячих клавиш" некоторые из них продолжают работать

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#602]
### Опишите баг

Горячие клавиши для установки стоп-лосса (left shift), выставления условной заявки (left ctrl) и центровки по спреду (пробел) работают при отключении соотв. настройки в виджете. Также 

### Воспроизведение

1. Выставить виджет "Скальперский стакан".
2. В настройках виджета включить тумблер "Выключить горячие клавиши".
3. Поочередно нажать left shift, left ctrl и пробел для проверки работы горячих клавиш.

### Среда.

Windows 10
Goggle Chrome, v106.0.5249.119 

### Ожидаемое поведение

Ни одна из горячих клавиш не работает.

### Скриншоты

https://user-images.githubusercontent.com/88287882/199479331-ffbf6fbe-19ff-47f2-8d17-d59435321d16.mp4

### Дополнительная информация

Также работает клик ПКМ - для выставления рыночной заявки (открывается соотв. вкладка в модальном окне). Возможно ее тоже стоит добавить под ограничение "Выключить горячие клавиши". 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
1. Клики мыши и горячие клавиши - это разные вещи. Для кликов своя настройка. Если совсем выключить клики, то какой смысл в виджете
2. Пробел не приводит к отправке заявок. Он служит для удобства просмотра. Какой смысл его отключать?

**Comment by sbelashevskiy** [comment]
@PilgrimViis это ожидаемое и логичное поведение. Я не вижу что здесь править

**Comment by PilgrimViis** [comment]
Звучит логично.
