### ISSUE TITLE
[FEATURE] Отображать поля с ценами во "Всех инструментах" в одной валюте

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#603]
### Опишите проблему, которую решает ваша фича

Сейчас в виджете "Все инструменты" для иностранных акций, облигаций в ин. валюте (RU000A1034K8), валютных пар (USDZAR_TOM) и инструментов SPBX поля "Цена". "Макс. цена" и "Мин. цена" представлены в иностранной валюте, которая отображается в колонке "Валюта". 
Однако для иностранных ETF "Цена" конвертируется в рубли, а макс/мин цены остаются в иностр. валюте. Хотя в поле "Валюта" выбрана иностранная валюта.

### Опишите предлагаемое вами решение

Сделать единое отображение полей с ценами для всех инструментов: в валюте цены, указанной в поле "Валюта" виджета. 

### Дополнительная информация

![image (112)](https://user-images.githubusercontent.com/88287882/199497598-e956fd39-9c39-4c3d-b056-69825bcc229c.png)

![2022-11-02_14h38_12](https://user-images.githubusercontent.com/88287882/199497564-7c916612-b0ad-4a66-bdff-20415f149cee.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Мы вообще-то просто публикуем то что пришлю с бека в эти поля. Пожалуйста уточни у Кирилла или Саши, или сам кинь запрос постаманом и проверь что приходит.

**Comment by PilgrimViis** [comment]
@ilya7am есть новости по этому вопросу?

**Comment by ilya7am** [comment]
По ETF посмотрел, теперь верно все отображает, в одной валюте. Но теперь остались некоторые облигации в иностранной валюте. Например, облигация RU000A1007R9 - торгуется в USD, по апи по запросу /quotes поле с ценой также в usd, но в /advanced цена переводится в рубли, из-за этого цена отличается в виджете "Выбор инструмента" и "Все инструменты":
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/b504f8ea-4a57-4471-bbae-0685af91e572)


Спросил этот момент, напишу, как будут подробности (скорее всего завтра).
