### ISSUE TITLE
[BUG] Разное отображение полей и значков для модального окна и виджета Заявки 

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#604]
### Опишите баг

Для модального окна Выставления заявки и виджета Выставления заявки по-разному отображается поле "Группа" во вкладках Лимитная и Рыночная (1 скрин).
Поле "Цена" для изменения стоп-лимитной заявки располагается под графой "Тип стопа", а не справа, как в модальном окне или виджете Выставления заявки (2 скрин).
В модальных окнах "Выставить заявку" и "Изменить заявку" кнопка "Справка" или "Крестик" выделены синим, как при наведении курсора мыши. При клике по рабочей области модального окна цвет иконок становится прежним (3 скрин).

### Воспроизведение

1. Поставить виджет "Выставление заявки" по тикеру MAGN.
2. Переключиться между вкладками "Лимитная" и "Рыночная".
3. Сравнить поля "Группа" с модальным окном выставления заявки.
4.  Выбрать портфель, где есть активный стоп-лимит, и нажать на "Изменение заявки".
5. Проверить поле "Цена" для открывшегося модального окна.
6. Для модального окна выставления и изменения заявки посмотреть на отображение значков в самом верху.

### Среда.

Windows 10
Goggle Chrome, v106.0.5249.119

### Ожидаемое поведение

1. Поле ""Группа" растягивается до конца блока в модальном окне и в виджете "Выставить заявку".
2. Поле "Цена" расположено справа, на уровне с "Тип стопа".
3. Значки "Справка" и "Крестик" для виджетов и модальных окон одинакового цвета.

### Скриншоты

![2022-11-02_16h39_15](https://user-images.githubusercontent.com/88287882/199508092-ebf72e60-c8df-4854-8d45-9e4b0fbb0001.png)
![2022-11-02_16h43_00 (1)](https://user-images.githubusercontent.com/88287882/199508419-e2932535-9fdd-4592-93e1-713f2e8c1a4d.png)
![2022-11-02_17h22_32](https://user-images.githubusercontent.com/88287882/199514488-8c263802-d088-42f0-8d3d-3309f275bfb2.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
На вкладке Лимитная все поля имею размер 50%.
![image](https://user-images.githubusercontent.com/29191749/201016000-1d86e262-63f8-440b-ae54-191a566acf78.png)
![image](https://user-images.githubusercontent.com/29191749/201016082-ad3f1e59-c9c1-4218-a507-d89d9c05c2d0.png)
На вкладке Рыночная - все поля имеют размер 100%
![image](https://user-images.githubusercontent.com/29191749/201016036-c41bb7da-6437-4e5b-95a9-cb552411109c.png)

![image](https://user-images.githubusercontent.com/29191749/201016112-2e95a2b4-e7ec-4295-9277-2699df4b6419.png)


Не вижу что здесь править
