### ISSUE TITLE
[FEATURE] Изменение верхней панели

### ISSUE THREAD

**Issue by Tattydes** [alor-broker/Astras-Trading-UI#607]
### Опишите проблему, которую решает ваша фича

Пункты виджеты и добавление заявки выглядят похожими по функционалу. Необходимо привести все пункты хидера к единому стилю. 

### Опишите предлагаемое вами решение

Сделать три пункта в обновленном дизайне: Виджеты, Портфель, Заявка

**1. Виджеты.**
В самом меню вниз добавить два пункта:
- Очистить все виджеты (удаляет все виджеты, как сейчас кнопка удаления)
- Стандартный вид (при нажатии возвращает виджеты в первоначальном виде, как после регистрации)
У всех пунктов сделать расстояние между иконками и пунктом больше, чем сейчас, см. превью.

**2. Портфель.**
Меняем сам поиск. Вставляем его во кладку (т.е. при нажатии на Портфель, появляется вкладка с наименованиями и поиск).

**3.** Увеличить высоту самого хидера, сейчас она 30рх, сделать 40.

**4.** Заменить иконки оповещения и пользователя на новые.

**5.** Цвет бэкграунда: #141922

### Опишите альтернативные решения, о которых вы думали

Иконки в svg, в размер: https://drive.google.com/drive/folders/174I1Ghy7L24xZFRrWdgdpteCPb1q6FPd?usp=sharing
Макет: https://www.figma.com/file/qUctvS64BOn5a03j3ZG2yl/Astras?node-id=194%3A3007

### Дополнительная информация

<img width="223" alt="Портфель_new_превью" src="https://user-images.githubusercontent.com/116548833/199699707-b8c15684-021a-461a-b9f0-d9ad2a527602.png">
<img width="223" alt="Виджеты_new_превью" src="https://user-images.githubusercontent.com/116548833/199699716-f453a279-13c6-491e-b1eb-6fbbbe113170.png">
<img width="223" alt="Виджеты_new_превью2" src="https://user-images.githubusercontent.com/116548833/199699720-86d32752-9602-4bae-a600-c6d2f950a23f.png">

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
![image](https://user-images.githubusercontent.com/6408195/200422227-1ce53372-967d-42f0-a102-b1d56e4dbc35.png)
Просьба при убирании корзины в подменю, не забудьте исправить описание тут.

**Comment by Tattydes** [comment]
Нашла в анте иконку для виджетов, только её нужно отзеркалить.

Её код:
<span nz-icon nzType="appstore-add" nzTheme="outline"></span>

**Comment by Tattydes** [comment]
[icon bag.txt](https://github.com/alor-broker/Astras-Trading-UI/files/9960173/icon.bag.txt)

**Comment by PilgrimViis** [comment]
Давай изменим кнопку "Удалить виджеты" на "Полный сброс" и перенесем её в профиль.  Данная кнопка должна удалять все состояние, кроме авторизации.

**Comment by PilgrimViis** [comment]
Эта кнопка должна быть красная и с подтверждением с сообщением, что удалятся все ваши настройки, списки наблюдения, виджеты и так далее.
