### ISSUE TITLE
[FEATURE] Изменение цветов

### ISSUE THREAD

**Issue by Tattydes** [alor-broker/Astras-Trading-UI#608]
Dark color
![Color dark - 1](https://user-images.githubusercontent.com/116548833/201867611-f84e1655-9550-42c8-85f9-3382db2a3da2.png)

![Color dark - 2](https://user-images.githubusercontent.com/116548833/201867659-69c4301b-6699-4c0e-9c64-1fde8dc2547e.png)

![Color dark - 3](https://user-images.githubusercontent.com/116548833/201867701-6b66b6f3-5253-4c28-8769-a5d6ceb2b97f.png)

Light color
![Color light - 1](https://user-images.githubusercontent.com/116548833/201867850-48b3167a-7ee5-43ae-88f8-b53c75ed7810.png)

![Color light - 2](https://user-images.githubusercontent.com/116548833/201867887-fc9d5136-120a-4713-9280-1ed959ca9db1.png)

![Color light - 3](https://user-images.githubusercontent.com/116548833/201867909-526d7244-99cb-4d8f-8a93-9ffda9a8bb44.png)

**Comment by PilgrimViis** [comment]
@Tattydes добавь пожалуйста коды цветов о которых мы говорили

**Comment by Tattydes** [comment]
@primary-color - 1890FF
@info-color - 1890FF
@warning-color - FFA200
@error-color - FF2E39
@highlight-color - 1890FF
@processing-color - blue-6
@body-background - 070C14
@component-background - 141922
@icon-color-hover - 1890FF
@heading-color - E2E5E9
@text-color - 97A4BB
@text-color-secondary - 97A4BB
@text-color-inverse - FFFFFF
@text-color-dark - FFFFFF
@text-color-secondary-dark - 97A4BB
@text-selection-bg - FFFFFF

@border-color-base - 141922
@border-color-split - 272E3B

@layout-body-background - 070C14
@layout-header-background - 141922

@disabled-color - 97A4BB
@disabled-color - dark - 97A4BB

@link-color - 97A4BB
@link-decoration - 1890FF
@link-hover-decoration - 1890FF

Outline
@background-color-light
- 141922
@background-color-base - 141922

Button
@btn-primary-color - FFFFFF

@checkbox-check-color - 272E3B

**Comment by Tattydes** [comment]
Корректировка красного и зеленого:

**Темная тема:** 
зеленый - 008D63
красный - D1261B

**Светлая:**
зеленый - 00DB8B
красный - FA4F38

**Comment by sbelashevskiy** [comment]
Нужно подобрать другое значение для @border-color-base на темной теме - бордеры совсем не видны и checkbox тоже

**Comment by Tattydes** [comment]
> Нужно подобрать другое значение для @border-color-base на темной теме - бордеры совсем не видны и checkbox тоже

Тогда давай возьмем вот этот цвет: 272E3B
