### ISSUE TITLE
[FEATURE] Изменение вида ссылок

### ISSUE THREAD

**Issue by Tattydes** [alor-broker/Astras-Trading-UI#609]
### Опишите проблему, которую решает ваша фича

Одинаковый цвет у табов и ссылок вводит в заблуждение. Также у ссылок нет отображения, что они внешние.

### Опишите предлагаемое вами решение

Добавить к ссылкам иконки. При наведении и клике делать их синим цветом #1890FF

![image](https://user-images.githubusercontent.com/116548833/199736053-d80791c0-e62c-4ff5-99da-40ab6285c04a.png)

Иконка: https://drive.google.com/file/d/1_gI2z80-xwhbFWr4rimPi2WrC-RLl6hJ/view?usp=share_link

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@Tattydes нужны иконки, цвет которых можно задавать через css, а харкодить в самой svg. В противном случае нам придется при необходимости изменении цвета каждый раз перерисовывать иконки.
Для примера иконки в ng-zorro нарисованы вот так
![image](https://user-images.githubusercontent.com/29191749/200306411-30b818d4-4890-4cf4-a332-40443d8f57be.png)
и я могу задать любой цвет иконки через color:
![image](https://user-images.githubusercontent.com/29191749/200306630-dd6e77c8-1265-4bc1-b616-2fb9de68656a.png)

В прикрепленной иконке так сделать невозможно. Это же касается всех остальных иконок, которые были нарисованы для данного приложения

**Comment by Tattydes** [comment]
[icon_profile.zip](https://github.com/alor-broker/Astras-Trading-UI/files/9954003/icon_profile.zip)
Сохранила в CSS, подойдет?

**Comment by sbelashevskiy** [comment]
Я что-то не понимаю что это за файл? Там стиль для элемента с классом image, который ссылается на image.png
![image](https://user-images.githubusercontent.com/29191749/200473377-336e32ca-02d5-4d26-8c99-d30d8598693a.png)

**Comment by PilgrimViis** [comment]
Надо поменять внешние ссылки везде где есть.
