### ISSUE TITLE
[FEATURE] Редактировать вид настроек профиля

### ISSUE THREAD

**Issue by Tattydes** [alor-broker/Astras-Trading-UI#612]
### Опишите проблему, которую решает ваша фича

Немного доработать.

Сейчас так
![Профиль темн_сейчас](https://user-images.githubusercontent.com/116548833/199743966-86fa0640-4e37-423c-acaa-8b5547429aa2.png)

### Опишите предлагаемое вами решение

Сделать так:
![Профиль темн](https://user-images.githubusercontent.com/116548833/199745902-247cb43e-0756-4219-a510-bcdf4216b7dd.png)

- Убрать полоску под названием. Если это возможно
- Рядом с именем пользователя поставить иконку и сам шрифт сделать меньше (17px)
- Скруглить края у модального окна (border-radius 6px)
- Кнопки Отмена и Сохранить убрать
- Кнопки Отмена и Сохранить поменять местами и обновить цвета в соответствии с новой цветовой схемой (пример ниже)

![Профиль темн_общие](https://user-images.githubusercontent.com/116548833/199745733-007df574-a0fd-46f1-a7ef-0759cf81e624.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Иконка для ссылок есть в иконках ант. Можно оттуда взять, только надо повернуть будет через rotate пропс.
