### ISSUE TITLE
[FEATURE] Улучшить существующий сервис выставления быстрого объема торгуемых бумаг

### ISSUE THREAD

**Issue by koreanhouse** [alor-broker/Astras-Trading-UI#613]
### Опишите проблему, которую решает ваша фича

![Скальперские кнопки Bid Ask](https://user-images.githubusercontent.com/84900477/199746592-f98036c3-2e57-4ce6-9412-c5da5a54f2cf.jpg)
Сейчас в терминале этот механизм устроен как на скрине.
Было бы удобнее перенести этот функционал в виджет заявки - меньше движений мышью, всё делается в одном виджете,
Далее - расширить поле быстрых объемов - дополнить функцией Bi Ask, как дорисовано на скрине. Этот функционал позволяет выбирать все доступные кол-ва из лучшего Бида или Аска
Представим ситуацию, когда кнопки настроены как на скрине. а в лучшем Аске 300 бумаг, которые торговец может и хочет выбрать мгновенно, исходя из риска, своего депо и доступного плеча

![Скальперские кнопки Bid Ask ТИ](https://user-images.githubusercontent.com/84900477/199747652-7877adcc-a5b1-43da-b2b2-711025b80b3b.jpg)
Прикрепил скрин из терминала ТИ с установленным расширением Вячеслава (Pantini)
Всего три движения
1. Выбрать цену Аска
2. Выбрать Ask в кнопках быстрого объема
3. Купить
Уходит около секунды, 
Спасибо

### Опишите предлагаемое вами решение

Было бы удобнее перенести этот функционал в виджет заявки - меньше движений мышью, всё делается в одном виджете,
Далее - расширить поле быстрых объемов - дополнить функцией Bi Ask, как дорисовано на скрине. Этот функционал позволяет выбирать все доступные кол-ва из лучшего Бида или Аска

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Думаю можно сделать.

**Comment by sbelashevskiy** [comment]
клик по ASK/BID не должен подставлять вместе с объемом и цену?
![image](https://user-images.githubusercontent.com/29191749/203709755-5d3b0703-c810-4091-b792-b60e9d40e5f2.png)

**Comment by koreanhouse** [comment]
> клик по ASK/BID не должен подставлять вместе с объемом и цену? ![image](https://user-images.githubusercontent.com/29191749/203709755-5d3b0703-c810-4091-b792-b60e9d40e5f2.png)

А кстати, это хорошая идея. Сейчас цена выбирается вручную в стакане ( лучший Бид или Аск)= один клик, а затем нажимается кнопка объема = второй клик. При логике, что нужно быстрее другого торговца выбрать весь объём - Ваше предложение кажется интересным. Два клика превращается в один

По идее, тогда и иные кнопки объема, указанные на скрине (1  5  10  20  40 и т.д) могут выполнять аналогичную функцию подстановки сразу же в заявку на покупку цены лучших аска или бида
