### ISSUE TITLE
[FEATURE] Добавить информацию по доступному кол-ву бумаг к покупке или продаже

### ISSUE THREAD

**Issue by koreanhouse** [alor-broker/Astras-Trading-UI#614]
### Опишите проблему, которую решает ваша фича

![Доступное кол-во](https://user-images.githubusercontent.com/84900477/199749894-261426bc-34f8-49d3-b537-6acd79f90635.jpg)
В Виджете Заявки уже есть частично описанный функционал, это удобно ( правда у меня не отражается доступное кол-во в шорт - смотрел несколько доступных к шорту бумаг на Алоре. Возможно это связано с тем, что депо в рублях на Спб)

Предлагаю дополнить это информационное поле так, как это реализовано в терминале Тинькоф
![Доступно](https://user-images.githubusercontent.com/84900477/199750541-3fc8cb65-d200-43c6-8d76-7e6462ba2a5a.jpg)
Указывается:
- Доступно при отключенной маржинальной торговле
-Доступно при включенной маржинальной торговле

### Опишите предлагаемое вами решение

Указал решение в тематике фичи.
Да, забыл ещё одно. Терминал Тинькофф сам считает доступное кол-во, исходя из текущей цены стакана. Поясню:
На скрине выставления заявки Астрас в поле "цена" всегда стоит единица, и в поле чуть ниже "Cтоимость" так же единица
У ТИ реализовано более удобно - в поле Цена пустота - торговец сам её выберет из стакана, а в поле "Стоимость" транслируется текущая цена в стакане и соответственно идёт автоматический расчёт доступного.
Экономит чертовски много времени

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Эту задачу я не до конца понял. 

1. Стоимость у вас 1, потому что вы не выбрали ту цену за которую хотите купить. Мы рассчитываем стоимость заявки именно по цене которую привел клиент. И вы тоже можете щелкнуть на стакан и выбрать конкретную цену, где у вас откроется модальное окно с выставлением заявки с нужной ценой.

Мы можем сделать, чтобы в "Стоимость" по умолчанию подставляюсь не 1, а цена последней сделки.

2. > Доступно при включенной маржинальной торговле

Тут тоже не понятно. Т.е. вы хотите 2 стоимости. Одна из которых будет считаться как для клиентов 100 категории, а вторая по обычной маржиналке?

**Comment by koreanhouse** [comment]
> Эту задачу я не до конца понял.
> 
> 1. Стоимость у вас 1, потому что вы не выбрали ту цену за которую хотите купить. Мы рассчитываем стоимость заявки именно по цене которую привел клиент. И вы тоже можете щелкнуть на стакан и выбрать конкретную цену, где у вас откроется модальное окно с выставлением заявки с нужной ценой.

_Это понятно, что если цена из стакана не выбрана - то будет стоять единица, как это сделано в Алоре, либо вообще пустота - как это сделано в ТИ.
Речь о том, что **доступное кол-во** рассчитывается из текущей справедливой цены стакана. Т.е. не в "Стоимость" подставлялась цена, а расчёте доступного кол-ва (я обвёл синей рамкой скрин вашей заявки) подставлялась справедливая цена, чтобы сразу было понятно доступное кол-во_
> 
> Мы можем сделать, чтобы в "Стоимость" по умолчанию подставляюсь не 1, а цена последней сделки.
> 
> 2. > Доступно при включенной маржинальной торговле
> 
> Тут тоже не понятно. Т.е. вы хотите 2 стоимости. Одна из которых будет считаться как для клиентов 100 категории, а вторая по обычной маржиналке?
Верно, две стоимости, как на скрине заявки ТИ. Там где я закрасил мои реально доступные кол-ва к покупке/продаже.
Так как у ТИ нет квалификаций по разным категориям, он просто считает:
**Первая строка** - то что доступно к продаже с выключенной маржинальной торговлей (т.е. только при наличии в портфеле этих акций), и то что доступно к покупке с выключенной маржинальной торговлей (т.е. исходя из имеющихся свободных денежных средств в портфеле)
**Вторая строка** - соответственно с включенной маржинальной торговлей - т.е. то, что я могу вшортить без имеющихся акций в портфеле с размером плеча, который устанавливает брокер, и то, что я могу купить не только с учетом имеющихся денежных средств в портфеле, но и с допустимым плечом от портфеля

**Comment by PilgrimViis** [comment]
На бекенде сделали.
Для маржинальной
    "quantityToSell": 100.0,
    "quantityToBuy": 166.0,
Для немаржинальной
    "notMarginQuantityToSell": 100.0,
    "notMarginQuantityToBuy": 166.0,
