### ISSUE TITLE
[FEATURE] Скальперские кнопки быстрого изменения цены бумаги в лимитных заявках

### ISSUE THREAD

**Issue by koreanhouse** [alor-broker/Astras-Trading-UI#615]
### Опишите проблему, которую решает ваша фича

![Доступно](https://user-images.githubusercontent.com/84900477/199753415-16a08f1d-0a6e-4f9b-8f38-15e1d9697062.jpg)
На скрине виджет заявки Тинькофф с **установленным расширением** Вячеслава (Pantini) ( Это функционал расширения, в голой версии терминала Тинькофф этого нет)
Выделенные кнопки позволяют мгновенно изменить цену, выставленную ранее в лимитной заявке на то кол-во пунктов, на которое считает торговец, исходя из изменений рыночной среды, принтов, индексов и движений в стакане

Пример:
![Скальп цена](https://user-images.githubusercontent.com/84900477/199754195-acb78eb0-094d-4af4-a083-fb6adc3a515b.jpg)
Выставлена лимитка на продажу бумаги Mara по цене 11,52$
Однако индекс Насдака и движение принтов подсказывают, что ценник дойдёт максимум до 11,50$
Без наличия этих кнопок заявку придётся аннулировать и выставлять другую-  потеря времени
Нажатием кнопки "-2" цена в лимитной заявке мгновенно меняется на 11,50$

Очень выручает в бумагах с высокой волатильностью

Зы. Соответственно кнопка + в Аске поднимает цену
Такая же логике в лимитке на покупку

### Опишите предлагаемое вами решение

Выделенные на скрине кнопки позволяют мгновенно изменить цену, выставленную ранее в лимитной заявки, на то кол-во пунктов, на которое считает торговец, исходя из изменений рыночной среды, принтов, индексов и движений в стакане

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Думаю можно сделать но 2 момента.
1. Надо сделать чтобы по умолчанию эти кнопки были скрыты
2. Надо сделать чтобы объемы на кнопках можно было настраивать вручную. Кто-то хочет сдвигать на 2 цента, а кто-то на 200 центов. Предлагаю вариант, что будет сдвигать на N шагов цены, где N будет конфигурироваться пользователем. @koreanhouse что думаете? Для СПБ это будет 1 цент всегда.

**Comment by koreanhouse** [comment]
> 1. Надо сделать чтобы по умолчанию эти кнопки были скрыты
_Почему бы и нет, уверен что кто-то ими и не пользуется, таким образом будет экономиться размер виджета Заявка. А кто пользуется - раскроет в расширенных настройках_

Надо сделать чтобы объемы на кнопках можно было настраивать вручную. Кто-то хочет сдвигать на 2 цента, а кто-то на 200 центов. Предлагаю вариант, что будет сдвигать на N шагов цены, где N будет конфигурироваться пользователем. @koreanhouse что думаете? Для СПБ это будет 1 цент всегда.

_Прямо в точку. В расширении именно так и реализовано - это собственные настройки пользователя_
![кнопки](https://user-images.githubusercontent.com/84900477/200299433-607fbe7b-e824-41e7-9210-a6712295799f.jpg)

**Comment by sbelashevskiy** [comment]
@koreanhouse @PilgrimViis 
Непонятно 2 момента:
1. Кнопки отображать только если по данному инструменту выставлена только 1 лимитка и скрывать если несколько (на разную цену, объем)? Или обновлять все текущие лимитки по данному инструменту?
2. Почему имеется 2 группы кнопок на Buy и Sell? Группа доступна если есть заявка на соответствующую сторону?

**Comment by koreanhouse** [comment]
> @koreanhouse @PilgrimViis Непонятно 2 момента:
> 
> 1. Кнопки отображать только если по данному инструменту выставлена только 1 лимитка и скрывать если несколько (на разную цену, объем)? Или обновлять все текущие лимитки по данному инструменту?
> 2. Почему имеется 2 группы кнопок на Buy и Sell? Группа доступна если есть заявка на соответствующую сторону?

![Скальперские кнопки Ask](https://user-images.githubusercontent.com/84900477/203712925-c7356592-4d7a-47b8-8e34-ad4b9be7e45b.jpg)

В приложенном скрине описал принцип, поэтому ответы на уточнения:
1. Кнопки отображаются постоянно, и действуют на все группы лимиток с разными ценами и разным объемом
2. В скрине указал вариативность - зачем нужны две группы кнопок под Bid или Ask. Как я понял, вопрос был по группам "-" и "+".  Если всё же неправильно понял Ваш вопрос - уточните плз, буду готов пояснить

**Comment by koreanhouse** [comment]
> > @koreanhouse @PilgrimViis Непонятно 2 момента:
> > 
> > 1. Кнопки отображать только если по данному инструменту выставлена только 1 лимитка и скрывать если несколько (на разную цену, объем)? Или обновлять все текущие лимитки по данному инструменту?
> > 2. Почему имеется 2 группы кнопок на Buy и Sell? Группа доступна если есть заявка на соответствующую сторону?
> 
> ![Скальперские кнопки Ask](https://user-images.githubusercontent.com/84900477/203712925-c7356592-4d7a-47b8-8e34-ad4b9be7e45b.jpg)
> 
> В приложенном скрине описал принцип, поэтому ответы на уточнения:
> 
> 1. Кнопки отображаются постоянно, и действуют на все группы лимиток с разными ценами и разным объемом
> 2. В скрине указал вариативность - зачем нужны две группы кнопок под Bid или Ask. Как я понял, вопрос был по группам "-" и "+".  Если всё же неправильно понял Ваш вопрос - уточните плз, буду готов пояснить

Опс, сорри, неверно описал действия при нажатии кнопок "-" "+", сорри
При нажатии красной кнопки "+5" на скрине цена продажи этого тикера **увеличится** на это значение, станет 7.180 и 7.186
И соответственно при нажатии кнопки "-2" - цена **уменьшится** на указанные пункты.
Т.е. всё наоборот.
Хорошо что всплыло уведомление о процессе в почте.
