### ISSUE TITLE
[BUG] Не отражается доступное кол-во в шорт в виджете "Выставить заявку"

### ISSUE THREAD

**Issue by koreanhouse** [alor-broker/Astras-Trading-UI#616]
### Опишите баг

![Шорт](https://user-images.githubusercontent.com/84900477/199758841-379e6a1f-1621-4256-9e95-946d047e58de.jpg)

Примечания:

1. Портфель Спб в **рублях**
2. Есть некоторое кол-во $, увеличивающееся от профитных сделок
3. Маржинальная торговля доступна

### Воспроизведение

1. Открыт виджет "Выставить Заявку"
2. Выбрана цена тикера из стакана
3. Доступное кол-во в шорт доступных к шорту бумаг всегда ноль

### Среда.

Windows 10
Хром Версия 107.0.5304.88 (Официальная сборка), (64 бит)

### Ожидаемое поведение

Почему-то не отражается кол-во, доступное в шорт
-$ на счету достаточно даже без учета рублевого портфеля
- Выбраны несколько тикеров, доступных в шорт в Алоре ( Mara, Baba, етс)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Передал коллегам из бекенда. Посмотрим.

**Comment by PilgrimViis** [comment]
http://youtrack.alor.ru/issue/DEV-3311
Для внутреннего использования.
