### ISSUE TITLE
[BUG] Профиль. Сообщения об ошибках при выходе.

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#62]
### Опишите баг

В процессе выхода из сеанса появляются сообщения об ошибках 403

### Воспроизведение

1. Нажать на иконку профиля
2. Выбрать "Выход"

### Среда.

- ОС Windows 10
- Браузер Chrome
- Версия 100.0.4896.127

### Ожидаемое поведение

Корректный выход из сеанса

### Скриншоты

![logout_403_1](https://user-images.githubusercontent.com/99450543/163990182-3cab2256-c20c-480f-adb5-13d88f94363d.png)
![logout_403_2](https://user-images.githubusercontent.com/99450543/163990178-6f2cc5aa-9861-4744-8090-b46f8de21384.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Ошибка refresh token request исправлена.

Второй тип ошибки 
![image](https://user-images.githubusercontent.com/29191749/164700835-f0af78d0-d652-46cc-9b55-2def67580d15.png)
не является ошибкой. Это отмененые запросы (отмечены как cancelled). Это angular завершает работу перед тем, как открыть пользователю другую страницу.
Эти запросы не отправляются на сервер и никак не влияют на работу пользователя.
