### ISSUE TITLE
[FEATURE] Добавить поиск по столбцу "Название" для виджета "Все инструменты"

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#623]
### Опишите проблему, которую решает ваша фича

1. Сейчас в блоттере во вкладке "Позиции" можно осуществить отдельный поиск для Тикера и Имени. Для виджета "Все инструменты" функция поиска располагается в колонке "Тикер" и ведется сразу по трем полям: name, shortName, description. Нет возможности поиска только по названию (поле shortName).
Причем в виджете "Все инструменты" поиск ведется только по первым символам. То есть при вводе "ETF" отображаются только результаты, начинающиеся на ETF, что отбрасывает часть инструментов, где ETF находится в середине или в конце названия инструмента (например, LQDT или FXRW).
2. В блоттере и "Все инструменты" по-разному обозначаются колонки с названием инструмента ("Имя" для блоттера и "Название" для "Все инструменты").

### Опишите предлагаемое вами решение

1. Добавить возможность поиска инструмента по его названию, даже если введенная фраза находится в середине или конце названия инструмента.
2. В блоттере поменять название колонки "Имя" на "Название" как в "Все инструменты"

### Дополнительная информация

![image](https://user-images.githubusercontent.com/88287882/200291043-e86c7d38-e95e-4c1f-954f-1102203f2bda.png)
![image](https://user-images.githubusercontent.com/88287882/200291650-b50b700a-fcc4-404d-8e98-002a5727f888.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
На бэке сделали. Можно делать на фронте.

**Comment by sbelashevskiy** [comment]
@PilgrimViis ,
не понимаю что в итоге в этой задаче нужно делать на стороне ASTRAS.

1. Добавлять фильтр на столбец "Название"? Если так, то на бэке этого так и нет - в прилинкованной задаче сделали только поиск CONTAINS. Судя по результатам поиск, который есть на столбце "Тикер" уже делает поиск по тикеру, shortName, description. В API значение поиска для столбца "Тикер" передается в едином параметре query, т.е. там **нет возможности** отдельно искать только по тикеру, или отдельно только по shortName или отдельно по description да и непонятно зачем это нужно. Повесить один и тот же фильтр на два разных столбца мы не можем - они будут конфликтовать друг с другом. Нужно либо оставлять как есть и просто выкатить текущие изменения API, либо вводить в API отдельные фильтры для столбцов "Тикер" и "Название", которые будут искать только по тикеру и только по названию. Судя по https://youtrack.alor.ru/issue/DEV-3408 разработчик тоже не понял что в итоге требуется
2. Поле "Имя" на вкладке Позиции виджета Блоттер переименовываем или нет?

**Comment by PilgrimViis** [comment]
1. Я тебе в дисе отвечал, но продублирую ещё тут для коллег. Они забыли опубликовать свои изменения. Поиск по имени должен работать в АПИ.
2. Думаю да, "Название" у нас в других местах. Для однообразия.

**Comment by sbelashevskiy** [comment]
В рамках этой задачи исправлено только название столбца.
Поиск исправлен на стороне бэкэнд. Отдельного фильтра для функционала виджета не  ребуется
