### ISSUE TITLE
[FEATURE] Индикация возможности короткой продажи по инструменту

### ISSUE THREAD

**Issue by MichaelChirkov** [alor-broker/Astras-Trading-UI#625]
### Опишите проблему, которую решает ваша фича

При торговле неясно по каким инструментам доступна продажа в короткую и в каком объёме. 

### Опишите предлагаемое вами решение

Предлагаю сделать маленькие эмблемы или значок, который бы давал понять о возможности продажи в короткую. В виджете "Выставить заявку" или хотя бы в виджете "Инфо" (сделав дополнительное поле "доступно для продажи в Short" - "да"). Круто было бы, если б так же была информация о размере плеча.

### Опишите альтернативные решения, о которых вы думали

Самым банальным решением бы было появление числа доступных к продаже бумаг в поле "К продаже" виджета "Выставить заявку"

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Сначало не так понял. Да, неплохая фича на самом деле. Сделаем.
