### ISSUE TITLE
[FEATURE] Виджет "Выставить заявку"

### ISSUE THREAD

**Issue by MichaelChirkov** [alor-broker/Astras-Trading-UI#630]
### Опишите проблему, которую решает ваша фича

Повышает скорость выставления лимитной заявки. 

### Опишите предлагаемое вами решение

•	Возможность добавления быстрых объёмов, как в скальперском стакане под полями "Кол-во лотов", "Цена"
•	Горячие клавиши в настройках виджета, если инпуты «Цена» или «Кол-во лотов» в фокусе (ввел быстро объём, нажал на горячую клавишу)

### Дополнительная информация

Сейчас выставление лимитной заявки не используя скальперский стакан проходит так:
- щелкнуть на желаемую цену в стакане (ввести с руки)
- набрать количество лотов
- щелкнуть мышкой на кнопку

Пока все это делаешь, за ценой очень тяжело успеть. Знаю про скальперский стакан.
С данными предложениями, скорость выставления заявки существенно бы повысилась с пользовательской стороны. 

-Щелк цена
-Щелк объём
-Щелк по клавише Покупка/продажа

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
В чем отличие от https://github.com/alor-broker/Astras-Trading-UI/issues/613?

**Comment by PilgrimViis** [comment]
Ответа не получили, закрою как дубликат тогда.
