### ISSUE TITLE
[FEATURE] Виджет «Все сделки»

### ISSUE THREAD

**Issue by MichaelChirkov** [alor-broker/Astras-Trading-UI#631]
### Опишите проблему, которую решает ваша фича

Убирает лишнюю информацию.

### Опишите предлагаемое вами решение

Опции для настройки таблицы как в виджете «Блоттер», а именно настройка отображения колонок в таблице

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Т.е. в виджет "Все сделки" предлагаете добавить выбор колонок, как сделано в блоттере, потому что сейчас там отображаются поля которые вам не нужны и занимают лишнее место?
