### ISSUE TITLE
[FEATURE] Виджет «Блоттер»

### ISSUE THREAD

**Issue by MichaelChirkov** [alor-broker/Astras-Trading-UI#632]
### Опишите проблему, которую решает ваша фича

Быстрая отмена заявки невозможна. Значок отмены мал, кнопка подтверждения тоже. Быстро не отменишь.

### Опишите предлагаемое вами решение

Опция в настройках отмены заявки без подтверждения, по умолчанию не включена.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Можно сделать настройку для отключения подтверждения. Про размер не знаю, не хотелось бы раздувать кнопкой отмены место. Сейчас отменить можно ещё прямо из стакана. И ещё мы планируем сделать чтобы можно было отменять с графика. Как думаете, этого достаточно?

**Comment by PilgrimViis** [comment]
В рамках этой задачи надо сделать настройку в блоттере, которая будет отменять заявки без предупреждения. По уомлчанию всё таки предупреждение давайте оставим.

**Comment by sbelashevskiy** [comment]
Добавлена настройка для отключения подтверждения:
![image](https://user-images.githubusercontent.com/29191749/203716787-628e8b25-5424-4b5b-b839-af6f94e7012b.png)
