### ISSUE TITLE
[BUG] Курсор над стаканом меняет свой вид

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#64]
### Опишите баг

Если стакан достаточно динамично меняется, то курсор, находясь над ним, дергается.
1. При нахождении над цифрами меняется между "Рука" и "Курсор"
2. При нахождении в области без цифр меняется между "Рука" и "Стрелка"
Если произвести щелчок в тот момент когда курсор сменился на "Курсор" или "Стрелка", то ожидаемого открытия виджета "Выставить заявку" не происходит

### Воспроизведение

1. Открыть виджет "Стакан" и выбрать инструмент с динамичным обновлением.
2. Навести курсор на любую позицию цены.

### Среда.

- ОС Windows 10
- Браузер Chrome
- Версия 100.0.4896.127

### Ожидаемое поведение

Курсор над стаканом не изменяет свой вид.
При щелчке на позицию в стакане - возникает виджет "Выставить заявку"

### Правила

- [ ] Я согласен следовать правилам

**Comment by dzeron13** [comment]
Сюда же добавлю еще одну особенность. При клике по стакану одновременно срабатывает и выставление заявки и подготовка к перемещению виджета, т.е. у остальных появляются границы, а если есть пустая область, то там отображается рамка куда можно переместить.
![Стакан_клик](https://user-images.githubusercontent.com/99450543/164199056-8ec57988-e8e1-4f83-a591-fd8e5417acfa.png)

**Comment by PilgrimViis** [comment]
Я не думаю, что это баг. Логика следующая:
_При нахождении над цифрами меняется между "Рука" и "Курсор"_ это происходит тогда, когда курсор попадает на линию разделения между разными ценами. Допустим в стакане 2 строчки 100 и 150. Вы щелкаете по линии разделения. Какую цену нужно подставить в лимитную заявку 100 или 150? Поэтому это не баг.
_При нахождении в области без цифр меняется между "Рука" и "Стрелка"_ это происходит тогда, когда пользователь навел курсор на край виджета. Если мы уберем "Стрелку", то как пользователь поймет, что он сможет менять размер виджета? Поэтому это тоже не баг, а необходимость.

**Comment by PilgrimViis** [comment]
> Сюда же добавлю еще одну особенность. При клике по стакану одновременно срабатывает и выставление заявки и подготовка к перемещению виджета, т.е. у остальных появляются границы, а если есть пустая область, то там отображается рамка куда можно переместить.

Вот это попробуем исправить, если мешает.

**Comment by PilgrimViis** [comment]
Сейчас посмотрел. Если уберем это, то виджет можно будет перемещать только через вернюю панель (там где названия и иконки). Наверное это не очень удобно будет. Проконсультируюсь с коллегами и решим.

**Comment by dzeron13** [comment]
Прилагаю видео. Курсор стоит четко над ценой и все равно "дергается" при изменении стакана. Смена курсона не между строками, а на любой позиции стакана. Фактически это приводит к тому, что выставить заявку со стакана - рандомная возможность.
https://user-images.githubusercontent.com/99450543/164431689-e69be94c-ecf9-4e41-a488-5a1ba6dffb86.mp4

**Comment by PilgrimViis** [comment]
Сделал чтобы курсор не менялся. Расширил зону клика на стакан, чтобы не терять клики пользователя. С зоной слева\справа ничего сделать нельзя к сожалению, если их выключить виджет нельзя будет уменьшать\увеличивать по горизонтали =(
