### ISSUE TITLE
[FEATURE] Снизить таймаут до появления опросника

### ISSUE THREAD

**Issue by scarletcloak** [alor-broker/Astras-Trading-UI#643]
### Опишите проблему, которую решает ваша фича

Получаем мало ответов на опросы, есть подозрение что это из-за большого начального таймаунта

### Опишите предлагаемое вами решение

Снизить таймаут до 3 минут.

### Правила

- [X] Я согласен следовать правилам

**Comment by scarletcloak** [comment]
![image](https://user-images.githubusercontent.com/87366246/201078992-857880ce-9b2e-471c-aa57-4fa78aded325.png)


Ещё вопрос. Можно ли в тайтл списать актуальный текст вопроса который будет задаваться? Есть вариант, что люди думают что это повторение вопроса и игнорируют. Плюс, непонятно а почему дата 28 октября, если опрос создали на днях, а само уведомление пришло только что. Дата чего это?

**Comment by sbelashevskiy** [comment]
Текст написать можно. 
По дате - скорее всего висит предыдущий не отвеченный фидбэк
