### ISSUE TITLE
[BUG] Блоттер. Фильтрация по тикеру (имени) визуально не отображается

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#65]
### Опишите баг

Если в виджете блоттер выполнить поиск тикеру или имени, то результат в таблице визуально отображается, как и без поиска. Т.е. введя в поиске некорректный тикер, мы получаем пустой виджет.

### Воспроизведение

1. Выставить заявку
2. Открыть виджет блоттер, перейти на вкладку "Заявки"
3. В колонке "Тикер" нажать на Поиск (лупа), ввести любые данные, не совпадающие с тикером.
4. Нажать на поиск еще раз, для скрытия поля поиска.

### Среда.

- ОС Windows 10
- Браузер Chrome
- Версия 100.0.4896.127

### Ожидаемое поведение

После фильтрации результатов, в колонке визуально отражается факт фильтрации, либо существует отдельный элемент, где виден критерий поиска.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Проблема понятна. Нужно как-то напомнить пользователю, что он применил фильтр. Вижу такие варианты:
1. Поменять надпись с "Заявок сегодня не было" на другую.
2. Подчеркнуть, выделить жирным, поставить какую-то иконку на поле "Тикер", чтобы визуально было понятно что была фильтарция.
