### ISSUE TITLE
[BUG] Не работают кнопки в ск стакане

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#657]
### Опишите баг

Снять все заявки "~" тильда
Закрыть все позиции  "Esc" 

### Воспроизведение

Выставить несколько лимитных заявок в ск стакане  нажать тильду 
Открыть несколько позиций по стакану нажать эскейп 

### Среда.

Виндовс 7 
Хром 

### Ожидаемое поведение

Кнопки должны работать 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@uncrashable а что конкретно не работает?
Я смог закрыть по рынку существующую позицию:
https://user-images.githubusercontent.com/29191749/202134183-f8019947-22b2-4d2c-b8f2-31cc2d555df4.mp4
Купить по рынку и закрыть позицию:

https://user-images.githubusercontent.com/29191749

https://user-images.githubusercontent.com/29191749/202135672-af0b7e19-257c-4cd2-9457-982748a45a10.mp4

/202134329-a152fc59-db49-4af9-959f-049c637dee2a.mp4

Поставить и снять лимитную заявку

https://user-images.githubusercontent.com/29191749/202135753-6fe2cfc4-a860-4646-9521-77c99e274d40.mp4

А также поставить несколько лимитных и снять:

https://user-images.githubusercontent.com/29191749/202136106-bde5dd47-34d0-46c8-af0d-e8345e7ae8eb.mp4

P.S указанные команды работаю точно также, как R и E для конкретного стакана с той лишь разницей, что не нужно наводить курсор на стакан.
Чтобы нажать тильда нужно переключиться на английский язык и зажать шифт.

**Comment by uncrashable** [comment]
а, понял. Да так работает . Тут получается даже если капс включен , всё равно надо нажать шифт.
