### ISSUE TITLE
[BUG] Разлогинивание терминала прии закрытии окна 

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#664]
### Опишите баг

При закрытии окна браузера с терминалом не происходит разлогинивание с сервером, при последующем открытия нового окна, и переходе по ссылке терминала дополнительно логин и пароль не просит ввести. Так же и "Время бездействия до приостановки сеанса, мин." при закрытии окна ставится на паузу и при последующем открытии окна, без ввода логина и пароля, возобновляется отсчет.

### Воспроизведение

Запустить терминал, залогиниться, закрыть окно с терминалом, и заново открыть

### Среда.

win8
Firefox

### Ожидаемое поведение

После закрытия окна с залогиненым терминалом разрывать соединение с сервером. Еще лучше, добавить возможность опционально выбирать - разрывать соединение или нет, при закрытии окна браузера, в профиле во вкладке Общие.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Пожалуйста. Ещё уберите 401 и 403 ошибки которые при логировании и разлогировании

**Comment by MorozovDen** [comment]
Поддерживаю!!!! по 401 и 403, они настораживают и клиенты очень просят их скрыть

**Comment by sbelashevskiy** [comment]
@MorozovDen речь идет о клике по кнопке "Выход" в меню 
![image](https://user-images.githubusercontent.com/29191749/202398432-276d8817-ecd3-42d7-90f0-4558cac2634c.png)

или просто закрытии окра браузера?

**Comment by MorozovDen** [comment]
просто о закрытии окна без нажатия этой кнопки "выйти"

**Comment by sbelashevskiy** [comment]
При реализации описанного поведение существует значительное техническое ограничение - мы не модем отличить когда пользователь закрывает вкладку, а когда он ее обновляет. Это создаст значительные неудобства для пользователя - при каждом  открытии браузера, а также обновлении страницы пользователь будет вынужден вводить логин/пароль. Если у пользователя включена двухфакторная аутентификация, то это будет еще более раздражающим для пользователя.

Кроме того такое поведение отличается от общепринятых поведений web-приложений.
Общепринятым является следующее поведение:
пользователь проходит аутентификацию 1 раз, затем в течении определенного периода (длительность сессии) он может закрывать и открывать приложении неограниченное количество раз без необходимости повторного ввода логина/пароля. После истечения данного периода, если пользователь не пользовался приложением, при попытке входа он должен ввести логин/пароль.

Итого текущая реализация:
1. При открытии приложения пользователь вводит логин/пароль. Создается сессия длительностью 30мин (это значение не настраивается)
2. По истечению 30 мин. если пользователь все еще пользуется приложением - сессия будет автоматически продлена
3. Если пользователь запускает приложение после истечения 30мин с момента последнего обновления сессии - он должен пройти аутентификацию заново.
4. Если пользователь хочет явно прервать сессию ранее 30 мин. - он должен нажать кнопку "Выход"
5. Если пользователь хочет обезопасить себя на случай оставленного ОТКРЫТОГО приложения, то он может изменять настройку "Время бездействия до приостановки сеанса, мин.". PS: эта настройка относится иммено к случаю, когда приложение открыто в браузере, но пользователь не производит каких-либо действий. Т.е пользователь открыл приложение и ушел. В этом случает по истечению указанного в настройке периода сеанс будет завершен автоматически из-за бездействия пользователя

**Comment by MorozovDen** [comment]
Логика понятна, спасибо! а про ошибки при логировании (https://github.com/alor-broker/Astras-Trading-UI/issues/664#issuecomment-1318245338) ?

**Comment by sbelashevskiy** [comment]
> Логика понятна, спасибо! а про ошибки при логировании ([#664 (comment)](https://github.com/alor-broker/Astras-Trading-UI/issues/664#issuecomment-1318245338)) ?

поправили
