### ISSUE TITLE
[FEATURE] Одинаковое отображение элементов при выставлении заявки

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#665]
### Опишите проблему, которую решает ваша фича

Сейчас в новом дизайне в модальном окне выставления заявки в отличие от виджета "Выставление заявки" по-другому выглядят кнопки "Купить", "Продать", а также информация о лотности инструмента. Можно сделать их отображение одинаковым.

### Опишите предлагаемое вами решение

1. В виджете заявки в поле "Кол-во лотов" можно поменять значок "вопрос" на текстовое отображение лотности.
2. Кнопки "Купить", "Продать" можно расположить чуть дальше друг от друга, и возможно стоит поменять шрифт (в модальном окне - 12px)

![image](https://user-images.githubusercontent.com/88287882/202372123-797f51af-66be-490e-9c00-7c6c4de4aac5.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
###
