### ISSUE TITLE
[BUG] Разная валидация обязательных полей при выставлении заявки

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#666]
### Опишите баг

1. В модальном окне при выставлении новой заявки под пустыми полями "Кол-во лотов", "Цена" и "Сигнальная цена" (для условных заявок) появляется красное предупреждение: "Введите кол-во/цену". Однако при смене инструмента этого уведомления уже не появляется (см. видео). Причем вокруг кнопок "Купить", "Продать" появляется серая рамочка (а кнопки становятся неактивными), она лишняя.
2. В виджете "Выставление заявки" для пустого поля "Кол-во лотов" появляется красная рамочка, однако в соседнем обязательном поле -"Цена" - этой рамки нет (фото), лучше ее добавить. Причем это лучше сделать и для полей Условной заявки ("Кол-во лотов", "Цена" и "Сигнальная цена), а также в модальном окне выставления заявки (сейчас там вообще нет красной рамочки для пустых полей).

### Воспроизведение

1. Обновить страницу.
2. Открыть модальное окно заявки по любому инструменту.
3. Удалить значения в полях "Кол-во лотов" и "Цена".
4.  Поменять инструмент и повторить шаг 3.
5. Проверить наличие предупреждения под полями.

### Среда.

Windows 10
Google Chrome 

### Ожидаемое поведение

Каждый раз при выставлении заявки для пустых полей появляется предупреждение "Введите кол-во/цену", а также появляется красная рамочка вокруг обязательного пустого поля.

### Скриншоты

Пропадают предупреждения:
https://user-images.githubusercontent.com/88287882/202375716-6d4b7769-c18d-4349-8cf4-2f5f81dddb2b.mp4

В модальном окне и в виджете Выставления заявки на всех вкладок нет красной рамки для обязательных полей:
![image](https://user-images.githubusercontent.com/88287882/202375928-6bee65bf-f908-4700-a7a1-4a28d15fdc67.png)
![image](https://user-images.githubusercontent.com/88287882/202376386-1e8f6bfc-04b0-4191-9519-6272ec6ffcab.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Илья, круто что ты такие вещи замечаешь. Спасибо @agushasok в рамках наших правок виджетов заявок задачу возьмешь? Или тут могут быть сложности?
