### ISSUE TITLE
[BUG] Долгая загрузка интерфейса при большом количестве сделок 

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#679]
### Опишите баг

Имеем два договора (не имеет значения).
На одном совершаем кучу сделок (~160 на ВТБ для теста) - 75008
Переходим на портфель, где мало или нет сделок (72698) - грузится вполне неплохо. Переходим на портфель, где много сделок (75008) - получаем зависший интерфейс. При этом если сделок относительно немного, то видно, что сначала грузятся данные блоттера - в частности если открыта вкладка "Сделки", то пока она не загрузится - не прогружается график и стакан. А если сделок много (как на видео 160), то при переключении портфеля интерфейс совсем не реагирует. А после обновления страницы - прогружает данные через минут 5-10.

Видео:
https://disk.yandex.ru/i/x57dIOfdy4cZyw

### Воспроизведение

1. Совершить какое-то количество сделок за день (пусть будет >100)
2. Обновить страницу

### Среда.

win 10, яндекс браузер 22.11.0.2424 corp (64-bit)

### Ожидаемое поведение

Адекватный ответ интерфейса при большом количестве сделок

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Такая же ерунда при относительно большом количестве заявок в блоттере. Если удалить виджет блоттер, то приложение грузится нормально:


https://user-images.githubusercontent.com/29191749/203959676-3e780fab-9e5f-4313-8be2-1fa61f8ed77a.mp4

**Comment by dzeron13** [comment]
@sbelashevskiy ну, т.е. тут два вопроса: долгая загрузка данных в блоттер и асинхронность этого действия?

**Comment by sbelashevskiy** [comment]
вся загрузка данных в приложении асинхронная. Какая-то проблема с отрисовкой самой таблицы. Будем смотреть

**Comment by dzeron13** [comment]
Понял. Спасибо
