### ISSUE TITLE
[BUG] При выставлении заявки на SPBX не отображается комиссия сделки

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#68]
### Опишите баг

При выставлении заявки на MOEX в окне автоматически пересчитывается значение суммы сделки и комиссии при изменении лотов/цены.
На SPBX эти поля отсутствуют

### Воспроизведение

1. Открыть окно "Выставить заявку" по инструменту на SPBX

### Среда.

- ОС Windows 10
- Браузер Chrome
- Версия 100.0.4896.127

### Ожидаемое поведение

При выставлении заявки на SPBX отображается стоимость покупки и комиссия.

### Скриншоты

![Заявки_SPBX-MOEX](https://user-images.githubusercontent.com/99450543/164004674-b866a54d-6a79-4837-a8e2-df69f547de07.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Спасибо. Исправили.

**Comment by dzeron13** [comment]
На валютной секции тоже нет
![image](https://user-images.githubusercontent.com/99450543/166655091-5a5f522b-fd20-4c58-bef0-9adaf973c7d3.png)
