### ISSUE TITLE
[FEATURE] Сделать одинаковой отображение лотности инструментов в заявках

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#685]
### Опишите проблему, которую решает ваша фича

Сейчас при выборе тикеров с большой лотностью (TGKA, VTBR, TGKN) в виджете указывается число с добавлением в конце "К", "М", но в модальном окне заявки число пишется полностью (фото). Причем, в виджете лотность указывается под полем, а в модальном окне заявки - справа от "Кол-во лотов".
Кроме того, для инструментов, у которых лотность равна 1 (например, WKHS), в виджете пишется "1 лот = 1 шт.", но в модальном окне - информация отсутствует. 

### Опишите предлагаемое вами решение

При выставлении заявки поменять отображение лотности: указывать или с пометкой "К", "М" или прописывать полностью. Саму надпись можно указывать под полем "Ко-во лотов".
В модальное окно заявки добавить пометку "1 лот = 1 шт." для соотв. инструментов.

### Дополнительная информация

![image](https://user-images.githubusercontent.com/88287882/203241160-36784f9b-ab4a-4ab9-b91e-6a2fa740db48.png)
![image](https://user-images.githubusercontent.com/88287882/203242648-2c43f1b1-6f52-4503-ac34-aea6d0bdfbfd.png)

### Правила

- [x] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Давайте указывать с К, для больших лотностей везде.
