### ISSUE TITLE
[BUG] Выставление заявки на SPBX. Ошибка 500

### ISSUE THREAD

**Issue by dzeron** [alor-broker/Astras-Trading-UI#70]
### Опишите баг

При выставлении заявки на SBPX, запрос на
"https://api.alor.ru/commandapi/warptrans/FX1/v2/client/orders/estimate" возвращает ошибку 500.

### Воспроизведение

1. Открыть окно "Выставить заявку" по инструменту на SPBX

### Среда.

- ОС Windows 10
- Браузер Chrome
- Версия 100.0.4896.127

### Ожидаемое поведение

Отсутствие ошибок при выставлении заявки

### Скриншоты

![Заявка_SPBX_err500](https://user-images.githubusercontent.com/99450543/164009916-15f762b7-1418-4d98-a4d1-93454f5d54bc.png)

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Мы исправили 500 по /estimate, когда разбирались почему не показывается комиссия на СПБ. Сейчас проверил, ошибок больше нет. Если проблема осталась, напишите пожалуйста в комментариях.
