### ISSUE TITLE
[BUG] В некоторых местах поля и кнопки "прилеплены" друг к другу

### ISSUE THREAD

**Issue by agushasok** [alor-broker/Astras-Trading-UI#701]
### Опишите баг

Сделать вертикальные отступы у полей и кнопок

### Воспроизведение

зайти в настройки виджета выставления заявки

### Среда.

-

### Ожидаемое поведение

поля не прилипают друг к другу

### Скриншоты

<img width="338" alt="image" src="https://user-images.githubusercontent.com/45139991/204227767-9683c6b6-7020-4a80-a48e-dcfde3b898d3.png">

### Правила

- [X] Я согласен следовать правилам

**Comment by Tattydes** [comment]
Дельное замечание, тем более что место для этого есть. Я бы ещё убрала у названия биржи фон, а то как будто тоже кнопка. В общем нарисую макет

**Comment by agushasok** [comment]
у названия биржи серый фон, так как поле неактивно. Оно изменяется в зависимости от вбыранного инструмента

**Comment by Tattydes** [comment]
В таком случае оставляю не активное поле серым, кнопки отлепила

![#701](https://user-images.githubusercontent.com/116548833/204473488-13098320-e8a5-44db-ab79-1e7005e4310b.png)

**Comment by sbelashevskiy** [comment]
Убирать фон у collapsed элемента плохая идея: он группирует элементы и если не будет фона, то и группы видно не будет:
![image](https://user-images.githubusercontent.com/29191749/204490550-8915f2f6-6585-4ea4-8029-8b79d60337bf.png)
![image](https://user-images.githubusercontent.com/29191749/204490694-fb8ec219-1ae0-4383-8220-1faca4692920.png)

тогда нужно придумать другой способ группировки подобных элементов

**Comment by agushasok** [comment]
может у вложенных элементов отступ сделать слева просто?
