### ISSUE TITLE
[BUG] Не загружается стакан по инструменту ORUP (режим TQPI)

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#705]
### Опишите баг

Не загружается стакан по инструменту ORUP (режим TQPI), график по данному инструменту строится, в АТ и в Трейдинг Вью есть стакан.

### Воспроизведение

1. открыть график
2. открыть стакан по инструменту

### Среда.

Chrom

### Ожидаемое поведение

отображение котировок в стакане

### Скриншоты

![IMAGE 2022-11-29 11:46:45](https://user-images.githubusercontent.com/104637334/204481722-be70ecaa-655e-4fc4-9969-4fc00d93948c.jpg)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@LuzhbinV 
на данный момент я не вижу каких-либо проблем
![image](https://user-images.githubusercontent.com/29191749/204485227-a180f334-8a73-47b4-9257-0229578a247b.png)

Проблема все еще актуальна?
Если да, прикрепите, пожалуйста, скрин настроек виджета.
Проверьте консоль браузера (F12) на наличие ошибок.
Попробуйте вернуться к стандартному виду 
![image](https://user-images.githubusercontent.com/29191749/204485967-84015019-749e-4158-bb57-abbfb9f6f814.png)

Опишите какие действия вы совершали ранее.

**Comment by scarletcloak** [comment]
На беке была проблема как выяснил. Они исправили
