### ISSUE TITLE
[FEATURE] В блоттере неверно работают фильтры

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#709]
### Опишите баг

1. В блоттере для вкладок "Заявки", "Стопы", "Позиции" и "Сделки" нельзя поставить несколько фильтров. Например, в "Позиции" при выставлении нескольких фильтров работает только первый (1-ое видео). Нельзя выставить несколько параметров для фильтрации.
2. При клике на "Сбросить" по конкретному фильтру обнуляются сразу все выставленные фильтры. Причем, иконка" лупа" выделяется синим цветом во всех местах, где можно использовать поиск, даже если фильтрации по полю не было. Нужно вернуть выделение синим цветом "лупы" только при активном фильтре (2-ое видео).

### Воспроизведение

1. В блоттере перейти на "Позиции" и выставить RU - для "Тикер" и ETF - для "Имя".
2.  Проверить результаты фильтрации.
3. В блоттере в "Сделки" для графы "Заявки" нажать "Сбросить".
4. Посмотреть на отображение иконки "лупа".

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

1. Можно выставить несколько параметров для фильтрации
2. При сбросе фильтра обнуляется только выбранный, а не все сразу. Значок "лупы" выделен синим только для активного(s[) фильтра(ов).

### Скриншоты

1. https://user-images.githubusercontent.com/88287882/204560340-10b43651-a615-4b11-9f21-adad096c0282.mp4

2. https://user-images.githubusercontent.com/88287882/204560359-d1c370ab-3047-40de-927b-4fb703c166ff.mp4

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Это не баг, а фича должна быть. Раньше никогда не работало. Но давайте попробуем сделать.
