### ISSUE TITLE
[BUG] Выбор инструмента. Некорректный поиск по некоторым тикерам

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#71]
### Опишите баг

Поиск в виджете по тикерам из одного символа и некоторых из двух (C, F, J, M, Y, Z, CC, DD, AA) отрабатывает некорректно.

### Воспроизведение

1. Открыть виджет "Выбор инструмента"
2. Выполнить поиск по одному из указанных тикеров.
3. Выбрать инструмент.

### Среда.

- ОС Windows 10
- Браузер Chrome
- Версия 100.0.4896.127

### Ожидаемое поведение

Корректный поиск по всем тикерам

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Ну либо вы можете искать по названию компании. Для того же T это будет AT&T в поиске.

**Comment by dzeron13** [comment]
Наверное, не так выразился. Поиск-то как раз происходит, но когда выбираешь такую бумагу, то результат отображается другой. Хотя стакан, например, переключается нормально.
Пример:
1. Набираю в поиске "FORD"
2. Находится "F". Выбираю
3. Результат "FTI"
![Выбор_тикера](https://user-images.githubusercontent.com/99450543/164020104-58dc5aa6-7634-4e47-86f7-fd2bb2bc4ab7.png)

**Comment by PilgrimViis** [comment]
Понял вас. Смог воспроизвести. Посмотрим.
