### ISSUE TITLE
[FEATURE] Добавить обратный отчёт на графике теханализа

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#722]
### Опишите проблему, которую решает ваша фича

В некоторых случаях, полезно видеть на графике обратный отчет времени закрытия свечи относительно таймфрейма.\
По аналогии в ТВ 

### Опишите предлагаемое вами решение

![image](https://user-images.githubusercontent.com/105817664/205898338-c3bbd657-e874-4837-b225-f96aae13b383.png)

На скрине видно, что рядом с ценой показывается обратный отчёт. Через 39 минут он обновится и начнет отчитывает еще час ( т.к. выбран часовой таймфрейм) 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Это включается в настройках графика

https://user-images.githubusercontent.com/29191749/205916940-53e411e9-a92a-4db0-9f84-bce3d012d8b8.mp4

Если это включать у всех по-умолчанию, то отсчет занимает лишнее место на оси - это может не всем пользователям понравиться
