### ISSUE TITLE
[FEATURE] Виджет массового выставления заявок (корзина)

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#730]
### Опишите проблему, которую решает ваша фича

Сейчас если нужно выставить заявки на какую-то сумму в разных инструментах или по разным ценам, приходится сначало считать что-то в екселе и потом уже выставлять. Было бы сильно проще если бы Астрас сам считал это

### Опишите предлагаемое вами решение

![image](https://user-images.githubusercontent.com/6408195/206659036-fcfdb115-fedf-421e-b037-bfd39ccf286c.png)

Нужно сделать виджет который бы позволил массово выставлять заявки. Делать естимейнт надо через estimate api

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Вопросы:
1. Изменяемые поля в строке процент и цена?
2. Выставляются рыночные заявки, если указана цена - лимитные?
3. При выставлении заявки по рынку цена (по котировкам) может сильно отличаться от цены сделки, а значит и объем будет отличаться. Что с этим сделать?
4. Каким образом обрабатывать ошибки - одна из заявок выполнилась, вторая отклонена

**Comment by sbelashevskiy** [comment]
Для реализации не хватает метода API:
Входные данные (массив):
[
{
  "portfolio": "string",
  "ticker": "string",
  "exchange": "string",

  "price": number,  //опциональное поле, если отсутствует, значит заявка по рынку
  "budget": number // общая сумма, которую можно потратить на данный инструмент
}
]

Выходные данные (массив):
[
{
  "portfolio": "string",
  "ticker": "string",
  "exchange": "string",

  "quantityToBuy": number // количество лотов к покупке
   "buyPrice": number // если есть возможность присылать это значение для рыночной цены
}
]
