### ISSUE TITLE
[FEATURE] В блоттере добавить кнопку переключения портфелей

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#731]
### Опишите проблему, которую решает ваша фича

Возможно, будет удобнее добавить кнопку переключения портфелей в самом блоттере. Быстрее и удобнее

### Опишите предлагаемое вами решение

![image](https://user-images.githubusercontent.com/105817664/206736906-3c410fff-62e7-49d1-9067-898a6fe05405.png)
![image](https://user-images.githubusercontent.com/105817664/206738484-0237076e-67e2-4b89-b421-9db8ea05cde0.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Честно говоря, не вижу особого смысла. Переключить портфели можно через настройки. + 2 клика, не должно быть проблемой. Если надо следить сразу за 2мя портфелями, то правильней поставить 2 блоттера...
