### ISSUE TITLE
[BUG] Подправить верстку для мобильных телефонов

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#732]
### Опишите баг

На мобильных устройствах через консоль разработчика (F12):
1. слетает верстка при изменении настроек в виджете "Выставить заявку":
2. для облигаций, опционов и валютных пар не на весь экран отображается модальные окна выставления и изменения заявки;
3. нужно подправить шапку приложения: для устройств с шириной экрана менее 370px не видно логотип "Астрас" и поменять отображение кнопок (колокольчик и профиль) справа в шапке сайта.

### Воспроизведение

1. Для всех мобильных устройств следует поменять ширину полей для номиналов и объемов в настройках виджета "Выставить заявку". Сейчас поля выходят за границы экрана и значения в них не видны полностью. Возможно слeдует убрать свойство flex для устройств с максимальной шириной 575px:

![Заяка  Настройки](https://user-images.githubusercontent.com/88287882/206969031-cc7ddc8b-6358-4b82-b144-d5118b2eacbe.png)

2. Для валютных пар, облигаций и опционов в модальном окне выставления, а также изменения заявки для устройств с шириной экрана не менее 390px (IphoneSE, Iphone12Pro Pixel 5 Samsung Galaxy S8) не всегда видно цену по инструменту и модалки выходят за рамки экрана:

![облигации и валюты - не помещается](https://user-images.githubusercontent.com/88287882/206969723-5a230223-dada-4c37-b1d5-9c1f279351fa.png)

3 На iPhone SE логотип очень мелкий, его не видно:
![Логотип](https://user-images.githubusercontent.com/88287882/206970288-d3612e27-21ab-4c91-a46d-5bcde7d77c62.png)

а для Samsung Galaxy S8+ и Galaxy Fold логотип вообще отсутствует:
![2022-12-11_21h06_15](https://user-images.githubusercontent.com/88287882/206970409-f1d4126c-9ecf-4437-9c7f-1901dd1572a8.png)

Кроме того, на мобильных устройствах кнопка с уведомлениями (колокольчик) и кнопка Профиль расположены друг под другом, можно убрать их в отдельную кнопку или расположить в один ряд. Также сейчас при появлении уведомления значок с количеством уведомлений расположен близко к краю экрана:
![image](https://user-images.githubusercontent.com/88287882/206972195-20d78473-9b07-4c22-ba6b-d7ea2006a7b6.png)

### Среда.

Разные разрешения экранов мобильных устройств через F12, Google Chrome

### Ожидаемое поведение

Все кнопки, значки и поля отображаются корректно и не выходят за рамки экрана

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Исправлены пункты 1 и 2.
Пункты 3 и 4 должны быть исправлены в https://github.com/alor-broker/Astras-Trading-UI/issues/469
