### ISSUE TITLE
[BUG] Скрываются все отложки после исполнения заявки.

### ISSUE THREAD

**Issue by daleburunduk** [alor-broker/Astras-Trading-UI#734]
### Опишите баг

На спб, если выставить отложки, в том числе по разным тикерам, то после совершения сделки/срабатывании любой из отложек, они скрываются из терминала и снять их можно только из приложения. Возможно, это происходит только при превышении общей суммы отложек доступной ликвидности по счету. Счет рублевый.

### Воспроизведение

1. Создать отложки.
2.  Выполнить любую сделку, не обязательно по тому же тикеру.
3. В виджете Блоттер на закладке Стопы убедится в отсутствии заявок. В мобильном приложении убедится в их наличии.

### Среда.

Windows 10
Brave [Версия 1.46.144 Chromium: 108.0.5359.128 (Официальная сборка), (64 бит]

### Ожидаемое поведение

Не скрывать существующие заявки ни в каких случаях. В том числе не пытаться отменить отложенный заявки до их срабатывания, если задумка была в этом.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@daleburunduk 
При проверке указанное поведение воспроизвести не удалось.
Логика приложения не предполагает какого-либо скрытия заявок. Если заявка выполняется, то он остается в списке, при этом у нее только обновляется статус.
Убедитесь, пожалуйста, что у Вас не настроены какие-либо фильтры в таблице Стоп-заявок.

Если указанное поведение повторяется, то пришлите, пожалуйста, скрин консоли браузера (F12). Описанное поведение возможно только в случае возникновения каких-либо ошибок, которые могут быть отображены в консоли.
При этом после перезагрузки страницы записи должны появится (если они отображаются в другом приложении).

**Comment by PilgrimViis** [comment]
Тоже никогда такого не замечал. @daleburunduk тут ваш комментарий нужен. Проверьте ещё раз пожалуйста. Пока я закрою задачу.
