### ISSUE TITLE
[BUG] После редактирования отложек срабатывание происходит и по цене "до", и по цене "после".

### ISSUE THREAD

**Issue by daleburunduk** [alor-broker/Astras-Trading-UI#735]
### Опишите баг

На СПБ, после срабатывания отложки на сдачу позиции, неоднократно обнаруживал "перевернутую" позу. Скорее всего, происходит это после редактирования цены в отложке, т.к. цены исполнения разные, т.е. старая заявка не отображается, но остается действующей. Счет рублевый.

### Воспроизведение

1. Создать условную лимитную заявку (использую одинаковые сигнальную и цену исполнения).
2.  Отредактировать цены на большее отклонение от текущей цены акции.
3.  Дождаться срабатывания.

### Среда.

Windows 10
Brave 
[Версия 1.46.144 Chromium: 108.0.5359.128 (Официальная сборка), (64 бит]

### Ожидаемое поведение

Выставление лимитной заявки только по итоговой цене в условной заявке.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Необходимо проверить указанное поведение на стороне backend. 
Со стороны приложения указанное поведение невозможно - при редактировании любой заявки старая заявка отменяется и создается новая с измененными параметрами
