### ISSUE TITLE
[FEATURE] В таблицах сохранять настройки фильтров и сортировки

### ISSUE THREAD

**Issue by daleburunduk** [alor-broker/Astras-Trading-UI#737]
### Опишите проблему, которую решает ваша фича

После перезагрузки страницы в таблицах фильтры и сортировки необходимо настраивать заново.

### Опишите предлагаемое вами решение

В таблицах сохранять настройки фильтров и сортировки.

### Дополнительная информация

Наверное, в дополнении к настройкам колонок https://github.com/alor-broker/Astras-Trading-UI/issues/97

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Но ведь фильтры и сортировка это как раз "временные" вещи. Т.е. при перезагрузке они должны слетать. Я уверен, что люди будут жаловаться в техподдержку, что у них "пропали позиции" и "перезагрузка страницы не помогает".  А зачем вы вообще перегружаете страницу при трейдинге?

**Comment by PilgrimViis** [comment]
Задачу пока закрою, но если вы добавите доводов в пользу сохранения фильтров, то открою опять.

**Comment by daleburunduk** [comment]
Страницу перегружаю в том числе, потому что данные на ней не обновляются, если некоторое время окно не активно, хоть это и временная проблема, надеюсь. Сортировку я бы временной настройкой не назвал, как раз хочется видеть все в привычном виде сразу, а не протыкивать каждый раз после перезагрузки. Фильтры тоже можно применять на постоянку, создав несколько копий виджетов с разными значениями, например. Ну значек активного фильтра можно подсветить поярче, чтобы пользователь не пугался собственных настроек...
