### ISSUE TITLE
[FEATURE] В полях ввода вводить разделитель дробной части независимо от раскладки

### ISSUE THREAD

**Issue by daleburunduk** [alor-broker/Astras-Trading-UI#739]
### Опишите проблему, которую решает ваша фича

Неудобно, что при вводе цены нужно контролировать раскладку клавиатуры, чтобы поставить точку разделителем. Особенно неудобно, если цена вводится с numpad - части клавиатуры, особенно тем, у кого этот блок вынесен отдельным устройством. Так же при копировании цены из внешних источников, если там в качестве разделителя выбрана запятая, необходимое значение так же не подставится.

### Опишите предлагаемое вами решение

1. В полях ввода (цены) вводить необходимый разделитель (точку) независимо от раскладки (при вводе запятой на русской раскладке).
2. При подстановке в поле ввода с дробной частью (цены) значения из буфера обмена заменять разделитель на необходимый (запятую на точку).

### Правила

- [X] Я согласен следовать правилам

**Comment by agushasok** [comment]
решено в рамках https://github.com/alor-broker/Astras-Trading-UI/issues/668

**Comment by PilgrimViis** [comment]
@agushasok решена но не полностью. Часть с копированием цены с "," не работает. 
![image](https://user-images.githubusercontent.com/6408195/210347305-d4a297ab-5b50-4589-8421-0cb172262399.png)
