### ISSUE TITLE
[FEATURE] Вкладка Условная виджета Заявки

### ISSUE THREAD

**Issue by daleburunduk** [alor-broker/Astras-Trading-UI#740]
### Опишите проблему, которую решает ваша фича

При выставлении нескольких отложенных заявок все действия необходимо проделывать каждый раз. 
Вкладка занимает много места из-за надписи с предупреждением.

### Опишите предлагаемое вами решение

1. При переключении с вкладки Лимитная (и обратно) переносить значения цены и количества в соответствующие поля.
2. При переключении тикера сохранять положение переключателя Limit-Market
3. При заполнении поля "Сигнальная цена" заполнять поле Цена (для последующего редактирования при необходимости, например способом https://github.com/alor-broker/Astras-Trading-UI/issues/738). 
4. При вводе цены ниже текущей значение поля Условие автоматически переключать на "Меньше" и наоборот. 
5. Надпись с предупреждением о новом сервисе открывать при первом в сессии открытии вкладки и убирать по кнопке ОК /сворачивать в значок восклицательного знака/ добавить такой знак в название вкладки и после закрытия сообщения отображать только там.
	

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Согласен, хорошие идеи. Сделаем. По №5 я думаю можем дисклеймер полностью убрать. Сервис со стоп заявками уже в боевой эксплуатации около полугода и не было ни одного инцидента с неккоретными срабатываниями стопов за это время.
