### ISSUE TITLE
[FEATURE] Вкладка Лимитная виджета Заявки

### ISSUE THREAD

**Issue by daleburunduk** [alor-broker/Astras-Trading-UI#741]
### Опишите проблему, которую решает ваша фича

Повысить скорость настройки и выставления заявок.

### Опишите предлагаемое вами решение

1. При нажатии на значения "К покупке"/"К продаже" подставлять значение в поле "Количество лотов".

	

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
> Горячие клавиши для кнопок "Купить"/"Продать" - B/S или настраиваемые (должны работать и для вкладки Условная).

Вот эту часть убрал. Вынесите её, пожалуйста, в отдельную задачу. Первую часть же, мы сделаем.
