### ISSUE TITLE
[FEATURE] Списки инструментов в выборе инструмента

### ISSUE THREAD

**Issue by daleburunduk** [alor-broker/Astras-Trading-UI#742]
### Опишите проблему, которую решает ваша фича

Повысить удобство создания списков тикеров.

### Опишите предлагаемое вами решение

1. Добавить предопределенный список "История тикеров", который будет заполняться автоматически.
2. Добавить возможность ручной сортировки списка.
3. Добавить возможность из контекстного меню тикера перемещать/копировать его в выбранный список.
4. Добавить возможность выгрузки списка в строку через пробел/загрузки из строки.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
1. А зачем эта история нужна, не понял?
2. А какая сортировка нужна? Сейчас есть сортировка по Тикеру. 
4. Не понял, что за "выгрузка списка в строку"?

**Comment by daleburunduk** [comment]
1. Для быстрого возврата к недавно просмотренным. 
2. Ручная, чтобы иметь возможность наиболее востребованные тикеры из списка переместить в его начало.
3. Возможность выгрузить сформированный список в строку вида "AAPL NVDA AMD...", либо создать новый список из такой строки. Простой способ обмена с другими приложениями, например, для того, чтобы из того же терминала Тинькофф перенести имеющиеся списки.

**Comment by sbelashevskiy** [comment]
1. Добавлен список "История". Создается автоматически. Нельзя удалить/переименовать. Нельзя в него явно добавить инструменты:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/8ee0a81d-a351-4b13-a3cd-3c90d6581c5c)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/0f7e6858-7f05-43e6-befd-26edfe2e9cc5)

2. Добавлена возможность сортировки через флаг. Для существующих виджетов фичу нужно включать:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/5aedb605-ff63-4c84-a03a-ff3edc53e3ab)
Для вновь добавленных виджетов фича включена по умолчанию:
https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/5225de7c-b302-40cf-bddb-1e677c40931b
Реализовано как в https://github.com/alor-broker/Astras-Trading-UI/issues/818
Инструмент можно пометить флагом "Избранное". Если включена сортировка по столбцу "Избранное", то избранные инструменты отображаются в начале списка. Сортировка включена по умолчанию

3. Добавлено перемещение/копирование инструментов между списками:
https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/e3a0136b-99bd-43bb-b2ef-3185b28e285d

4. Добавлен импорт/экспорт инструментов:
https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/d6271f3f-acb5-400f-87c9-765ea3978ac0
