### ISSUE TITLE
[FEATURE] Улучшения виджета Теханализ

### ISSUE THREAD

**Issue by daleburunduk** [alor-broker/Astras-Trading-UI#743]
### Опишите проблему, которую решает ваша фича

Добавить информативность графику/повысить удобство управления заявками.

### Опишите предлагаемое вами решение

Отображать выставленные лимитки и отложки с возможностью перетаскивать их на нужную цену со всплывающим окном подтверждения/редактирования новой цены. 
Отображать линию средней цены позиции, на ней отображать текущую прибыль/убыток в центах/процентах (опционально).

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@sbelashevskiy просьба посмотреть поддерживает ли либа такой функционал.

**Comment by sbelashevskiy** [comment]
Отображение позиции, заявок и редактирование заявок путем перетаскивания уже реализовано
