### ISSUE TITLE
[FEATURE] Разделение новостей на подразделы

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#756]
### Опишите проблему, которую решает ваша фича

Сейчас новости показываются сразу по всему. Их очень много

### Опишите предлагаемое вами решение

Сделать 3 раздела в виде настройки или переключателя в самом виджете
1. Новости по портфелю, 
2. Новости по инструменту 
3. Все новости

### Правила

- [X] Я согласен следовать правилам

**Comment by agushasok** [comment]
необходимо доработать бек, чтоб с фильтрами можно было отправлять фильтры поиска
