### ISSUE TITLE
Более быстрый и удобный поиск и смена инструмента

### ISSUE THREAD

**Issue by LinaRitchie** [alor-broker/Astras-Trading-UI#772]
### Опишите проблему, которую решает ваша фича

Свежее обновление "Смена инструмента при вводе. С помощью Ctrl+F (#417)" переносит на виджет "Выбор инструмента" всегда одной определенной группы. Если в терминале открыты несколько групп виджетов, предлагаю менять инструмент именно той группы, с которой было нажатие Ctrl+F.

### Опишите предлагаемое вами решение

Пока не поняла, от чего сейчас зависит выбор группы после нажатия Ctrl+F.
Догадка 1: Желтая группа виджетов в левой части экрана, синяя справа. "Выбор инструмента" есть в обеих группах. При нажатии Ctrl+F с синих виджетов всегда активируется желтый "Выбор инструмента". Думала, что приоритет отдается тому цвету, который первый в списке цветов. Поменяла желтый на красный, сохранив расположение виджетов. Все равно активировался красный (хотя он ниже синего в списке цветов). 
Догадка 2: Ctrl+F переносит на ближайший "Выбор инструмента" слева направо, сверху вниз. Добавила новый виджет в самый верхний левый угол терминала. Нет, Ctrl+F все равно переносило на красный (бывший желтый) "Выбор инструмента". Убирала красный "выбор инструмента" в правый нижний угол терминала - все равно активировался именно он.
Догадка 3: удалила красный виджет полностью. Оставила синий справа, а слева создала новый. И теперь Ctrl+F стало всегда направлять на синий. Похоже, Ctrl+F выбирает самый ближайший виджет "Выбор инструмента" (слева направо) на момент загрузки терминала, до тех пор, пока виджет не будет удален. Затем переходит на второй с момента загрузки.

### Опишите альтернативные решения, о которых вы думали

Дополнительно хотелось бы такие улучшения: 
1. Сделать возможность смены инструмента при вводе названия (тикера) в заголовке любого виджета. Это позволило бы не занимать пространство виджетом "Выбор инструмента" вообще, если список инструментов как таковой не нужен, нужно просто менять открытый в рабочем пространстве тикер.
Слева - как сейчас. Справа - пример, как предлагаю. Достаточно кликнуть в заголовок любого открытого виджета и начать вводить текст.
![search](https://user-images.githubusercontent.com/122786098/212654088-5e58da06-0ddc-4daf-9a74-0f9578da5dde.jpg)

2. При поиске инструмента отдавать приоритет тому, чей тикер совпадает с введенным текстом.
Например, нужен C (CitiGroup), инструмент СПБ Биржи. Сейчас при вводе символа такой инструмент даже не предлагается, а на первом месте выпадает юань, инструмент Мосбиржи. Может, хотя бы можно отдать приоритет инструментам той биржи, чей портфель сейчас активен в терминале.
![tickers](https://user-images.githubusercontent.com/122786098/212661993-e7c6102a-f282-487f-b8b2-e02726ff401c.jpg)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
1. Использование групп и быстрая смена инструмента **противоречат** друг другу - если используются группы, то в них есть определенные виджеты, из которых можно изменить инструмент и только определенным образом. Т.е. при включенной группировки инструмент должен меняться, например, только через через виджет выбора инструмента, привязанного к этой группе.
2. Нет никакой особой зависимости в выборе в каком виджете активируется поиск - поиск активируется в первом виджете в порядке их добавления. Хоткей это глобальная штука и он не подразумевает использование для конкретной группы т.к. мы не можем угадать что именно хотел пользователь и тем более определить из какой группы он был вызван т.к у нас нет понятия активный виджет/ активная группа. Более того наличие нескольких виджетов смены инструмента это исключительная ситуация для данной фичи, потому и реализовано текущее поведение - активируется поиск только в первом по порядку добавления виджете.
3. Вариант с поиском в заголовке мало чем отличается от текущей реализации смены инструмента через настройки виджета. Более того такой вариант будет нести только больше проблем - нехватка места для отображения результатов поиска, незавершенная операция смены (пользователь что-то начал вводить, ничего не выбрал - к какому инструменту сейчас привязан виджет?). Кроме того реализованная фича подразумевает смену инструмента у всего дашборда, а описывается фактически ситуация для одного виджета

**Comment by LinaRitchie** [comment]
По поводу 1 и 2 поняла.
По пункту 3. Действительно, сейчас смена инструмента с любого виджета реализована через настройки (открыть настройки, ввести название тикера, сохранить, закрыть настройки). Это много кликов. Я, например, не пользуюсь таким способом и держу отдельные виджеты "выбор инструмента" на каждую группу просто чтобы быстрее вбить тикер (если у компании вышла новость и требуется скорость). Можно было бы освободить это пространство не в ущерб скорости смены тикера. Примеры терминалов, где реализован поиск по инструментам из любого виджета с любым количеством групп в минимальное количество кликов: Webull десктопная версия, Aurora, Tinkoff.

**Comment by PilgrimViis** [comment]
@LinaRitchie Решили сделать альтернативное решение. №1. По поводу проблемы №2 я создал отдельную задачу. https://github.com/alor-broker/Astras-Trading-UI/issues/1091
