### ISSUE TITLE
[BUG] В блоттере не отмечается число исполненных лотов условной заявки

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#773]
### Опишите баг

При исполнении стоп-заявки или стоп-лимита в блоттере в колонке "Остаток" не отмечается число исполненных лотов. Воспроизводится на любом рынке

### Воспроизведение

1. На ВР выбрать EURRUB_TMS. 
2. Выставить стоп-заявку на покупку 1000 лотов.
3. В блоттере на вкладке "Стопы" для графы "Остаток" проверить отображение исполненных лотов.

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

В колонке "Остаток" для исполненной валютной пары- 1000/1000

### Скриншоты

https://user-images.githubusercontent.com/88287882/212664672-bc3f164f-6653-454c-ad7c-aa70e40aa972.mp4

На ФР ситуация повторяется:
![image](https://user-images.githubusercontent.com/88287882/212664865-8f015a51-f27c-41ce-b3d1-25a58f2d6f0c.png)

### Дополнительная информация

Также лучше поправить всплывающее уведомление при наведении мыши на "Остаток":
![image](https://user-images.githubusercontent.com/88287882/212665491-1c64183e-979b-4ac6-bc18-2610e72a56df.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Бэкенд не присылает значения для выполненных заявок (согласно документации он должен прислать filledQtyBatch)
