### ISSUE TITLE
[BUG] При сужении виджета "Выбор инструмента" ширина столбцов не уменьшается

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#775]
### Опишите баг

При растягивании виджета "Выбор инструмента" -   ширина заголовков таблицы становится шире, однако при сужении виджета - заголовки уже не сужаются  и появляется горизонтальный ползунок (как для "Все инструменты", например).

### Воспроизведение

1. Выставить виджет "Поиск инструмента".
2. Расширить его, а потом сузить.
3. Посмотреть на ширину колонок виджета.

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

При сужении виджета размер колонок уменьшается (до 75px в ширину).

### Скриншоты

Можно только увеличить ширину столбцов:
![image](https://user-images.githubusercontent.com/88287882/212686289-19f40aec-8215-4564-9c1b-b06fb680ea87.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@ilya7am 
Очень странно, что проблема с сужением проявляется только на виджете выбора инструмента.
Она проявляется на других виджетах?
Она проявляется в других браузерах?
Она повторяется?
Она повторяется после приведения дашборда к стандартному виду?
У меня ничего подобного нет:

https://user-images.githubusercontent.com/29191749/212811247-3d084209-6f05-46bc-888f-151bc82cfaad.mp4

**Comment by ilya7am** [comment]
@sbelashevskiy 
Воспроизвел еще раз. Если выставить любой виджет справа от дашборда и расширить его вправо за рамки сетки, то при сужении виджета обнаруживается такой баг. Помогает перезагрузка страницы:
https://user-images.githubusercontent.com/88287882/212865015-6e6a76ce-b6b8-44b8-ae9c-18985824730a.mp4

После приведения дашборда к стандартному виду и повторению шагов - баг воспроизводится снова.
Обнаружен в браузерах Google Chrome (v108.0.5359.125), Mozilla v109.0b9 (64-разрядный) и Microsoft Edge (v109.0.1518.55)
