### ISSUE TITLE
[BUG] В настройках виджетов не ищутся бумаги торгуемые на СПБ

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#779]
### Опишите баг

После последнего обновления в настройках виджетов не ищутся бумаги торгуемые на СПБ, до это все было. Сейчас поиск идет только по moex

### Воспроизведение

Открыть настройку виджета (стакан, график, скальперский стакан, выставление заявки) в поле инструмента напечатать например BIDU, предложит варианты только на moex, на spbx нет.

### Среда.

вин10
firefox

### Ожидаемое поведение

предлагать инструменты с СПБ

### Скриншоты

как сейчас
![изображение](https://user-images.githubusercontent.com/105856884/212874839-7b373f4b-ff8b-4e7e-9471-2a21d58f17cf.png)

а в виджете выбор инструмента вот так
![изображение](https://user-images.githubusercontent.com/105856884/212875082-730e37f9-4da5-4d85-b5c8-81aa71d71717.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by ilya7am** [comment]
Ситуация повторяется и для виджета "Выбор инструмента" для бумаг, торгуемых на обеих биржах. Так, при вводе SBER, ALRS, VTBR, LKOH выдаются результаты только для MOEX. Пользователю придется указывать в поле ввода саму биржу (SPBX:SBER, SPBX:ALRS). Это не совсем удобно, занимает время. Поправьте, пожалуйста.

https://user-images.githubusercontent.com/88287882/213149717-40235e97-cdd0-4d8b-b6ab-1e8411eb5a01.mp4
