### ISSUE TITLE
[BUG] Поправить верстку при входе через Мозиллу

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#782]
### Опишите баг

При авторизации в браузере Firefox Developer Edition:
1. для четырех виджетов  - Выбор инструмента, Все инструменты, Все сделки и Новости - в шапке справа присутствуют стрелки-переключатели, которые не работают и по сути лишние. Их можно убрать, в браузере Google Chrome и Edge таких стрелок нет. Сортировка в случае необходимости осуществляется по каждому столбцу в отдельности.
![2023-01-18_09h06_04](https://user-images.githubusercontent.com/88287882/213097342-875553aa-fa80-4fd1-ac20-5f752b9c66cb.png)

2. Появляется большой ползунок, а именно:
![2023-01-17_14h11_14](https://user-images.githubusercontent.com/88287882/212885244-4cca4448-8e67-4de5-a546-1537a9a9e08d.png)

### Воспроизведение

1. Зайти в Астрас на Mozilla Firefox Developer Edition.
2. Для Выбор инструмента, Все инструменты, Все сделки и Новости проверить отображение элементов.
3. Выставить виджеты и сузить их.
4. В "Выборе инструмента" указать "E".
5. Зайти в Профиль клиента, в дропдауне выбрать валюту по умолчанию.
6. В виджете выставления заявки для условных заявок выбрать дату в календаре
7. Оставить фидбек о приложении.
8. В каждом из шагов проверить отображение ползунков.

### Среда.

Windows 10
Mozilla Firefox Developer Edition v109.0b9 

### Ожидаемое поведение

1. В шапках виджетов нет неактивных кнопок-стрелок.
2. Вертикальные и горизонтальные ползунки более узкие в размерах и не выделяются на общем фоне приложения.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
C большим ползунком не получится поправить, у фаерфокса его просто нельзя сделать меньше. Ну по крайней мере нельзя было полгода назад. А вот стрелки убрать надо бы
