### ISSUE TITLE
Поправить название виджета "Все инструменты"

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#785]
В названии виджета есть небольшая опечатка:
![2023-01-18_09h14_57](https://user-images.githubusercontent.com/88287882/213098302-72fff5a1-fd2e-4902-9a77-7425a32bef83.png)

**Comment by PilgrimViis** [comment]
@agushasok это уже поправил у себя. не опубликовали пока просто
