### ISSUE TITLE
[BUG] Поправить функционал "Корзины заявок"

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#788]
### Опишите баг

1.1 При успешном выставлении одной или нескольких лимитных заявок внизу виджета появляется сообщение: "Выставление одной или нескольких заявок завершилось с ошибкой", хотя заявки успешно размещены в блоттере, запросы limit отправлены успешно, консоль не содержит ошибок:
![image (39)](https://user-images.githubusercontent.com/88287882/213432537-43250037-0240-4a38-90ae-2bc2fe593a78.png)

1.2 Кроме того, при переключении между портфелями в виджете "Корзина заявок" сообщение об ошибке сохраняется:

https://user-images.githubusercontent.com/88287882/213432780-dcf49432-5ce3-4948-bfee-02e4cf3a3ac4.mp4

2.1 При размещении виджета в ширину более 267px и клике на "плюс" для появления новой графы  - новая запись не сразу (1-2 сек.) размещается на одной строке:
![image](https://user-images.githubusercontent.com/88287882/213433083-28d2d7cb-7073-4cd7-9a7b-6f9af033300a.png)

2.2 При изменении привязки виджета Корзины (клике на кнопку "замок") - содержимое виджета "прыгает":

https://user-images.githubusercontent.com/88287882/214028475-94224a7c-bfff-43ef-a967-3607d950a6c6.mp4

3. "Корзина заявок" - выставляет заявки по разным бумагам, она не предполагает привязки к одному тикеру. Однако при включенной опции "привязки инструментов к лейблам " для нее появляется круглый лейбл, которые никак не влияет на привязку бумаги при выставлении лимитной заявки. Лучше этот лейбл вообще скрыть, как реализовано для виджета Курсы валют" или "Новости":
![2023-01-19_14h30_56](https://user-images.githubusercontent.com/88287882/213434542-252b682d-6a33-4aa5-ab3c-fc6a63786ce6.png)

4. Убрать лишний пробел при валидации поля по шагу цены:
![2023-01-25_09h30_51](https://user-images.githubusercontent.com/88287882/214496467-28c8ea2e-a5af-4004-be77-fe4179577217.png)

### Воспроизведение

1. Выставить виджет "Корзина заявок".
2. Разместить лимитные заявки на 2 лота APTK и 1 лот DSKY.
3. Переключиться между портфелями.
4. Нажать на "плюс" в виджете.
6. В Профиле включить привязку к лейблам.
7. Посмотреть на отображение корзины.

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

1. При успешном выставлении лимитной заявки не появляется сообщения: "Выставление одной или нескольких заявок завершилось с ошибкой". При переключении между портфелями ошибки не дублируются.
2. При клике на "плюс" поля для ввода сразу располагается на одной строке.
3. Отсутствует привязка "Корзина заявок" к лейблам

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@ilya7am у тебя язык по умолчанию в Edge английский?

**Comment by ilya7am** [comment]
Сам Edge на русском, но приложение открывается по умолчанию на английском
