### ISSUE TITLE
[BUG] не могу выбрать тикер SPBE SPBX

### ISSUE THREAD

**Issue by exvion** [alor-broker/Astras-Trading-UI#793]
### Опишите баг

Не могу выбрать тикер SPBE SPBX в виджете Стакан

### Воспроизведение

- В виджете Стакан нажимаю шестеренку
- Редактирую Ticker - пишу SPBE
- В настройках advanced указываю SPBX

### Среда.

- MacOS
- Safari

### Ожидаемое поведение

Чтобы работал стакан

### Скриншоты

![Снимок экрана 2023-01-23 в 17 49 26](https://user-images.githubusercontent.com/254680/214071593-a82a3569-af73-47b8-b1cf-a1340eee849c.png)
![Снимок экрана 2023-01-23 в 17 57 12](https://user-images.githubusercontent.com/254680/214071605-358b901b-1e7a-4d42-8e54-980fb18f9388.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Возможно это дубликат. #779 Мы через час выпустим фикс этого бага. Если проблема продолжится, то посмотрим.

**Comment by PilgrimViis** [comment]
Да, этот баг не воспроизводится да и не было больше жалоб закрываю задачу.

**Comment by exvion** [comment]
> Да, этот баг не воспроизводится да и не было больше жалоб закрываю задачу.
Как мне объяснили это не баг, а архитектурные особенности приложения. Предложили решать задачу другим способом, но в нем тоже был баг, который устранили
