### ISSUE TITLE
[BUG] Огромный отступ внизу виджета 

### ISSUE THREAD

**Issue by exvion** [alor-broker/Astras-Trading-UI#794]
### Опишите баг

<img width="666" alt="Снимок экрана 2023-01-23 в 22 19 14" src="https://user-images.githubusercontent.com/254680/214130835-1dbb20f3-b723-4c91-aedb-b4cba9c4f41e.png">

### Воспроизведение

Создать виджет Blotter

### Среда.

Macos
Safari

### Ожидаемое поведение

Хотелось бы иметь минимально возможный отступ, чтобы больше информации влезало в виджет

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Непонятно о чем речь: на скринах вообще нет данных, потому и такой отступ. Высота таблицы  = высоте иконки 
![image](https://user-images.githubusercontent.com/29191749/221546625-9be72922-c7c3-40aa-8218-6b3534571442.png)

Таблица всегда отображает максимально допустимое количество строк, если таковые имеются, Например:

![image](https://user-images.githubusercontent.com/29191749/221546894-e81f821b-4566-4ed2-8ddb-0b83e2bb7cd0.png)
![image](https://user-images.githubusercontent.com/29191749/221546934-9758f5ca-c137-4259-9e8c-42dbfaa09a45.png)
![image](https://user-images.githubusercontent.com/29191749/221546970-560fd191-77fa-49bc-87f7-de56fec76fb8.png)

При этом таблица целенаправленно не растягивается во всю высоту виджета - чтобы кнопка экспорта данных всегда располагалась максимально близко к данным (стандартное поведение футтера таблицы) и не было такого, что строк мало, они отображаются в самом верху виджета, а кнопка экспорта где-то внизу. Что-то типа такого:
![image](https://user-images.githubusercontent.com/29191749/221548334-75d3cf24-1cd7-4f21-b220-807087dd664c.png)

**Comment by exvion** [comment]
Речь не о высоте таблицы, а об отступе снизу таблицы. Видимо в этой области когда есть данные появляется кнопка Сохранить в файл

**Comment by sbelashevskiy** [comment]
@exvion 
на данный момент я не наблюдаю никакого отступа. См. скриншоты

**Comment by exvion** [comment]
@sbelashevskiy отметил на ваших скриншотах, по мне так это расточительство тратить область равную почти двум строкам данных на одну кнопку экспорта. Можно же ее сделать более компактной или перенести в другой место
![221546970-560fd191-77fa-49bc-87f7-de56fec76fb8](https://user-images.githubusercontent.com/254680/221600721-b9f68e4d-4dd9-4afd-8d65-c074caa33062.png)
![221546934-9758f5ca-c137-4259-9e8c-42dbfaa09a45](https://user-images.githubusercontent.com/254680/221600735-81e4aeba-d738-42a2-aa72-3b2a4dd896d7.png)
