### ISSUE TITLE
[BUG] Ошибка кол-ва инструмента в заявке

### ISSUE THREAD

**Issue by ErmakovAnton** [alor-broker/Astras-Trading-UI#809]
### Опишите баг

При наличии неполного лота в лимитах клиента выставляется заявка на бОльшую сумму. Пример: у клиента на счете 12.64 WDB. При вводе 12.64 в поле кол-во на биржу уходит заявка с объемом 13. 

### Воспроизведение

1. Добавить в лимит инструмент с дробным количеством.
2. В виджете ввода заявки кликнуть по лимиту.
3. Проверить кол-во в виджете заявки. 

### Среда.

Любой браузер

### Ожидаемое поведение

Дробные заявки не должны выставляться, либо округляться в меньшую сторону.

### Скриншоты

![image](https://user-images.githubusercontent.com/104133077/215438862-477c4002-422f-4c32-85b8-f04dc6922aa8.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Судя по всему ото ошибка округления API.
Приложение отправляет корректное значение:
![image](https://user-images.githubusercontent.com/29191749/215459373-091f8511-d1ff-4206-a7c4-78054130ce1a.png)
а API в данных о заявке производит округление:
![image](https://user-images.githubusercontent.com/29191749/215459694-0f70aaf4-91b2-4d7f-a799-7b6a03796060.png)
