### ISSUE TITLE
[BUG] Бумаги с разными режимами торгов отображаются одновременно с одним лейблом

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#814]
### Опишите баг

При указании одной и той же бумаги на разных бордах активный желтый лейбл присваивается сразу двум бумагам.
Например при выборе SBER (SMAL) и SBER (TQBR) лейбл ставится рядом с каждой из них, хотя в шапках виджетов и модальном окне заявки указан определенный борд.

### Воспроизведение

1. Выставить "Выбор инструмента" и "Стакан".
2. В "Выборе инструмента" выбрать SBER (SMAL, а потом SBER (TQBR).
3. Посмотреть на желтый лейбл для выбранной бумаги.
4. Переключиться между бумагами и сравнить отображение стаканов.

### Среда.

Любая

### Ожидаемое поведение

Желтый лейбл ставится рядом с активной бумагой выбранного режима торгов.

### Скриншоты

https://user-images.githubusercontent.com/88287882/216611137-36e66f0e-4abd-4b4d-acd2-37d19c05e117.mp4

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я считаю что это не баг, а нормальное поведение.
