### ISSUE TITLE
[BUG] При смене учетки не выбирается портфель

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#815]
### Опишите баг

После смены учетки меняется список портфелей. После смены учетки последний выбранный портфель не находится в новом списке и изменить портфель невозможно

### Воспроизведение

1. Залогиниться с какой-либо учеткой
2. Выбрать портфель
3. Разлогиниться
4. Залогиниться с другой учеткой
5. Список портфелей пуст, выбрать портфель невозможно
![image](https://user-images.githubusercontent.com/29191749/216933906-57dbd6a3-2dd7-4741-803d-d901fff6960b.png)

### Среда.

любая

### Ожидаемое поведение

Необходимо уточнить

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@PilgrimViis 
Это относится к новой фиче с несколькими дашбордами. У каждого дашборда запоминается какой портфель был выбран последним. После смены учетки меняется список портфелей, и последний выбранный в новый список уже не попадает.

Не совсем понятно какое ожидаемое поведение в этом случае. Вижу 2 варианта:
1. Если последний выбранный для дашборда портфель не находится в списке, то выбираем дефолтный портфель из списка. Самый простой вариант, НО пользователь мог создавать дашборд под конкретный портфель, а мы его изменим на дефолтный.
2. У дашбордов должны быть привязка к учетной записи, из-под который их создавали. Вариант посложнее, но выгляди более логичным, чем подгружать дашборды другой учетки.

Этот фикс нужно сделать до паблиша на бой - при 2 варианте нужно скорректировать хранимую структуру настроек дашборда

**Comment by PilgrimViis** [comment]
Работать должно так.
1. Стандартное поведение. Клиент логинится и у него уже есть сохраненный портфель в дашборде. И этот портфель отдается с бекенда. Все работает как обычно в общем.
2. Клиент логинится, но сохраненного портфеля уже нет. Он пропал т.к. человек закрыл порфель, вывел с него деньги или залогинился с другого аккаунта. В там случае мы должны выбрать портфель по тому же алгоритму как выбирается портфель в первый раз при первом открытии терминала. НИКАКОЙ ошибки или оповещения делать не надо. 
3. Клиент логинится, но у него нет ни одного портфеля в доступных. В таком случае, надо показывать ошибку как у тебя на скрине, что портфелей нет.
