### ISSUE TITLE
[FEATURE] Увеличить доступные таймфреймы в виджете Тех Анализ

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#822]
### Опишите проблему, которую решает ваша фича

Запросы от клиентов на дополнительные теймфреймы, и курс онлайн-школы по наставничству, на котором наставник использует предлагаемые теймфреймы.

### Опишите предлагаемое вами решение

Добавить в виджет Тех анализ таймфреймы: 3 минуты,  30 минут, 1 неделя

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Ох боже, это ящик пандоры ей богу. Сейчас если начать добавлять, то список можно продолжать вечно. Давайте так, мы попробуем добавить таймфреймы на 30 минут, 1 неделю, 2 недели и 3 месяца. Остальные либо слишком большие (в 1 год большинство инструментов даже на 1 экран не влезет), либо какие-то нелогичные. Почему 3 минуты, а не 3.5 минуты например? 

@sbelashevskiy проверь ещё, пожалуйста, есть ли возможность в ТВ устанавливать свои собственные таймфреймы. Бэк должен поддерживать по идее. Если можно, то это бы решило проблему глобально.

**Comment by sbelashevskiy** [comment]
@PilgrimViis ,
возможности добавлять полностью кастомные интревалы в библиотеке нет.
Можно сделать через настройки, но нет никакой гарантии, что добавленные пользоваталем интревалы будут корректно поддерживаться бэком

**Comment by MorozovDen** [comment]
нас бы устроили те интервалы, которые есть в стандартном ТВ. Собственные не нужны, но в реальности эта тема интересна, типа рисовать уже закрытый бар и принимать решение в автомате до момента когда этот бар закроется у других))) Так что это может быть тема для каких нибудь дальних предложений.
