### ISSUE TITLE
[FEATURE] Расширить возможности управления мышью в скальперском стакане

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#825]
### Опишите проблему, которую решает ваша фича

Проблема касается выставления заявки мышью в спред. При открытии и закрытии позиции.
Ввиду этого много возможностьей трейдера становятся не доступными.

### Опишите предлагаемое вами решение

Предлагаю сделать альтернативный вариант управления мышью, добавить в ПРОФИЛЬ выбор того или иного варианты управления, первое , которое сейчас имеется, а второе:

- лкм в бидах: выставит лимитку на покупку по указанной цене
- лкм в офферах:  также выставит лимитку на покупку по указанной цене
- лкм в спреде: выставит лимитку на покупку по указанной цене 

- пкм в бидах:  выставит лимитку на продажу по указанной цене 
- пкм в офферах: выставит лимитку на продажу по указанной цене
- пкм в спреде: выставит заявку на продажу по указанной цене

### Дополнительная информация

https://user-images.githubusercontent.com/105817664/219027178-68cb071d-f513-493a-ade4-8040ac9cbad9.mp4

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Добавлена возможность переключать схемы (Профиль -> Горячие клавиши -> Действия мыши)
![image](https://user-images.githubusercontent.com/29191749/226566389-c7144b2c-32a3-44b6-a65a-4b72273ff796.png)
![image](https://user-images.githubusercontent.com/29191749/226566424-0ff96a84-1abf-4d2b-ada0-9ed86eabf0fc.png)
