### ISSUE TITLE
[FEATURE] Изменение ширины столбцов

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#832]
### Опишите проблему, которую решает ваша фича

Сломалось оно или так и было, но сейчас с изменением ширины какая-то беда.
1. При установке курса на границу и попытке перетащить, ширина столбца становится больше.
2. У колонок есть какая-то минимальная ширина, меньше которой перетащить не дает. При чем эта величина пересчитывается относительно ширины виджета.
3. "Резиновость" других колонок. При изменении ширины столбца, меняется ширина других - таким образом невозможно выставить все колонки по очереди на нужную величину.

https://user-images.githubusercontent.com/99450543/220092221-0feb1a4d-2193-4d14-b550-4c0c18303f2f.mp4

### Опишите предлагаемое вами решение

1. При изменении ширины - величина берется по текущему значению
2. Без ограничений на минимальный или максимальный размер. В части минимального можно ограничиться длинной заголовка, т.к. уже уже ползет на вторую строку
3. Изменение ширины только выбранного столбца

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Это ожидаемое поведение - изменение ширины имеет смысл только когда колонок слишком много и они не влезают на экран. Когда их так мало, то они растягиваются во всю ширину и изменение г=ширины одного столбца приводит к изменению ширины другого

**Comment by dzeron13** [comment]
Ок, с резиновостью понятно. А чего размер-то скачет при попытке изменения?

**Comment by sbelashevskiy** [comment]
Потому что ширина таблицы избыточна и таблица скачкообразно изменяет ширину. Сложно вообще представить кейс, когда пользователь захочет при такой ширине виджета (когда все данные заведомо помещаются, да еще и с большим запасом)  менять ширину столбцов

https://user-images.githubusercontent.com/29191749/220107012-bf88a546-5612-4a4e-b9eb-3ea52c425ec0.mp4

**Comment by sbelashevskiy** [comment]
И то если по каким-то непонятным причинам пользователю потребуется растянуть ширину столбцов гораздо больше ширины виджета, то он может это сделать
https://user-images.githubusercontent.com/29191749/220108193-b0120457-0881-47b5-ae51-c0c48dc4782a.mp4

Но  очень большой вопрос для чего это ему может понадобиться.

**Comment by PilgrimViis** [comment]
Джерон, я все таки не понимаю, в чем конкретно проблема с которой вы столкнулись? Какую конфигурацию таблицы для своей работы вы хотите сделать, но не можете?

**Comment by dzeron13** [comment]
> Джерон, я все таки не понимаю, в чем конкретно проблема с которой вы столкнулись? Какую конфигурацию таблицы для своей работы вы хотите сделать, но не можете?

Вообще основной вопрос, что конкретную колонку нельзя выставить по нужному размеру. Вот для примера, хочу я часть колонок узких, а пару длинных - так не получится.
![image](https://user-images.githubusercontent.com/99450543/224931893-dd40e08d-b8cf-439d-b64d-2b0bb41785cb.png)


При этом же если увеличивать ширину колонки, то те же самые колонки, которые нельзя было сузить - уже отлично скукожились.
![image](https://user-images.githubusercontent.com/99450543/224930537-2c515e25-0004-412a-9146-76ca21e9e4be.png)
Т.е. та самая "резиновость" она по сути однобокая - сузить колонки я не могу, но теоретически за счет увеличения ширины других и самого виджета смогу выстроить нужный мне сетап)

Думаю, можно закрыть. Если общая концепция выстроена на автомасшбировании, то менять это где-то локально или делать опциональным смысла особого нет.
