### ISSUE TITLE
[BUG] При смене учетки проверяется портфель от старого аккаунта

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#835]
### Опишите баг

В новом sso при смене аккаунта и авторизации идет проверка по портфелю с предыдущего аккаунта. Этот портфель, конечно же, не находится, из-за чего выдается сообщение об ошибке:

![image (163)](https://user-images.githubusercontent.com/88287882/220144857-366b8a0e-05fb-4038-bb05-a15a4d4c55b3.png)

D73420 - портфель предыдущего аккаунта

### Воспроизведение

1. Зайти в аккаунт, на котором есть деньги, например:
`логин: 71111111124
пароль: 654321`

2. Посмотреть на селектор портфелей в шапке приложения.
3. Сменить аккаунт на `p039004`.
4. Проверить уведомления.

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

Нет проверки на портфели от предыдущей учетной записи.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Нет никакой проверки на предыдущие портфели.
Всегда запрашивается список портфелей для текущего аккаунта.
Сделай корректное описание. По текущему описанию никакой ошибки не наблюдается:

https://user-images.githubusercontent.com/29191749/220281394-7b815ad0-0546-40fc-be2b-72af0361bde3.mp4

**Comment by ilya7am** [comment]
Ошибка воспроизводилась в запущенной ветке CCО на деве, сейчас в новой версии такого не наблюдаю.
Думаю, можно закрыть
