### ISSUE TITLE
[BUG] Не выбирается инструмент с СПБ в корзине заявок 

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#836]
### Опишите баг
Не выбирается инструмент с СПБ в корзине заявок

### Воспроизведение

- 1. Создать виджет корзины
- 2. Поискать бумагу с СПБ

### Среда.

- Chrome
- Android 

### Ожидаемое поведение

Инструмент должен находиться

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@PilgrimViis инструмент ищется по бирже текущего портфеля. В противном случае мы будем получать непонятные ошибки, когда часть заявок валится из-за отсуствующего портфеля для инструмента. Тем более вообще неочевидно, что при выбранном MOEX портфеле  будут отправлены заявки на SPBX портфель
