### ISSUE TITLE
[BUG] При авторизации в аккаунте без позиций часть функций работает некорректно

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#837]
### Опишите баг

При смене аккаунта и авторизации под логином, под которым у клиента нет позиций- данные сохраняются за предыдущий аккаунт, а именно:
- в "Выбор инструмента" список бумаг сохраняется по первому аккаунту
- в уже поставленном "Блоттере" и "Корзине заявок" - в шапках виджетов указан портфель от старого аккаунта, хотя токен и данные о юзере обновились и не содержат старый портфель:
![image](https://user-images.githubusercontent.com/88287882/220262415-3190a4a9-e9b9-4ce1-8ee9-d84ba7a50646.png)
![image](https://user-images.githubusercontent.com/88287882/220265543-4f77785d-555b-4c77-89ee-53e4b15dec94.png)

- расположение элементов дашборда такое же, как в предыдущем аккаунте. Возможно стоит делать сброс на "стандартный вид".

<br>
Кроме того, при попытке выставить новый "Блоттер" или  "Корзину заявок" - появятся два пустых серых блока, без возможности закрытия. Причем в самой консоли ошибки отсутствуют:

https://user-images.githubusercontent.com/88287882/220264091-4345e9e4-923b-4458-a348-1ae74d108a21.mp4

- Нельзя просмотреть Профиль клиента и основные настройки - откроется пустое модальное окно и в консоли появятся ошибки:
![image](https://user-images.githubusercontent.com/88287882/220264564-7bdb1a07-2f61-404e-a300-2b44b50b8996.png)

- кнопка "Заявка" неактивна

- виджет "Выставления заявки" пустой:
![image](https://user-images.githubusercontent.com/88287882/220262554-71399ed5-d76a-40e4-b9f2-f5bc5ab4ac0a.png)

### Воспроизведение

1. Зайти под аккаунтом `логин: P000661, пароль 123456`. Выставить блоттер, корзину, виджет заявки и поиск инструментов. 
2. Указать в строке поиска ALRS и AAPL.
3. Разлоигинться и зайти под `логин: 71111111124, пароль 654321`.
4. Открыть консоль F12.
5. Посмотреть на шапки виджетов, список бумаг в Инструментах.
6. Выставить новый "Блоттер" и "Корзину заявок".
7. Нажать на Профиль и Заявка.

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

Выставленные Блоттер и Корзина заявок - отображают основные вкладки и разделы. Профиль открывается. В "Выбор инструмента" список бумаг обнуляется при смене аккаунта. В консоли нет ошибок.

При открытии УОС в Кабинете клиента в рамках заключенного договора у клиента появляется список портфелей без позиций:
![image](https://user-images.githubusercontent.com/88287882/220267788-eb5ebb26-1823-47ae-95f2-158af43bfcc6.png)

Как вариант, можно выводить по умолчанию в "Блоттер", "Корзине заявок", модальном окне и виджете "Заявка" основной портфель фондового рынка MOEX (совпадающий с номером договора). А уже при попытке выставить заявку- ожидаемую ошибку об отсутствии средств в портфеле.

 

### Дополнительная информация

Если зайти в Астрас в режиме инкогнито - то проблема с серыми блоками для "Корзина заявок", "Блоттер" повторяются, кнопка  "Заявка" неактивна, "Профиль" не загружает данные, в консоли выдаются ошибки.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
1. Приложение показывать ТОЛЬКО портфели с позициями. Если таковых нет, то тогда и отображается надпись. Это ожидаемое поведение.
2. Список инструментов не привязан к аккаунту - оэто ожидаемое поведение.
3. Виджеты постоянно привязаны к одному и тому же порфелю. Портыель у виджетов меняется только пользователем или автоматически, если если портфель с позициями. Это ожидаемое поведение
4. Настройки дашборда НЕ привязаны к аккаунту. Ничего сбрасываться не должно. Это ожидаемое поведение,
5. Если у пользователя нет активных портфелей - это исключительная ситуация.

Из всего описания валидно только то, что в консоли не должно быть ошибок. Все остальное - ожидаемое поведение.
