### ISSUE TITLE
[FEATURE] Убрать анимации

### ISSUE THREAD

**Issue by DaaGER** [alor-broker/Astras-Trading-UI#841]
### Опишите проблему, которую решает ваша фича

Много различных анимаций, который хоть немного, но тратят как время, так и мощности компьютера, что может сказаться в ответственный момент. Немного, но всё же. От терминала люди ждут удобства, а скорость и легкость входят в это понятие.

### Опишите предлагаемое вами решение

Убрать все transition и animation, если они не обладают функциональной составляющей.
Отключение глобальное через: https://ng.ant.design/docs/animations/en
Плавное перекрашивание иконок в хедере виджета, анимация свечения вокруг после клика, модальное окно, список виджетов и т.д.

Всё отключить, либо сделать настройку для тех, кому хочется плавности.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Интересное предложение. Спасибо за ссылку на ант. Если действительно отключается ю несложно, то сделаем.

**Comment by DaaGER** [comment]
> Интересное предложение. Спасибо за ссылку на ант. Если действительно отключается ю несложно, то сделаем.

Я во всех компонентах добавил этот параметр и часть анимаций ушло. К сожалению на кнопочки это не распространилось т.к. это в dark.css, так что ещё заглушил через * {transition: none!important; animation: none!important;}

**Comment by PilgrimViis** [comment]
Мы решили, что затраченные усилия того всё-таки не будет стоить.
