### ISSUE TITLE
[BUG] Не отображаются все заявки / стоп-ордера

### ISSUE THREAD

**Issue by WISEPLAT** [alor-broker/Astras-Trading-UI#842]
### Опишите баг

В виджете не отображаются все заявки / стоп-ордера. Такое ощущение что у вас они выводится до некоторого минимального числа.
Все заявки были выставлены одним методом - но часть их не видна!
В приложенных скриншотах всё видно.
P.S. Прошу исправить, уже 2 недели в телег. чате футболите.

### Воспроизведение

Сделайте 30 ордеров / стоп-ордеров и увидите, что не все они отобразятся.

### Среда.

Пробовал в разных браузерах - везде та же проблема. Браузеры обновлены!

### Ожидаемое поведение

Должны отображаться все ордера, даже если их 200 шт.

### Скриншоты

<img width="1681" alt="1" src="https://user-images.githubusercontent.com/29922332/221189345-1a00ef7f-81ac-4b80-8394-bc47800a63dc.png">
<img width="1847" alt="2" src="https://user-images.githubusercontent.com/29922332/221189354-4c109ccf-ae41-4e74-8ccc-c4817d24c8aa.png">

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Проблема наблюдается ТОЛЬКО на Stop  заявках. На них по каким-то причинам отображалось только 10 заявок. Другие заявки (лимитки, рыночные) отображаются все.

При этом проблема наблюдается только **в виджете "Блоттер"** (с каким виджетов конкретно проблема в описании не указано).

В виджете "Тех. анализ" (также присутствует на скринах) никаких проблем не наблюдается. Если есть какая-то проблема в виджете "Тех. анализ", то нужно изменять масштаб оси цен (скролл мыши в области графика, ctrl+ зажатая левая клавиша мыши в области цен) - график не может отобразить заявки, у которых шаг цены очень маленький - они просто накладываются друг на друга. Также следует учесть, что при одной и той же цене заявки могут накладываться друг на друга. 
 
 Не совсем понятно что должно быть видно на прикрепленных скринах. Если это сравнение, что в Trading view отображается большее количество заявок, то нужно сделать скрины заявок для одного и того же инструмента, в один и тот же промежуток времени и одинаково отсортированные - на скринах заявки разных инструментов. При этом в trading view отображается, что **ВСЕГО заявок 18 (стопы, лимитки и рыночные)**, из них для тикера HHRU **8 заявок**, заявки OZON не видны, но по логике их должно быть <= 10 (18-8 = 10). Второй скрин из ASTRAS и там ровно 10 стоп заявок для OZON).
 
 Проблема с отображение STOP заявок будет исправлена в следующем релизе. Прочих описанных проблем не наблюдается
