### ISSUE TITLE
[FEATURE] Сделать идентификатор buy\sell в виде палочки для сделок и всех сделок

### ISSUE THREAD

**Issue by PilgrimViis** [alor-broker/Astras-Trading-UI#845]
### Опишите проблему, которую решает ваша фича

Единообразность интерфейса и экономия места

### Опишите предлагаемое вами решение

Сделать в виджете "все сделки" и "сделки" такую же палочку как для заявок и стопов. Которая идентифицирует покупку и продажу. Смотреть скриншот.

### Дополнительная информация

![image](https://user-images.githubusercontent.com/6408195/221503554-0eefe893-b440-452d-90dc-d2e5b4833e0b.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@PilgrimViis ,
правильно понимаю, что раз есть этот индикатор, то столбец side можно убрать из столбцов по умолчанию?

**Comment by PilgrimViis** [comment]
Да, правильно
