### ISSUE TITLE
[BUG] В виджете в закладке Positions и закладке ордеров / стоп-ордеров и на графике!!! - не правильно отображаются кол-во акций в лотах и штуках

### ISSUE THREAD

**Issue by WISEPLAT** [alor-broker/Astras-Trading-UI#856]
### Опишите баг

[BUG] В виджете в закладке Positions и закладке ордеров / стоп-ордеров и на графике!!! - не правильно отображаются кол-во акций в лотах и штуках.
Такое ощущение что у вас для части акций выводится значение в лотах, а для другой части в штуках!!!
Все заявки выставлены одним методом!
В приложенных скриншотах всё видно.
Прошу исправить.

### Воспроизведение

Создайте покупки по акциям из скриншотов.

### Среда.

Пробовал в разных браузерах - везде та же проблема. Браузеры обновлены!

### Ожидаемое поведение

Везде - и на графике и в виджетах всё должно отображаться в лотах.

### Скриншоты

![capture_2](https://user-images.githubusercontent.com/29922332/222221182-46e47b79-c92d-41ce-993d-453eca027c34.JPG)
![capture_3](https://user-images.githubusercontent.com/29922332/222221188-bcbbb889-5700-41c6-b9f9-1d826c50f890.JPG)
![capture_1](https://user-images.githubusercontent.com/29922332/222221191-5d535d05-af06-4e69-b60f-70fec7a9add7.JPG)

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@PilgrimViis ,

Для **ВСЕХ** инструментов отображение одинаковое.
SPBE имеет лотность 1. **54 лота = 54 штуки**
![image](https://user-images.githubusercontent.com/29191749/222331578-c041da46-57c9-4b32-8a00-7ca0641fd0a0.png)

AFLT имеет лотность 10. **200 лотов = 2000шт**
![image](https://user-images.githubusercontent.com/29191749/222331887-34615ed6-8d75-4aff-afe7-ba6b78a30d0e.png)

MRKC имеет лотность 1000. **38 лотов = 38000шт**
![image](https://user-images.githubusercontent.com/29191749/222333709-fac267d4-a24e-4242-b21e-20a4f45de38d.png)


1. Графике, вкладке Orders, StopOrders отображение в ЛОТАХ. Это логично, потому что заявки выставляются в лотах.
2. Поля "Quantity Т0", "Quantity Т1", "Quantity Т2", "Quantity ТFuture" **ВСЕГДА** отображали значение в ШТУКАХ. И это логично, потому что в режиме SMAL можно и по одной акции торговать

Если сейчас переделывать отображение "Quantity Т0", "Quantity Т1", "Quantity Т2", "Quantity ТFuture", со штук на лоты,  то это породит вопросы у пользователей, которые уже привыкли к такому отображению. Либо нужно добавлять отдельные поля для отображения в лотах.

Прошу подтвердить, то это нужно делать. Никаких других изменений не требуется - все отображается корректно в ЛОТАХ

**Comment by WISEPLAT** [comment]
"породит вопросы у пользователей, которые уже привыкли к такому отображению" - что значит привыкли???
фиксить надо - везде всё в лотах однотипно должно быть.

**Comment by WISEPLAT** [comment]
как поясните https://user-images.githubusercontent.com/29922332/222221191-5d535d05-af06-4e69-b60f-70fec7a9add7.JPG 
вот эту ситуацию???

**Comment by sbelashevskiy** [comment]
> как поясните https://user-images.githubusercontent.com/29922332/222221191-5d535d05-af06-4e69-b60f-70fec7a9add7.JPG вот эту ситуацию???
 По этому скрину могу только сказать, что у вас выставлена заявка на 19000 лотов

**Comment by WISEPLAT** [comment]
> 

у меня резервируются деньги на выставление заявок. На такое кол-во лотов их просто нет...

**Comment by sbelashevskiy** [comment]
Это стоп заявка, на момент ее выставления я не вижу какого-либо резерва. Вы можете ее снять и выставить снова - она же у вас не срабатывала.
Вот я выставил точно такую же заявку на 19000 лотов с 900р. свободных средств в портфеле. 

![image](https://user-images.githubusercontent.com/29191749/222366082-f5f38a88-3221-4cfe-95a4-6936511ba860.png)

**Comment by sbelashevskiy** [comment]
А вот заявка на 19 лотов
![image](https://user-images.githubusercontent.com/29191749/222366690-ea2ff218-a44b-4f4b-99d0-fbcb6b42dfef.png)
Я не вижу какой-либо ошибки.
Если есть проблема - запишите видео

**Comment by WISEPLAT** [comment]
Прямо сейчас ошибка - исправьте плиз
![Capture](https://user-images.githubusercontent.com/29922332/222382264-7f5bd52b-0d32-421b-b999-a6873857191f.JPG)

**Comment by sbelashevskiy** [comment]
> Прямо сейчас ошибка - исправьте плиз ![Capture](https://user-images.githubusercontent.com/29922332/222382264-7f5bd52b-0d32-421b-b999-a6873857191f.JPG)

Вы так и не прислали видео, не описали как выставляете заявку, скрыли портфель на скринах. Я не могу ничего исправить. На вашем скрине выставлена заявка в 19000 лотов
