### ISSUE TITLE
[FEATURE] Увеличить максимальную глубину стакана в терминале и в подписке Websocket

### ISSUE THREAD

**Issue by alekssn** [alor-broker/Astras-Trading-UI#859]
### Опишите проблему, которую решает ваша фича

На данный момент максимальная глубина стакана в Алоре - 20. Иногда бывает необходимо посмотреть стакан на бОльшую глубину. Этот вопрос стоит уже очень давно, уже более двух лет он поднимается в разных чатах

### Опишите предлагаемое вами решение

Увеличить максимальную глубину стакана в подписке Websocket до 40-50

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
@agushasok вот по этой задачи убери пожалуйста предупреждение которое мы делали для стаканов с 50 глубиной. Уже не особо актуально.
