### ISSUE TITLE
[FEATURE] Перетаскивание заявок в скальперском и обычном стаканах

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#863]
### Опишите проблему, которую решает ваша фича

Прошу добавить возможность ператаскивания лимитных заявок в стакане мышкой. 

### Опишите предлагаемое вами решение

![image](https://user-images.githubusercontent.com/105817664/223391644-358b000a-8bc6-498c-bdee-614e3aa4a377.png)
Выставили лимитную заявку в стакане.
Взяли мышкой ёё и претаскиваем ниже или выше по цене. 

Если поставил несколько лимитных заявок по одной цене (друг другу на "голову", то при перемещении , перетаскивались все заявки  

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я думаю такой функционал в обычном стакане тоже пригодится. Поэтому когда начнем делать, надо ещё и в обычном попробовать реализовать.

**Comment by sbelashevskiy** [comment]
В обычном стакане это уже есть
