### ISSUE TITLE
[BUG] Разные валюты по бумаге при выставлении заявки и в Инфо

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#868]
### Опишите баг

Если взять гонконгский инструмент, например 2318, то по апи по бумаге `/md/v2/Securities/SPBX/2318` придет поле "currency": "HKD", однако в виджете "Инфо" базовая валюта - юани (CNY):
![image (169)](https://user-images.githubusercontent.com/88287882/224248775-e03015a7-da0a-4b0b-b577-58058373ac61.png)

Кроме того, в виджете и модальном окне заявки - неверный значок валюты: указаны `$`, а должно быть HK$:
![image (171) (1)](https://user-images.githubusercontent.com/88287882/224253090-710fcb2d-a82c-486b-a0f4-5449a8e9b7aa.png)

Для бумаги 9988 такие же расхождения в виджете и модалке:
![image](https://user-images.githubusercontent.com/88287882/224250542-4743b962-4bea-4897-84b4-680a45fcb529.png)

### Воспроизведение

1. Выставить виджет Инфо.
2. Указать тикер 2318. Проверить поле "Базовая валюта".
3. При выставлении заявки в поле "к покупке" посмотреть на значок валюты.

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

1. При выставлении заявки корректно отображается значок валюты торгов по бумаге. Если торги в валюте HK$, то указан именно этот значок. Расчеты также ведутся по аналогичной доступной валюте в портфеле клиента.
2. Так как торги ведутся в валюте, которая приходит по АПИ, то в виджете "Инфо" можно указывать ее. На других платформах также ведутся расчеты в гонк. долларах:
![image](https://user-images.githubusercontent.com/88287882/224252715-9e3ca87f-28f6-4876-896d-ee3b807ea5d3.png)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Илья, там есть 2 поля валюта. Первое это валюта торгов, второе это поле валюты в которой номинирована бумага. Например RUS28 номинирована в USD, но торгуется и в рублях и в долларах. Проверь пожалуйста этот момент.

**Comment by ilya7am** [comment]
Есть бумаги, например EDIT и EW, которые номинированы в USD для СПб, но с добавлением RM (EDIT-RM или EW-RM) уже расчеты будут проводиться в рублях. Валюта торгов поменяется на RUB, сам /estimate в торгах по USD и RUB отличается. В виджете "Инфо" по этим бумагам базовая валюта так и останется USD. 
Насчет RUS28 - не нашел такую, подскажи, что имел в виду?

По значкам проверил - при выставлении заявки не рисуется только значок HK$ для гонконгских инструментов. Для KMG@KT (валюта KZT) рисуется верный значок, но в "Инфо" запрос 404 "Isin for KMG@KT not found".

**Comment by ilya7am** [comment]
У нас торги по инструментам ведутся по валюте расчетов, но сейчас в Астрас нет поля с явным указанием на валюту расчетов. Есть только поле "базовая валюта", которое находится в виджете "Инфо". Однако по некоторым бумагам валюта номинала и валюта расчета отличается, а выставление заявки будет происходить именно по валюте расчета:

Например, для RU000A1054W1 (китайская облигация) - "базовая валюта" (в виджете Инфо) - CNY, но по `/md/v2/Securities/MOEX/RU000A1054W1` "currency": "RUB" и бумага будет торговаться в рублях. Такая же разница валют есть для "2318" и "9988" на СПб.
Поэтому лучше добавить в виджет "Инфо" новое поле - "валюта расчетов" с указанием верной валюты.

А также в виджете и модалке "Заявка" подправить отображение значка валюты расчета по бумагам (см. в задаче)

**Comment by PilgrimViis** [comment]
> У нас торги по инструментам ведутся по валюте расчетов, но сейчас в Астрас нет поля с явным указанием на валюту расчетов. Есть только поле "базовая валюта", которое находится в виджете "Инфо". Однако по некоторым бумагам валюта номинала и валюта расчета отличается, а выставление заявки будет происходить именно по валюте расчета:
> 
> Например, для **RU000A1054W1** (китайская облигация) - "базовая валюта" (в виджете Инфо) - CNY, но по `/md/v2/Securities/MOEX/RU000A1054W1` "currency": "RUB" и бумага будет торговаться в рублях. Такая же разница валют есть для **2318** и **9988** на СПб. Поэтому лучше добавить в виджет "Инфо" новое поле - "валюта расчетов" с указанием верной валюты.
> 
> А также в виджете и модалке "Заявка" подправить отображение значка валюты расчета по бумагам (см. в задаче)

Логично. А ты случайно не знаешь, в API отдаётся эти поля? В информации по инструменту я например вижу только 1 валюту.

**Comment by ilya7am** [comment]
> А ты случайно не знаешь, в API отдаётся эти поля? В информации по инструменту я например вижу только 1 валюту.

Не нашел отдельного эндпоинта, чтобы и базовая валюта и валюта расчетов были вместе. Базовая валюта только по `https://api.alor.ru/instruments/v1/APTK/description`, а валюта расчетов (currency) в `/md/v2/Securities`

**Comment by sbelashevskiy** [comment]
Что в итоге нужно делать в задаче? Где из каких полей отображать данные?
В информации по инструменту есть только одно поле валюты
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/0df5e4a8-8343-4759-84ed-97c9d290cdc3)

**Comment by PilgrimViis** [comment]
Решили исправить эту проблему после интеграции graphql api

**Comment by PilgrimViis** [comment]
@agushasok обрати внимание на эту задачу пожалуйста тоже
