### ISSUE TITLE
[FEATURE] Дополнение к отображению сделки в скальперском стакане. 

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#873]
### Опишите проблему, которую решает ваша фича

Когда заходишь в сделку,  цвет шрифта меняется , на красный или зелёный , в зависимости в прибыли или в убытке. 
Но это очень плохо видно, почти не отличимо. 

### Опишите предлагаемое вами решение

Предлагаю добавить , возможно какую нибудь линию вот типо такой (как на скриншоте) что бы было лучше видно  позицию в сделке 
![image](https://user-images.githubusercontent.com/105817664/225053725-b84c259b-4af5-4589-9e9d-146a7ea483b8.png)
Линия растягивается от точки входа , красная если сделка отрицательная и зеленая если положительная. 
Можно так сделать? 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
Технически можно сделать. Изменение цвет шрифта тогда убрать? Чтобы не было красного шрифта на красном фоне и зеленого на зеленом

**Comment by uncrashable** [comment]
Да, можно оставить вот такую полосочку.

**Comment by sbelashevskiy** [comment]
> Нормально. Можно чуть зазор больше оставить между цифрами и полоской ?

да, без проблем
