### ISSUE TITLE
[FEATURE] Ограничить список бумаг в "Выбор инструмента" до 50 штук

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#901]
### Опишите проблему, которую решает ваша фича

Сейчас нет ограничения на максимальное возможное число размещаемых бумаг в виджете "Выбор инструмента", по каждой из бумаг грузятся котировки, меняются данные в режиме реального времени. Если бумаг в списке очень много (более 100), то из-за этого иногда возникают лаги в работе терминала, дольше отправляются запросы /quotes и дольше грузятся стаканы.

### Опишите предлагаемое вами решение

Лучше ограничить максимальный размер списка бумаг до 50 штук. В целом, этого достаточно для сравнения и получения информации по группе бумаг.
Если клиент захочет добавит новые бумаги, он может создать новый список и добавить бумаги туда. Тем самым, запрсоов будет отправляться меньше, и это ускорит работу терминала.

### Правила

- [X] Я согласен следовать правилам

**Comment by LinaRitchie** [comment]
Но при ограничении списка в штуках нельзя будет, например, разом отсортировать все торгующиеся бумаги по изменению % за день и выбрать самую выросшую/упавшую (никогда не знаешь заранее, что за тикер это будет) и наблюдать за тем, как меняется лидерство, а в некоторых стратегиях это важно.

**Comment by sbelashevskiy** [comment]
Добавлю: если у пользователя открыты несколько виджетов "Выбор инструмента", и в каждом свой список, то ограничение никак не решит проблему. 
В рамках этой проблемы требуется детальнее рассматривать как пользователи используют данный виджет.

1. Вообще текущая реализация предполагает, что пользователь может формировать несколько **небольших** списков интересующих его бумаг и легко переключаться между ними. Поэтому не совсем понятно почему вообще у пользователей возникают проблемы с данными списками. В том числе подобные этой https://github.com/alor-broker/Astras-Trading-UI/issues/818. Разные списки уже предполагают, что у пользователя есть "Избранные" инструменты, которыми он торгует
2. То, что любой поиск сразу добавляет инструмент в список - вот это проблема. Как раз из-за этого, на мой взгляд, списки разрастаются. Лучше бы отдельно вести историю поиска и именно ее ограничивать, например 15 записями. А уже из истории должна быть возможность добавить инструмент в конкретный список.
3. Главный вопрос: точно ли пользователям нужна возможность создавать большие списки и следит за изменениями цены в них. Если да, то текущая реализация API явно не удовлетворяет  этим потребностям - отслеживание каждого инструмента по отдельности требует слишком больших ресурсов

**Comment by PilgrimViis** [comment]
> То, что любой поиск сразу добавляет инструмент в список - вот это проблема. Как раз из-за этого, на мой взгляд, списки разрастаются. Лучше бы отдельно вести историю поиска и именно ее ограничивать, например 15 записями. А уже из истории должна быть возможность добавить инструмент в конкретный список.

Мысль хорошая, но я не могу придумать как это сделать, чтобы при этом пользователю было удобно. Это либо лишние клики для добавления (типо знака +), что при активном использовании будет раздражать. Либо лишние переключения между 2мя списками. Истории и Избранным, например.

По задаче послушав ваши с @LinaRitchie я думаю что ограничивать все таки не надо. Будем думать дальше. Там Илья ещё баг нашел с зависанием терминала для некоторых инструментов при добавлении их в список. Может быть это как-то пересекается.
