### ISSUE TITLE
[FEATURE] Увеличить пространство для виджетов.

### ISSUE THREAD

**Issue by uncrashable** [alor-broker/Astras-Trading-UI#913]
### Опишите проблему, которую решает ваша фича

1. На небольших экранах не помещается интерфейс, который бы хотелось настроить. 
2. При добавлении новых виджетов, постоянно идет смещение остальных, потом опять приходится все подстраивать.
3. При необходимости нескольких одинаковых по размерам виджетов, приходится каждый настраивать по отдельности. 

### Опишите предлагаемое вами решение

1.  Предлагаю расширить рабочее пространство таким образом, что бы виджеты можно было перетягивать ниже области экрана (видео 1 ). На видео видно, что сейчас, если я перетягиваю график , его обратно размещает в область экрана и уменьшает его размер.
В моем  предложенном варианте, график оставался за пределами экрана, и появлялся ползунок браузера. Т.о. я бы мог не часто используемые виджеты оставлять ниже видимой части экрана, и смотреть , когда в этом есть необходимость. 
Например, Виджет блотер, мне нет необходимости постоянно за ним смотреть, я бы его просто убрал вниз и ползунком просматривал, когда нужно. 

https://user-images.githubusercontent.com/105817664/231555440-4447dc0c-df41-403d-b593-5ae241aaf369.mp4

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Убрать вот эти пункты из задачи. Взаимодействия не будет точно, а копирование планируем сделать в рамках другой задачи.
2. Предлагаю, дать виджетом возможность, накладываться один на один. Не взаимодействуя друг с другом. Т.к. это часто сбивает настройки размеров виджетов и потом приходиться заново их настраивать. 
3. Добавить возможность копирования виджетов.

**Comment by PilgrimViis** [comment]
Надо сделать в виде опции в профиле пользователя. По умолчанию пусть будет как у нас сейчас. В том случае если пользователь включил опцию, мы меняем грид на другой тип, который всегда добавляет вниз и который бесконечно вниз скролится. Я посмотрел по докам gridster'а там есть опция вертикального скролла, но проблемы какие-то мне кажется у нас все равно будут. Поэтому надо смотреть.

**Comment by sbelashevskiy** [comment]
Добавлен выбор поведения сетки:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/4177ebc6-aff9-4a06-8727-7d83ff9edb45)
