### ISSUE TITLE
[FEATURE] Глубина стакана

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#93]
### Опишите проблему, которую решает ваша фича

Нет возможности узнать максимальную глубину стакана без попытки сохранения и перебора значений.
Сам параметр спрятан в "Продвинутые".
![image](https://user-images.githubusercontent.com/99450543/165492368-83c22bfe-dab2-4bab-9d90-bede20719679.png)

### Опишите предлагаемое вами решение

Реализовать параметр "Глубина стакана" списком значений.
Вынести параметр в основной блок настроек.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Если проблема в том, что нужна максимальная глубина стакана, то предлагаю просто написать об этом в подсказке. Перебор значений это хорошо, мы тоже думали сначало сделать так (5, 10, 15, 20). Но потом поняли, что человек может окно смаштабировать по разному. И может ему надо 7, чтобы выглядело красиво.

**Comment by PilgrimViis** [comment]
Из продвинутых можно вынести.
