### ISSUE TITLE
[BUG] Уведомления по цене остаются в виджетах после исполнения

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#941]
### Опишите баг

Если добавить уведомление по смене цены и дождаться исполнения условия - запись не пропадет из виджета "Выставить заявку" и из блоттера в табе "Уведомления". А при клике на крестик по уже несуществующей записи- появится ошибка 400 "Can't find a subscription":
![2023-05-03_13h31_43](https://user-images.githubusercontent.com/88287882/235892963-921fc6d0-d36c-4ff9-8246-d9c0fee4fa01.png)

Помогает переключение между табами или перезагрузка страницы.

### Воспроизведение

1. Выставить виджет Заявка и блоттер.
2. По любой бумаге выставить уведомление по цене.
3. Дождаться выполнения условия.
4. Посмотреть на отображение Заявки и блоттера.
5. Нажать на крестик напротив данного уведомления.

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

При исполнении условия - уведомление по цене сразу пропадет из "Заявка" и "Блоттер". Не нужно переключаться между табами или обновлять страницу.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Стоп. А почему уведомление вообще пропадает после выполнения? Мне кажется так быть не должно...

**Comment by PilgrimViis** [comment]
Предлагаю обсудить

**Comment by PilgrimViis** [comment]
Решили что будем следить за приходящими уведомлениями при активном окне и делать повторный запрос на /subsciptions каждый раз как пришло уведомление типа priceSpark

**Comment by PilgrimViis** [comment]
В дальнейшем нужен более надежный вариант.

**Comment by ilya7am** [comment]
Если оставаться во вкладке Астрас, то уведомления по цене пропадают из виджета после соблюдения условий. Однако если окно не в фокусе, то после получения нативного уведомления - запись с ценой не пропадает и появляется такая же ошибка 400:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/360561ff-0b44-419c-b746-fd024bf33b00



Лучше подправить этот момент
