### ISSUE TITLE
[BUG] Несовпадающие котировки по бумагам в разных виджетах

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#943]
### Опишите баг

По данным в виджете "Выбор инструмента":
1. Для **инструментов на СПБ** не совпадают данные из колонок "Д.изм" и "Д.изм.,%" и "Закр" с Тех анализом, данные совпадают с модальным окном "Заявка", лучше сделать одинакового (как сейчас на МБ):
![2023-05-03_17h59_33](https://user-images.githubusercontent.com/88287882/235957409-ef6bc533-72b4-4ba5-9669-c2b272b24530.png)

2. На обеих биржах не совпадают данные по "Объем". По Мб ощущение, что не там ставится разделитель и перепутано десятичное значение:
![Котировки2](https://user-images.githubusercontent.com/88287882/235958074-84fbc2fb-cd5e-4609-b336-66ef122bf97c.png)

Причем данные меняются в режиме реального времени одинакового, хотя в виджете "Инструменты" указаны миллиарды (В):

https://user-images.githubusercontent.com/88287882/235958060-b2a1577a-bb62-4ca1-980c-ce8b88bfdf51.mp4

### Воспроизведение

1. Выставить виджеты "Тех анализ" и "Выбор инструмента".
2. По Мб и СПБ добавить на дашборд разные бумаги. 
3. Сравнить котировки с  модальным окном "Заявка" и "Тех анализ".

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

Котировки по одинаковым бумагам совпадают между всеми виджетами, модальным окном "Заявки" и валидны.

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@ilya7am ты сам указал, что это расхождение только на SPB бирже. У нас нет в приложении никаких корректировок типа на MOEX показывать одно, а на SPB прибавлять, отнимать, умножать делить.
Данный вопрос нужно адресовать бэкэнд разработчикам - почему дневные котировки и свечи на SPB бирже не совпадают

**Comment by PilgrimViis** [comment]
Сергей, согласен с тобой. Т.к. задача нас вообще не касается и её решение не ожидается, то я её закрою. Но не вдаваясь в подробности, скорее всего причина в особенностях СПБ биржи и того что она транслирует котировки с США.
