### ISSUE TITLE
[FEATURE] Предотвратить случайное закрытие окна настроек терминала

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#947]
### Опишите проблему, которую решает ваша фича

Я испытываю трудности когда что-то меняю в окне настроек терминала и случайно кликаю вне его. Все, что я настраивал сбрасывается и приходится снова открывать это окно и заново вносить изменения.

### Опишите предлагаемое вами решение

Не закрывать окно настроек при клике вне его границ, также, ка это сделано в диалоге выставления заявок

### Правила

- [X] Я согласен следовать правилам

**Comment by scarletcloak** [comment]
Хм, а это реальная проблема? Странно. Надо обсудить. Ещё как вариант давайте обсудим сохранение настроек при закрытии окна. Мне кажется было бы гораздо полезнее.

**Comment by sbelashevskiy** [comment]
Настройки должны сохраняться когда пользователь явно подтверждает сохранение, т.е. по кнопке сохранить.
Также как и окно должно закрываться когда пользователь этого хочет, а не в результате случайного действия.

**Comment by PilgrimViis** [comment]
@sbelashevskiy давайте сделаем по другому. Сделаем чтобы настройки сохранялись при закрытии окна. Это решит твою проблему тоже.
