### ISSUE TITLE
[BUG] Не удается получить демо-счет для тестирования пользовательского интерфейса

### ISSUE THREAD

**Issue by noobshow** [alor-broker/Astras-Trading-UI#949]
### Describe the bug

Привет,
Было сложно получить демо-счет для тестирования пользовательского интерфейса.

### Reproduction

- 1. ng serve
- 2. [Login to what?](https://login-dev.alor.ru/?url=http://localhost:4200/auth/callback&scope=Astras)

### Platform

- OS: Windows 10
- Browser: Edge

### Expected behavior

Not expecting that login or it should be easy to acquire a demo account

### Code of Conduct

- [X] I agree to follow this project's terms

**Comment by scarletcloak** [comment]
Пожалуйста не делайте так больше. Если у вас есть вопросы по разработке, вы можете спрашивать в нашем чате, мы попробуем вам помочь там. Не надо заводить вопрос как баг. Это точно не баг приложения Астрас. По поводу учётки для тестов, её вы можете получить написав техподдержке Алора на почту support @ alor.ru
