### ISSUE TITLE
[FEATURE] Переработать окно с информацией о новом релизе

### ISSUE THREAD

**Issue by scarletcloak** [alor-broker/Astras-Trading-UI#950]
### Опишите проблему, которую решает ваша фича

Сейчас там не видно что собственно изменилось и 90% текста это всякие дисклеймеры. 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/87366246/fcf98808-1382-45df-b3a4-4f5962be1244)

### Опишите предлагаемое вами решение

Предлагаю переработать дизайн для этого окна.

### Правила

- [X] Я согласен следовать правилам

**Comment by Tattydes** [comment]
Дельное замечание, хорошо бы сразу расписывать все изменения. Плюс сделать дропдаун "Если приложение не загружается" и разместить там информацию по возможному решению (которая на скрине)

**Comment by PilgrimViis** [comment]
https://www.figma.com/file/qUctvS64BOn5a03j3ZG2yl/Astras?type=design&node-id=1429%3A2453&mode=design&t=2mKqsnmrDIFPUncD-1 дизайн готов.

**Comment by PilgrimViis** [comment]
Только прошу не переименовывать Changes в заголовке.
