### ISSUE TITLE
[BUG] В Firefox и Сафари подправить мобильную версию Астрас

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#951]
### Опишите баг

1. В Firefox при авторизации в Астрас, а затем переходе по прямой ссылке https://astras.alor.ru/mobile - вёрстка съезжает:
![mobile_file_2023-05-10_10-46-20 (1)](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/5f1f5d4a-ff96-45f6-bae4-289052da3f58)

2. В Firefox при клике на “Соединение” - открывается окошко с уведомлениями:
 ![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/233e90cf-a5e2-47ef-bf47-3f37d1e5196f)

<br>
3. В Firefox при редактировании заявки – меню внизу становится очень мелким:
 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/719589d2-b5f4-4aac-a544-8241283bd25b)

4. В Firefox и Сафари при клике на поле ввода или дропдаун - масштаб страницы увеличивается и его нельзя потом полностью уменьшить. При переключении табов проблема остается. Помогает перезагрузка страницы:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/aaf0e373-eb95-49bc-8b38-55d909578cf6

### Воспроизведение

1. Авторизоваться в Firefox, открыть новую вкладку и перейти по https://astras.alor.ru/mobile.
2. Кликнуть на значок "соединение" в хедере.
3. Перейти в Блоттер - Стопы и изменить цену стопа.
4. Посмотреть на нав. панель в футере.
5. В табе "Стакан" нажать на "шестеренку" и поменять поле "Глубина".
6. Повторить шаги 2-5 на iPhone 14.

### Среда.

Android 9, JSN-L21
Firefox 110.1.0

Эмулятор iPhone 14, iOS 16.2

### Ожидаемое поведение

1. При авторизир. переходе в https://astras.alor.ru/mobile верстка не съезжает.
2. При клике на "соединение"- появляется тултип с качеством связи, при клике на "колокольчик" - открывается окно  с уведомлениями.
3. В любом браузере с телефона при торговле и использовании Астрас панель с табами в футере не обрезается, не мелькает и не пропадает.
4. При клике на поле ввода в ФФ или Сафари - можно вручную уменьшить размер экрана, без перезагрузки страницы.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Не воспроизводится
