### ISSUE TITLE
[FEATURE] На Графике на телефоне сделать изменение масштаба оси Y в зависимости от направления 

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#952]
### Опишите проблему, которую решает ваша фича
В табе "График" на оси Y только уменьшении или только при увеличении масштаба двумя пальцами - данные на оси сами меняются в обе стороны (ось Y то суживается, то расширяется): 
https://portal.alorbroker.ru/docs/pub/dc8ae49bcefd74c0f2b1301c8c3ed6bd/default/?& 

### Опишите предлагаемое вами решение
Масштаб оси Y на Графике меняется в зависимости от направления pinch-to-zoom.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Илья, пожалуйста раздели на несколько задач. Это слишком разные вщеи.
