### ISSUE TITLE
[BUG] Не сразу переводится содержимое Календаря событий при смене языка

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#954]
### Опишите баг

1. В виджете "Календарь событий" при смене языка приложения - дни недели и дропдаун месяцев не сразу переводятся на новый язык. Для корректной смены требуется перезагрузка страницы:
![2023-05-10_17h19_40](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/7b9a7d39-4290-4876-8da7-ad4c5bcdd882)

<br>

2. Подправить опечатку в английской версии:
![2023-05-10_17h28_28](https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/849d5e7a-09af-4f8c-8b68-e27f3c51b985)

### Воспроизведение

1. Выставить виджет "Календарь событий" -таб "Календарь".
2. Поменять в Профиле язык приложения.
3. Проверить перевод. Переключиться на раздел "Список".
4. Выбрать срочный рынок и прочитать текст.

### Среда.

Windows 10
Google Chrome 112

### Ожидаемое поведение

1. При переключении языка все табы, дропдауны и их содержимое сразу переводится на новый язык.
2. Если нет данных в календаре в табе "Список", то отображается текст: "There are no events for selected portfolio".

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
При смене языка и темы нужно просто программно обновлять страницу.
Нет никакой необходимости применять тему и менять язык приложения "на лету". 
Этот кейс возможен только при тестировании. Рядовому пользователю он совершенно без надобности
