### ISSUE TITLE
[FEATURE] Привязывать время отображения данных в виджетах к выбранному в Профиле

### ISSUE THREAD

**Issue by ilya7am** [alor-broker/Astras-Trading-UI#955]
### Опишите проблему, которую решает ваша фича

Сейчас данные в виджетах отображаются в разных часовых поясах: "Все сделки" всегда приходят по местному времени, а "Тех анализ" - по московскому.
Причем, в Профиле клиента при смене часового пояса с местного времени на московское и наоборот данные в виджете "Все сделки" и свечки в "Тех анализе" не обновляются под новое время. Это может вызвать путаницу у клиента:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/fba228de-61c0-4306-888a-5af798610e23

### Опишите предлагаемое вами решение

Отображать данные по всем виджетам в том часовом поясе, который выбран клиентом в "Профиле - Общие" в поле "Часовой пояс отображения времени". При смене значения - обновлять все виджеты под новое время.

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я бы сказал, что это даже баг, а не фича.
