### ISSUE TITLE
[FEATURE] Вынести в конфиг ссылки, инструмент по умолчанию, отображаемые виджеты

### ISSUE THREAD

**Issue by ktochilkin** [alor-broker/Astras-Trading-UI#957]
### Опишите проблему, которую решает ваша фича

Для более удобной развертки терминала.

### Опишите предлагаемое вами решение

Вынести в конфиг ссылки на "Отчеты", "Поддержка", "Релизы"(может еще что-то упустил). 
Вынести в конфиг инструмент по умолчанию(когда пользователь открывает первый раз терминал открывается MOEX:SBER).
Вынести в конфиг отображаемые виджеты, чтобы можно было отключать ненужные. 

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@PilgrimViis @ktochilkin 
Данные настройки должны меняться на CI (храниться в одном файле) или для деплоя будет создаваться отдельный бранч приложения и данные настройки могут изменяться не в момент билда?

Я спрашиваю потому что у нас есть файл с настройками рынка, где перечислены биржи, и, например, дефолный инструмент логичнее хранить в нем. Но модифицировать его во время билда будет неправильно.
Также для  хранения перечня доступных виджетов есть более подходящее место, чем конфиг

**Comment by PilgrimViis** [comment]
> @PilgrimViis @ktochilkin Данные настройки должны меняться на CI (храниться в одном файле) или для деплоя будет создаваться отдельный бранч приложения и данные настройки могут изменяться не в момент билда?
> 
> Я спрашиваю потому что у нас есть файл с настройками рынка, где перечислены биржи, и, например, дефолный инструмент логичнее хранить в нем. Но модифицировать его во время билда будет неправильно. Также для хранения перечня доступных виджетов есть более подходящее место, чем конфиг

Ты просто вложи из в файлик environment.ts. Дальше девопсы сами подменят.

**Comment by sbelashevskiy** [comment]
@PilgrimViis ,
дак я про то и спрашиваю, что все должно меняться при билде? ТОгда все придется вкладывать в environments, хотя для этого у нас есть более подходящие места

**Comment by sbelashevskiy** [comment]
Добавлена конфигурация.

**Внешние ссылки:**
Настраиваются в файле  src/environments/environment.ts (environment.dev.ts, environment.prod.ts).
Секция externalLinks.
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/16aaace2-abef-4e88-a485-f4e238e3124a)

Файлы должны быть модифицированы **ДО** билда.

**Изменение инструмента по умолчанию:**
Необходимо отредактировать файл **assets/marketSettings.json** (src/assets/marketSettings.json для локального запуска).
Необходимо поменять секции defaultInstrument для каждой биржи и для биржи по умолчанию ("isDefault": true) в том числе.
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/f8ba246c-e233-461a-a359-9922c6b9d5cc)

При локальном запуске просто меняем данный файл.
При разворачивании данный файл нужно подменить **ПОСЛЕ** деплоя (только если нужно изменить конфигурацию по умолчанию).

**Отключение виджетов в меню виджетов (галереи виджетов):**
Необходимо отредактировать файл **assets/widgets-meta.json** (src/assets/widgets-meta.json для локального запуска).

Чтобы "отключить" виджет на desktop версии можно поставить у него флаг "enabled": false
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/2896d78c-8716-497b-b690-ffaa001a6428)
либо удалить секцию целиком:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/2829f9b7-330e-4929-b407-f51869b09492)

При локальном запуске просто меняем данный файл.
При разворачивании данный файл нужно подменить **ПОСЛЕ** деплоя (только если нужно изменить конфигурацию по умолчанию).

На мобильной версии пользователь не имеет возможности добавлять/удалять виджеты. У него всегда создается 1 определенный набор виджетов. Для удаления виджета из мобильной версии смотри следующую секцию.

**Настройка виджетов, отображаемых по умолчанию:**
Виджеты по умолчанию отображаются:

- при первом запуске
- при нажатии на кнопку Виджеты->Стандартный вид
- при сбросе настроек терминала
- в мобильной версии

Набор, расположение и порядок следования (в мобильной версии) виджетов определяется в файле **assets/default-dashboard-config.json** (src/assets/default-dashboard-config.json для локального запуска).
Данный файл содержит раздельные настройки для desktop и mobile версий:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/a4fd80fc-4675-466a-aaaa-e4bce25f79a5)

**ВАЖНО**: если какой-либо виджет отключен на desktop версии (см. предыдущую секцию), то его следует также убрать из конфигурации desktop  дашборда по умолчанию, иначе при сбросе он будет появляться у пользователя.

Для удаления виджета из мобильной версии достаточно удалить соответствующую секцию из данного файла:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/b5d0559c-0db5-41a1-b1ee-a5c19089e5d0)

При разворачивании данный файл нужно подменить **ПОСЛЕ** деплоя (только если нужно изменить конфигурацию по умолчанию).
