### ISSUE TITLE
[BUG] Заявки на календарные фьючерсы с отрицательной ценой

### ISSUE THREAD

**Issue by zlobinm** [alor-broker/Astras-Trading-UI#962]
### Опишите баг

Не выставляются заявки на календарные фьючерсы с отрицательной ценой.

Кнопки Купить / Продать неактивны

### Воспроизведение

- Выбрать инструмент. Например SI-6.23-9.23
- Попробовать выставить из стакана, ЛКМ по цене

### Среда.

- ОС Windows 10
- Google Chrome
- Mozilla Firefox

### Ожидаемое поведение

Ручной ввод отрицательной цены не работает.

### Скриншоты

![Аннотация 2023-05-17 174650](https://github.com/alor-broker/Astras-Trading-UI/assets/104907168/e021af0d-7632-4587-b049-dcb65f60bc28)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Эх, все таки надо делать отрицательную цену. Календарные спреды мы даем всем клиентам
