### ISSUE TITLE
Некорректное отражение графика на фьючерсах

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#964]
В Astras на графике 4 час timeframe на фьючерсах (например, Si-6.23 и других) не верно отражается период свечки - время начала свечки(при наведении курсора на свечку), в сравнении с данными на аналогичном графике в TradingView .
Почему то в Astras на 3 часа раньше отображает начало свечи. Можно ли скорректировать обозначение начала таймфрейма на 4х часовом графике? На других таймфреймах графики совпадают.
![Снимок экрана 2023-05-18 в 10 13 01](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/456771ec-4943-4a1c-99af-521a9e6bd1f0)
![Снимок экрана 2023-05-18 в 10 14 24](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/5fde0486-dda9-4bf4-9d00-a01634769dd4)

**Comment by sbelashevskiy** [comment]
Дата смещается абсолютно на всех инструментах, а не только фьючерсах
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/d63a40ff-c613-4ac5-96d2-667f58fd4439)

**Comment by PilgrimViis** [comment]
Составлено не по шаблону, закрываю. Вадим, ты же знаешь как надо правильно.
