### ISSUE TITLE
[BUG] Время начала свечей на 4х часовых графиках не корректно

### ISSUE THREAD

**Issue by LuzhbinV** [alor-broker/Astras-Trading-UI#966]
### Опишите баг

В Astras на графике 4х час таймфрейме на фьючерсах (например, Si-6.23 и других) не верно воспроизводится время начала периода свечки (при наведении курсора на свечку),  например, свечка на графике Si-6.23 начинается с 04:00, а на аналогичном графике в TradingView данная свечка отражает время начала построения 07:00.
Почему то в Astras на 3 часа раньше показывает начало свечи. Можно ли это скорректировать на 4х часовом графике? На других таймфреймах графики и время начала свеч совпадают.

### Воспроизведение

Открыть график Si-6.23
Установить 4х часовой таймфрейм
Навести курсор на тело свечи
Зафиксировать обозначение времени на этой свечке
Сравнить показатели времени на свечи в Астрас с аналогичным графиком в TradingView

### Среда.

браузер Chrom

### Ожидаемое поведение

Время начала построения свечей на графиках с 4х часовым таймфреймом совпадают в Астрас и в TV

### Скриншоты

![Снимок экрана 2023-05-18 в 10 13 01](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/995c5544-3e1a-4db8-9a9f-435131825e3d)
Обратить внимание на время начала свечи
![Снимок экрана 2023-05-18 в 10 14 24](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/4da6a64e-e25b-4c0d-a83c-2e85cfa020d3)

### Правила

- [X] Я согласен следовать правилам

**Comment by LuzhbinV** [comment]
![Снимок экрана 2023-05-18 в 13 21 11](https://github.com/alor-broker/Astras-Trading-UI/assets/104637334/db8b2406-c771-4310-a4da-b6c7dfe3dc81)
В графике и в графике Теханализ разное время начала свечей

**Comment by PilgrimViis** [comment]
Большое спасибо

**Comment by sbelashevskiy** [comment]
Необходимы изменения в API. 
Ендпоинт https://api.alor.ru/md/v2/Securities/MOEX/SBER?instrumentGroup=TQBR должен в респонзе возвращать параметр session, такой же, как возвращает https://tradingview.alorbroker.ru/md/Securities/MOEX/SBER?format=TV.v2.

Без данного параметра график отказывать корректно отображать время для таймфрейма 4ч и отображаете его в UTC

**Comment by BattleSky** [comment]
Данные для TV графика. Он получал их из эндпоинта /securities/{exchange}/{ticker} с форматтером TV.v2, там отдается поле "session".

Пример: 
{
"..":"...",
"session":"0700-2350"
}

Для этого ответа отдавались следующие значения:

"FOND": "0700-2350",
"FORTS": "0700-2350",
"CURR": "0700-2350",
"SPBX": "0700-0000,0000-0200",
"BE": "0700-0000,0000-0200",
"ITS": "0700-0000,0000-0200" // <- возможно, здесь требуется уточнение времени

**Comment by sbelashevskiy** [comment]
На данный момент не представляется возможным решить данную проблему без ущерба кодовой базы.
Основная причина - некорректное поведение библиотеки.
Таймфрэйм 4H временно отключен до тех пор, пока не будет решена проблема в библиотеке графика https://github.com/tradingview/charting_library/issues/8310

**Comment by sbelashevskiy** [comment]
Добавлен воркароунд для учета "особенностей" сторонней библиотеки
