### ISSUE TITLE
[FEATURE] Столбцы в блоттере. Ширина, перетаскивание

### ISSUE THREAD

**Issue by dzeron13** [alor-broker/Astras-Trading-UI#97]
### Опишите проблему, которую решает ваша фича

Нет возможности изменить ширину столбцов в блоттере, а также менять их местами - для этого приходится удалять и добавлять в нужном порядке.

### Опишите предлагаемое вами решение

Реализовать возможность изменения границ и перетаскивания.

### Правила

- [ ] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
`Масштабирование ширины колонок в блоттере не отрабатывает при изменении размера виджета:`
https://user-images.githubusercontent.com/99450543/166920973-d4033050-5be8-456a-849b-f66a6da0872e.mp4

Дополнение. Возможно это отдельная проблема, а возможно нет.

**Comment by dzeron13** [comment]
> `Масштабирование ширины колонок в блоттере не отрабатывает при изменении размера виджета:` https://user-images.githubusercontent.com/99450543/166920973-d4033050-5be8-456a-849b-f66a6da0872e.mp4
> 
> Дополнение. Возможно это отдельная проблема, а возможно нет.

Вот эта штука актуальна, но в текущих условиях выглядит так. Масштабирование элементов при изменении размера виджета работает только в сторону увеличения:
https://user-images.githubusercontent.com/99450543/205038874-80bb8da7-01ea-4cff-afdd-7efa4a98a741.mp4
