### ISSUE TITLE
[FEATURE] Визуализация сделок на графике астрас

### ISSUE THREAD

**Issue by m484xw** [alor-broker/Astras-Trading-UI#974]
### Опишите проблему, которую решает ваша фича

Визуализация сделок на графике астрас

### Опишите предлагаемое вами решение

Для контроля позиция очень удобно, когда на графике отражаются совершенные сделки. 
Пример

![Снимок](https://github.com/alor-broker/Astras-Trading-UI/assets/134391633/952d3db4-bc68-4a42-ba9b-9d541f62372e)

Это позволяет визуально отслеживать не только среднюю цену покупки, но и отдельные позиции.
Идеально, если будут отражаться сделки на максимально возможную историческую глубину графика

### Правила

- [X] Я согласен следовать правилам

**Comment by sbelashevskiy** [comment]
@PilgrimViis,
Это делать в тех. анализе или лайтчарте?

**Comment by PilgrimViis** [comment]
Это light

**Comment by PilgrimViis** [comment]
Это на тех. анализе.

**Comment by PilgrimViis** [comment]
@sbelashevskiy можно кстати сюда же исторические сделки подключить, если это проблем не создаст. Будет круто. 

Так же, прошу обязательно сделать этот функционал отключаемым.
