### ISSUE TITLE
[FEATURE] Возможность добавить дашборд в избранное

### ISSUE THREAD

**Issue by aronsx** [alor-broker/Astras-Trading-UI#977]
### Опишите проблему, которую решает ваша фича

Когда много дешбордов и нудно между ними переключаться, приходится искать нужный дашборд в выпадающем меню

### Опишите предлагаемое вами решение

Добавить кнопку «добавления в избранное» (например с иконкой звездочки), при нажатии на которую избранный дашборд будет отображаться в виде вкладки (отдельный кнопки в шапке) и будет пропадать из выпадающего меню
(Как это реализовано на графике теханализа с выбором таймфрейма)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Хм... А можно спросить, зачем вам так часто переключаться между дашбордами?

**Comment by aronsx** [comment]
при открытии новых окон/вкладок, приходится искать нужные дашборды, было бы в разы удобнее частоиспользуемые вынести в избранное, чтобы можно было быстро выбрать нужный при открытии нового окна
