### ISSUE TITLE
[FEATURE] Сохранение настроек терминала в аккаунте

### ISSUE THREAD

**Issue by aronsx** [alor-broker/Astras-Trading-UI#978]
### Опишите проблему, которую решает ваша фича

При использовании терминала на нескольких машинах приходится все заново настраивать: дашборды, уведомления и горячие клавиши 

### Опишите предлагаемое вами решение

Сохранить настройки в аккаунте и загружать настройки при входе с нового устройства

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Здравствуйте. Да, мы хотели это сделать тоже. Но тут без высокого приоритета.
