### ISSUE TITLE
[DOCS]  У виджетов отсутствует справка

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#980]
### Опишите баг

Нет справки у следующих виджетов:

- Карта рынка
- Опционная доска

При клике на справку показывается Ошибка 500 и пустое окно

### Воспроизведение

1. Добавить один из виджетов
2. Кликнуть по значку справка

### Среда.

любая

### Ожидаемое поведение

1. Если для виджета вообще не планируется писать справку, то скрыть значок
2. Если значок есть, но справка не написана, то не показывать ошибку 500 и пустое окно, а отображать текст: "Справка еще не готова, но мы это скоро исправим"

### Скриншоты
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/5057feed-4361-45b3-a12a-e2b8838543ea)

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Добавил пока "заглушки" в виде 1 параграфа текста. Когда в конце года будем делать ревью документации, доработаем.
