### ISSUE TITLE
[BUG] ASTRAS не видит портфелей после поступления дс на счет

### ISSUE THREAD

**Issue by MorozovDen** [alor-broker/Astras-Trading-UI#981]
### Опишите баг

У клиента счет нулевой, сегодня пополняет дс банковским переводом, деньги поступают в АЛОР, видим их в лимите на серверах АЛОР-Трейд и в кабинете клиента (т.е. в варпе они уже должны тоже отображаться). Но ASTARAS показывает, что доступных портфелей нет, т.е. по прежнему видит, что счета нулевые. Ранее сталкивались с такой же проблемой, и на следующий день начинает видеть портфель. В обоих случаях был портфель СРОЧНОГО рынка, с фондовым такого не встречал. Если для уточнения нужен номер портфеля - могу написать в личку.

### Воспроизведение

открываем ASTRAS, отображает, что нет доступных портфелей

### Среда.

вин7, мозила

### Ожидаемое поведение

Отображение доступных портфелей сразу после поступления дс в портфель

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Это проблема на бекенде, у них уже есть задача на этот счет. Поэтому задачу закрою.
