### ISSUE TITLE
[FEATURE] Быстрая работа со связанными условными заявками

### ISSUE THREAD

**Issue by Extred** [alor-broker/Astras-Trading-UI#984]
### Опишите проблему, которую решает ваша фича

При выставлении заявок типа корридор (bracket) надо заполнять параметры в форме заявки. Это не позволяет "ловить" небольшие и быстрые движения цен.

### Опишите предлагаемое вами решение

Добавить возможность выставлять заявки "без подтверждения" по преднастройкам. Условно - стоп+тейкпрофик на 0.5% от позиции или заявки.

Функционал подразумевается в виджетах "скальперский стакан" и при выставлении заявок с графика.

Также потребуется индикация выставленного корридора в этих же виджетах, чтобы было видно границы, где позиция закроется при достижении ценой.

Это относится как к стандартным брекетам, там и к условным (где стопы активируются после срабатывания лимитки).

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Я не вижу особого смысла делать такое же для стопов. Стопы мы же добавляли чтобы как раз решить эту проблему. Чтобы после лимитки быстро выставить стоп чтобы зафиксировать прибыль\убыток. Тут же мы автоматизируем этот процесс. Стопы будут ставится сами. Поэтому зачем на стопы такой же функционал?

**Comment by Extred** [comment]
Эта функция позволяет ловить быстрые движения при высокой волатильности или при скальпинге. Сейчас быстро выставить брекет нет возможности в интерфейсе, но сам механизм при этом есть.

**Comment by PilgrimViis** [comment]
Логика следующая. При выставлении заявки в скальперском стакане у человека появится опция автоматически устанавливать условные заявки на закрытие сверху и снизу, образуя коридор. Эти заявки будут связаны в группу. Каждая заявка должна закрывать позицию открытую по главной заявке. В настройках каждого стакана должна быть возможность указать отступ от основной заявки по которому будет производится закрытие. Отступ должен быть либо в пунктах (шагах цены) либо процентах. В случае если отсутуп в процентах, надо округлить до ближайшего шага цены. Так же когда человек самостоятельно закрывает (или частично закрывает) позицию выставляя заявки в стакане это не должно вызывать выставление дополнительных стопов. На случай если это кому-то надо, предлагаю сделать опциональную настройку, которая включает выставление стопов при закрытии.
