### ISSUE TITLE
[BUG] Лишний вызов API

### ISSUE THREAD

**Issue by sbelashevskiy** [alor-broker/Astras-Trading-UI#985]
### Опишите баг

Любое действие на дашборде приводит к вызову метода https://apidev.alor.ru/commandapi/warptrans/FX1/v2/client/orders/clientsRisk

### Воспроизведение

1. Добавить виджет информация
2. Добавить/переместить, изменить размеры любого виджета
3. Проверить network

### Среда.

любая

### Ожидаемое поведение

Нет лишних вызовов

### Скриншоты

https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/7f214cb9-bdc7-4afc-a94f-0d06268b6cb8

### Правила

- [X] Я согласен следовать правилам

**Comment by PilgrimViis** [comment]
Очень странно. А есть ли сокет для получение инфы по рискам?

**Comment by sbelashevskiy** [comment]
pipe где-то неправильно написан. При перемещении виджета обновляется его позиция, при обновлении позиции идет запрос
